### ISSUE TITLE
Autosave nodes

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#104]

**Comment by jasloe** [comment]
@cchristopherhowardd: oy, this is a monster project. I'm going to table this as a won't do for now. If I write for another project in the future, I can port to aarome.org. 

Meantime, I installed a little JS that simply warns the user if they are about to navigate away from an unsaved node. 

To replicate: 

-- open a node
-- edit a field (or simply place cursor in a field)
-- select browser back button
-- notice popup warning

Let me know if that works for you.

**Comment by cchristopherhowardd** [comment]
This works, both for hitting the back button and attempting to navigate to another page.
