### ISSUE TITLE
Stylesheet refactor

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#108]

**Comment by jasloe** [comment]
@cchristopherhowardd: I'm merging one of two stylesheet branches now. The first will fix a whole slew of spacing and font size issues. The second will temporarily break the footer. I'll have a third branch for that tomorrow afternoon.

**Comment by jasloe** [comment]
Reopening to track various CSS/JS refinements.

@cchristopherhowardd: I just pushed code that dispenses with the differently oriented margins in the page title region and the full-width image on smaller viewports. It became too onerous to manage. 

Instead of a dozen different conditions, I simply changed the layout container's left/right margin to 1rem (i.e. 16px). It's reliable, saves a lot of time, and simplifies long-term maintenance.  

Happy to consider other options but in this case (most cases?) simpler is better.

**Comment by cchristopherhowardd** [comment]
I'm not sure what's at issue here, but if you've found a workable solution, that's fine.
