### ISSUE TITLE
Notes on search

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#112]
Search backend implemented here. (Front end needs theming obv.)

Search for common name:

**John** 

Returns results in the following order:

![boost](https://user-images.githubusercontent.com/1063667/52235635-b5af1f80-2892-11e9-8669-1a37c2703810.jpeg)

Search for uncommon name:

**Talia**

Or name with different domains:

**Virginia**

Short words not working:

**T.** (i.e. T. Geronimo)

@cchristopherhowardd: Other fields we want to return? Can return nearly anything, though images may be tricky.

**Comment by jasloe** [comment]
Note that search tangent weights are exponential. Let me know which content you want to prioritize in search results and I'll take it from there. 

![boost](https://user-images.githubusercontent.com/1063667/52235932-71704f00-2893-11e9-8ddc-45c70fb0ac5a.jpeg)

**Comment by cchristopherhowardd** [comment]
Most of those numbers look fine. I’d increase Publications to 3.0 or 4.0.

Chris
-------
Christopher Howard
Communications Manager
