### ISSUE TITLE
/about/staff refactor

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#119]
Redesign according to SOF directory pattern.

**Comment by cchristopherhowardd** [comment]
I've created page sections for the people on each department. There should be three left-side headers: Locations, Rome Office, and New York Office. The page sections for Administration through Rome Sustainable Food Project should appear within the Rome Office page sections. Those for (the second) Administration through Programs should appear within the New York Office page section.

**Comment by cchristopherhowardd** [comment]
Update: Those page sections for (the second) Administration through Finance should appear within the New York Office page section. I combined Communications and Programs into one page section.
