### ISSUE TITLE
Test core i18n 

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#12]

**Comment by cchristopherhowardd** [comment]
I haven't looked at the Italian-language pages much. Do you need a comprehensive list of changes, like the /people/current --> /it/comunita/attuale example you give?

**Comment by jasloe** [comment]
No, I think we're ok on that front. Point being that there may not be a cheap way to render URLs in Italian. (We can do that on the current site; the same functionality in Drupal 8 is a work-in-progress.)

e.g.

Look at this URL in English:
http://www.un.org/en/sections/what-we-do/index.html

And this in French:
http://www.un.org/fr/sections/what-we-do/index.html

I'm going to post a query to various developers' forums and see what I can find out but I think resolving this immediately is a pretty lower priority.
