### ISSUE TITLE
Fix indentation and line spacing between line items

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#121]
/about/jobs-internships

**Comment by cchristopherhowardd** [comment]
Can the style sheet be amended so that there is a line space between the final bullet point and the paragraph that comes next? See https://dev.aarome.org/research/library/access-rules-policies as an example.

**Comment by jasloe** [comment]
Yes. The bulleted lists are a bit complicated because there are so many variants:

bulleted list with no preceding paragraph
bulleted list without following paragraph
bulleted list with/without preceding <h*> tag

Working to track all of these down and write an efficient style.
