### ISSUE TITLE
Corrections for Resources subsection in the Research section

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#131]
The images I upload for this section page — http://dev.aarome.org/research/resources — aren’t appearing on that page. For instance, the image on this page 
( http://dev.aarome.org/research/resources/online-catalogues ) does not appear on the section page.

**Comment by cchristopherhowardd** [comment]
On the section page ( http://dev.aarome.org/research/resources ), the link for Digital Humanities Center should to go http://dhc.aarome.org/. Also, the image for the section page does not appear (probably related to above issue?).

**Comment by cchristopherhowardd** [comment]
Content for several boxes on the section page ( http://dev.aarome.org/research/resources ) is missing:

Electronic Journals: http://dev.aarome.org/research/resources/electronic-journals\
Research Databases & Digital Collection: http://dev.aarome.org/research/resources/research-databases-digital-collections
Libraries & Institutions: http://dev.aarome.org/research/resources/libraries-institutions
Useful Links: http://dev.aarome.org/research/resources/useful-links

Content for these pages work as expected:

Online Catalogues
Maps & GIS
Research Tutorials

**Comment by cchristopherhowardd** [comment]
The Photographic Archive section is missing the page footer: http://dev.aarome.org/research/photographic-archive.

All other pages in this section (e.g., http://dev.aarome.org/research/photographic-archive/exhibitions-events) have the footer.

**Comment by cchristopherhowardd** [comment]
The Notices page for the Library ( http://dev.aarome.org/research/library/notices ) should not be used for the Photographic Archive ( http://dev.aarome.org/research/photographic-archive/notices ). Node 44 is used for both. The Photographic Archive needs a separate node.

**Comment by cchristopherhowardd** [comment]
Where are we with the formatting of long lists of Resources in the Research section? I am thinking of pages such as http://dev.aarome.org/research/resources/libraries-institutions and http://dev.aarome.org/research/resources/research-databases-digital-collections. Open has suggested pages look like this attached image.

![laptop 1080 overview 7 - resources](https://user-images.githubusercontent.com/38765846/53197989-5f0f4880-35e9-11e9-9736-5c9524ff6feb.png)

This page type looks clean, while the content in this section is kinda messy. I'll soon have Sebastian and crew review the information and send me changes, which should help. Maybe they'll reduce the content, which would be fantastic.

Relatedly, I see slight discrepancies among Resources pages. The headers in the body text at http://dev.aarome.org/research/resources/research-databases-digital-collections (Amphora & Other Pottery, Ancient Graffiti Project, Arachne, etc.) have a different <h> coding than those at http://dev.aarome.org/research/resources/electronic-journals. Should we go with the style for the former page?

**Comment by jasloe** [comment]
Shoot, I thought I pushed that to dev. Will button that up this afternoon.

**Comment by jasloe** [comment]
Pushed functionality. CSS forthcoming.

**Comment by jasloe** [comment]
I think the arrow adds noise. What do you think?

**Comment by cchristopherhowardd** [comment]
It does.

I'd like to eventually move toward not having the <h> header be the link, but an overhaul of that kind isn't a priority now.

**Comment by jasloe** [comment]
I assumed the header was supposed to the link. Is that not so?

**Comment by cchristopherhowardd** [comment]
Yes, the header links. I have other ideas but I'll keep them to myself for now. Can of worms.

**Comment by cchristopherhowardd** [comment]
This problem has come back. The Notices page for the Library (http://dev.aarome.org/research/library/notices) is appearing on the Photographic Archive (http://dev.aarome.org/research/photographic-archive/notices) again. Would using a different title for the page solve the problem?

**Comment by jasloe** [comment]
http://dev.aarome.org/research/library/notices
http://dev.aarome.org/research/photographic-archive/notices

I hardcoded the node values in the view. Should be ok now. 

Since I'm already working on an announcement modal that drops from the top, it would be trivial to configure one for library pages with closure announcements. 

For example, it could display two weeks prior to a scheduled closing, appear for 15 seconds above then menu, then either disappear after 15 seconds or can be dismissed by the user (an 'x' for close), similar to GDPR or cookie notices.

**Comment by jasloe** [comment]
> Where are we with the formatting of long lists of Resources in the Research section? I am thinking of pages such as http://dev.aarome.org/research/resources/libraries-institutions and http://dev.aarome.org/research/resources/research-databases-digital-collections. Open has suggested pages look like this attached image.
> 
> ![laptop 1080 overview 7 - resources](https://user-images.githubusercontent.com/38765846/53197989-5f0f4880-35e9-11e9-9736-5c9524ff6feb.png)
> 
> This page type looks clean, while the content in this section is kinda messy. I'll soon have Sebastian and crew review the information and send me changes, which should help. Maybe they'll reduce the content, which would be fantastic.
> 
> Relatedly, I see slight discrepancies among Resources pages. The headers in the body text at http://dev.aarome.org/research/resources/research-databases-digital-collections (Amphora & Other Pottery, Ancient Graffiti Project, Arachne, etc.) have a different coding than those at http://dev.aarome.org/research/resources/electronic-journals. Should we go with the style for the former page?

Almost done with this. Need to re-run an import to pick up the 100 or so bits of content k.iara has added in the last couple of months, as well as the HTML markup for resource body copy. Will take care of that this evening.

**Comment by jasloe** [comment]
@cchristopherhowardd: closing this issue as it has become muddy. If anything arises pertaining to /research/resources, please open a new issue.
