### ISSUE TITLE
Research section: changes and edits

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#132]
Content for several boxes on the section page ( http://dev.aarome.org/research/resources ) is missing:

Electronic Journals: http://dev.aarome.org/research/resources/electronic-journals\
Research Databases & Digital Collection: http://dev.aarome.org/research/resources/research-databases-digital-collections
Libraries & Institutions: http://dev.aarome.org/research/resources/libraries-institutions
Useful Links: http://dev.aarome.org/research/resources/useful-links

Content for these pages work as expected:

Online Catalogues
Maps & GIS
Research Tutorials

_Originally posted by @cchristopherhowardd in https://github.com/aarome/aarome/issues/131#issuecomment-463231709_

**Comment by cchristopherhowardd** [comment]
In the Photographic Archive section, the content for this page ( http://dev.aarome.org/research/photographic-archive/juries ) should be published here: http://dev.aarome.org/people/juries. 

This page ( http://dev.aarome.org/research/photographic-archive/notices ) needs to be placed in the first box at http://dev.aarome.org/research/photographic-archive (where Juries is right now).

**Comment by cchristopherhowardd** [comment]
In the Library section ( http://dev.aarome.org/research/library ), the box for Special Collections should produce the content from http://dev.aarome.org/node/28 with the header Collections. The box should **not** take users to http://dev.aarome.org/research/special-collections.

**Comment by jasloe** [comment]
> In the Photographic Archive section, the content for this page ( http://dev.aarome.org/research/photographic-archive/juries ) should be published here: http://dev.aarome.org/people/juries.

Fixed.

Note that I broke Juries and Advisors into separate nodes.

http://dev.aarome.org/node/4000/edit
http://dev.aarome.org/node/2435/edit

**Comment by jasloe** [comment]
> In the Library section ( http://dev.aarome.org/research/library ), the box for Special Collections should produce the content from http://dev.aarome.org/node/28 with the header Collections. The box should **not** take users to http://dev.aarome.org/research/special-collections.

Fixed. How do users get to Special Collections (other than the footer menu)?

**Comment by cchristopherhowardd** [comment]
Collections and Special Collections are two separate things. 

Collections is http://dev.aarome.org/node/28 and accessed in the Library section (http://dev.aarome.org/research/library).

Special Collections is http://dev.aarome.org/research/special-collections and its own index page. It is found in the main Research section: http://dev.aarome.org/research (but is no longer there).

**Comment by jasloe** [comment]
> Collections and Special Collections are two separate things.
> 
> Collections is http://dev.aarome.org/node/28 and accessed in the Library section (http://dev.aarome.org/research/library).
> 
> Special Collections is http://dev.aarome.org/research/special-collections and its own index page. It is found in the main Research section: http://dev.aarome.org/research (but is no longer there).

Have a look. I moved "Collections" to node/4003. (Long story.)

**Comment by cchristopherhowardd** [comment]
The link to Collections at http://dev.aarome.org/research/library still goes to http://dev.aarome.org/research/library/special-collections. Can you make it link to http://dev.aarome.org/research/library/collections?

**Comment by jasloe** [comment]
Done.

**Comment by cchristopherhowardd** [comment]
The text for each of the boxes at http://dev.aarome.org/research is all uppercase. Can you reinstate the  normal sentence case?

**Comment by jasloe** [comment]
Oops. Got a little ham-fisted with some CSS and targeted too many elements. Fixed.

**Comment by cchristopherhowardd** [comment]
The image I upload for this page (https://dev.aarome.org/research/resources/useful-links) is not loading on the page. It is loading on the section page (https://dev.aarome.org/research/resources), bottom right.

**Comment by cchristopherhowardd** [comment]
> The image I upload for this page (https://dev.aarome.org/research/resources/useful-links) is not loading on the page. It is loading on the section page (https://dev.aarome.org/research/resources), bottom right.

The image loads for this page (https://dev.aarome.org/research/resources/maps-gis) but not for Useful Links and Research Databases & Digital Collections (https://dev.aarome.org/research/resources/research-databases-digital-collections).

**Comment by jasloe** [comment]
The design for pages with dynamic lists don't contain a marquee image. Would you like to change that?

**Comment by cchristopherhowardd** [comment]
Yes, please.

Chris
-------
Christopher Howard
Communications Manager

**Comment by jasloe** [comment]
Like so? 

https://dev.aarome.org/research/resources/electronic-journals

If ok, I'll cobble together the other views. Note that this display required a workaround (i.e. a hack). It should be refactored down the road.

**Comment by cchristopherhowardd** [comment]
These Resources photos/pages look good except for that JSTOR image for the link above. The source file is 1600 pixels wide, so it should span more of the page.

**Comment by jasloe** [comment]
Oops, wrong formatter. Fixed.

**Comment by cchristopherhowardd** [comment]
The very last box at https://dev.aarome.org/research, for Archeology, also has bad formatting.

**Comment by jasloe** [comment]
How so? 

FYI-- I have a fix for the Archeology inside pages forthcoming....page title needs padding.

https://dev.aarome.org/research/archaeology/norton-van-buren-seminar-room

**Comment by cchristopherhowardd** [comment]
Screenshot of webpage https://dev.aarome.org/research on Chrome while logged into AAR dev site.
<img width="944" alt="Screen Shot 2019-03-13 at 4 13 20 PM" src="https://user-images.githubusercontent.com/38765846/54311485-0c52fc00-45ab-11e9-832e-fd6f37365189.png">

**Comment by cchristopherhowardd** [comment]
Looks normal on Safari, not logged in.
<img width="850" alt="Screen Shot 2019-03-13 at 4 14 30 PM" src="https://user-images.githubusercontent.com/38765846/54311518-2096f900-45ab-11e9-873e-ad7c11359422.png">

**Comment by jasloe** [comment]
I was able to replicate with the site editor role. Weird! Will investigate.
