### ISSUE TITLE
non-breaking spaces of doom

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#133]
Well, as predicted, we picked up those entities from the old CMS. We can either:

1. blow them away via SQL queries or 
2. configure the body/page section fields to sanitize the offending character entity

Caveat for 1.: MYSQL stores the &nbsp; in clunky way so we can't specifically address those character, e.g.: find and replace

```
 "  " with " "
```
instead of 
```
"&nbsp;" with " "
```

Caveat for 2.: This would take quite a bit more time and custom code.

**Comment by cchristopherhowardd** [comment]
I don't know which options is better. The second sounds time consuming. What about the first option?

**Comment by jasloe** [comment]
I attempted the second option and it's a nightmare. 

We'll have to go with the first option. I'll test the query locally, then replicate in production. Would be good to carve out 20 minutes or so tomorrow to confirm the changes on dev.

**Comment by jasloe** [comment]
Took a crack at this with db queries. 

I replaced &nbsp; and '  ' (two spaces) with ' ' (one space).

@cchristopherhowardd: can you keep an eye out for any irregularities?

**Comment by cchristopherhowardd** [comment]
OK. 

When I copy text from Word, I paste it into TextEdit and make it plain text. That generally gets rid of evil nbsp formatting.

**Comment by jasloe** [comment]
I can add a filter to remove non-breaking spaces for new content. The markup paste-from-Word produces is still pretty ugly. 

Of course, there's always Markdown.... 

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
