### ISSUE TITLE
Support section changes

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#134]
Functionality issues for http://dev.aarome.org/support:

The link for the first box (Donate) does not work. Clicking the link should take you to http://dev.aarome.org/support/donate.

The link for the third box (Galas) does not produce any content. The page http://dev.aarome.org/support/galas should produce content from http://dev.aarome.org/node/2417/

**Comment by jasloe** [comment]
Fixed. Will push changes this afternoon.

**Comment by cchristopherhowardd** [comment]
The Galas box on the Support section index page (http://dev.aarome.org/support) disappeared after I changed the image for the Galas page (http://dev.aarome.org/support/galas). Can you reinstate the box?

**Comment by jasloe** [comment]
Sorry....there was a disconnect between local and remote dbs that caused that block to fail. Can you confirm that's the node you want to display there? 

http://dev.aarome.org/node/4002/edit

**Comment by cchristopherhowardd** [comment]
Yes, this is the node for the Galas page.
