### ISSUE TITLE
Publications section: changes and edits

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#135]
On the section page ( http://dev.aarome.org/publications ), the link for Supplements to the Memoirs is broken. The box links to http://dev.aarome.org/publications/supplements-memoirs but the page content exists at http://dev.aarome.org/publications/supplements-to-the-memoirs.

**Comment by cchristopherhowardd** [comment]
The magazine page ( http://dev.aarome.org/publications/magazine ) is doubling each issue, meaning the Fall/Winter 2018 issue appears twice, the Spring 2018 issue appears twice, and so on.

**Comment by cchristopherhowardd** [comment]
The last box on the section page is for Society of Fellows News. This page is for archiving the PDFs of what I believe was a print publication called _Society of Fellows News_. I'd like to have this page resemble that of the _AAR Magazine_ page ( http://dev.aarome.org/publications/magazine ).

The current website has all the issues here: https://www.aarome.org/people/alumni/sof/archive.

I've placed _Society of Fellows News_ in the Publications section, but am leaning strongly toward moving it to Society of Fellows section ( http://dev.aarome.org/society-of-fellows ).

**Comment by jasloe** [comment]
> The magazine page ( http://dev.aarome.org/publications/magazine ) is doubling each issue, meaning the Fall/Winter 2018 issue appears twice, the Spring 2018 issue appears twice, and so on.

Fixed. Added Download link. This link will get styled after next stylesheet build.

**Comment by jasloe** [comment]
> On the section page ( http://dev.aarome.org/publications ), the link for Supplements to the Memoirs is broken. The box links to http://dev.aarome.org/publications/supplements-memoirs but the page content exists at http://dev.aarome.org/publications/supplements-to-the-memoirs.

Fixed. Ditto stylesheet note on previous note.
