### ISSUE TITLE
SOF News

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#136]
The last box on the section page is for Society of Fellows News. This page is for archiving the PDFs of what I believe was a print publication called _Society of Fellows News_. I'd like to have this page resemble that of the _AAR Magazine_ page ( http://dev.aarome.org/publications/magazine ).

The current website has all the issues here: https://www.aarome.org/people/alumni/sof/archive.

I've placed _Society of Fellows News_ in the Publications section, but am leaning strongly toward moving it to Society of Fellows section ( http://dev.aarome.org/society-of-fellows ).

_Originally posted by @cchristopherhowardd in https://github.com/aarome/aarome/issues/135#issuecomment-463777803_

**Comment by jasloe** [comment]
@cchristopherhowardd: Let me know which section you want to post this in as it will dictate which templates I use.

**Comment by cchristopherhowardd** [comment]
Stick it in the Society of Fellows section.

**Comment by cchristopherhowardd** [comment]
Society of Fellows News has returned to the Publications section (last item in https://dev.aarome.org/publications). It should be removed from here and placed as the last item in the Society of Fellows section (https://dev.aarome.org/society-of-fellows). Next, the page https://dev.aarome.org/society-of-fellows/society-fellows-news (or /society-**of-**fellows-news?) should be created, as indicated above.
