### ISSUE TITLE
Remove trailing commas from incomplete locations

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#137]
e.g.: http://dev.aarome.org/events/michael-ray-charles-helen-o-leary

**Comment by cchristopherhowardd** [comment]
Good riddance, trailing comma!

**Comment by jasloe** [comment]
@cchristopherhowardd -- This is done. I'm rendering the place name and city. (Not sure if we need the country.)

Do you want to display the street address, too?

**Comment by cchristopherhowardd** [comment]
Yes, please display the full street address.

**Comment by jasloe** [comment]
Ok, all set. Ex.: 

http://dev.aarome.org/events/modern-architecture-media-gender
http://dev.aarome.org/events/helen-o-leary

The address block can be placed somewhere else on the page if desired.
