### ISSUE TITLE
Reimport resources, update style sheets for /research/resources/*

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#141]
> Where are we with the formatting of long lists of Resources in the Research section? I am thinking of pages such as http://dev.aarome.org/research/resources/libraries-institutions and http://dev.aarome.org/research/resources/research-databases-digital-collections. Open has suggested pages look like this attached image.
> 
> ![laptop 1080 overview 7 - resources](https://user-images.githubusercontent.com/38765846/53197989-5f0f4880-35e9-11e9-9736-5c9524ff6feb.png)
> 
> This page type looks clean, while the content in this section is kinda messy. I'll soon have Sebastian and crew review the information and send me changes, which should help. Maybe they'll reduce the content, which would be fantastic.
> 
> Relatedly, I see slight discrepancies among Resources pages. The headers in the body text at http://dev.aarome.org/research/resources/research-databases-digital-collections (Amphora & Other Pottery, Ancient Graffiti Project, Arachne, etc.) have a different coding than those at http://dev.aarome.org/research/resources/electronic-journals. Should we go with the style for the former page?

Almost done with this. Need to re-run an import to pick up the 100 or so bits of content k.iara has added in the last couple of months, as well as the HTML markup for resource body copy. Will take care of that this evening.

_Originally posted by @jasloe in https://github.com/aarome/aarome/issues/131#issuecomment-468066097_

**Comment by jasloe** [comment]
Reimported resources and imported new resources. Body_value now show anchor tags as expected. Attempted

**Comment by cchristopherhowardd** [comment]
Great, thanks! Yesterday I sent links to the Research section to Sebastian and crew in Rome. They're reviewing their pages and compiling notes and changes on a shared google doc.
