### ISSUE TITLE
Workbench, user login enhancements

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#144]
@cchristopherhowardd: This is a little out of scope but a nice (I hope) enhancement. I've added some so-called "Workbench" features to the admin. 

When you have a moment, can you navigate to /admin/workbench (or select the icon from the toolbar) and let me know what you think? Not everything is final/working here quite yet; if there's any sorting mechanism or content display you'd like to see here, do let me know.  

This is poached from another project so no big time commitment here.

**Comment by jasloe** [comment]
I also cleaned up the login theming. Let me know if you notice any issues.

**Comment by cchristopherhowardd** [comment]
Looks great--no issues!

**Comment by jasloe** [comment]
Ok, reopen if there's anything you'd like the admin page to do.
