### ISSUE TITLE
/people/residents/* refactoring

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#146]
Yesterday I was creating and updating People pages for Italian Fellows and Residents. I discovered that the template for Rome Prize Fellows and Italian Fellows doesn't work with Residents. I'll use http://dev.aarome.org/people/residents/marlon-blackwell as an example. 

1. Blackwell does not have a fellowship name, but he does have a residency name: William A. Bernoudy Architect in Residence. Can the page say "Residency" instead of "Fellowship"?

2. Residents rarely have project names. Can we hide the "Project" header?

3. Residents don't have "Project Descriptions" but rather we write short biographical entries with quotes from the residents. Can we call this header "Biography"? 

4. A general concern regarding the "Profession(s)" field for People pages. A person often has multiple affiliations (academic, job/company) like Blackwell does. In order for the page to express these facts, I have to add the word "and" in the field for the second affiliation. Is it possible to list multiple affiliations on their own lines? This seems like a more coherent way to present the information.
<img width="904" alt="screen shot 2019-03-01 at 11 12 36 am" src="https://user-images.githubusercontent.com/38765846/53651258-3fdd7000-3c14-11e9-9e58-2758f8f61444.png">
<img width="630" alt="screen shot 2019-03-01 at 11 12 18 am" src="https://user-images.githubusercontent.com/38765846/53651270-45d35100-3c14-11e9-9897-47be0bb6a3ee.png">

_Originally posted by @cchristopherhowardd in https://github.com/aarome/aarome/issues/72#issuecomment-468721822_

**Comment by jasloe** [comment]
@cchristopherhowardd: ok I took a little extra time to break out separate views for the following affiliation types:

dev.aarome.org/people/rome-prize-fellows
dev.aarome.org/people/italian-fellows
dev.aarome.org/people/residents
dev.aarome.org/people/affliliated-fellows
dev.aarome.org/people/visiting-artists-scholars

This will give us more control over how people detail pages are rendered. 

I also added a template override that hides labels if the field is empty. 

Professions are listed in the order set in the node. 

Biographical note added to people content type. 

If ok, please close ticket. I'm opening a new one to track portrait image handling and media queries which are little wonky atm.

**Comment by cchristopherhowardd** [comment]
The pages for individual people aren't loading with full content--photos but no text. See http://dev.aarome.org/people/italian-fellows/carmen-belmonte or http://dev.aarome.org/people/residents/nasser-rabbat as examples.

For the moment, the Affiliated Fellows and Visiting Artists and Scholars pages should be lists of names, like they are on the current site: https://www.aarome.org/people/current/affiliated-fellows. It is going to take time to get People pages for these folks.

**Comment by jasloe** [comment]
Yes, working on the media query for people. It's tricky because the sizes and aspect ratios are all over the place.

**Comment by jasloe** [comment]
> The pages for individual people aren't loading with full content--photos but no text. See http://dev.aarome.org/people/italian-fellows/carmen-belmonte or http://dev.aarome.org/people/residents/nasser-rabbat as examples.
> 
> For the moment, the Affiliated Fellows and Visiting Artists and Scholars pages should be lists of names, like they are on the current site: https://www.aarome.org/people/current/affiliated-fellows. It is going to take time to get People pages for these folks.

Fixed the people detail. See #147.

Do you want to publish the AF and VAVS lists as a simple node or as a collection of people nodes?

The latter is more flexible, scalable. At one point we discussed importing this data as a small side project:

https://docs.google.com/spreadsheets/d/1pfmvz5MBfiM9MPawC4KbbNIxkMxFiz9SACj5WvDeSso/edit?usp=sharing

I could get this cleaned up, imported, and formatted in a few hours.

**Comment by cchristopherhowardd** [comment]
I totally forgot about importing the spreadsheet! If you can create People nodes with all these Affiliated Fellows, then please do!
