### ISSUE TITLE
Import affiliated fellows

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#148]
I totally forgot about importing the spreadsheet! If you can create People nodes with all these Affiliated Fellows, then please do!

_Originally posted by @cchristopherhowardd in https://github.com/aarome/aarome/issues/146#issuecomment-469443062_

**Comment by cchristopherhowardd** [comment]
What is the state of the Affiliated Fellows import?

**Comment by cchristopherhowardd** [comment]
I totally forgot about this.
