### ISSUE TITLE
Webforms

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#150]
I took a stab at this. (Currently, placed in the about breadcrumb path because I couldn't remember where the form is supposed to live.)

dev.aarome.org/about/tours

@cchristopherhowardd: let me know if there's any feedback. Form translations are a little tricky but I should have that wrapped up in the next hour or so.

**Comment by jasloe** [comment]
Ok, candidate translations available at:

dev.aarome.org/informazioni/tours

**Comment by cchristopherhowardd** [comment]
Page not found for IT version.

**Comment by jasloe** [comment]
http://dev.aarome.org/it/informazioni/tours

**Comment by cchristopherhowardd** [comment]
I'm waiting to hear back from Rome about this form.

**Comment by jasloe** [comment]
Any feedback on both tour and library forms?

**Comment by cchristopherhowardd** [comment]
Regarding tour form: 

> The system we have right now with people directly writing to tours@aarome.org is working quite well and I'm wondering if we need to really change it.

**Comment by cchristopherhowardd** [comment]
If this is the case, let's shelve the Tours form and return to it later, if it makes sense. The Tours page can publish content from the existing page: https://www.aarome.org/about/tours. I can update the dates when Rome wants to.

**Comment by cchristopherhowardd** [comment]
The Tours page needs to find a home in a section. The two that make sense are About, Place, and Events. Place makes the most sense, but the page would not appear in the footer menu. Therefore it may be useful to add Tours as the last item on the About section page.

**Comment by jasloe** [comment]
I stuck it in Place and added it to the About footer menu. 

https://dev.aarome.org/about

Let me know how/if you want "Tours" translated.

**Comment by jasloe** [comment]
@cchristopherhowardd do we have a translation for Tours?

**Comment by cchristopherhowardd** [comment]
Yes.  It is https://dev.aarome.org/it/informazioni/luoghi/**visite-guidate**.

**Comment by cchristopherhowardd** [comment]
Or rather, https://dev.aarome.org/it/informazioni/luoghi/visite-guidate

**Comment by jasloe** [comment]
Retitled as generic placeholder for form issues.
