### ISSUE TITLE
Include "calendar" breadcrumb

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#153]
Can the breadcrumb for an individual event (e.g., https://dev.aarome.org/events/2019-mckim-medal-gala) be Events / Calendar? Or does the URL/file structure not allow for this? Just wondering....

_Originally posted by @cchristopherhowardd in https://github.com/aarome/aarome/issues/111#issuecomment-472138861_

**Comment by jasloe** [comment]
Here's a quick and dirty implementation. 

https://dev.aarome.org/events/calendar/2019-mckim-medal-gala

I wonder if we should implement path and breadcrumb patterns? Something like?

/events/calendar (all events): Events / Calendar
/events/exhibitions (exhibitions): Events / Exhibitions
/events/[series-name] (series): Events / Shoptalks

Where series-name is one of the series types.

**Comment by cchristopherhowardd** [comment]
I’ll get back to you tomorrow about this.

Chris
-------
Christopher Howard
Communications Manager

**Comment by jasloe** [comment]
What do you think?
