### ISSUE TITLE
Create conditional field for displaying AAR security notice

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#154]
Can you change the text in the Notice box that appears on the Create Event pages to this?

**A valid photo ID is required for entry into the American Academy in Rome. Backpacks and luggage with dimensions larger than 40 x 35 x 15 cm (16 x 14 x 6 in.) are not permitted on the property. There are no locker facilities available.**

The specific changes are: (1) delete "Please note:"; (2) Start first sentence with capital A; (3) add a period after "in" in the parenthetical phrase; and (4) bold the entire text by default.

The Italian-language equivalent is:

**I visitatori dell’American Academy in Rome sono pregati di mostrare un documento d’identità all’ingresso. Non è possibile accedere con bagagli o zaini di dimensioni superiori a cm 40 x 35 x 15. Non sono disponibili armadietti né guardaroba.**

Because not every event takes place at the Academy, I am slowly going through past events to remove the text in the Notice box.

_Originally posted by @cchristopherhowardd in https://github.com/aarome/aarome/issues/111#issuecomment-472019864_

**Comment by cchristopherhowardd** [comment]
Are the Notice boxes turned off for most or all events? Because it's better if they are. I'll go through events for 2019 and maybe half of 2018 (September to December) and choose a notice for each. It does not matter if past events have a notice because, well, they're past events and we obviously can't police oversized bags. Besides, the body text for many, many events have the notice language within that body text, so a separate, activated notice field is totally redundant.

**Comment by cchristopherhowardd** [comment]
Is it possible to have the Italian translation page automatically select yes for Security Notice if the English-language page has it selected yes?

**Comment by cchristopherhowardd** [comment]
> Is it possible to have the Italian translation page automatically select yes for Security Notice if the English-language page has it selected yes?

OK I think it does this already.

**Comment by jasloe** [comment]
Can't remember how I set this up. Let me check.

**Comment by jasloe** [comment]
Ok....

The original field is called "Notice" and contains a default value that is applied to all Event nodes. 

I created another configuration that is more modular. It's a radio button that, when selected, connects the Event node to this content: 

https://dev.aarome.org/node/4654/edit

It sounds like we should 1) delete the first field entirely and 2) select this radio button for current and recent Event content. 

Do I have that right?

**Comment by jasloe** [comment]
> > Is it possible to have the Italian translation page automatically select yes for Security Notice if the English-language page has it selected yes?
> 
> OK I think it does this already.

If you select the security notice radio button at the time of node creation, it'll cascade down the translation.

If you select the security notice radio button after node creation, it won't cascade down. We'd have to write a hook that synchronizes the /en and /it fields.

**Comment by cchristopherhowardd** [comment]
<img width="390" alt="Screen Shot 2019-03-20 at 4 02 04 PM" src="https://user-images.githubusercontent.com/38765846/54715314-8d6d3e80-4b29-11e9-9d20-ee414ed331e0.png">

We should use the radio button only. Default for new and past events should be nothing (in use now) or N/A. I prefer nothing because it encourages me to choose one or the other. If N/A is checked by default, I might overlook it.

**Comment by cchristopherhowardd** [comment]
Can we use a smaller point size for the SECURITY NOTICE header? It's too big here. Would an <h4> of <h5> do?

The style sheet needs adjusting to place some space before the header, too, but you probably know that already.

**Comment by cchristopherhowardd** [comment]
I meant to write "Would an < h4 > or < h5 > do?

**Comment by jasloe** [comment]
In process: https://github.com/aarome/aarome/issues/158#issuecomment-474667648

**Comment by jasloe** [comment]
> <img alt="Screen Shot 2019-03-20 at 4 02 04 PM" width="390" src="https://user-images.githubusercontent.com/38765846/54715314-8d6d3e80-4b29-11e9-9d20-ee414ed331e0.png">
> 
> We should use the radio button only. Default for new and past events should be nothing (in use now) or N/A. I prefer nothing because it encourages me to choose one or the other. If N/A is checked by default, I might overlook it.

Ok, no problem. There's a way to conditionally trigger the security notice based on location selection. But we can configure that later.
