### ISSUE TITLE
Malformed block at /research

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#155]
Screenshot of webpage https://dev.aarome.org/research on Chrome while logged into AAR dev site.
<img width="944" alt="Screen Shot 2019-03-13 at 4 13 20 PM" src="https://user-images.githubusercontent.com/38765846/54311485-0c52fc00-45ab-11e9-832e-fd6f37365189.png">

_Originally posted by @cchristopherhowardd in https://github.com/aarome/aarome/issues/132#issuecomment-472587339_

**Comment by jasloe** [comment]
@cchristopherhowardd: is that looking ok now?

https://dev.aarome.org/research/archaeology

**Comment by cchristopherhowardd** [comment]
Looks good when I'm not logged into the dev site. When I log in, the text spans the screen like before.

**Comment by jasloe** [comment]
Oh right. I forgot to test for the site editor role! Sorry. Rebuilding the arch pages now.

**Comment by jasloe** [comment]
Cleaned this up. Much better, less code.
