### ISSUE TITLE
People - showing current year and previous years

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#156]
For now, can we show all Italian Fellows (https://dev.aarome.org/people/italian-fellows) that have relatively complete profiles, like we're doing for Residents (https://dev.aarome.org/people/residents)? And is it possible to have the Rome Prize Fellows' and Italian Fellows' date(s) appear under their name, like the Residents? This would be an easy way to identify the year of a fellow. Does this idea raise any conflicts or challenges?

**Comment by jasloe** [comment]
Would that be year only for RP and IF people? Do you want their dates to appear on each detail page, too?

**Comment by cchristopherhowardd** [comment]
I'm thinking out loud here.

**Comment by cchristopherhowardd** [comment]
> Would that be year only for RP and IF people? Do you want their dates to appear on each detail page, too?

Year only. So 2017 for people at the Academy in 2016 to 2017. Year should appear on detail page, too. Right now it looks like detail page for People is only producing some of the content for each individual: see https://dev.aarome.org/people/italian-fellows/carmen-belmonte for instance.

**Comment by jasloe** [comment]
Ok adding fields to IF, etc. is trivial. 

So it sounds like we want a date picker by year for People?

**Comment by cchristopherhowardd** [comment]
How is a date picker different from the range of dates we select for People?

A related request: can the order of people at https://dev.aarome.org/people/residents be reverse chronological order? I'd like the more recent people to appear at the top of each section.

**Comment by cchristopherhowardd** [comment]
I didn't mean to suggest that we dissolve the disciplinary categories at https://dev.aarome.org/people/residents. Can you reinstate Architecture, Literature, Visual Arts, and other categories?

**Comment by cchristopherhowardd** [comment]
Why do the disciplines "History of Art" and "Classical Studies & Archaeology" appear after "Visual Arts" on the Residents page? They should be in alphabetical order with the previous categories.

**Comment by jasloe** [comment]
> Is a date picker a drop-down selection that has a year or range of years? I'm thinking of the two VIEW sections at https://www.aarome.org/people/current/rome-prize-fellows.



> How is a date picker different from the range of dates we select for People?
> 
> A related request: can the order of people at https://dev.aarome.org/people/residents be reverse chronological order? I'd like the more recent people to appear at the top of each section.

Yes.

**Comment by jasloe** [comment]
> Is a date picker a drop-down selection that has a year or range of years? I'm thinking of the two VIEW sections at https://www.aarome.org/people/current/rome-prize-fellows.

We didn't have any specific plans for that though it's a good idea.

**Comment by jasloe** [comment]
Hi @cchristopherhowardd-- Can you take a look at:

https://dev.aarome.org/people/residents/marlon-blackwell
https://dev.aarome.org/it/comunita/residenti-invitati/marlon-blackwell

https://dev.aarome.org/people/rome-prize-fellows/allison-emmerson
https://dev.aarome.org/it/comunita/rome-prize-fellow/allison-emmerson

I've lost track of how to render these but I think this is close. I am trying to come up with clever template overrides to include accents in the breadcrumb and handle the repeating year. 

Specific questions: 

- /it date format is correct, yes?
- Regarding "Rome Prize Fellows", will that be translated? 
- Placement of title? I think it works in both places. Below breadcrumb is consistent with rest of site, but above right column looks better.

**Comment by jasloe** [comment]
Also, are there cases where portraits will take captions?

**Comment by cchristopherhowardd** [comment]
Yes, when we might use a reproduction of an artwork or performance or whatever instead of a head shot.

**Comment by cchristopherhowardd** [comment]
I glanced at the People pages for Fellows and Residents that you link to above. We're very close. I'll send my minor corrections and suggestions tomorrow.

**Comment by jasloe** [comment]
Ok cool...

**Comment by cchristopherhowardd** [comment]
I'm consulting Shawn and Marques about dates for Fellows, Residents, and Affiliated Fellows. For Residents, I'd like exact dates. The others are up in the air.

A stylistic note for dates: can you delete the character space on both sides of the en dash? I strongly prefer to present dates as, for example, December 17, 2018–January 7, 2019, per _The Chicago Manual of Style_.
<img width="550" alt="Screen Shot 2019-03-22 at 11 54 50 AM" src="https://user-images.githubusercontent.com/38765846/54835932-8ebd7900-4c99-11e9-8b6b-001a617ba6cf.png">

**Comment by jasloe** [comment]
No problem. Also, I have the beginning of a template override for the repeated year. Let me know when you know about dates for F, R, AF and I'll see what I can do to make that modular.

**Comment by cchristopherhowardd** [comment]
Let's do the full date range for Fellows, Italian Fellows, and Residents.

We should do full date ranges for Affiliated Fellows, too, but I will need to research them. Some of these are for a month, others three months. Some take place around the same time each year--but not always.

Shawn will soon provide me with the opening and closing dates for each fellowship year. This year, he tells me the fellowship year in September 10, 2018 to July 26, 2019.

**Comment by jasloe** [comment]
Ok, no problem. And you also want to show that date below the person's name on the /people/something pages, correct?

**Comment by cchristopherhowardd** [comment]
Yes, please show the date(s) below a person's name on the people/something pages.
