### ISSUE TITLE
Some views and breadcrumbs are untranslated

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#157]
@cchristopherhowardd: Some detail view URLs and breadcrumbs aren't translating correctly, ex.:

https://dev.aarome.org/it/events/calendar/2019-mckim-medal-gala

This should be:

https://dev.aarome.org/it/eventi/calendario/2019-mckim-medal-gala

& with the correct breadcrumb. 

These types of views are a little complicated though I have an idea of the root cause. 

I'd like to take most of today to resolve this. I could live with /it/events/calendar/* though the breadcrumbs were a late addition and will not work correctly without a correct URL. (Breadcrumbs are inherited from the URL.)

Anyway, it's a small thing but we've come pretty far and I want to get this right. Will report back in a bit.

**Comment by jasloe** [comment]
Holy crap that sucked! 

After a long day of debugging I came up with a solution. Think we're in good shape but will need end user testing. Will be in touch when I've pushed the new views!

**Comment by jasloe** [comment]
@cchristopherhowardd: ok I have this working on dev.

Event paths have their full paths translated and breadcrumbs are correct and working.

https://dev.aarome.org/events
https://dev.aarome.org/events/calendar
https://dev.aarome.org/events/calendar/2019-mckim-medal-gala

https://dev.aarome.org/it/eventi
https://dev.aarome.org/it/eventi/calendario
https://dev.aarome.org/it/eventi/calendario/2019-mckim-medal-gala

Of course, if the node title and body are translated, the last component of the /it URL will appear in Italian. 

I have a little style sheet clean up to do on these pages, then a bulk update of Event nodes. Until that happens, event detail pages will not be available.

**Comment by cchristopherhowardd** [comment]
Great, thanks! I won't update or make changes to any Events page until Monday.

**Comment by jasloe** [comment]
Cool. I'll have it untangled by then.

**Comment by jasloe** [comment]
I should add that I need to a few other views, incl. news features, people. The latter will resolve the special character encoding issue we discussed in another thread.

**Comment by cchristopherhowardd** [comment]
OK, I won't sweat the English/Italian URLs this week.

**Comment by jasloe** [comment]
> OK, I won't sweat the English/Italian URLs this week.

These are pretty much done. Just need to run a bulk update on all of the nodes, which I'll do at the end of the week. 

Now returning to refactoring stylesheets to account for changes as described here: 

https://github.com/aarome/aarome/issues/158#issuecomment-474667648
