### ISSUE TITLE
Diacritic or punctuation in People name

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#158]
Did we ever figure out URLs for people with punctuation in their name?

Doesn't work: https://dev.aarome.org/people/rome-prize-fellows/helen-o-leary
Works: https://dev.aarome.org/carl-d-alvia
Doesn't work: https://dev.aarome.org/people/italian-fellows/ila-b-ka

**Comment by cchristopherhowardd** [comment]
Drupal 7 allows me to reword URLs on pages, but I don't see such a feature while editing pages on the dev site.

**Comment by jasloe** [comment]
I have a solution for this that is actually part of the fixes #157 

Names will be transcoded to ASCII characters.

**Comment by jasloe** [comment]
This, along with #157, is just about done. In retrospect, adding multilingual, non-Unicode friendly breadcrumbs is non-trivial. Nothing to be done about it now except to see it through with logical, consistent breadcrumbs and URLs.

**Comment by jasloe** [comment]
@cchristopherhowardd: ok this is resolved for most content types, excepting News Features, which I will wrap up tomorrow. 

I had to rebuild some structure to a) make content work reliably with multi-lingual breadcrumbs b) incorporate non-ascii characters in URLs (i.e. Ila Bêka -> /ila-beka). Style sheets will need an extra class declaration or two to return them to their previous state.  

There's still the matter of things like Comunita showing without an accent grave, but I think I can override that easily.

**Comment by jasloe** [comment]
attualità, et al. now render correctly in breadcrumbs.
