### ISSUE TITLE
Translating disciplines

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#164]
Do we have a set of translated disciplines somewhere?

**Comment by cchristopherhowardd** [comment]
I'm sure it's somewhere, probably on the current website where a laundry list of disciplines is published. I'll look and send you the words.

**Comment by cchristopherhowardd** [comment]
Here are the basic translations of primary disciplines. A second message (coming soon) will have some secondary ones.

ancient studies – studi classici
architecture – architettura 
design – design 
historic preservation and conservation – conservazione e restauro dei beni storico-artistici
landscape architecture – architettura del paesaggio
literature – letteratura 
medieval studies – studi medievali
modern Italian studies – studi italiani moderni
musical composition – composizione musicale
Renaissance and early modern studies – studi sul Rinascimento e sulla prima età moderna
visual arts – arti visive

**Comment by cchristopherhowardd** [comment]
archaeology – archeologia
classical philology – filologia classica
classical studies – studi classici
history – storia
history of art– storia dell’arte 
history of architecture – storia dell’architettura
history of art and architecture – storia dell’arte e dell’architettura
history of literature – storia della letteratura
musicology – musicologia
religious studies – studi religiosi
anthropological studies – studi antropologici
jewelry design – design di gioielli
fashion design – design di moda
theatrical design – design di arredamento
theatrical design – design teatrale

**Comment by jasloe** [comment]
You should be able to edit/translate these terms directly at:

https://dev.aarome.org/admin/structure/taxonomy/manage/disciplines/overview

Just tested with a dummy site editor account. Let me know that it works for you.

**Comment by cchristopherhowardd** [comment]
Great, I'll do this tomorrow.

**Comment by cchristopherhowardd** [comment]
Translations completed.
