### ISSUE TITLE
Node editing

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#165]
@cchristopherhowardd-- let me know if you want node form elements to appear in a certain order. Easy to change to whatever you like. 

Note, that I changed things around on the content admin page. Selecting an event, news, or people node will take you directly to the front end page and not some chaotic, partially unstyled page. Much better!

**Comment by jasloe** [comment]
Unfortunately, basic pages will take you to chaos because I took a short cut when I set those up. We should fix this.

**Comment by cchristopherhowardd** [comment]
Ugh.

**Comment by jasloe** [comment]
It not a huge deal. That content won't change that often.

**Comment by cchristopherhowardd** [comment]
I knew the chaotic page after creating or saving something was unstyled, but a newer or unskilled user might get confused.

**Comment by jasloe** [comment]
Yeah, kind of a Drupal-specific quirk. Let me think about how to fix up the basic page editorial workflow without breaking the bank.

**Comment by jasloe** [comment]
Solution in the works!

**Comment by jasloe** [comment]
@cchristopherhowardd I finished the configuration for this. All nodes can be reached directly through admin/content now. I have to change a few lines of the style sheets to restore styling. Getting started on that now.
