### ISSUE TITLE
Home page translations

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#166]
Not sure how deeply you want to get into this...translation candidates text for home page....

Rome Prize
Time and space to think and werk
Meet the fellows
Join us in Rome
Apply for a Rome Prize
Explore other fellowships
Become a visiting artist or scholar
Apply
Other opportunities

**Comment by cchristopherhowardd** [comment]
The Italians may have suggestions for better words in time. Let's use these for now:

Rome Prize – same
Time and space to think and work – Tempo e spazio per pensare e lavorare
Meet the fellows – Incontra i borsisti
Join us in Rome – Unisciti a noi a Roma
Apply for a Rome Prize – Richiedi un Rome Prize
Explore other fellowships – Esplora altre comunioni
Become a visiting artist or scholar – Diventa un artista in visita o un erudito in visita
Apply –  Fai domanda
Other opportunities – Altre opportunità

**Comment by cchristopherhowardd** [comment]
Apply for a Rome Prize – **Richiedi** un Rome Prize

Richiedi isn't the correct Italian equivalent to "apply for." I've asked Rome for feedback on the above translations but haven't head back.

**Comment by jasloe** [comment]
This is done. Leaving open for feedback from Rome.

**Comment by cchristopherhowardd** [comment]
Rome says:

Join us in Rome – Partecipa ai nostri eventi a Roma
