### ISSUE TITLE
New slideshow library

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#168]
The old one was atrocious, caused elements to jump around on load. Additional tasks:

- [x] Configure plugin for sliding (currently fades in)
- [x] Rewrite prev/next CSS

**Comment by jasloe** [comment]
Placement of prev/next arrows is odd. Some event title/date stacks are long; others are short. 

The title window has to accommodate both. 

Arrows are pushed down to provide enough space for long titles. 

Options are: 

1. arrow track slides up/down consuming free space between title track and arrows (not ideal)
2. position arrows over image track, ex: https://www.newmuseum.org/

Preference?

![short-event-title](https://user-images.githubusercontent.com/1063667/55198724-92ffff80-518d-11e9-9416-348c576a007b.jpeg)
![long-event-title](https://user-images.githubusercontent.com/1063667/55198725-92ffff80-518d-11e9-8e27-25adef2ca39e.jpeg)

**Comment by cchristopherhowardd** [comment]
Position arrows over image track

**Comment by cchristopherhowardd** [comment]
Did we ever find a solution to the vertical image problem for slideshows used throughout the new site? A page like https://staging.aarome.org/news/features/2019-open-studios-musical-performances-readings, for example, has a few vertical images that take up as much screen real estate as the horizontal photos. These vertical images push the text down and are impossible to see in full on a laptop or desktop screen. Can a solution be found that is similar to the slideshows for Fellows and Residents on the homepage?

**Comment by jasloe** [comment]
Sure, for vertically-oriented images I plan on constraining the image height. I'll get started on this now.
