### ISSUE TITLE
Browser and OS support

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#17]
We'll likely use the [CSS Grid layout module](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) to position page elements. CSS Grid is a new system with full support for the modern editions of Edge, Chrome, Firefox, Opera, Safari, and iOS Safari.

The following **old** browsers are not supported (all will be 1-2 years at minimum by the site release date):

Internet Explorer 9 (or IE 11 and below if only considering the new spec)
Edge 15 and below
Firefox older than version 52
Safari and iOS Safari older than version 10.1
Chrome older than version 57
Samsung Internet older than version 6.2

As such, we'll build and live test modern browsers on MacOS, Windows, and iOS. Further tests can be executed with emulations. @cchristopherhowardd: for more extensive (and faster) automated tests, a [BrowserStack](https://www.browserstack.com/) subscription is required. 

See attached for browser and OS statistics.

[aarome-os.pdf](https://github.com/aarome/aarome/files/2017717/aarome-os.pdf)
[aarome-browser.pdf](https://github.com/aarome/aarome/files/2017718/aarome-browser.pdf)

**Comment by cchristopherhowardd** [comment]
I signed up for a BrowserStack account but will need to get approval before receiving a paid account. Is there a tier that you recommend for AAR?

**Comment by cchristopherhowardd** [comment]
CSS Grid layout module looks good--but are there no square shapes?

**Comment by jasloe** [comment]
The proportions can be arbitrarily defined.
