### ISSUE TITLE
Changes to Apply section

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#171]
The top of the Italian page for Affiliated Fellowships (https://dev.aarome.org/it/partecipazione/studio-affiliate) displays the photo used on the Apply section page (https://dev.aarome.org/it/partecipazione). This photo of Chuck Webster's should not be there!

**Comment by cchristopherhowardd** [comment]
The breadcrumb on Italian-language pages in the Apply section has a break of some kind. Inserted between items in the breadcrumb is this: {{ Title }} 

See https://dev.aarome.org/it/apply/affiliated-fellowships/acls-burkhardt-residential-fellowships for example.

**Comment by cchristopherhowardd** [comment]
The top two items on the Affiliated Fellowships index page in the Apply section (https://dev.aarome.org/apply/affiliated-fellowships) are not aligning horizontally. The CAORC box is the culprit.

**Comment by jasloe** [comment]
@cchristopherhowardd-- Ok, will fix. I'm pushing quite a few changes right now. These commits may include breaking changes but I'll get them resolved shortly.

**Comment by jasloe** [comment]
Hm....didn't quite get all of these squashed today. Will revisit in the morning!

**Comment by cchristopherhowardd** [comment]
Thanks!
