### ISSUE TITLE
Headlines for News Features, Quick News, Events

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#172]
Something is capitalizing the first letter in each word of the title. Can capitalization in titles match what it typed into the field?

For example, at https://dev.aarome.org/news/features/announcing-2019-20-rome-prize-winners-italian-fellows, "the" and "and" should be lower case.

At https://dev.aarome.org/events/calendar/water-culture-view-rome, "and" and "from" should be lowercase.

**Comment by jasloe** [comment]
Ah good catch. That’s an easy fix.
