### ISSUE TITLE
Internal linking customization

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#173]
I need a target="_blank" option for inserting links. The current site has this option (see attached screenshot). The new site does not have it but needs to.

<img width="580" alt="Screen Shot 2019-04-10 at 2 48 31 PM" src="https://user-images.githubusercontent.com/38765846/55905420-e582e800-5b9f-11e9-83b8-6300da018e00.png">

**Comment by jasloe** [comment]
Added an open new window checkbox (and a few other things we may need).

**Comment by cchristopherhowardd** [comment]
I'm getting an annoying LinkIt feature when I copy and paste a URL. Can you get rid of it, or modify it? I can't imagine a scenario in which I'm typing a URL instead of copying and pasting.

<img width="755" alt="Screen Shot 2019-04-24 at 10 26 11 AM" src="https://user-images.githubusercontent.com/38765846/56667492-ec1f5e00-667b-11e9-9818-48ef4373757a.png">

**Comment by jasloe** [comment]
The link widget both looks up nodes and accepts external URLs. The message simply gives notice that the external link doesn't match any internal paths. I can maybe look at parceling out the two functions into separate widgets if that's desirable.

**Comment by jasloe** [comment]
Looks like there's not much that can be done with this module without writing a fair amount of code to override its default behavior. If it is a showstopper, I can work on this as a maintenance task.

**Comment by jasloe** [comment]
Note that the desired _blank behavior is available under Advanced/Open in new window
