### ISSUE TITLE
Formatting Page Sections in /support

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#174]
We've lost proper header formatting for Section Titles on Page Sections on pages like https://dev.aarome.org/support/donate and https://dev.aarome.org/support/join-renew. On the former page, "In Memory of Pina Pasquantonio" and "Sponsorship" should be a header on the left side of the page. On the latter page, we've lost all formatting for Section Titles.

**Comment by cchristopherhowardd** [comment]
Methinks this error can be found site-wide.

**Comment by jasloe** [comment]
I think it's just the support section which was part of the style sheet merge I committed on Monday. (Sorry, was out sick yesterday and didn't get a chance to finish that up.) Will fix.
