### ISSUE TITLE
Security Notice

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#175]
Can the Security Notice on Event pages (e.g., https://dev.aarome.org/events/calendar/water-culture-view-rome) appear on the page in full? Right now, a browser must click on the link to read the notice, and the link opens on a new page.

**Comment by jasloe** [comment]
That was a bug. Fixed. The title – "Security notice" – still renders as a link. I'll roll a quick template override to remove the a href.

**Comment by jasloe** [comment]
@cchristopherhowardd -- 

https://dev.aarome.org/events/calendar/grear-patterson-forest-theater

**Comment by cchristopherhowardd** [comment]
Looks great!
