### ISSUE TITLE
/it breadcrumb shows {{ Title }} token

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#176]
The breadcrumb on Italian-language pages in the Apply section has a break of some kind. Inserted between items in the breadcrumb is this: {{ Title }} 

See https://dev.aarome.org/it/apply/affiliated-fellowships/acls-burkhardt-residential-fellowships for example.

_Originally posted by @cchristopherhowardd in https://github.com/aarome/aarome/issues/171#issuecomment-480390852_

**Comment by cchristopherhowardd** [comment]
Can "Partecipazione" and "Affiliated Fellowships" (with a capital F because it's a header) take the same typeface and point size?

**Comment by jasloe** [comment]
This was part of #166 and just pushed to production. Fixed.
