### ISSUE TITLE
People pages for residents

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#177]
On the people pages for residents (e.g., https://dev.aarome.org/people/residents/marlon-blackwell), can you replace the header "Project description" with "Biography"?

**Comment by jasloe** [comment]
That's a matter of copying the project description to the biography field.

https://dev.aarome.org/people/residents/marlon-blackwell

**Comment by cchristopherhowardd** [comment]
I'm copying the text now.

Text in the biography field is rendering in the sans serif font Trade Gothic. The text should be serif (Gravitas or whatever it's called). See https://dev.aarome.org/people/residents/stefan-sagmeister for example.

**Comment by jasloe** [comment]
Added styling to support new field.
