### ISSUE TITLE
Quick News links

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#178]
I noticed that we no longer have links for individual items in the Quick News section (https://dev.aarome.org/news/quick-news). On the current site (lower right corner of https://www.aarome.org/), the text "Read More" links to an external webpage. On the back end, we add this as an Internal Link with a Title and URL. See https://www.aarome.org/node/2224707/edit?destination=admin/content for the most recently published Quick News. How can this information be migrated to the new site? It seems like the photo on the dev site can be a link to the external webpage (with a target="blank"). We could make the headline and body text a combined link, too, like we did for the section/index pages across the new site.

**Comment by jasloe** [comment]
Maybe include a link with the title of the external url to make it clear to the user they'll be leaving aarome.org?

Ex.:
Matter Design Is PS1 Finalist
The Architect Newspaper  (https://archpaper.com/2018/12/moma-yap-2019-finalists/)

**Comment by cchristopherhowardd** [comment]
We could use phrases like "Read more from the _Architect Newspaper_" or "Read more from the _New York Times_" but we would have to write something for each and every Quick News item.

**Comment by cchristopherhowardd** [comment]
Can we just reimport the Quick News and include the external link text and URL?

<img width="1332" alt="Screen Shot 2019-04-30 at 11 12 04 AM" src="https://user-images.githubusercontent.com/38765846/56972397-e83a8280-6b38-11e9-8c5d-b6d5c0126ac3.png">

**Comment by cchristopherhowardd** [comment]
Then, underneath the body text, include the external link text (e.g., Read More, Learn More) and the URL, making sure that the webpage opens in a new tab.

<img width="1332" alt="Screen Shot 2019-04-30 at 11 12 04 AM" src="https://user-images.githubusercontent.com/38765846/56972629-50896400-6b39-11e9-9452-53c46ef7b5e8.png">

**Comment by cchristopherhowardd** [comment]
Then, underneath the body text, include the external link text (e.g., Read More, Learn More) and the URL, making sure that the webpage opens in a new tab.

<img width="743" alt="Screen Shot 2019-04-30 at 11 14 13 AM" src="https://user-images.githubusercontent.com/38765846/56972674-6565f780-6b39-11e9-84a6-c600cb542780.png">

**Comment by jasloe** [comment]
Like so? 

There are a couple of ways to do this.

We can either: 

1. Enter arbitrary text (i.e. "Read more") in the node edit page at Links(s)/Link text. 

or 

2. Rewrite the URL at the view with "Read more" applied to all nodes.

I've configured the latter here (though un-styled at the moment):

https://dev.aarome.org/news/quick-news

Option 2 will always work. Option 1 is useful if you want the text to be something other than "Read more".

**Comment by cchristopherhowardd** [comment]
Option 2 is fine. Can the words "Read more" be styled differently? Perhaps bold, all caps, and underlined, like the "LOAD MORE" links for Quick News, Events, etc. 

In any case, the READ MORE link should be closer physically to the Quick News item above it. Right now "Read more" is sometimes closer to the Quick News item below it. Across the board there should be more white space between READ MORE and the Quick News item below it.

**Comment by jasloe** [comment]
Yes, I haven't styled it yet. Will do.
