### ISSUE TITLE
Next 30 days

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#179]
Stub for new calendar feature.

**Comment by jasloe** [comment]
@cchristopherhowardd -- ideas for translating 'next 30 days'?

**Comment by cchristopherhowardd** [comment]
It's going to be either "Previsioni 30 Giorni" or "Prossimi 30 Giorni." I'm awaiting confirmation of the better phrase.

**Comment by cchristopherhowardd** [comment]
The final decision: Prossimi 30 Giorni

**Comment by jasloe** [comment]
Ok, sounds good.

**Comment by cchristopherhowardd** [comment]
EVENTS!!!

Please note: on the index pages, put the Exhibitions box before the Full Calendar box. (Another note: the URLs for Calendar and Calendario can stay the same.)

English updates:

Next 30 Days
https://dev.aarome.org/events/calendar/next-30-days

Full Calendar replaces Calendar

Watch
https://livestream.com/aarome

Italian updates:

Eventi
New URL: https://dev.aarome.org/it/eventi

Prossimi 30 Giorni
https://dev.aarome.org/it/eventi/prossimi-30-giorni

Calendario Completo replaces Calendario

Mostra replaces Exhibitions
New URL: https://dev.aarome.org/it/eventi/mostra

Serie replaces Series
New URL: https://dev.aarome.org/it/eventi/serie

Guardare replaces Watch

**Comment by cchristopherhowardd** [comment]
Is it possible to keep events with an end date (such as an exhibition) that extends into the future on the Next 30 Days page? The exhibition _The Academic Body_ (which had an opening yesterday but is on view through July 13) has disappeared from https://dev.aarome.org/events/next-30-days.
