### ISSUE TITLE
Merging RP Fellowship names

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#18]
Given a longish list of named Rome Prize Fellowships, is it possible for someone more familiar with this data to flag duplicates? With that in hand, I can make the merges in the database.

[rp_terms.txt](https://github.com/aarome/aarome/files/2125396/rp_terms.txt)

**Comment by cchristopherhowardd** [comment]
I can go over this list with my colleague Shawn Miller, who as programs director for twelve years knows what's important and what's not. He returns tomorrow after two weeks' vacation.

**Comment by cchristopherhowardd** [comment]
Obviously many of these names are duplicates, contain typos, and the like.

**Comment by jasloe** [comment]
Sounds good. Leaving this open for now. 

When you're through evaluating values, I can merge them in the database.

**Comment by cchristopherhowardd** [comment]
Wow, what a slog. 
[Rome Prize Names.docx](https://github.com/aarome/aarome/files/2150552/Rome.Prize.Names.docx)

**Comment by jasloe** [comment]
I'll take a look. I have some ideas about how to prevent that from happening in the future.
