### ISSUE TITLE
Compressed dates

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#180]
Took a stab at a new date formatter.

https://dev.aarome.org/people/residents/marlon-blackwell
https://dev.aarome.org/it/comunita/residenti-invitati/marlon-blackwell

https://dev.aarome.org/people/residents/annabelle-selldorf
https://dev.aarome.org/it/comunita/residenti-invitati/annabelle-selldorf

**Comment by cchristopherhowardd** [comment]
I love it!

**Comment by cchristopherhowardd** [comment]
How do you feel about setting the dates in the serif typeface?

**Comment by jasloe** [comment]
Funny I was just writing to you about normalizing all of the dates. I think Open had a few different patterns. Let me pull that together.
