### ISSUE TITLE
Footer menu changes

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#182]
Changes to the Italian links for Publications:

Exhibition Catalogues to Cataloghi di Mostre

Academy Books to Libri Accademia

Affiliated Books to Libri Affiliati

Memoirs of the AAR to Memorie della AAR
New URL: https://dev.aarome.org/it/pubblicazioni/memorie

Supplements to the Memoirs  Supplementi alle Memorie
New URL: https://dev.aarome.org/it/pubblicazioni/supplementi-memorie

Papers & Monographs to Carte & Monografia
New URL: https://dev.aarome.org/it/pubblicazioni/carte-monografia

Cookbooks to Ricettari

**Comment by cchristopherhowardd** [comment]
Changes to one English and two Italian footer links in the Support section:

Support Opportunities
New URL: https://dev.aarome.org/support/support-opportunities

Iscriviti e Rinnova: replace e with &
New URL: https://dev.aarome.org/it/sostegno/iscriviti-rinnova

Support Opportunities to Opportunità di Supporto
New URL: https://dev.aarome.org/it/sostegno/opportunita-supporto

**Comment by cchristopherhowardd** [comment]
About section, English and Italian:

Tours
English page URL: https://dev.aarome.org/place/tours
Italian page URL: https://dev.aarome.org/it/luoghi/tours

Consiglio di Amministrazione
New URL: https://dev.aarome.org/it/informazioni/consiglio-amministrazione

Opportunita di Lavoro
New URL: https://dev.aarome.org/it/informazioni/opportunita-lavoro

Rome Sustainable Food Project to Roma Progetto Alimentare Sostenible on Italian page

**Comment by cchristopherhowardd** [comment]
People section changes:

Italian Fellows
New URL: https://dev.aarome.org/it/comunita/borse-studo-italiani

Vincitori di Borse di Studio Affiliate all’AAR becomes Borsisti Affiliati
New URL: https://dev.aarome.org/it/comunita/borsisti-affiliati

Visiting Artists & Scholars becomes Artisti & Studiosi Ospiti

Giurie & Advisors split into two items:

1. Consulenti for https://dev.aarome.org/it/comunita/consulenti
2. Giurie for https://dev.aarome.org/it/comunita/giurie

**Comment by cchristopherhowardd** [comment]
Giurie goes above Consulenti, just like Juries is above Advisors on the English footer menu.

**Comment by jasloe** [comment]
Tours lives at /about/place/tours. The 'about' component is for way-finding consistency (/about/place is a branch of /about).  

Almost done. Have to root out a few stale translation aliases. Hang on a few minutes.

**Comment by jasloe** [comment]
Also fixing all of the /it paths for apply, research, others.

**Comment by cchristopherhowardd** [comment]
Italian language phrases and URLs need updating in the Apply section (i.e., the Partecipazione section):

Rome Prize
New URL: https://dev.aarome.org/it/partecipazione/rome-prize

Borse di studio per italiani
New URL: https://dev.aarome.org/it/partecipazione/borse-di-studio-italiani

Borse di Studio Affiliate all'AAR – use curly apostrophe
New URL: https://dev.aarome.org/it/partecipazione/borse-di-studio-italiani

Artisti e Studiosi Ospiti – replace e with &
New URL: https://dev.aarome.org/it/partecipazione/artisti-studiosi-ospiti


Academic Programs becomes Programmi Accademici
New URL: https://dev.aarome.org/it/partecipazione/programmi-accademici

Roma Progetto Alimentare Sostenible
New URL: https://dev.aarome.org/it/partecipazione/roma-progetto-alimentare-sostenible

**Comment by jasloe** [comment]
Ok think I got everything with a couple of exceptions: I have to configure the translation parameters for webforms (and corresponding links) and clean up the translated press release and coverage views.

**Comment by cchristopherhowardd** [comment]
One quick edit for About/Informazioni footer, for English and Italian.

Please place "Jobs & Internships" before "Rome Sustainable Food Project"
Please place "Opportunita di Lavoro" before "Roma Progetto Alimentare Sostenible"

**Comment by cchristopherhowardd** [comment]
One missed update for People/Comunita:

"Vincitori di Borse di Studio Affiliate all’AAR" becomes "Borsisti Affiliati"

I'd like the URL for the page to change, too, from https://dev.aarome.org/it/comunita/studio-affiliate to https://dev.aarome.org/it/comunita/borsisti-affiliati

**Comment by cchristopherhowardd** [comment]
I thought that I pasted the Events changes yesterday. Here they are:

**Please note:** on the index pages, put the Exhibitions box before the Full Calendar box. (Another note: the URLs for Calendar and Calendario can stay the same.)

**English updates:**

Next 30 Days
https://dev.aarome.org/events/calendar/next-30-days

Full Calendar replaces Calendar

Watch
https://livestream.com/aarome

**Italian updates:**

Prossimi 30 Giorni
https://dev.aarome.org/it/eventi/prossimi-30-giorni

Calendario Completo replaces Calendario

**Comment by jasloe** [comment]
I just crawled all of the Footer links. I have to haggle with the request/submit forms a bit more to get those URLs to translate properly. 

Let me know if it all checks out on your end and we'll close this ticket.

**Comment by cchristopherhowardd** [comment]
Most everything checks out. I'll double check a few things and let you know momentarily.

**Comment by cchristopherhowardd** [comment]
People/Comunita section

Vincitori di Borse di Studio Affiliate all’AAR becomes Borsisti Affiliati
New URL: https://dev.aarome.org/it/comunita/borsisti-affiliati

**Comment by cchristopherhowardd** [comment]
About/Informazioni section:

Please place "Jobs & Internships" before "Rome Sustainable Food Project"
Please place "Opportunita di Lavoro" before "Roma Progetto Alimentare Sostenible"
