### ISSUE TITLE
Override "add another item" entity references

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#19]
Replace "add another item" on /node/add/* forms with something more useful, like a + graphic.

**Comment by cchristopherhowardd** [comment]
What kinds of things can we add? Graphic (JPG, GIF), document (Word, PDF). What else?

**Comment by jasloe** [comment]
This is meant to describe overriding the user interface for adding images. 

If you go to:

https://dev.aarome.org/node/add/people

You'll see "Add new image" and "Add existing image". (Formerly, it read 'add another item', which is sort of cryptic.)

Regarding documents and images, I added a page to the wiki and instructional text to the upload form.

https://github.com/aarome/aarome/wiki/Supported-file-types

**Comment by cchristopherhowardd** [comment]
Same here—access is denied.

Chris
-------
Christopher Howard
Communications Manager
