### ISSUE TITLE
Select list, sorting for People

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#192]

**Comment by jasloe** [comment]
@cchristopherhowardd --

I have this working in a very basic way. There's one small hitch. The custom date filter expects a year and our RP fellow nodes stores a date range, e.g. 09/01/2018 – 7/31/2019. Which end of the date range should I use? Put more broadly are current RP fellows the "class of 2018" or "class of 2019"? (Sticking with the academic year analogy, it would seem the latter would make more sense.

**Comment by cchristopherhowardd** [comment]
We refer to people with the date range September 2018 to July 2019 as "2019 Fellows."

The anomalous thing is that Residents, Italian Fellows, and Affiliated Fellows who are in Rome in fall and winter 2018 are still called 2019 Residents.

That means this guy is a 2019 Resident, even though his dates are from 2018: https://dev.aarome.org/people/residents/edward-hirsch. 

The same with this guy: in Rome in 2018 but called a 2019 Italian Fellow: https://dev.aarome.org/people/italian-fellows/francesco-zorzi

**Comment by jasloe** [comment]
I see. Makes a certain amount of....sense?

I think we may need to tag these folks with a year, outside of the date range field, and be done with it.

**Comment by jasloe** [comment]
@cchristopherhowardd -- 

Ok, RP fellows year sorting is working pretty well now. For testing purposes, I'm displaying the new field, affiliation year, and displaying all content.

**Comment by jasloe** [comment]
Closing this in favor of #197
