### ISSUE TITLE
Theming bugs

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#193]
~~Tune up date formatter: https://dev.aarome.org/events/exhibitions~~
~~Fix title padding at: https://dev.aarome.org/events~~
~~Fix title padding at: https://dev.aarome.org/events/calendar~~
~~Reposition slide show arrows: <front> and /events~~
News feature ss needs to be tuned: https://dev.aarome.org/news/features/milton-gendel-tribute

**Comment by jasloe** [comment]
@cchristopherhowardd --

Screen jitter on page load? Are you seeing this? 

https://drive.google.com/file/d/1FjIN7swkQZIPjAxmN0Og3k4NahPqnlBh/view?usp=sharing

Super annoying.

**Comment by jasloe** [comment]
@cchristopherhowardd --

Temporarily disabled header navigation to troubleshoot.

**Comment by cchristopherhowardd** [comment]
I don't understand what a screen jitter is. Perhaps that's because I haven't seen one on the site?
