### ISSUE TITLE
Select list, series

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#195]
When selecting a particular series, any event tagged as Exhibition does not show up in the results. 

For example, choosing the series Cinque Mostre produces only collateral events, not the exhibitions themselves. And when choosing New Works in the Arts and Humanities: East and West, the exhibitions tagged with that series do not show up in the results (here, the Yto Barrada exhibition should appear first.)

**Comment by jasloe** [comment]
Try it now.

**Comment by cchristopherhowardd** [comment]
It works.
