### ISSUE TITLE
Fix plain address formatting, date component ordering

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#196]
@cchristopherhowardd --

Event in Rome:
https://dev.aarome.org/events/calendar/conversations-conversazioni/mark-robbins-patricia-cronin-stefan-sagmeister-visible

https://dev.aarome.org/it/eventi/calendario/conversations-conversazioni/mark-robbins-patricia-cronin-stefan-sagmeister

Event in NY:
https://dev.aarome.org/events/calendar/conversations-conversazioni/2019-arthur-janet-c-ross-rome-prize-ceremony

https://dev.aarome.org/it/eventi/calendario/conversations-conversazioni/2019-arthur-janet-c-ross-rome-prize-ceremony

To render cities, states, etc. Italian you'll need to translate the referenced place node.

**Comment by cchristopherhowardd** [comment]
Rome needs to be Roma for the Italian-language pages.

**Comment by cchristopherhowardd** [comment]
Can US states be postal abbreviations? NY instead of New York, CA instead of California.

**Comment by jasloe** [comment]
Sure! Just pushed to dev. Can you test?

**Comment by jasloe** [comment]
> Rome needs to be Roma for the Italian-language pages.

Ack, there's a snag with that which I'll explain at 2. I have a clunky workaround I'm not very happy about it but it'll work....

**Comment by cchristopherhowardd** [comment]
Looks good.
