### ISSUE TITLE
add news byline to main content section

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#200]

**Comment by cchristopherhowardd** [comment]
Has the byline field been added to News Features?

**Comment by jasloe** [comment]
I just pushed that to development. The lookup is performed against the People content type, so you'll need to add the desired author there first.

**Comment by cchristopherhowardd** [comment]
Great. Remember that the byline and date of a News Feature article should be placed below the headline and above the image!

**Comment by jasloe** [comment]
How's that? 

https://dev.aarome.org/news/features/scrutinizing-academic-body

**Comment by cchristopherhowardd** [comment]
Beautiful!
