### ISSUE TITLE
add discipline to IF

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#202]

**Comment by jasloe** [comment]
@cchristopherhowardd -- is this still needed? I can't quite recall what the issue was here.

**Comment by cchristopherhowardd** [comment]
This is done, no? The People page for Italian Fellows (https://dev.aarome.org/people/italian-fellows) categorizes folks by discipline now.

**Comment by cchristopherhowardd** [comment]
I can confirm that "Historic Preservation & Conservation" can be removed from the discipline drop-down for Italian Fellows.

**Comment by jasloe** [comment]
> This is done, no? The People page for Italian Fellows (https://dev.aarome.org/people/italian-fellows) categorizes folks by discipline now.

Yep, all set.
