### ISSUE TITLE
Quick News bug

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#204]
I found a Quick News bug: https://dev.aarome.org/news/quick-news

If a URL to an external site is long, the site cuts off part of the link. Look at "New Opera by Vittorio Montalti." The Read More button works property, but the the link for the photo/date/headline/summery block doesn't. 

"Katherine Ludwig Jansen ... Speculum" does the same thing.

**Comment by jasloe** [comment]
Try it now.

**Comment by cchristopherhowardd** [comment]
Problem solved.
