### ISSUE TITLE
Question about exhibition dates

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#207]
@cchristopherhowardd -- somewhere in the bowels of this issue queue (or possibly email) there is a recent note about making a minor change to events and their corresponding date sorting, specifically Exhibitions. Do you recall? If so, can you direct me to the issue?

**Comment by cchristopherhowardd** [comment]
Looking at https://dev.aarome.org/events/exhibitions

The string of information for the opening and closing dates for exhibitions is too long.

Now: Wednesday, May 22, 2019–7:00 PM–Saturday, July 13, 2019–7:00 PM

Preferred: Wednesday, May 22–Saturday, July 13, 2019
Preferred (spanning years): Wednesday, December 22, 2018–Saturday, January 13, 2019

**Comment by jasloe** [comment]
Best I can do at the moment is this:

Wednesday, May 22, 2019–Saturday, July 13, 2019

The problem is that there isn't a formatter available for the desired pattern that also respects the existing pattern we are using for events. 

I can write one after we move the project into production. Labeling issue as an enhancement and moving out of this milestone.

**Comment by cchristopherhowardd** [comment]
This format is good for now.
