### ISSUE TITLE
Finishing up webforms

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#208]
http://localhost:8081/research/desiderata
local.aarome.local/it/ricerca/desiderata

Translation

* * *

http://localhost:8081/research/rare-book-request
http://localhost:8081/it/node/4647

~~Fix last useful date~~
Fix /it url
Translation

* * *

http://localhost:8081/research/storage-request
http://localhost:8081/it/node/4676

~~Fix last useful date~~
Fix /it url
Translation

* * *

http://localhost:8081/research/missing-book
http://localhost:8081/it/node/4642

~~Fix last useful date~~
Fix /it url
Translation

**Comment by jasloe** [comment]
@cchristopherhowardd -- 

Need a little help wrapping up these translations. Mostly just a handful of fields, lefthand section titles, and the last segment of urls.

https://dev.aarome.org/research/rare-book-request
https://dev.aarome.org/it/ricerca/rare-book-request

https://dev.aarome.org/research/storage-request
https://dev.aarome.org/it/ricerca/storage-request

https://dev.aarome.org/research/missing-book
https://dev.aarome.org/it/ricerca/missing-book

https://dev.aarome.org/ricerca/desiderata
https://dev.aarome.org/it/ricerca/desiderata

http://local.aarome.local/news/press-inquiry
http://local.aarome.local/it/attualita/press-inquiry

https://dev.aarome.org/news/film-photo-request
https://dev.aarome.org/it/attualita/film-photo-request

**Comment by cchristopherhowardd** [comment]
I'm reviewing the forms now. The URLs for the Press Inquiry form don't work.

**Comment by jasloe** [comment]
> I'm reviewing the forms now. The URLs for the Press Inquiry form don't work.

Forms are on the dev server. 

~~http://local.aarome.local/news/press-inquiry~~
~~http://local.aarome.local/it/attualita/press-inquiry~~

to 

dev.aarome.org/news/press-inquiry
dev.aarome.orgit/attualita/press-inquiry

**Comment by cchristopherhowardd** [comment]
https://dev.aarome.org/it/ricerca/rare-book-request
https://dev.aarome.org/it/ricerca/richiesta-libro-raro

https://dev.aarome.org/it/ricerca/storage-request
https://dev.aarome.org/it/ricerca/richiesta-archiviazione

https://dev.aarome.org/it/ricerca/missing-book
https://dev.aarome.org/it/ricerca/libro-mancante

https://dev.aarome.org/it/ricerca/desiderata (Italian page OK)
https://dev.aarome.org/research/book-suggestion

http://local.aarome.local/it/attualita/press-inquiry
http://local.aarome.local/it/attualita/richieste-stampa

https://dev.aarome.org/it/attualita/film-photo-request
https://dev.aarome.org/it/attualita/richiesta-film-fotografia

https://dev.aarome.org/it/node/4678
https://dev.aarome.org/it/segnala-problema

**Comment by cchristopherhowardd** [comment]
Edits to https://dev.aarome.org/it/ricerca/richiesta-libro-raro

The headers on the left side of the page need Italian translations:

Contact information --> Informazioni sui contatti
Publication information --> Informazioni sulla pubblicazione
Additional information --> Informazioni aggiuntive

**Comment by cchristopherhowardd** [comment]
After someone completes and sends a form, can he or she see a message that says something like "Thank you for your request. An Academy representative will be in touch soon"? This could be a temporary message onscreen. Alternatively, a page could present this message with another sentence that reads "Return to the Request Forms & Services page" with a link to https://dev.aarome.org/research/library/request-forms or https://dev.aarome.org/it/ricerca/biblioteca/modulistica.

**Comment by cchristopherhowardd** [comment]
Edits to https://dev.aarome.org/it/ricerca/richiesta-archiviazione

The headers on the left side of the page need Italian translations:

Contact information --> Informazioni sui contatti
Publication information --> Informazioni sulla pubblicazione
Additional information --> Informazioni aggiuntive

In the form itself, change "Email address" to "Indirizzo email"

**Comment by cchristopherhowardd** [comment]
Changes to https://dev.aarome.org/it/ricerca/libro-mancante

The headers on the left side of the page need Italian translations:

Contact information --> Informazioni sui contatti
Publication information --> Informazioni sulla pubblicazione
Additional information --> Informazioni aggiuntive

In the form itself, change "Email address" to "Indirizzo email" and "Comments" to "Commenti"

This page should only publish the Italian-language instructions.
The apostrophe in the running text should be curly, not straight.
The running text needs padding or indentation on the left side of the screen (also needed for https://dev.aarome.org/research/missing-book).

**Comment by cchristopherhowardd** [comment]
Edits to running text of https://dev.aarome.org/research/missing-book

In the second sentence of the English text, delete "Please" and begin the sentence with "Provide"; add a curly apostrophe and an s to "author" [author's]; and add a serial comma after "number"

**Comment by cchristopherhowardd** [comment]
Changes to https://dev.aarome.org/research/book-suggestion

In the breadcrumb trail, change "Desiderata" to "Book Suggestions"

Add running text between breadcrumb tail and first header (Contact Information):

The AAR Library welcomes suggestions for the purchase of materials supporting the mission of the Academy. If you would like to recommend a title or publication for purchase, please submit the requested information below.

**Comment by cchristopherhowardd** [comment]
Changes to https://dev.aarome.org/it/ricerca/desiderata

Add running text between breadcrumb tail and first header (Contact Information, to be changed to Informazioni sui contatti, as indicated below]):

La biblioteca accoglie con favore i suggerimenti per l’acquisto di materiali di studi che supportono la missione dell’Accademia. Se si desidera suggerire un titolo o una pubblicazione per l’acquisto, si prega di inviare il modulo sottostante.

The headers on the left side of the page need Italian translations:

Contact information --> Informazioni sui contatti
Publication information --> Informazioni sulla pubblicazione
Additional information --> Informazioni aggiuntive

In the form itself, change "Email address" to "Indirizzo email" and "Comments" to "Commenti"

**Comment by cchristopherhowardd** [comment]
Changes to https://dev.aarome.org/research/rare-book-request

Add running text between breadcrumb tail and first header (Contact Information):

Access to rare books is available to registered AAR Library users only. Please request your materials before 10:00am on the day of consultation. Books are retrieved for review from 2:30 to 4:30pm.

Please see the **Access, Rules & Policies** page for more information about library access.

Note: The Access, Rules & Policies page bolded above is currently published as https://dev.aarome.org/node/3922. It should be https://dev.aarome.org/research/library/access-rules-policies. Check the link to the page at https://dev.aarome.org/research/library. The final running text does not need bold, as I have done above.

**Comment by cchristopherhowardd** [comment]
Changes to https://dev.aarome.org/research/storage-request

Add running text between breadcrumb tail and first header (Contact Information):

Requests from storage are available to registered AAR Library users only. Please place requests before 1:00pm on the day of consultation. Depending on the quantity of volumes requested, we may provide you with the requested books at the front desk of the library at 2:30pm, or we may ask you to accompany us to storage to consult and make scans on location. 

Please see the **Access, Rules & Policies** page for more information about library access.

Note: The link to phrase Access, Rules & Policies bolded above should be https://dev.aarome.org/research/library/access-rules-policies.

**Comment by cchristopherhowardd** [comment]
Changes to https://dev.aarome.org/it/ricerca/richiesta-archiviazione

The headers on the left side of the page need Italian translations:

Contact information --> Informazioni sui contatti
Publication information --> Informazioni sulla pubblicazione
Additional information --> Informazioni aggiuntive

In the form itself, change "Email address" to "Indirizzo email" and "Comments" to "Commenti"

Add running text between breadcrumb tail and first header (Contact Information, to be changed to Informazioni sui contatti, as indicated above):

Servizio disponibile solo per gli utenti della biblioteca registrati. La richiesta va fatta entro le 13:00 del giorno di consultazione. A seconda del numero dei volumi richiesti, gli stessi potranno essere disponibili al front desk della biblioteca alle 14:30, oppure potrà essere chiesto all’utente di accompagnare lo staff in magazzino per consultare i volumi e fare scansioni sul posto.

Per ulteriori informazioni sull’accesso alle librerie, consultare la pagina **Accesso, Regole & Politiche**.

Note: The Access, Rules & Policies page bolded above should link to https://dev.aarome.org/it/ricerca/biblioteca/accesso-regole-politiche.

**Comment by cchristopherhowardd** [comment]
Changes to https://dev.aarome.org/news/press-inquiry

Add fields for "Name" (or "First name" and "Last name") and "Email address" above "Job title."

**Comment by cchristopherhowardd** [comment]
Changes to https://dev.aarome.org/it/attualita/richieste-stampa

The headers on the left side of the page need Italian translations:

Contact information --> Informazioni sui contatti
Inquiry --> Domanda

Add fields for "Nome" "Cognome" and "Indirizzo email" above "Job title"

Translations are needed for the fields on the right side of the page:

Job title --> Titolo di lavoro
Media organization --> Compagnia dei media
Media organization website --> Sito web della compagnia dei media
Telephone number --> Numero di telefono
Inquiry --> Domanda
Deadline --> Scadenza

**Comment by jasloe** [comment]
Ok, that was a lot. Can you check it over? Not surprised if I miss something. I'll work on the notification message.

**Comment by cchristopherhowardd** [comment]
Changes to https://dev.aarome.org/it/attualita/richiesta-film-fotografia

The headers on the left side of the page need Italian translations:

Contact information --> Informazioni sui contatti
Production details --> Dettagli della produzione

Translations are needed for the fields on the right side of the page:

Name --> Titolo di lavoro
Email --> 
Affiliation/organization --> Compagnia dei media
Affiliation/organization website --> Sito web della compagnia dei media
Telephone number --> Numero di telefono
Your relationship to AAR (if any) --> La tua relazione con AAR (se presente)
Type of production --> Tipo di produzione
Brief explanation of your project and the reason you would like to film at AAR --> Breve spiegazione del tuo progetto e la ragione per cui vorresti filmare in AAR
Size of proposed team or crew --> Dimensioni della squadra o dell’equipaggio proposte
What type of equipment will you require for this project? --> Che tipo di attrezzatura hai bisogno per questo progetto?
Desired AAR location(s) --> Posizione desiderata presso AAR
How and where will the video or photos will be used? --> Come e dove verranno utilizzati i video o le foto?

The send button should read Inviare la richiesta (replacing "Submit request")

**Comment by cchristopherhowardd** [comment]
Changes to https://dev.aarome.org/it/segnala-problema

The header on the left side of the page needs an Italian translation:

Technical information --> Informazioni tecniche

**Comment by cchristopherhowardd** [comment]
Changes to https://dev.aarome.org/it/ricerca/libro-mancante (part 2)

The apostrophe in the running text should be curly, not straight.

**Comment by cchristopherhowardd** [comment]
Edits to running text of https://dev.aarome.org/research/missing-book (part 2)

In the second sentence of the English text, delete "Please" and begin the sentence with "Provide"; add a curly apostrophe and an s to "author" [author's]; and add a serial comma after "number"

**Comment by jasloe** [comment]
> Edits to running text of https://dev.aarome.org/research/missing-book (part 2)
> 
> In the second sentence of the English text, delete "Please" and begin the sentence with "Provide"; add a curly apostrophe and an s to "author" [author's]; and add a serial comma after "number"

You should be able to edit the nodes that contain the webform header here. Let me know if you can't access:

https://dev.aarome.org/node/4642/edit?destination=/admin/content

**Comment by jasloe** [comment]
I've incorporated these changes. I'd like to final feedback on text translations today. 

I'll push a style sheet that fixes the header text shortly, as well as the form completion notification.

**Comment by cchristopherhowardd** [comment]
What are the outstanding text translations?

**Comment by jasloe** [comment]
> What are the outstanding text translations?

For the webforms. I might've missed something!

**Comment by cchristopherhowardd** [comment]
For https://dev.aarome.org/it/attualita/richieste-stampa: replace "Email address" with "Indirizzo email"

For https://dev.aarome.org/news/film-photo-request: need field for "Job Title" after name

For https://dev.aarome.org/it/attualita/richiesta-film-fotografia - need field for "Nome" before "Titolo di lavoro"

**Comment by cchristopherhowardd** [comment]
Changes to https://dev.aarome.org/it/attualita/notizie-veloci/submit

The headers on the left side of the page need Italian translations:

Contact information --> Informazioni sui contatti
News or Event Item --> Notizie o evento

Translations are needed for the fields on the right side of the page:

Name --> Nome
Email --> Indirizzo email
Fellowship or residency year --> Anno di fellowship o di residenza
Link to news or event --> Link a notizie o eventi
Description of news or event --> Descrizione di notizie o eventi


Box for "Send Message" should be "Invia"

**Comment by jasloe** [comment]
Ok, all set.

**Comment by cchristopherhowardd** [comment]
I came across the Library Access Form this week after realizing that there wasn't a form to request normal library access (not rare books or storage requests). We will need an English and Italian page for the form at https://docs.google.com/forms/d/e/1FAIpQLSeXwwVr7qY8ciKiTuPrzTCmbtgBssZ8wTZBhz0SqOnD8Drb4A/viewform?formkey=dHdhVmNpQmFNYlZQS3R6dFdncGg1ZEE6MQ#gid=0. 

The attached Word file contains the text needed for each page.

[Library Access Form.docx](https://github.com/aarome/aarome/files/3267538/Library.Access.Form.docx)

All the other forms look great!

**Comment by jasloe** [comment]
> Ok, that was a lot. Can you check it over? Not surprised if I miss something. I'll work on the notification message.

Regarding notification, options are a generic "thank you for submitting" (or whatever you like) or, better...

Redirect user to a page that contains a summary of what the user just submitted and whatever other text you like. 

[Example](https://dev.aarome.org/node/4648/webform/confirmation?token=-Fx6JVHau5CAtX0xKnzpMed8ltveMkJgfatlMlvHLok)

The latter is a bit out of scope and will take a little a few hours to organize and implement. Let me know which way you want to go.

**Comment by jasloe** [comment]
> I came across the Library Access Form this week after realizing that there wasn't a form to request normal library access (not rare books or storage requests). We will need an English and Italian page for the form at https://docs.google.com/forms/d/e/1FAIpQLSeXwwVr7qY8ciKiTuPrzTCmbtgBssZ8wTZBhz0SqOnD8Drb4A/viewform?formkey=dHdhVmNpQmFNYlZQS3R6dFdncGg1ZEE6MQ#gid=0.
> 
> The attached Word file contains the text needed for each page.
> 
> [Library Access Form.docx](https://github.com/aarome/aarome/files/3267538/Library.Access.Form.docx)
> 
> All the other forms look great!

Great. I just added in the required field indicator. One of my younger associates pointed out that people don't automatically understand that (*) means "required field" so I'll add some text to the header that states just that. 

Regarding the new form and the possible form submission pages I described above, are there still maintenance hours to tap into?

**Comment by cchristopherhowardd** [comment]
> Regarding the new form and the possible form submission pages I described above, are there still maintenance hours to tap into?

I don't know. The last invoices I received from you are from April. Last Friday I submitted the final invoice for the migration and redesign to Matt for payment.

**Comment by cchristopherhowardd** [comment]
Can you add my email address, c.howard@aarome.org, to the recipients of all web forms? For the first several months, I'd like to receive every submission in order to see how they function. Thanks!
