### ISSUE TITLE
Drupal core update from 8.6.4 to 8.7.2 (or possibly 8.7.3)

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#211]
It's time for Drupal core updates. There may be additional code updates to module code but can't say for sure until I start testing the core updates.

I'll also need to update the old site with a few security patches. It's several versions behind at the moment.

@cchristopherhowardd -- let me know if ok and I'll proceed.

**Comment by cchristopherhowardd** [comment]
OK to make the updates. I'll stay out of Drupal until you've finished.

**Comment by jasloe** [comment]
Come to think of it, I'm just going to roll up an entirely new server. I generally do this every summer anyway. The transition will be seamless and you won't notice any downtime or content synchronization problems. I'll have this done by end of the week.
