### ISSUE TITLE
URL translation management is dumb

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#212]
For some god-only-knows-why reason, URL translation is broken. 

Apply this patch and rejoice in the lamb.

https://www.drupal.org/project/drupal/issues/2877994
https://www.drupal.org/pift-ci-job/1304972

https://www.drupal.org/files/issues/2019-05-29/2877994-140.patch

**Comment by cchristopherhowardd** [comment]
What the hell!

**Comment by jasloe** [comment]
This was more about me being stupid and less about the code itself being stupid.

**Comment by jasloe** [comment]
Patch works. Hopefully this is remedied for good in 8.8.
