### ISSUE TITLE
Gala page for current site

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#218]
I have created a page for the 2019 New York Gala on the current site, but it needs an adjustment that I can’t seem to figure out.

Basically, I need the image for the new page (https://www.aarome.org/support/2019-new-york-gala) to fit the width of the main column, and also second header match the other gala pages (such as https://www.aarome.org/support/2019-mckim-medal-gala). In other words, the unformatted phrase “2019 New York Gala” that is under the “View  Edit Translate Nodequeue” on the former page should be formatted like a similar header the latter page....

**Comment by jasloe** [comment]
Unfortunately, had to hack together a new template for this kind of support page! Will fix the left indentation.

**Comment by cchristopherhowardd** [comment]
How strange that a new template was needed!

**Comment by jasloe** [comment]
I don't think we had a template specifically for that layout (wide image, body below):
https://www.aarome.org/support/2019-new-york-gala

vs.

(thumbnail at left, body below):
https://www.aarome.org/support/2019-mckim-medal-gala
