### ISSUE TITLE
Facebook and Twitter Feeds on the AAR Homepage

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#225]
I cannot figure out how make the Facebook and Twitter feeds on the current AAR website work. We are killing these features on the staging website, of course, but they need to function on the current site!

https://www.aarome.org/

**Comment by jasloe** [comment]
There's something very wrong with the background job that pulls in the data. It very likely broke with a module update somewhere along the line. With some maintenance budget now allotted through the end of the FY, I can put some time into it. Will report back.

**Comment by cchristopherhowardd** [comment]
Does changing the password of the FB or TW account affect the data grab?

**Comment by jasloe** [comment]
No, both use API keys. 

I'd like to confirm the Twitter credentials array. 

Go to: https://developer.twitter.com and login with your Twitter credentials. Go to the API keys tab.

Copy and paste the following into a privnote and post the privnote link here.

https://privnote.com/

Account Name
Consumer Key
Consumer Secret
Oauth Token
Oauth Token Secret

**Comment by jasloe** [comment]
Regarding FB, it looks like the public access token has expired. I'll need access to Academy Facebook account to reset the token.

**Comment by cchristopherhowardd** [comment]
c.howard@aarome.org
GVio.K]Y]UN22AuUfQYLLXGE2gYUkuL

**Comment by cchristopherhowardd** [comment]
Twitter https://privnote.com/QfeDRrVV#2uLxgYiOF

I don't know where the Oauth Token and Oauth Token Secret are found.

**Comment by cchristopherhowardd** [comment]
Access token info https://privnote.com/4oVqlfx6#Iv8j9MeMz

**Comment by cchristopherhowardd** [comment]
Was this task actually completed? I still see March 2019 posts for Facebook and January 2019 posts for Twitter at https://www.aarome.org/.

**Comment by jasloe** [comment]
Yes. Refer to #226. The legacy site was updated to the latest Drupal 7 stable release, as well as PHP and Apache. Once you've had a chance to look it over and approve, let me know and I'll cut the site over. There may be some content that needs to recreated on the updated site.

**Comment by jasloe** [comment]
Follow these steps to add a host record and view the updated site:

https://github.com/aarome/aarome/issues/226#issuecomment-511549207

**Comment by jasloe** [comment]
Ugh. The Facebook feed died again. 

Throws the following error:
```
Exception: Download of https://graph.facebook.com/157261774241/feed?access_token=1022096097814320|B4RWJHFjeefkRjS23UtRBVTQPXk failed with code 400. in FeedsHTTPFetcherResult->getRaw() (line 52 of /var/www/drupal/web/sites/all/modules/contrib/feeds/plugins/FeedsHTTPFetcher.inc).
```

**Comment by jasloe** [comment]
Furthermore, a conventional http request returns: 

```
{
   "error": {
      "message": "(#10) To use 'Page Public Content Access', your use of this endpoint must be reviewed and approved by Facebook. To submit this 'Page Public Content Access' feature for review please read our documentation on reviewable features: https://developers.facebook.com/docs/apps/review.",
      "type": "OAuthException",
      "code": 10,
      "fbtrace_id": "AEWoMe_idGzHSv4WBbRRNED"
   }
}
```

**Comment by jasloe** [comment]
New API access token here:

```
https://graph.facebook.com/157261774241/feed?access_token=EAAOhl0rWJzABAJlkj2xKC6BB4NOZBMuZCuWz8XQxZB4EVXbeud3Mc19N5pVfJzZBcfdwfQzYdk059bxccL0clzHaNLP1kZB9KJJpIxrVZCVA00qhfFZC0IpWtgaXfbOuIAEkZB4d9isvrgiAj6yksUWY9Qe2tgzSbnF9KIwGK0FpL0oOQrvS3ZBIBJS2OThAzZBhMZD
```

Closing. Will monitor and reopen if FB changes their policy (again) or key gets borked (again).
