### ISSUE TITLE
PHP 5.5 no longer recommended

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#226]
Drupal 7 site runs on PHP 5.5 As of May 2019 (or possibly eariler), PHP 7.2 is recommended. 

Build new server with PHP 7.2/Apache 2.4 to run aarome.org until new site is released.

**Comment by cchristopherhowardd** [comment]
I had no idea the current site is breathing ancient PHP fumes!

**Comment by jasloe** [comment]
It's a pretty old project in website years (6 yrs 9 mos to be exact)! 

Here's the support matrix. 

![php_2018_10_support_timeframe](https://user-images.githubusercontent.com/1063667/60838019-b9bfd000-a197-11e9-8194-37630b55d930.png)

**Comment by jasloe** [comment]
A running list of patches needed to upgrade from PHP 5.5 to 7.2.

Editable fields
https://www.drupal.org/files/issues/editablefields-php7-compatibility-2686329-1.patch

Nodequeue
https://www.drupal.org/files/issues/nodequeue-php-7-deprecated-warning-2638684-1-7-38.patch

**Comment by jasloe** [comment]
Remove VAVS/RSFP code from aarome.module.

**Comment by jasloe** [comment]
Replace SASS processor with a very slightly newer edition: https://github.com/richthegeek/phpsass

**Comment by jasloe** [comment]
@cchristopherhowardd -- on my local server, I have the following built and tested:

- PHP upgraded to 7.2
- MySQL updated from 5.5 to 5.7
- Apache updated from 2.2 to 2.4
- Drupal core updated to latest stable release
- Twitter feed working 

I'll build a new public server and starting move the current site over.

**Comment by jasloe** [comment]
@cchristopherhowardd -- 

I found this an app to manage your host files. This will let you see projects that aren't published to the web, e.g.: the upgraded edition of the current aarome.org site. 
 
Download HostBuddy: https://clickontyler.com/hostbuddy/download/
Open HostBuddy. Close the Unlock/Serial Number screen.
Select Add Hosts.
Paste in:
```
3.221.120.1 aarome.org
3.221.120.1 www.aarome.org
```
Select Apply Changes, then Flush Cache. 

You should be able to view the upgraded site by navigating to http://www.aarome.org.

This upgrade is ready for testing.

Only remaining tasks are installing an SSL certificate and turning on the Twitter/Facebook feeds.

**Comment by jasloe** [comment]
SSL cert installed and file permissions set. Fonts will come online when the DNS is changed to the upgraded Drupal 7 site. 

@cchristopherhowardd -- it looks like I'll need access to the Academy Facebook page in order to create a new app that Drupal can pull from.

**Comment by jasloe** [comment]
@cchristopherhowardd -- I was actually able to pass the token to Facebook without an app, so need for access. 

Looks like there's a small volume new-ish content on the D7 site that will need to be manually copied to the upgraded D7 server.

**Comment by jasloe** [comment]
@cchristopherhowardd -- 

Were you able to access the upgraded edition of aarome.org? Let me know if you need help.

**Comment by cchristopherhowardd** [comment]
I just completed the HostBuddy tasks. On what day was the currently live AAR website and the upgraded edition in sync? I will need to update the upgraded website with the changes made to the live website, as best I can.

**Comment by cchristopherhowardd** [comment]
It seems like any updates made to the website for nearly a month have been wiped out. Is there any way we can recover the previous website?

**Comment by jasloe** [comment]
Yes the site was updated 25 days ago and awaiting feedback since then. 

https://github.com/aarome/aarome/issues/226#issuecomment-511549207

There's really no way to shuttle content over from the old site to the updated site without writing a migration which is pretty time consuming. Would a csv file of recent content be helpful?

**Comment by cchristopherhowardd** [comment]
Yes, a list (CSV file or otherwise) is all that I need.

**Comment by jasloe** [comment]
This export goes back to July 5. I included the HTML markup where appropriate to simplify adding the content to the Drupal 8 site. Images and PDF files included in the attached zip.

[aarome-content.xlsx](https://github.com/aarome/aarome/files/3493975/aarome-content.xlsx)

[aarome-new-content.zip](https://github.com/aarome/aarome/files/3493971/aarome-new-content.zip)

**Comment by cchristopherhowardd** [comment]
What version of the website is live now? Because a coworker and I are seeing different information on the same webpages. Here is one example: https://www.aarome.org/support/2019-new-york-gala

I just updated the page so that Wendy Fisher's telephone extension is 352, not 350. A coworker is loading the same page and sees the extension 348. Browsers on my laptop show 352, but browsers on my iMac and on my iPhone show the same page with ext. 348--even after I clear my browser cache completely.

**Comment by cchristopherhowardd** [comment]
We have the regular aarome.org and an alternate universe aarome.org occupying the same internet space!!!

**Comment by jasloe** [comment]
aarome.org prime IP address: 54.83.63.20
aarome.org alternative universe IP address: 3.221.120.1

Your co-worker (and the rest of the world) is on aarome.org prime (i.e. running PHP 5.x, social media blocks not working), i.e. the live-to-the-world site. 

You are in the alternate universe (PHP 7.x, social media blocks working). Your HostBuddy-enabled host file is the portal to the alternate universe. 

In order to see aarome.org prime, you'll need to change your host file back to the aarome.org address: 54.83.63.20.

In order to merge the alternate universe into mainstream reality, you'll need to recreate the content included in the attachments in this thread. When that is complete, I can take it from there.

**Comment by cchristopherhowardd** [comment]
Shouldn't the alternate universe website be the one the world sees? The PHP 7.x site is the most current version, right? I don't understand why I would re-create content added to alternate universe site to the prime site.

**Comment by cchristopherhowardd** [comment]
Can the alternate universe site replace the prime site?

**Comment by jasloe** [comment]
That's the idea. As you pointed out above the upgraded site is lacking content from the last month. The spreadsheet contains content from the last month. It needs to be added to the upgraded site to bring it current.

**Comment by cchristopherhowardd** [comment]
I've been updating the alternate universe (AU) site (upgraded site?) for a few weeks now. Can we just flip the switch and make the AU site live, and I'll make any updates to it if necessary? I'd like to stop using the outdated prime site as soon as we can.

**Comment by jasloe** [comment]
Sure. I'll swap the IP addresses this evening. Should be propagated by the time you get in tomorrow.

**Comment by jasloe** [comment]
Did not have a chance to get to this last night. Will make the change this afternoon.

**Comment by jasloe** [comment]
@cchristopherhowardd -- ok all set. The upgraded site is now live-to-the-world.

**Comment by jasloe** [comment]
Hm....looks like the fonts.com token is no longer valid. Do you happen to have the fonts.com login handy?

https://fast.fonts.com/jsapi/05630915-d662-40ba-ab52-f97ced095ab4.js

**Comment by cchristopherhowardd** [comment]
The website isn't loading for me.

<img width="1237" alt="Screen Shot 2019-08-19 at 9 10 15 AM" src="https://user-images.githubusercontent.com/38765846/63268026-44005700-c261-11e9-9f50-25e4a3e7dcf2.png">

**Comment by jasloe** [comment]
You'll need to dump your custom host file from HostBuddy.

**Comment by jasloe** [comment]
New fonts.com token applied. 

```
<script type="text/javascript" src="//fast.fonts.net/jsapi/68a0b0c7-64ef-4145-b55c-4e8692d35aaa.js"></script>
```

**Comment by cchristopherhowardd** [comment]
What should I do with this code?

**Comment by jasloe** [comment]
Nothing. Just for my record keeping.

**Comment by jasloe** [comment]
Where you able to access the live site?

**Comment by cchristopherhowardd** [comment]
Can you please explain why two version of the website were created in the first place? I have colleagues in Rome and New York who have become upset that information about the Rome Prize (and other pages) that was updated several weeks ago is no longer current. I cannot explain to them what happened, and why it happened, because I don't know the answer.

**Comment by cchristopherhowardd** [comment]
Also, wasn't the "alternate universe site" the version that was to be made public?

**Comment by jasloe** [comment]
Quick summary of our call:

- The Drupal 7 site's version of PHP was out of date. Upgrade to PHP 7 was necessary in order to get Facebook and Twitter feeds working again.
- PHP 5.x site content was migrated to PHP 7.2 site on an entirely new server on July 9.
- On the new server, I made the PHP update as well as a number of security patches and updates to Apache and MYSQL.
- Content drifted between the two sites from July 9 and August 9. Content editors continued to contribute to the old PHP 5.x site during that timeframe. 
- I provided a text file containing those contributions last week. These need to be added to the PHP 7.2 site (if they haven't been already). I'm happy to do the grunt work to get these integrated into the site. 
- Live site is online as of August 16. 

Outcomes:

- The old PHP 5.x site is still available. Its services are stopped at the moment and can be brought back online, if necessary.  
- We'll continue to use the GitHub ticketing system. 
- I'll provide more explicit communication about the status of staging vs. production servers when appropriate. 
- The Drupal 8 edition of the site will use discreet namespaces to prevent confusion, i.e. staging.aarome.org (staging site for client testing, viewable only by developer and client), aarome.org (production site viewable by public).
