### ISSUE TITLE
Rome Prize Guidelines and FAQ

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#227]
The left-side headers at https://staging.aarome.org/apply/rome-prize/application and https://staging.aarome.org/apply/rome-prize/faq need to be appropriately styled with the larger typeface.

**Comment by jasloe** [comment]
Totally forgot about those pages. How does the user reach them?

**Comment by jasloe** [comment]
Those were never converted from view pages to node pages. Just transformed them and added translation paths. 

https://staging.aarome.org/apply/rome-prize/application
https://staging.aarome.org/it/partecipazione/rome-prize/application
https://staging.aarome.org/apply/rome-prize/faq
https://staging.aarome.org/it/partecipazione/rome-prize/faq
