### ISSUE TITLE
Society of Fellows - missing events

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#228]
I don't see events like https://staging.aarome.org/society-of-fellows/news-events/sof-events-march-2016 in the News & Events listings in the Society of Fellows section (https://staging.aarome.org/society-of-fellows/news-events). Can you add them?

**Comment by cchristopherhowardd** [comment]
On the current site, events are published at https://www.aarome.org/people/alumni/sof/events.

**Comment by jasloe** [comment]
A small number of records were incorrectly tagged. I've fixed this and added a temporary drop down filter to filter the view. Will fix filter label when #226 is complete. 

https://staging.aarome.org/society-of-fellows/news-events

**Comment by cchristopherhowardd** [comment]
The drop-down menu functions nicely in its temporary form. Thanks! I have reformatted the ill-formatted photos and cleaned up several headlines. 

It would be nice to have the arrow beneath each headline like we do on other pages (https://staging.aarome.org/news/features, https://staging.aarome.org/people, etc.).

**Comment by jasloe** [comment]
Fixed. I added the slideshow tweak to the SOF news/events nodes. Close if ok.

**Comment by jasloe** [comment]
@cchristopherhowardd --

Can this be closed?
