### ISSUE TITLE
People - move Society of Fellows box

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#229]
On the index page for People (https://staging.aarome.org/people), can you move the Society of Fellows box from last (bottom right) to sixth (second from bottom right), after Visiting Artists & Scholars and before Advisors?

The appropriate change would need to be made on the footer menu, moving Society of Fellows to after Visiting Artists & Scholars and before Advisors.

**Comment by jasloe** [comment]
Fixed.
