### ISSUE TITLE
Merging event data (types and locations)

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#23]
Oy. Lots of redundancy and weirdness.

Related to #18. 

[event_locations.txt](https://github.com/aarome/aarome/files/2125588/event_locations.txt)
[event_types.txt](https://github.com/aarome/aarome/files/2125589/event_types.txt)

**Comment by cchristopherhowardd** [comment]
A few similarly named fields can be combined. It looks like they're mostly redundant. For example, "British School in Rome - Via Antonio Gramsci 61" could be folded into "British School in Rome," and "AAR Gallery and Lecture Room" and "AAR Lecture Room and Gallery" could be combined (chosen by coin flip).

Many of these locations are for past events--and many are likely one-time only events. My feeling is to capture the name of the venue and drop the address in cases like the British School in Rome. 

Should I review the txt files and point out which lines can be combined?

**Comment by jasloe** [comment]
Ok. Note which values you want to merge, post the file here, and I'll take it from there.

**Comment by cchristopherhowardd** [comment]
Can I recategorize the Event Types on the current website before migration? For instance, I want to recategorize all events with the type "Jerome Lectures" to the type "Thomas Spencer Jerome Lecture Series." Can I do that now?

**Comment by jasloe** [comment]
No need to muck around with that. When I process the merge, all content will be automatically updated with the new term. You'll simply need to tell me which terms need to be merged. 

For example:

Merge id: 341 into id: 319, e.g.

event 1 - Jerome Lecture (id: 341)
event 2 - Jerome Lecture (id: 341)
event 3 - Thomas Spencer Jerome Lecture Series (id: 319)
event 4 - Jerome Lecture (id: 341)

to: 

event 1 - Thomas Spencer Jerome Lecture Series (id: 319)
event 2 - Thomas Spencer Jerome Lecture Series (id: 319)
event 3 - Thomas Spencer Jerome Lecture Series (id: 319)
event 4 - Thomas Spencer Jerome Lecture Series (id: 319)

**Comment by cchristopherhowardd** [comment]
I don't know the id numbers for Event Types. Do the instructions in this Word file make sense?
[Event Types.docx](https://github.com/aarome/aarome/files/2141534/Event.Types.docx)

**Comment by jasloe** [comment]
Yeah, you don't need the ids. That's just for demonstration purposes. Your doc is just fine, thanks.

**Comment by cchristopherhowardd** [comment]
Great. I just finished the remapping of Event Locations.
[Event Locations.docx](https://github.com/aarome/aarome/files/2142135/Event.Locations.docx)

**Comment by jasloe** [comment]
Tested out the merge code and it appears to work fine. I'll make the changes on the current production site so that we have a clean slate for migrations.

**Comment by jasloe** [comment]
@cchristopherhowardd: for your review.

<pre>
14	AIA Lecture
14	Benefit
14	Book Presentation
14	Ceremony
14	Colloquium
14	Concert
14	Conference
14	Conversation
14	Conversations That Matter
14	Conversations/Conversazioni
14	Exhibition
14	Fellow Shoptalks
14	Film Screening and Conversation
14	Home from Rome
14	Keynote
14	Lecture
14	Multimedia Conversation
14	Ongoing
14	Open Studios
14	Panel Discussion
14	Patricia H. Labalme Friends of the Library Lecture
14	Performance
14	Presentation
14	Reading
14	Reading and Musical Performance
14	Reunion
14	Seminar
14	Symposium
14	Talk
14	Thomas Spencer Jerome Lecture Series
14	Tour
14	Workshop
</pre>

**Comment by jasloe** [comment]
@cchristopherhowardd: How's this?

<pre>
15	AAR and Deutsches Historisches Institut
15	AAR Cryptoporticus
15	AAR Gallery
15	AAR Garden
15	AAR Lecture Room
15	AAR Lecture Room and Courtyard
15	AAR Lecture Room and Gallery
15	AAR Lecture Room and Istituto Svizzero
15	AAR Lecture Room and Museo Nazionale Romano di Palazzo Altemps
15	AAR Salone
15	AAR Studio 124
15	AAR Studio 125
15	AAR Studio 126
15	AAR Studio 127
15	AAR Studio 201
15	AAR Studio 253
15	AAR Studio 303
15	AAR Studio 309
15	AAR Studio 404
15	American Academy in Rome
15	American Academy in Rome Photo Archive
15	American Academy in Rome, 7 East 60th Street
15	American University of Rome
15	American University of Rome and American Academy in Rome
15	Angel Orensanz Foundation
15	Architectural League of New York
15	Arthur Ross Gallery, of the University of Pennsylvania
15	Biblioteca Angelica and AAR
15	Bibliotheca Hertziana, Max Planck Institute for Art History
15	British School at Rome
15	Casa delle Letterature
15	Casa delle Letterature and AAR
15	Casa dell’Architettura
15	Casa Italiana Zerilli-Marimò
15	Casa Rustica and Bass Garden
15	Centro Studi Americani and American Academy in Rome
15	Chicago Cultural Center
15	Columbia University
15	Depart Foundation
15	Fondazione Biagiotti Progetto Arte
15	Fondazione Isabella Scelsi
15	Four Seasons Restaurant
15	Frederick P. Rose Auditorium at Cooper Union
15	Harmonie Club
15	Istituto Nazionale per la Grafica
15	Italian Cultural Institute
15	John Cabot University
15	Knickerbocker Club
15	LETTERATURE Festival Internazionale di Roma
15	Longwood Gardens
15	MAXXI
15	McKim, Mead & White Building
15	McKim, Mead & White Building Cortile
15	Menil Collection
15	Metropolitan Club
15	MIT List Visual Arts Center
15	Morgan Library and Museum
15	Museo Carlo Bilotti
15	Museo Nationale Romano
15	Museum of Arts and Design
15	New School
15	New York Hilton Midtown
15	New York Studio School
15	Notre Dame Global Gateway
15	ODC Theater
15	Palazzo Colonna and AAR Lecture Room
15	Palmer House Hilton
15	Park Plaza Hotel
15	Piazza del Campidoglio
15	Plaza Hotel
15	Rice School of Architecture
15	Sala della Protomoteca, Campidoglio
15	Sapienza Università di Roma and AAR
15	SCI-Arc
15	Seagram Building
15	Stephan Weiss Studio
15	Swedish Institute in Rome
15	Tempietto del Bramante
15	Villa Aurelia
15	Villa Aurelia and AAR Lecture Room
15	Villa Lante and Villa Aurelia
15	Waldorf Astoria
15	Washington Marriott Wardman Park Hotel
15	Whitney Museum of American Art
</pre>

**Comment by cchristopherhowardd** [comment]
No changes to Event Types. A few for Event Locations.

American Academy in Rome Photo Archive --> AAR Photo Archive
American University of Rome and American Academy in Rome --> American University of Rome and AAR
Arthur Ross Gallery, of the University of Pennsylvania --> Arthur Ross Gallery, University of Pennsylvania
Centro Studi Americani and American Academy in Rome --> Centro Studi Americani and AAR

**Comment by jasloe** [comment]
Done.
