### ISSUE TITLE
Tracking performance

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#231]
### uninstall 
help
history
menu export
migrations
restful web services

### delete content type
article
articles

**Comment by jasloe** [comment]
@cchristopherhowardd -- is the Workbench module useful?

https://staging.aarome.org/admin/workbench

If it accomplishes the same thing as /admin/content, I can dump it.

**Comment by cchristopherhowardd** [comment]
I find that I am using the content module almost exclusively. I have needed to visit webpages all over site, and often within a single section (Events, Publications, Apply), and seeing recently edited pages isn't a priority.

**Comment by cchristopherhowardd** [comment]
<img width="1256" alt="Screen Shot 2019-07-24 at 3 00 43 PM" src="https://user-images.githubusercontent.com/38765846/61820935-1374fb00-ae24-11e9-89d6-8ec68043993a.png">

I have been using the Title box and Content Type selection A LOT in the past couple of months.

**Comment by jasloe** [comment]
Ok, I'm going to ditch it. It's a resource hog anyway.
