### ISSUE TITLE
Style sheets for Support section

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#232]
I am experiencing pages in the Support section (https://staging.aarome.org/support) that seem to lack the correct style sheets. Page views vary by browser, so I will review and categorize them shortly.

**Comment by cchristopherhowardd** [comment]
**Chrome**

https://staging.aarome.org/support/donate - needs style sheet
https://staging.aarome.org/support/join-renew - needs style sheet
https://staging.aarome.org/support/galas - needs style sheet
https://staging.aarome.org/support/support-opportunities - needs style sheet [links to photos embedded in running text are broken]
https://staging.aarome.org/support/planned-giving - needs style sheet
https://staging.aarome.org/support/corporate - needs style sheet

**Safari**

https://staging.aarome.org/support/donate - needs style sheet
https://staging.aarome.org/support/join-renew - needs style sheet
https://staging.aarome.org/support/galas - needs style sheet
https://staging.aarome.org/support/support-opportunities - needs style sheet [links to photos embedded in running text are broken]
https://staging.aarome.org/support/planned-giving - needs style sheet
https://staging.aarome.org/support/corporate - needs style sheet

**Firefox**

Pages appear with correct formatting if the browser page is at the maximum width on a 15 inch MacBook Pro, but they lose desktop/laptop formatting at any smaller size. Also, the left margin of the page barely exists when the browser page has maximum width.

**Comment by cchristopherhowardd** [comment]
I have made the Safari browser on my laptop really, really wide. Wider than can appear onscreen. The formatting appears as it should, but of course I can't see the entire page all at once.

**Comment by jasloe** [comment]
I can't replicate here. I'm looking at the site on those browsers and the site is consistent. No broken stylesheets. E.g., screen shot from Safari at ~2500 px wide:

![Screen Shot 2019-07-26 at 1 57 00 PM](https://user-images.githubusercontent.com/1063667/61971571-662dee80-afad-11e9-92c2-bf5f9f2fefcf.png)

Can you send me a screenshot? 

Regarding the broken links at /support-opportunities, those simply need to be removed from the content body.

**Comment by cchristopherhowardd** [comment]
<img width="1418" alt="Safari 1" src="https://user-images.githubusercontent.com/38765846/62064297-8b636c80-b1fa-11e9-9be0-79b09ae06b9c.png">
<img width="1425" alt="Safari 2" src="https://user-images.githubusercontent.com/38765846/62064300-8dc5c680-b1fa-11e9-97cc-47661d1df7af.png">
<img width="1431" alt="Safari 3 (left edge)" src="https://user-images.githubusercontent.com/38765846/62064308-90c0b700-b1fa-11e9-9031-98415583b98a.png">
<img width="1440" alt="Safari 3 (right edge)" src="https://user-images.githubusercontent.com/38765846/62064313-928a7a80-b1fa-11e9-9050-e8948e4f27d2.png">

**Comment by jasloe** [comment]
Having a really hard time replicating this. This is my view in Safari's built-in emulator. Can you tell me which edition of Safari you're running?  

![Screen Shot 2019-07-29 at 2 04 11 PM](https://user-images.githubusercontent.com/1063667/62071139-e2247280-b209-11e9-97d9-f0906ed99a89.png)

**Comment by cchristopherhowardd** [comment]
I have Version 12.1.1 

Chrome does the same thing.

**Comment by jasloe** [comment]
Kind of stumped on this one with visual testing. I'm going to look over the style sheets to see if I can identify any problems.

**Comment by cchristopherhowardd** [comment]
I'll check the pages on my wife's laptop tonight, which is a 13 inch MacBook Air. It seems as if screens that are 15 inches or smaller are getting a compromised browsing experience. The problem only surfaced for me last week. I don't recall seeing this earlier, but can't say with 100 percent certainty.

<img width="1435" alt="Screen Shot 2019-07-31 at 3 07 42 PM" src="https://user-images.githubusercontent.com/38765846/62240467-0e282b00-b3a5-11e9-9b32-a75315e934c3.png">

<img width="1440" alt="Screen Shot 2019-07-31 at 3 08 04 PM" src="https://user-images.githubusercontent.com/38765846/62240473-12544880-b3a5-11e9-9985-32699623a6d3.png">

**Comment by jasloe** [comment]
I was able to replicate the issue on an 13" Macbook Air here. I think it's a combination of the screen dimensions and retina display. I'll start working on a fix.

**Comment by jasloe** [comment]
Added rule to style sheet for all node pages. Added extra padding in right column so that paragraph width isn't too long.

**Comment by cchristopherhowardd** [comment]
Great, thanks. I don't see any formatting problems in the Support section.
