### ISSUE TITLE
Character spaces after email addresses

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#233]
Throughout the site, character spaces appear after email addresses. You can find an example at https://staging.aarome.org/society-of-fellows/council and in the screenshot below.

<img width="1396" alt="Screen Shot 2019-07-31 at 2 55 57 PM" src="https://user-images.githubusercontent.com/38765846/62240011-0ae06f80-b3a4-11e9-9ca7-23cc1874d455.png">

There should not be a character space after email addresses and sentence-ending periods.

**Comment by jasloe** [comment]
Ok I have a fix. 

Tracked the issue here: https://www.drupal.org/project/obfuscate/issues/3003559

In the template files on my local server, I've wrapped the following with the "spaceless" filter:

```
{% spaceless %}
  <span class="boshfpngr">
    {{ link|raw }}
  </span>
{% endspaceless %}
```
I'll push that up to staging this evening.

**Comment by jasloe** [comment]
This is fixed and ready for testing. Please close if ok.

https://staging.aarome.org/support/planned-giving
https://staging.aarome.org/about/place/tours

This is certainly a bug; no time billed for this one.

**Comment by jasloe** [comment]
Closing. Please re-open if there are any issues.

**Comment by cchristopherhowardd** [comment]
Thank you!
