### ISSUE TITLE
Refactor slideshow

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#235]
I recreated the slideshow implementation from scratch. I'll start with the Events home page carousel and move on to residents/fellows home page, then inside Events page. I'll try to get this pushed up to staging this weekend/early next week.

**Comment by jasloe** [comment]
List of supporting tasks:

- [ ] implement rfs
- [ ] replace HTML markup
- [ ] install carousel library

**Comment by cchristopherhowardd** [comment]
The slideshow looks better already--thank you. A problem with missing images from News Feature slideshows was also resolved, for the most part. In months past, a gray "no symbol" replaced photos that didn't make it through the import process. The "no symbol" is largely gone now, and I've been slowly replacing the others this week and last.

**Comment by jasloe** [comment]
I still have a bit of work to do on this but it's incrementally getting better.

**Comment by jasloe** [comment]
Note that RFS is a new-ish font resizing library from the Bootstrap project. When fully implemented, it will intelligently scale the font sizes up and down depending on the device/viewport dimensions.
