### ISSUE TITLE
Boxes on certain section pages not lining up

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#237]
The boxes on these index/section pages are not lining up: https://staging.aarome.org/news. In the News section, Press Coverage occupies the space for two boxes.

<img width="1427" alt="Screen Shot 2019-08-09 at 10 01 18 AM" src="https://user-images.githubusercontent.com/38765846/62784624-eb74d100-ba8c-11e9-9936-724b6ea39769.png">

<img width="1433" alt="Screen Shot 2019-08-09 at 10 01 28 AM" src="https://user-images.githubusercontent.com/38765846/62784631-efa0ee80-ba8c-11e9-8251-86fa2fafee23.png">

So does Society of Fellows (https://staging.aarome.org/society-of-fellows), where the Bylaws box takes up the space for two.

<img width="1436" alt="Screen Shot 2019-08-09 at 10 01 52 AM" src="https://user-images.githubusercontent.com/38765846/62784652-f891c000-ba8c-11e9-8b59-29eaecca493f.png">

<img width="1417" alt="Screen Shot 2019-08-09 at 10 01 59 AM" src="https://user-images.githubusercontent.com/38765846/62784661-fb8cb080-ba8c-11e9-8190-e377f640d2c0.png">

**Comment by cchristopherhowardd** [comment]
I see the same problem at https://staging.aarome.org/about and https://staging.aarome.org/about/place, so the issue might be site wide.

**Comment by cchristopherhowardd** [comment]
Events has the problem: https://staging.aarome.org/events
Research has the problem: https://staging.aarome.org/research

Research-->Library does not: https://staging.aarome.org/research/library
Research-->Resources does not: https://staging.aarome.org/research/resources
Research-->Special Collections does not: https://staging.aarome.org/research/special-collections
Research-->Photographic Archive does not: https://staging.aarome.org/research/photographic-archive
Research-->Archaeology does not: https://staging.aarome.org/research/archaeology
Support does not: https://staging.aarome.org/support

**Comment by jasloe** [comment]
@cchristopherhowardd -- I got a little too aggressive cleaning up the stylesheet that governs layouts.

Note to self: instead of hiding the <article> element on body.section-front, remove the <article> element entirely from the Twig template.

For example, at page--node--3274.html.twig, change:

```
{{ attach_library('classy/node') }}
<article{{ attributes.addClass(classes) }}>

  {{ title_prefix }}
  {% if not page %}
    <h2{{ title_attributes }}>
      <a href="{{ url }}" rel="bookmark">{{ label }}</a>
    </h2>
  {% endif %}
  {{ title_suffix }}

  {% if display_submitted %}
    <footer class="node__meta">
      {{ author_picture }}
      <div{{ author_attributes.addClass('node__submitted') }}>
        {% trans %}Submitted by {{ author_name }} on {{ date }}{% endtrans %}
        {{ metadata }}
      </div>
    </footer>
  {% endif %}

</article>

to, simply:
```
{{ attach_library('stable/node') }}
{{ metadata }}
```
