### ISSUE TITLE
Publishing Library Resources

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#238]
I am able to create but not publish Library Resources. Can you give me the ability to publish them?

Here is one example: https://staging.aarome.org/node/5046/edit?destination=/admin/content

**Comment by jasloe** [comment]
It looks like the content type was not configured properly. I fixed it by re-setting the publication default to 'published'. Please test and let me know if that works for you.

**Comment by cchristopherhowardd** [comment]
It doesn't work. At the bottom of each unpublished page I have the options of save, preview, and delete. Nowhere on the page is something that allows me to publish!

**Comment by cchristopherhowardd** [comment]
![Edit Library resources Duke Databank of Dokumentary Papyri _ American Academy in Rome](https://user-images.githubusercontent.com/38765846/63693958-53444f00-c7e3-11e9-8933-d1f25481c0dd.png)

**Comment by jasloe** [comment]
https://www.drupal.org/project/publishcontent/issues/2932094

```
In Drupal 8.4 the "Save and keep unpublished" and "Save and keep published" buttons were replaced with a single checkbox.

It's currently not possible to show that checkbox for roles other than the main site administrator role/user.
```

Yikes. This is new to me!

There is a module available to fix this.

https://www.drupal.org/project/override_node_options

Going to look at the source code now.

**Comment by jasloe** [comment]
Can this be closed?
