### ISSUE TITLE
Change default year for Rome Prize Fellows, Italian Fellows, and Residents

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#239]
Jason, can you change the default year for the Rome Prize Fellows (https://staging.aarome.org/people/rome-prize-fellows), Italian Fellows (https://staging.aarome.org/people/italian-fellows), and Residents (https://staging.aarome.org/people/residents) from 2019 to 2020?

**Comment by jasloe** [comment]
Ok all set. 

On the home page, you'll see quite a few placeholder images under the Invited Residents stanza. 

Do you want to revert to 2019 until the 2020 nodes are populated?

**Comment by cchristopherhowardd** [comment]
Yeah, leave the Residents be. Not everything has been finalized, and nobody has been asked to provide portrait photos and other information.

**Comment by cchristopherhowardd** [comment]
I noticed in the Rome Prize Fellows that Victoria C. Moses appears twice. She is a two-year fellow, and probably the last one, because the academy is no longer awarding two-year fellowships. Can you remove the photo and link for the 2019 profile from the homepage, while keeping the 2020 profile? To clarify, the 2019 profile has the photo of her wearing a tan coat and red and black checkered scarf.

**Comment by cchristopherhowardd** [comment]
You know what? Maybe Victoria C. Moses appearing twice is no big deal. I happened to look at the homepage slideshow when it randomly put her two People profile photos right next to each other. I forgot that the selection of pictures is random, so this pairing will not occur often. Even a sequence of another fellow in a VCM sandwich is unlikely to occur.

**Comment by cchristopherhowardd** [comment]
As far as I know, the Residents haven't all been confirmed, so I can't contact them for bios and photos. (I copied and pasted the current bios from unattributed internet sources.) There is no timeline or schedule for the new website going live, so it's fine to keep the 2019 Residents on the homepage.
