### ISSUE TITLE
Maps?

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#24]
I banged out some geolocation code last year for the DHC project which never went anywhere. Might be nice to incorporate mapped event locations as a design element. 

The site editor only has to enter the street address and the module will render a map (which, naturally, can be easily customized with style sheets). 

http://academy.minorscience.com/node/38

**Comment by cchristopherhowardd** [comment]
Go for it.

What map is that?

**Comment by jasloe** [comment]
It's an ESRI map layer with a Google backend.

**Comment by jasloe** [comment]
Geocoding fails under certain conditions. 

Apply patch against dev release: https://www.drupal.org/files/issues/2018-05-01/geocoder_field_update_logic-2930013-6.patch

**Comment by jasloe** [comment]
Hi @cchristopherhowardd:

I am putting some of the simpler migration sources under version control: https://github.com/aarome/migration-sources

If you want to assign addresses for place names, go here:

https://github.com/aarome/migration-sources/blob/master/event_locations.csv

Select the "Raw" tab and copy and paste into a spreadsheet editor, then attach your work as a file to this ticket. 

If not, the data can be filled in later, though entering the information into spreadsheet records is probably more efficient.
