### ISSUE TITLE
2019 Experience Packages page

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#243]
A request for the current website.

Can you make it so that the page I created for the 2019 Fall Gala Experience Packages (https://www.aarome.org/support/2019-experience-packages) looks like other Support pages (such as https://www.aarome.org/support/planned-giving or https://www.aarome.org/support/2019-mckim-medal-gala for example). I'd like to get the sidebar menu on the 2019 Experience Package page.

**Comment by jasloe** [comment]
Oops I missed this. Will take a look.

**Comment by jasloe** [comment]
@cchristopherhowardd –– 

I parceled out the long body text into discrete page section nodes as it makes the page easier to handle with the current stylesheets. 

Let me know if you need the URL changed or anything else tightened up. 

https://www.aarome.org/support/2019-new-york-gala-experience-packages

**Comment by cchristopherhowardd** [comment]
URL stays the same. Thanks for the work!

**Comment by cchristopherhowardd** [comment]
How can I edit the text below the headline at https://www.aarome.org/support/2019-new-york-gala-experience-packages ?

I would expect to be able to do this at https://www.aarome.org/node/2224260/edit?destination=admin/content but the page above doesn't appear to draw from this node.

**Comment by jasloe** [comment]
That's right. The content is in a views header which is a little onerous to give write access to non-admin users. Can you just paste the text here and I'll update?

**Comment by cchristopherhowardd** [comment]
This sentence should be its own paragraph:

Your participation will provide critical support for AAR Fellows and programs.

**Comment by cchristopherhowardd** [comment]
This URL ( https://support.aarome.org/2019-experience-packages ) should be added  to the phrase "Purchase online today" with the exclamation mark excluded.

**Comment by jasloe** [comment]
Ok all set.

**Comment by cchristopherhowardd** [comment]
Can you add this new page section (https://www.aarome.org/hudson-valley-holiday-market-tour-cooking-demo-chef-mona-talbott) to the 2019 Experience Packages page (https://www.aarome.org/support/2019-new-york-gala-experience-packages)? Right now you can place the new page section last, as I am waiting to hear back where it should go.

**Comment by cchristopherhowardd** [comment]
The new page section can appear after "Divine Design" and before "MoMA Returns."

**Comment by jasloe** [comment]
💰

Done.

**Comment by cchristopherhowardd** [comment]
Two more Experience Packages to place on this page: https://www.aarome.org/support/2019-new-york-gala-experience-packages

This page section ( https://www.aarome.org/tuscany-meets-napa-explore-antica-winery ) should be placed after "Buyer's Choice" and before "Put It in Writing."

This page section ( https://www.aarome.org/great-landscape-design-consultation-mary-margaret-jones-1998-fellow-and-2020-resident ) should be placed last, after "MoMA Returns."

**Comment by cchristopherhowardd** [comment]
We need a second main section on the 2019 Experience Packages page ( https://www.aarome.org/support/2019-new-york-gala-experience-packages ) for 2019 Support Packages. There are three page sections that should be added under the new header:

https://www.aarome.org/internships-young-chefs
https://www.aarome.org/books-library
https://www.aarome.org/greener-academy

**Comment by cchristopherhowardd** [comment]
Jason, is it possible to complete the Experience Package work this afternoon?

**Comment by jasloe** [comment]
> Two more Experience Packages to place on this page: https://www.aarome.org/support/2019-new-york-gala-experience-packages
> 
> This page section ( https://www.aarome.org/tuscany-meets-napa-explore-antica-winery ) should be placed after "Buyer's Choice" and before "Put It in Writing."
> 
> This page section ( https://www.aarome.org/great-landscape-design-consultation-mary-margaret-jones-1998-fellow-and-2020-resident ) should be placed last, after "MoMA Returns."

This is done.

**Comment by jasloe** [comment]
> We need a second main section on the 2019 Experience Packages page ( https://www.aarome.org/support/2019-new-york-gala-experience-packages ) for 2019 Support Packages. There are three page sections that should be added under the new header:
> 
> https://www.aarome.org/internships-young-chefs
> https://www.aarome.org/books-library
> https://www.aarome.org/greener-academy

With this page template, there's no way to drop in a second header. I recommend adding a new page, i.e.: ```support/2019-new-york-gala-support-packages``` and corresponding menu item, and adding these three pages to its queue.

**Comment by jasloe** [comment]
In other words: https://www.aarome.org/support/2019-new-york-gala-support-packages

**Comment by cchristopherhowardd** [comment]
This page is fine. 

At the top of the page, can you delete the phrase "Statement on Support Packages" and the sentence "Or bid in person at the Gala Silent Auction on November 6."? Thanks!

**Comment by cchristopherhowardd** [comment]
Please change the headline to: 2019 Support Opportunities

Thansk!

**Comment by cchristopherhowardd** [comment]
Relatedly, can you tell me how I can edit this page? https://www.aarome.org/support/2019-new-york-gala. I need to make a few text corrections and don't know how to do this.

**Comment by cchristopherhowardd** [comment]
Edits to Experience Packages and Support Opportunities pages in the attached PDF.
[Edits to Experience Packages and Support Opportunities pages.pdf](https://github.com/aarome/aarome/files/3768043/Edits.to.Experience.Packages.and.Support.Opportunities.pages.pdf)

**Comment by jasloe** [comment]
> This page is fine.
> 
> At the top of the page, can you delete the phrase "Statement on Support Packages" and the sentence "Or bid in person at the Gala Silent Auction on November 6."? Thanks!

Done.

**Comment by jasloe** [comment]
> Relatedly, can you tell me how I can edit this page? https://www.aarome.org/support/2019-new-york-gala. I need to make a few text corrections and don't know how to do this.

https://www.aarome.org/node/2224831/edit

**Comment by jasloe** [comment]
> Edits to Experience Packages and Support Opportunities pages in the attached PDF.
> [Edits to Experience Packages and Support Opportunities pages.pdf](https://github.com/aarome/aarome/files/3768043/Edits.to.Experience.Packages.and.Support.Opportunities.pages.pdf)

Can you paste the text as you'd like it to appear in this issue?

**Comment by cchristopherhowardd** [comment]
Is there something unclear about what's in the PDF?

**Comment by cchristopherhowardd** [comment]
Can you please change the URL https://www.aarome.org/support/2019-support-opportunities back to https://www.aarome.org/support/2019-new-york-gala-support-packages IMMEDIATELY? I sent an email blast this morning with links to the latter URL.

**Comment by jasloe** [comment]
> Can you please change the URL https://www.aarome.org/support/2019-support-opportunities back to https://www.aarome.org/support/2019-new-york-gala-support-packages IMMEDIATELY? I sent an email blast this morning with links to the latter URL.

Fixed.

**Comment by jasloe** [comment]
> Is there something unclear about what's in the PDF?

Let me know if ok.

**Comment by cchristopherhowardd** [comment]
On this page ( https://www.aarome.org/support/2019-new-york-gala-support-packages ), is there a way to make the headline read "2019 Support Opportunities" without changing the URL?

**Comment by jasloe** [comment]
Sure, I made the change. Let me know if ok.

**Comment by cchristopherhowardd** [comment]
It looks good but the development department now wants to combine the two pages. Can you attach the three page sections at https://www.aarome.org/support/2019-new-york-gala-support-packages to the end of page sections at https://www.aarome.org/support/2019-new-york-gala-experience-packages?  And also change the headline from "2019 NEW YORK GALA EXPERIENCE PACKAGES" to "2019 EXPERIENCE PACKAGES AND SUPPORT OPPORTUNITIES"?

**Comment by cchristopherhowardd** [comment]
Yes to both. I hadn't gotten there yet.

**Comment by cchristopherhowardd** [comment]
Can you remove "New York Gala" from the headline at https://www.aarome.org/support/2019-new-york-gala-experience-packages?

**Comment by cchristopherhowardd** [comment]
Cancel the above request. "New York Gala" can stay where it is. 

Is it possible to drop "AND SUPPORT OPPORTUNITIES" to a second line? Development has requested this, but my understanding of the Drupal site means that we can't create two-line headers.

**Comment by cchristopherhowardd** [comment]
On this page (https://www.aarome.org/support/2019-new-york-gala-experience-packages), the introductory should text should read like this, in three paragraphs:

Our unique Experience Packages for the 125th Anniversary New York Gala offer you the chance to enjoy exclusive access to distinguished artists and scholars of the Academy.

You can also browse a list of Support Opportunities, which help to enrich the day-to-day life at the Academy.

Your participation will provide critical support for AAR Fellows and programs.

**Comment by cchristopherhowardd** [comment]
In the second paragraph above ("You can also browse..."), can you create an anchor link for the words "Support Opportunities" that, if clicked, will take browsers down the page to the first of three items: "SUPPORT OPPORTUNITY: INTERNSHIPS FOR YOUNG CHEFS"?

**Comment by cchristopherhowardd** [comment]
Can you unpublish this page?

https://www.aarome.org/support/2019-new-york-gala-support-packages

**Comment by jasloe** [comment]
The anchor link and line break can be implemented with a little custom code. I'll try to get to this this evening.
