### ISSUE TITLE
Italian Fellowships FAQ

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#246]
The Apply page for the Italian Fellowships ( https://staging.aarome.org/apply/italian-fellowships ) has a link on the page going to an FAQ ( https://staging.aarome.org/apply/italian-fellowships/faq ).

The Italian-language equivalents don't work the same way. The Apply page ( https://staging.aarome.org/it/partecipazione/borse-di-studio-italiani ) is fine, but the FAQ page has a URL that is stuck in Node World: https://staging.aarome.org/it/node/2443. 

I created the Italian-language page for FAQ through the English page using the translation option. 

Can you give the Italian-language page this URL?

https://staging.aarome.org/it/partecipazione/borse-di-studio-italiani/domande-frequenti 

And also makes sure the breadcrumb is working for the page? Right now the Italian FAQ page starts with "Node /"

**Comment by jasloe** [comment]
This is fixed.

**Comment by cchristopherhowardd** [comment]
Hooray!
