### ISSUE TITLE
Event Types and Series

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#248]
It turns out that some AAR events have been part of three different Event Series, like this one: https://staging.aarome.org/events/calendar/david-i-kertzer-mauro-canali-new-perspectives-fascist-ventennio-what-archives

Can you expand the number of fields in the Event Types and Series to three, four, or even five? At present, there are only two.

<img width="996" alt="Screen Shot 2019-11-21 at 10 10 33 AM" src="https://user-images.githubusercontent.com/38765846/69350385-76966300-0c47-11ea-971a-471bea175d3d.png">

**Comment by jasloe** [comment]
Types/events are now unlimited. I added a quick JS widget for selecting and removing values and moved the form elements to the top of the form. Please test and close.
