### ISSUE TITLE
Update core/modules directory.aarome.org

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#249]

**Comment by jasloe** [comment]
Got about halfway through with this. Drupal core is up to date. 

Will finish up tomorrow including SSL certificate installation, testing content creation, media handling, and search indexing.

**Comment by jasloe** [comment]
Done.

**Comment by cchristopherhowardd** [comment]
Great, thanks!

**Comment by jasloe** [comment]
Closing. 

Doing same for #251.
