### ISSUE TITLE
2020 McKim Medal Gala webpage

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#252]
The current website needs a page for the 2020 McKim Medal Gala, similar to past pages for the event (such as https://www.aarome.org/support/2018-mckim-medal-gala). 

The URL for the new page can be https://www.aarome.org/support/2020-mckim-medal-gala

We only have bare-bones content at the moment, which I have posted to an Event for the gala (https://www.aarome.org/events/calendar/2020-06?mini=2020-06). 

Can you create a page for 2020 using this content? I recall that I can't create Gala pages on my own because of the vagaries of Drupal 7.

**Comment by jasloe** [comment]
Sure, you bet, I can dispatch this and #250 by tomorrow afternoon.

**Comment by jasloe** [comment]
Bare bones page here: https://www.aarome.org/support/2020-mckim-medal-gala

The page image can be part of a slideshow or in the body of the page section. 

Let me know which you prefer and I'll clean up the CSS. If you want to use the slideshow format, you can add additional images here: https://www.aarome.org/node/2225652/edit

**Comment by cchristopherhowardd** [comment]
Great, thanks!

**Comment by cchristopherhowardd** [comment]
Can you add a link for "2020 McKim Medal Gala" ( https://www.aarome.org/support/2020-mckim-medal-gala ) on the right-side menu in the Support section? It can go below "Join / Renew" and above "2019 New York Gala Experience Packages."

**Comment by jasloe** [comment]
In production. The Italian side is a little wonky. I'll see if I can fix this from here.
