### ISSUE TITLE
Second Summer Program needed for D7 website

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#253]
The Academy has a second summer program, on Latin Epigraphy, that needs to be added to the Drupal 7 website and organized within the Apply section. Here is the page section: https://www.aarome.org/latin-epigraphy-program

The Apply section for Summer Programs is https://www.aarome.org/apply/summer-programs. Right now the Classical Summer School (CSS) information appears both there and at https://www.aarome.org/apply/summer-programs/classical-summer-school. I need the Latin Epigraphy program to be published on the Summer Programs page above the CSS information, as well as on its own page that can be accessed via the menu on the right side of the Apply pages (see attached image).

<img width="1057" alt="Screen Shot 2020-01-02 at 2 47 37 PM" src="https://user-images.githubusercontent.com/38765846/71688985-f1868980-2d6e-11ea-9153-4743e15b7750.png">

Does this make sense?

**Comment by jasloe** [comment]
I think that program was added then removed in the last year or so, so it's possibly a matter of simply turning it back "on". I'm out of the office beginning tomorrow and will try to dispatch this this evening.

**Comment by cchristopherhowardd** [comment]
Might you be able to dispatch the freestanding Latin Epigraphy webpage today?

**Comment by jasloe** [comment]
Sorry, Chris, on vacation and didn't have time to finish this on my way out of town. 

I just pushed the change now. Pushed #252 too.
