### ISSUE TITLE
News Section - Press Coverage

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#255]
I'm making the executive decision to eliminate a box in the News section (https://staging.aarome.org/news). The box for "Press Coverage" can be taken off the page and the page https://staging.aarome.org/news/coverage can be unpublished. Judging by the dates of posting, this section hasn't been an AAR priority for almost five years.

**Comment by jasloe** [comment]
This is done. In the event someone wants to resurrect these pages, I've simply disabled the menu item and the index block, then unpublished the content. It's trivial to bring this functionality back, if needed.
