### ISSUE TITLE
News Section - Quick News

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#256]
On the Quick News page (https://staging.aarome.org/news/quick-news), do you think we might unlink the headline and body text? It's fine to link the image and the READ MORE box, but I wonder if it's overkill to link the text. A few times this week I wanted to copy and paste the text for Twitter and Facebook posts, but was not able to because of the hyperlink.

**Comment by jasloe** [comment]
Yes, that should be decoupled in this context. Spacing needs to be tweaked as well.

**Comment by jasloe** [comment]
Quick news had a few style issues, so I dispatched those first. 

Regarding the behavior of index and news/events item cards, the idea is that the entire card is linked: makes it less fussy and more clickable for users. But I understand your use case, i.e. making text selectable. Let me think about how to do this

**Comment by cchristopherhowardd** [comment]
I'm not wedded to the idea of uncoupling the entire card. If it's simpler to link everything for users as a whole, then my minor concern isn't really a concern.

**Comment by cchristopherhowardd** [comment]
Seriously, it's completely OK to couple all the individual elements for each item.

**Comment by jasloe** [comment]
Recoupled card elements. Test and close.
