### ISSUE TITLE
Automatic links for emails

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#262]
The website no longer creates automatic links for email addresses. See https://staging.aarome.org/about/staff as one example.

**Comment by jasloe** [comment]
Reconfigured obfuscate module. Working. Please test and close.

**Comment by cchristopherhowardd** [comment]
The email links are created automatically, but an older problem has resurfaced: there is a character space between the email address and the sentence-ending period.

<img width="1394" alt="Screen Shot 2020-03-24 at 11 51 39 AM" src="https://user-images.githubusercontent.com/38765846/77447385-ff740580-6dc5-11ea-9602-abf3ed0ba43f.png">
<img width="1377" alt="Screen Shot 2020-03-24 at 11 51 27 AM" src="https://user-images.githubusercontent.com/38765846/77447388-000c9c00-6dc6-11ea-8481-42ab5d36d828.png">

**Comment by cchristopherhowardd** [comment]
An obvious question: why did the staging site have no trouble rendering Dignitas bold and italics before the merge with the dev site?

**Comment by jasloe** [comment]
Huh. That's weird. It looks like my fix at #233 is no longer working for no obvious reason. Will check itout.

**Comment by jasloe** [comment]
Ditched ```obfuscate``` in favor of ```spamspan```.
