### ISSUE TITLE
Italics and Bold

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#263]
Italics renders as bold text: see https://staging.aarome.org/news/features/art-video-live-performance-converge-rome and https://staging.aarome.org/publications/exhibition-catalogues for example.

Bold text doesn't render as bold: all questions on the FAQ page ( https://staging.aarome.org/apply/rome-prize/faq ) should be bold.

**Comment by jasloe** [comment]
I am seeing italicized text as expected on the news item. Ditto publications. Maybe excerpt the problematic text and post here. 

It occurs to me that the Dignitas typeface package I received does not have a bold font. Do you happen to have the entire family handy somewhere?

![Screen Shot 2020-03-23 at 6 40 10 PM](https://user-images.githubusercontent.com/1063667/77370119-8d081480-6d36-11ea-94a4-595dd32ad423.png)

**Comment by cchristopherhowardd** [comment]
Larger font size and bold replaces italics in this example.
<img width="1398" alt="Screen Shot 2020-03-24 at 10 59 15 AM" src="https://user-images.githubusercontent.com/38765846/77440401-a359b300-6dbe-11ea-9924-52744ce42324.png">

**Comment by cchristopherhowardd** [comment]
The questions "What is offered if I win a Rome Prize fellowship?" and "Is the fellowship open to all?" are supposed to appear in bold.

<img width="1367" alt="Screen Shot 2020-03-24 at 11 02 02 AM" src="https://user-images.githubusercontent.com/38765846/77440697-faf81e80-6dbe-11ea-9f1e-2074130643eb.png">

**Comment by cchristopherhowardd** [comment]
I only have regular and italic Dignitas on my computer. According to Martha from Open, only those two (and not bold) were part of the initial design plan--which seems very odd to me. Why no bold? Here is her email about the matter.

<img width="904" alt="Screen Shot 2020-03-24 at 11 41 32 AM" src="https://user-images.githubusercontent.com/38765846/77446342-ae174680-6dc4-11ea-80ef-cc4884e4ae2a.png">

Can we get bold dignitas from https://commercialtype.com/catalog/dignitas or from Open? How AAR orders these kinds of things is still a mystery to me.

**Comment by cchristopherhowardd** [comment]
An obvious question: why did the staging site have no trouble rendering Dignitas bold and italics before the merge with the dev site?

**Comment by jasloe** [comment]
Fixed titles at publications/*. Italics rendered fine; it was just bad styling in this example. 

I don't exactly recall off-hand but I don't think bold was ever implemented; I possibly just did ```font-weight: 900``` to make the text appear bold-ish. 

Anyway, the Academy will need to purchase a web license for $150 from CT.

**Comment by cchristopherhowardd** [comment]
Pricing for the full Dignitas typeface (regular, italic, bold, and bold italic) is $150 for one website with up to 15,000 unique visitors a month and $375 for those with up to 500,000 unique visitors a month. Am I correct in assuming that aarome.org gets fewer than 15,000 unique visitors a month? It's sad if we do, but is it correct?

**Comment by jasloe** [comment]
Sadly correct!

**Comment by cchristopherhowardd** [comment]
I've already asked Marques for the OK to purchase the font and will need a credit-card number from him. I realize that an alternate method is for you to buy the font and add it to your invoice, but since I've already asked I will follow up with MQ again today.

**Comment by cchristopherhowardd** [comment]
MQ has asked that you purchase the license for the web font and add the cost to the invoice. Can you do this?

**Comment by jasloe** [comment]
Sure, not a problem. As long as my invoices can be expedited as I haven't invoiced in a couple of months. Note that I was also charged an auto-renewal for Iubenda. I think it's about $50. I've since removed my payment info from the account.

**Comment by jasloe** [comment]
@cchristopherhowardd –– In addition to make questions bold, I think the answers should be contained in an accordion like this: 

https://loghaven.org/residencies/faq/

Sound good?

> The questions "What is offered if I win a Rome Prize fellowship?" and "Is the fellowship open to all?" are supposed to appear in bold.
> 
> <img alt="Screen Shot 2020-03-24 at 11 02 02 AM" width="1367" src="https://user-images.githubusercontent.com/38765846/77440697-faf81e80-6dbe-11ea-9f1e-2074130643eb.png">

**Comment by cchristopherhowardd** [comment]
Invoices can be expedited, thanks. Roseann in AAR's Finance Department is working from home like the rest of us!

**Comment by jasloe** [comment]
Very good! Thanks!

**Comment by cchristopherhowardd** [comment]
The accordion for this FAQ is fine. There are a few others across the site, too. Move this to a separate issue?

**Comment by cchristopherhowardd** [comment]
When will the **bold** and _italics_ kick in?

**Comment by cchristopherhowardd** [comment]
Can you implement the full Dignitas typeface on the website this week? Staff members have been reviewing webpages for a month, and I keep having to tell them that **bold** and _italics_ are broken. Is there something keeping us from getting the font to work correctly?

**Comment by cchristopherhowardd** [comment]
A bug?

**Comment by jasloe** [comment]
This is fixed. Will push to staging this evening.

**Comment by cchristopherhowardd** [comment]
Italics looks fine, but bold text appears to be in a larger font.

<img width="1390" alt="Screen Shot 2020-05-18 at 2 31 03 PM" src="https://user-images.githubusercontent.com/38765846/82247349-3d982c00-9914-11ea-9eb3-af311561e4c2.png">

**Comment by jasloe** [comment]
Looking at the specimen, bold is very bold. Changing the font weight does nothing. This may be why Open did not include a bold style in their specification.

https://commercialtype.com/catalog/dignitas

**Comment by cchristopherhowardd** [comment]
Maybe so, but the bold text in the example above is a totally different typeface.

**Comment by jasloe** [comment]
Spelling error in style sheet:

~~$dignitasbold: "Digitas Bold";~~
$dignitasbold: "Dignitas Bold";

I see from this example that the <strong> element can include a link, i,e. "making a contribution."

I'll had that use case to #294.
