### ISSUE TITLE
Affiliated Fellowships section page

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#266]
The Affiliated Fellowships section page (https://staging.aarome.org/apply/affiliated-fellowships) is not loading from the Apply section page (https://staging.aarome.org/apply).

In other words, when I am at https://staging.aarome.org/apply and click on Affiliated Fellowships, I am taken to https://staging.aarome.org/node/3298 instead of https://staging.aarome.org/apply/affiliated-fellowships.

**Comment by cchristopherhowardd** [comment]
A smaller issue at https://staging.aarome.org/apply/affiliated-fellowships. The box for CAORC Multi-Country Fellowships should appear second on the page, right after ACLS/Frederick Burkhardt Residential Fellowships. The two Brodsky fellowships should be positioned third and fourth.

**Comment by cchristopherhowardd** [comment]
Another small issue in this section: Can you reconcile the different spacing heights for the [More Information] and [Fellowship Brochure] boxes at https://staging.aarome.org/apply/affiliated-fellowships/oscar-broneer-traveling-fellowship with the two boxes at https://staging.aarome.org/apply/affiliated-fellowships/raiziss-de-palchi-traveling-fellowship-for-poets?

There is more space between the two boxes on the first page than there is on the second page. To my eye, the second page looks better. On both pages, I'd like to see a little more space between the paragraph text and the first box. Perhaps you can use the same amount of space between paragraphs as you do between paragraph and box.

**Comment by jasloe** [comment]
> The Affiliated Fellowships section page (https://staging.aarome.org/apply/affiliated-fellowships) is not loading from the Apply section page (https://staging.aarome.org/apply).
> 
> In other words, when I am at https://staging.aarome.org/apply and click on Affiliated Fellowships, I am taken to https://staging.aarome.org/node/3298 instead of https://staging.aarome.org/apply/affiliated-fellowships.

Fixed. Side effect of #261. This will come up again on /research index page and sub-index pages. Possibly also SOF though can't remember how those are set up. Tabling for now so that I can get through some of these other issues.

**Comment by jasloe** [comment]
> A smaller issue at https://staging.aarome.org/apply/affiliated-fellowships. The box for CAORC Multi-Country Fellowships should appear second on the page, right after ACLS/Frederick Burkhardt Residential Fellowships. The two Brodsky fellowships should be positioned third and fourth.

Fixed.

**Comment by jasloe** [comment]
This is a bug. Opened #268.

> Another small issue in this section: Can you reconcile the different spacing heights for the [More Information] and [Fellowship Brochure] boxes at https://staging.aarome.org/apply/affiliated-fellowships/oscar-broneer-traveling-fellowship with the two boxes at https://staging.aarome.org/apply/affiliated-fellowships/raiziss-de-palchi-traveling-fellowship-for-poets?
> 
> There is more space between the two boxes on the first page than there is on the second page. To my eye, the second page looks better. On both pages, I'd like to see a little more space between the paragraph text and the first box. Perhaps you can use the same amount of space between paragraphs as you do between paragraph and box.
