### ISSUE TITLE
Publications section page

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#267]
Boxes on the Publications section page (https://staging.aarome.org/publications) need rearranging. The box for Affiliated Books should be placed second to last, after Papers & Monographs and before Cookbooks.

**Comment by cchristopherhowardd** [comment]
Links for many of the boxes on the Publications section page are out of whack. Clicking on Magazine goes to https://staging.aarome.org/publications/magazine; clicking on Exhibition Catalogues goes tohttps://staging.aarome.org/publications/exhibition-catalogues; and clicking on Academy Books goes to https://staging.aarome.org/publications/academy-books. Clicking on each of the five remaining goes to the wrong page.

**Comment by jasloe** [comment]
Fixed.
