### ISSUE TITLE
Write iterator for links/files

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#268]
Another small issue in this section: Can you reconcile the different spacing heights for the [More Information] and [Fellowship Brochure] boxes at https://staging.aarome.org/apply/affiliated-fellowships/oscar-broneer-traveling-fellowship with the two boxes at https://staging.aarome.org/apply/affiliated-fellowships/raiziss-de-palchi-traveling-fellowship-for-poets?

There is more space between the two boxes on the first page than there is on the second page. To my eye, the second page looks better. On both pages, I'd like to see a little more space between the paragraph text and the first box. Perhaps you can use the same amount of space between paragraphs as you do between paragraph and box.

_Originally posted by @cchristopherhowardd in https://github.com/aarome/aarome/issues/266#issuecomment-603353914_

**Comment by jasloe** [comment]
Fixed. Re-open if you notice any edge cases.

**Comment by cchristopherhowardd** [comment]
Looks good, thanks!
