### ISSUE TITLE
Move Tours section from Place to About

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#269]
At your convenience, please move the box for Tours (https://staging.aarome.org/about/place/tours) from Place (where it's at the bottom of https://staging.aarome.org/about/place) to About (https://staging.aarome.org/about). Tours can be positioned last on the About page, after Rome Sustainable Food Project.

**Comment by jasloe** [comment]
Fixed. Ready for testing.

**Comment by cchristopherhowardd** [comment]
Looks great, thanks!
