### ISSUE TITLE
Research Section - pages are rendering only the first of two or more PDFs

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#272]
The Affiliated Projects page in the Archaeology section of Research ( https://staging.aarome.org/research/archaeology/affiliated-projects ) is rendering only the first of two PDF forms. 

The first PDF, called "Affiliated Archaeology Projects Application," is fine. The second PDF, called "Space Use Form," does not appear on the page.

**Comment by cchristopherhowardd** [comment]
I found another page ( https://staging.aarome.org/research/institutional-archive ) that should be publishing three PDFs in the Finding Aids section. Only one appears on the page.

**Comment by jasloe** [comment]
These are related to #268. Closing.
