### ISSUE TITLE
Search API Solr update

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#274]
Drupal has a new module compatible with Solr 7+. From the release notes: 

"While 8.x-2.x merged the multilingual and the "any schema" backends, 8.x-3.x combined them with the standard backend. In fact the multilingual backend became the unified backend for all purposes. That reduced the code base, improved the performance and enabled us to solve some 8.x-2.x issues we couldn't solve before, like the multisite search.

For the same reason we had the chance to optimize the query builder in order to ideally deal with the Solr internal caching and mechanisms introduced with Solr 6 and 7, especially docValues and filter caches."

This issue documents the upgrade process.

**Comment by jasloe** [comment]
@cchristopherhowardd –– finally got this working. Whew. Much improved, faster indexing time. Will rebuild frontend this week. 

Notes-wise: not much to report...pretty trivial update just took a bit of troubleshooting with the vendor to get the modules working!

**Comment by cchristopherhowardd** [comment]
Great!

**Comment by jasloe** [comment]
Reopening to log a couple of notes on facets.

On configuring a multilingual facet, be sure to select "Transform entity ID to label" else the facet will render with an untranslated entity label.
