### ISSUE TITLE
Society of Fellows - News & Events

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#276]
Two changes for the SOF News & Events section:

1. On the Society of Fellows index page ( https://staging.aarome.org/society-of-fellows ), position the News & Events box second on the page, after Council and before History.

2. On the News & Events page itself ( https://staging.aarome.org/society-of-fellows/news-events ), can you constrain the height of all images in the section? As you scroll down, you'll see that vertically oriented images are published at their full height, instead of the same height at the standard 400 x 600 size.

**Comment by jasloe** [comment]
See note at #283. In order to constrain the height of very tall images, we'd need to put them in a container. On the legacy site, such images were bound by a gray box. How would you like them contained on the new site? Gray box? No box (just white margins)?

**Comment by jasloe** [comment]
Note: fixed language negotiation at /society-of-fellows/news-events.

**Comment by cchristopherhowardd** [comment]
Tall images can be constrained by height and flush left. This is how the staging site presented them for many months, wasn't it? I don't like the gray box for images on the current (legacy?) site and think it would look not-so-great on the new site.
