### ISSUE TITLE
Support index page changes

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#277]
I had a call this morning with Marques McClary and Elizabeth Harris, the academy's acting development director, regarding the Support section and its index page (https://staging.aarome.org/support). Much of the conversation revolved around changing the photos, which I fully expected. 

One significant change was the idea to split the Galas page (https://staging.aarome.org/support/galas) into two pages, the McKim Medal Gala and the New York Gala, and placing boxes for both on the index page. 

This means that the box for Support Opportunities ( https://staging.aarome.org/support/support-opportunities ) no longer needs to be on the index page. This content will eventually be folded into, or linked from, the New York Gala page when we get closer to November.

The current Galas page can be converted to McKim Medal Gala. The New York Gala page can draw from https://staging.aarome.org/new-york-gala, which I created today. 

We don't need translations for the Italian site for the two galas. For instance, the McKim page can be aarome.org/support/mckim-medal-gala in English and aarome.org/it/sostegno/mckim-medal-gala in Italian, and New York can be aarome.org/support/new-york-gala and aarome.org/it/sostegno/new-york-gala.

One more index page change: Donate ( https://staging.aarome.org/support/donate ) will now be called Annual Fund. I changed the header of the page, but the URL will need to become https://staging.aarome.org/support/annual-fund for English and https://staging.aarome.org/it/sostengo/fondo-annuale for the Italian site.

We'll of course need to make changes in the site's footer to reflect all this.

**Comment by jasloe** [comment]
No problem. I am working on this search engine update at #274. As soon as I have that resolved (hopefully by Monday EOD), I'll turn attention to this and other issues posted this week.

**Comment by jasloe** [comment]
Got hung up on #274 which is mercifully, finally resolved. Will dispatch this issue tomorrow (Tuesday).

**Comment by jasloe** [comment]
Fixed.

**Comment by cchristopherhowardd** [comment]
Can you make these changes to the URL?

One more index page change: Donate ( https://staging.aarome.org/support/donate ) will now be called Annual Fund. I changed the header of the page, but the URL will need to become https://staging.aarome.org/support/annual-fund for English and https://staging.aarome.org/it/sostengo/fondo-annuale for the Italian site.

**Comment by jasloe** [comment]
Whoops, missed that. Fixed now.

**Comment by jasloe** [comment]
Reopening to log a not
