### ISSUE TITLE
Catalog of translation issues

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#278]
Systematically going through site to tighten up translation issues, e.g. "fallback" issues (i.e. when a translation is unavailable, display English content), issues pertaining to repeated content displaying in search results, untranslated content, etc. 

**/it**

- [x] at home page, "Node" appearing in breadcrumb
- [x] at news/features, **Features** is untranslated, should be **Articoli**
- [x] #261 
- [x] "Read more" incorrectly styled at /it/attualita/notizie-veloci. Possibly other places.
- [x] it/attualita/comunicati-stampa has incorrect layout and styling for download. Related to above. 

**/en**
no issues so far

**Comment by jasloe** [comment]
at home page: excluded breadcrumb display at /admin/structure/block

**Comment by jasloe** [comment]
at news/features: it appears the view is untranslated. Reminder to add translations.

**Comment by cchristopherhowardd** [comment]
The only problem I have on the site with English/Italian pages is at https://staging.aarome.org/publications/magazine. Changes made on the Italian page replace what's on the English page.
