### ISSUE TITLE
External links in the Publications section

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#280]
Since the dev and staging sites have been merged, we've lost the external links for the Publications pages.

For the Academic Body catalogue:

<img width="985" alt="Screen Shot 2020-04-08 at 11 31 30 AM" src="https://user-images.githubusercontent.com/38765846/78803233-bce92600-798c-11ea-8c51-02367e6070a4.png">

There should be the words PURCHASE NOW and a link to AAR's shop after the text description and before the next book

<img width="1350" alt="Screen Shot 2020-04-08 at 11 33 35 AM" src="https://user-images.githubusercontent.com/38765846/78803452-076aa280-798d-11ea-9e7b-474c2660875e.png">

Some publications have two links. For the Memoirs, there is a link to the University of Michigan website to buy the book and another to JSTOR to read it online.

<img width="963" alt="Screen Shot 2020-04-08 at 11 32 03 AM" src="https://user-images.githubusercontent.com/38765846/78803547-25380780-798d-11ea-8622-857fc0569794.png">

The formatting should be similar to that for PDF links in the Publication section, like those for the Magazine. See https://staging.aarome.org/publications/magazine as an example. 

<img width="1346" alt="Screen Shot 2020-04-08 at 11 37 44 AM" src="https://user-images.githubusercontent.com/38765846/78803776-66301c00-798d-11ea-88b2-f8504346bc3e.png">

**Comment by cchristopherhowardd** [comment]
Before the merge, I believe the Title of Publication field for all publications was styled Trade Gothic and all caps. Can we get this formatting again?

**Comment by jasloe** [comment]
Related to #268. Closing.
