### ISSUE TITLE
Residents lose biographies

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#281]
After the merge, the Residents pages no longer publish text in the biography field. Here is Mary Beard ( https://staging.aarome.org/people/residents/mary-beard ) as an example. Under the hood we have text in the biography field:

<img width="920" alt="Screen Shot 2020-04-09 at 10 08 42 AM" src="https://user-images.githubusercontent.com/38765846/78904326-53c7e800-7a4a-11ea-8515-0d2ff1830a52.png">
This text does not appear on the published page:

<img width="1355" alt="Screen Shot 2020-04-09 at 10 08 58 AM" src="https://user-images.githubusercontent.com/38765846/78904350-604c4080-7a4a-11ea-8f06-88166df78b9e.png">

**Comment by jasloe** [comment]
Whoops, missing a tag in the template. Will fix.

**Comment by jasloe** [comment]
Fixed. Also fixed some inconsistent typography.
