### ISSUE TITLE
Residents and Italian Fellows datepickers

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#282]
I don't have any Residents or Italian Fellows posted from before 2015. Can you hide the years from 2011 to 2014 from the Residents and Italian Fellows datepickers?

<img width="699" alt="Screen Shot 2020-04-09 at 3 29 00 PM" src="https://user-images.githubusercontent.com/38765846/78933226-fbf3a600-7a76-11ea-9a77-278ec634ef04.png">

<img width="761" alt="Screen Shot 2020-04-09 at 3 31 02 PM" src="https://user-images.githubusercontent.com/38765846/78933368-35c4ac80-7a77-11ea-9ca5-3c8ea3ca6010.png">

**Comment by jasloe** [comment]
Fixed. Limited ```views.view.people``` to selected items.
