### ISSUE TITLE
People index page changes

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#284]
The order of boxes the People index page ( https://staging.aarome.org/people ) needs a refresh, partly due to the merge reverting to an earlier order, but also with a new change. Here is the ideal order of People boxes, from top to bottom:

Rome Prize Fellows
Italian Fellows
Residents
Affiliated Fellows
Visiting Artists & Scholars
Society of Fellows
Juries
Advisors

**Comment by jasloe** [comment]
Fixed.
