### ISSUE TITLE
Year of Publication as part of header

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#285]
Can we add the year of publication to the header information for all publications? I feel like we had the year on prior versions of the Publications section, but that it may have been overwritten in the merge. All books in the Publications section are listed in reverse chronological order, but this isn't obvious to visitors to the page.

<img width="1379" alt="Screen Shot 2020-04-14 at 11 40 42 AM" src="https://user-images.githubusercontent.com/38765846/79244749-3f6a5d80-7e45-11ea-93e8-3dbf2bb68a5c.png">

Only the year, not the complete date, should appear with each book.

<img width="896" alt="Screen Shot 2020-04-14 at 11 42 55 AM" src="https://user-images.githubusercontent.com/38765846/79244882-64f76700-7e45-11ea-81c0-a0df5dfaa5a3.png">

**Comment by cchristopherhowardd** [comment]
Do you like my handwritten notes?

<img width="1345" alt="Screen Shot 2020-04-14 at 11 40 21 AM" src="https://user-images.githubusercontent.com/38765846/79245118-ad168980-7e45-11ea-9fc0-0575cf9916b6.png">

**Comment by jasloe** [comment]
> Do you like my handwritten notes?

State of the art! Fixed.
