### ISSUE TITLE
More Events button/link

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#287]
We used to have a stylized way for the button/link to "More events," "More ____" across the site. I believe it was text in Trade Gothic and all caps, similar to the h3 header. Can you reinstate this?

Here is the Events --> Series page:

<img width="1412" alt="Screen Shot 2020-04-16 at 9 56 27 AM" src="https://user-images.githubusercontent.com/38765846/79465185-00fdab80-7fc9-11ea-9bb8-0ee0ed8d2023.png">

Here is the News --> Quick News page:

<img width="1394" alt="Screen Shot 2020-04-16 at 10 00 19 AM" src="https://user-images.githubusercontent.com/38765846/79465281-212d6a80-7fc9-11ea-8811-9167419b74d1.png">

It could say "More Quick News."

Here is the News --> Features page:

<img width="1396" alt="Screen Shot 2020-04-16 at 10 18 20 AM" src="https://user-images.githubusercontent.com/38765846/79467305-a580ed00-7fcb-11ea-9ff8-aaf45d754ddc.png">

It could say "More Features."

**Comment by jasloe** [comment]
Style sheet is fixed and will push shortly. But closing in favor of #288.
