### ISSUE TITLE
Inconsistent spacing for section pages

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#289]
I've noticed that we have inconsistent spacing for the section pages. First example: Events looks normal, with breathing room between photo, headline, text, and arrow [ the >]

<img width="1370" alt="Screen Shot 2020-04-23 at 3 16 34 PM" src="https://user-images.githubusercontent.com/38765846/80140249-aa1e4600-8575-11ea-875f-6762c6546236.png">

The People section page does not have this elegant spacing:

<img width="1417" alt="Screen Shot 2020-04-23 at 3 16 47 PM" src="https://user-images.githubusercontent.com/38765846/80140369-d76af400-8575-11ea-8c06-de95e693969a.png">

These pages look rad:

https://staging.aarome.org/events
https://staging.aarome.org/events/calendar
https://staging.aarome.org/news
https://staging.aarome.org/news/features

These pages look sad:

https://staging.aarome.org/about
https://staging.aarome.org/people
https://staging.aarome.org/society-of-fellows
https://staging.aarome.org/apply
https://staging.aarome.org/research
https://staging.aarome.org/publications
https://staging.aarome.org/support

**Comment by jasloe** [comment]
I noticed that. I think I munged a style sheet somewhere. It's a quick fix.

**Comment by jasloe** [comment]
Much less sad now.

**Comment by cchristopherhowardd** [comment]
So very unsad now!

**Comment by jasloe** [comment]
Yep, closing!
