### ISSUE TITLE
COVID-19 notice, EU Cookie notice

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#296]
@cchristopherhowardd –– I roughed out a COVID-19 notice just below the main navigation and a dismissible cookie acceptance fly-in at the footer.  These are mostly un-styled at the moment and the buttons/links don't go anywhere quite yet. Let me know if you have any feedback on placement and content in the next couple of days. Thanks!

**Comment by cchristopherhowardd** [comment]
COVID-19 notice looks good. I'm sure the higher-ups will probably change the wording, but it's fine for now. You can link the "More Information" to https://staging.aarome.org/news/features/aar-close-rome-campus-early-april-3.

**Comment by cchristopherhowardd** [comment]
Can the COVID-19 notice have a circled X (or something similar) so that people can close the notice? Perhaps on the far right side?

**Comment by cchristopherhowardd** [comment]
Translation for /it/ pages: 

A causa di COVID-19, l’Accademia è temporaneamente chiusa. Maggiori informazioni.

**Comment by jasloe** [comment]
> Can the COVID-19 notice have a circled X (or something similar) so that people can close the notice? Perhaps on the far right side?

I'd have to write a cookie handler to make it dismissible. If there's extra time this month, I can write one.

**Comment by cchristopherhowardd** [comment]
Shelf the task for now. We have bigger fish to fry this month.

**Comment by jasloe** [comment]
I forgot to add that the content block in the header can be changed. For example, "now accepting Rome Prize applications", "Event streaming live now", that kind of thing. Just something to file away for now.

**Comment by cchristopherhowardd** [comment]
Can you make the link for "More Information" go to https://staging.aarome.org/news/features/aar-close-rome-campus-early-april-3 ?

**Comment by jasloe** [comment]
@cchristopherhowardd –– here's the current text for the fly-in.

We use cookies to improve user experience, analyze website traffic, and provide social media services. We may share your site usage data with our analytics partners. By continuing to the site, you consent to store on your device all the technologies described in our Cookie Policy. Please read our privacy policy for full details.

**Comment by jasloe** [comment]
Closed in favor of #317.
