### ISSUE TITLE
Design feedback from Open

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#298]
Open reviewed the staging website and have a few comments on the design. These largely have to do with spacing and the grid, with a few remarks about typeface size and selection. Can you review the attached PDF and let me know your thoughts? I know that we've made adjustments to Open's design along the way.

[ad49_adjustments_050520mm.pdf](https://github.com/aarome/aarome/files/4593636/ad49_adjustments_050520mm.pdf)

**Comment by jasloe** [comment]
@cchristopherhowardd –– just a quick note that this is in progress. A little time consuming but what can you do. Will work on pushing those changes beginning this evening. It'll be incremental as I'll need to test quite a bit.

**Comment by jasloe** [comment]
Temporarily disabled some image style sheets to make refactoring easier.
