### ISSUE TITLE
New section page for Academic Programs

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#299]
Anne Coulson, our senior program officer in Rome, wants to expand the Academic Programs webpage (https://staging.aarome.org/apply/academic-programs), which is located in the Apply section (https://staging.aarome.org/apply). Instead of having the Academic Programs page be a single-page palimpsest, where we overwrite the previous year's content with the current offerings, I want to create an index-y section like we have for the Affiliated Fellowships (https://staging.aarome.org/apply/affiliated-fellowships). I hope this isn't too much of a headache.

The following Basic Pages should be added to the new Academic Programs index page in this order, from top to bottom. I created pages for summer and winter programs back to 2016 (probably one year too many, but oh well).

CANCELED: 2020 Classical Summer School [5239]
CANCELED: Roman Epigraphy [5238]
2019 Classical Summer School [5237]
Art Historical Image in the Digital Age [5236]
2018 Classical Summer School [5241]
Latin Epigraphy [5242]
Winter Program in Latin Paleography and Codicology [5243]
2017 Classical Summer School [5240]
Howard Comfort, FAAR’29, Summer School in Roman Pottery Studies [5245]
Art Historical Image in the Digital Age [5246]
AAR/Gabii Joint Summer Program in the Digital Documentation of Archaeological Collections [5244]
Greek Paleography and Codicology [5247]
2016 Classical Summer School [5250]
Latin Epigraphy [5248]
Documentation and Analysis of Ancient Buildings [5249]

URL for the English-language pages will form as they naturally do. I don't care about translating the names of the programs, so the Italian-language URLs can begin with https://staging.aarome.org/it/partecipazione/programmi-accademici and end with /whatever-the-title-is.

A new Academic Programs section isn't critical for a site launch--this summer's two programs have been canceled. If the workload for creating the section is too much, we can take this project up in June.

**Comment by jasloe** [comment]
No problem. Let's just get it done now. Possible to meet on Tuesday to briefly discuss this and also events? I'm still fuzzy on what we're after there: #286.

**Comment by cchristopherhowardd** [comment]
A Tuesday meeting is fine. The only thing on my schedule is a call with Open from 4:00 to 5:00 PM.

**Comment by jasloe** [comment]
Looks like our NEH grant application deadline is extended another day, so we may still be working on that tomorrow. Will keep you posted.

**Comment by cchristopherhowardd** [comment]
My schedule is generally open. I'm not available this Thursday from 11:30 AM to 12:30 PM, but have no meetings scheduled for tomorrow.

**Comment by jasloe** [comment]
In order to make this work as desired, I've created a new content type called "Programs." A little more effort up front but will make it easier to perform search operations (show me only Programs) and administer permissions (allow Anne to edit Program content types and not Basic Pages, for example). Building the view (i.e. the index page) is a lot easier if it's based on a content type and not some other arbitrary data point, like the node ID. Lastly, this content type also includes date fields which we'll need in order to chronologically sort the records.

**Comment by jasloe** [comment]
@cchristopherhowardd –– this is pushed to staging with two example nodes.

https://staging.aarome.org/apply/academic-programs
https://staging.aarome.org/it/partecipazione/programmi-accademici

Don't worry about the left/right margins. I am refactoring those per #298.

**Comment by cchristopherhowardd** [comment]
Sounds/looks like this is a good solution.
