### ISSUE TITLE
Rediscovered Library page

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#300]
A couple of weeks ago I rediscovered a Basic Page about the AAR Library that I'd like to place on the site: https://staging.aarome.org/node/26. It's a short, nicely written essay on the library that has an existing Italian translation.

I'd like for the node to appear at https://staging.aarome.org/research/library as the second box on the page, after Notices and before Request Forms & Services. It can have the name https://staging.aarome.org/research/library/about and https://staging.aarome.org/it/ricerca/biblioteca/sulla-collezione. 

You'll find a similar placement of information at https://staging.aarome.org/research/photographic-archive.

**Comment by cchristopherhowardd** [comment]
I am looking for a replacement photo for this page. It currently uses the same image as https://staging.aarome.org/research/library/notices.

**Comment by jasloe** [comment]
Ok, no problem.

**Comment by cchristopherhowardd** [comment]
Related work: unpublish https://staging.aarome.org/research/library/guides-histories and remove the box for it from the Library section page ( https://staging.aarome.org/research/library ). I have added the four PDFs on this page to the rediscovered Library About page .

**Comment by jasloe** [comment]
Done. Please test and close.
