### ISSUE TITLE
increase disk volume from 16 GB to 100 GB

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#301]
@cchristopherhowardd ––

It looks like we've run out of disk space. The current size of the storage volume is 16 GB, which is enormous for a web server. I cleaned up a few caches so the server should be ok temporarily. 

I recall running into this issue once or twice before with Academy projects. Lots of PDFs and large-ish images (> 5 MB) are uploaded and attached to nodes. In the past, we tried restricting image sizes to < 5 MB but that didn't work out to well for various reasons. 

Instead, I'm going to attach a 100 GB volume dedicated to images and PDFs. This volume is entirely separate from the operating system and code and can be detached and resized as needed (though I doubt we'll ever reach its upper limit).

**Comment by jasloe** [comment]
@cchristopherhowardd ––

Moving files to new volume now. Images will be broken until that is completed. Should take < 10 minutes.

**Comment by jasloe** [comment]
Ok, this is done:

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvdp       100G  6.2G   94G   7% /vol0/files
```

100 GB should last quite a long time!

**Comment by jasloe** [comment]
I am leaving this open because it might be a good idea to move the MySQL database storage to a separate volume as well. Some of the benefits cited in the AWS documentation:

```
Persistent storage in the event of instance failure - If an EBS volume is used as the storage for a MySQL database, then the data is protected from instance termination or failure. You can simply attach/mount the volume on another instance and MySQL will run its normal recovery procedures to bring the database up to date with the binary logs.

Safety & Replication - According to Amazon, "EBS volume data is replicated across multiple servers". This makes your data safer than the default instance storage.

Improved performance - Early reports from studies on random access disk IO performance indicate that EBS IO rates can be faster than ephemeral storage and even local disk IO. This has obvious benefits for databases which are often IO bound.

Fast and easy backups - EBS snapshots alone can be a sufficiently attractive reason to move a database server to Amazon EC2. Being able to take live, consistent, binary snapshots of the database in just a few seconds is a thing of beauty. Add in the ability to create a new EBS volume from a snapshot so another EC2 instance can run against an exact copy of that database... and you've opened up new worlds of possibilities.
```

**Comment by cchristopherhowardd** [comment]
The upper limit for images on the new website is 5 MB, which I've obeyed. Maybe the stuff imported from the current site is to blame for hogging all the space. Jerks.

<img width="1396" alt="Screen Shot 2020-05-13 at 5 37 49 PM" src="https://user-images.githubusercontent.com/38765846/81868646-ab251080-9540-11ea-8cdf-5d2930334002.png">

**Comment by jasloe** [comment]
Ah ha. That certainly explains it.
