### ISSUE TITLE
Missing News Features and Events

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#305]
This morning I noticed that about six weeks of Events, from December 2019 and January 2020, disappeared from https://staging.aarome.org/events/calendar. Even the images associated with those pages were gone. I created new Events for them and uploaded the photos again and moved on with my day.

Now I noticed that we’re missing all News Features (https://staging.aarome.org/news/features) between June 2019 and January 2020. Where might these pages be hiding?

**Comment by cchristopherhowardd** [comment]
There are only three Features missing, but still. I re-created about six or seven Events earlier.

**Comment by jasloe** [comment]
That was my fault, sorry. There was a content delta in the wake of The Great Merge. I successfully migrated in the missing content and missed a few nodes in that migration.
