### ISSUE TITLE
Missing Job Opportunities

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#307]
I noticed a few days ago that the Jobs & Internships page ( https://staging.aarome.org/about/jobs ) is missing from the About section page ( https://staging.aarome.org/about ). Can you add it to the section page, dead last after Tours?

The footer will need to be adjusted, too, with Jobs & Internships moved last (and Society of Fellows added, too.)

**Comment by jasloe** [comment]
Thought we took that out? Maybe, not? Who knows. Anyway, restored.
