### ISSUE TITLE
For the Ages

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#314]
It looks like Open envisions the new "For the Ages" section to be a page that falls within the News Features purview. We should have a conversation very soon (today?) to discuss how this page relates to existing News Feature pages.

[ad72_fortheages_webpagelayout_061120mm.pdf](https://github.com/aarome/aarome/files/4781217/ad72_fortheages_webpagelayout_061120mm.pdf)

**Comment by cchristopherhowardd** [comment]
For the Ages is a News Feature on steroids.

**Comment by cchristopherhowardd** [comment]
Two previous requests here, and a new third request:

1. Can you overwrite the URL stripping so that it’s https://staging.aarome.org/news/features/for-the-ages?

2. Also, can you code something so that the inline captions are a smaller font size? Maybe an <h6> at 12 or 14 point? I don’t see specs for captions in Open’s recent document. The regular image caption is coded <div class="blazy__caption--media-caption”> but I don’t know how to replicate that inline.

3. I created this page as a Basic Page, not as a News Feature. Is there an easy way to slip the page into News Features, or do I need to re-create it as a NF page?

**Comment by cchristopherhowardd** [comment]
Regarding the Basic Page/News Feature question, it looks like the News Feature template does not take the h2 tags on the left side of the screen. What to do?

**Comment by jasloe** [comment]
We’re working on dev. Also I haven’t been able to push anything to dev on this flaky internet connection. Mobile is basically 2G out here. We’re heading into Albany for a meeting right now and will see if I can get something going there.

________________________________

**Comment by cchristopherhowardd** [comment]
Oh, right--moving to dev now.

**Comment by cchristopherhowardd** [comment]
The node is dev.aarome.org/node/5311/

**Comment by jasloe** [comment]
Just pushed code and content to dev.

**Comment by jasloe** [comment]
You'll need to add in the inline images.

**Comment by cchristopherhowardd** [comment]
I uploaded an image for each page section. Do I need to hard code the photos in the running text?

**Comment by cchristopherhowardd** [comment]
How strange that all of the images I uploaded have disappeared.

**Comment by jasloe** [comment]
one sec

**Comment by jasloe** [comment]
I'm at the train station and can't connect to the server from here. One of the template files is missing a variable that I need to update. Not much I can do until I can get back online.

**Comment by cchristopherhowardd** [comment]
That’s OK. The wife and I are about to go on a short afternoon walk.

Chris
-------
Christopher Howard
Communications Manager

**Comment by cchristopherhowardd** [comment]
I added one image to each page section. Open's design calls for the image and caption to be placed after the first paragraph of body text, though.

**Comment by jasloe** [comment]
If you take a look at the screenshot, you'll see the first two items contain Esther VD content. Edit the node, select 'Collapse All' at Page section, then add a page section and drag under C. Brian Rose. The first page section will contain the opening paragraph and image, the second page section will contain the remaining paragraphs. Repeat as needed.

I'm back in the city now and have had a chance to look at this more closely. If there are going to be more of these types of pages, we'll definitely want to move this content to a refactored and extended news feature content type. (I stuck this content in a basic page just to get something up and running.) Let me know what the plans are with regard to long term plans. As I typed this, I realize we will probably have to do that anyway to support slideshows in page sections.

![Screen Shot 2020-06-16 at 10 25 32 PM](https://user-images.githubusercontent.com/1063667/84848593-731e5b00-b021-11ea-8b6c-b52d38ebbcb5.png)

**Comment by cchristopherhowardd** [comment]
I created new page sections for the texts that come after the first paragraph and the image. The solution worked well. Captions for the images aren't appearing on the page. Is this the next step toward completing the page?

I can imagine there being more of these types of pages, so it's worth creating a refactored and extended news feature content type down the road (later this summer, after launch). Having slideshows in page sections is a part of Open's original design, so we'll need to make them anyway.

The "For the Ages" page was supposed to be in the spring 2020 issue of _AAR Magazine_, which was canceled. It's unlikely that we'll publish a fall/winter 2020 magazine later in the year, so whatever article ideas that would have been appropriate for print will need to live online, as a News Feature on Steroids.

Side note: for the fall/winter 2019 AAR Magazine, we did the first "For the Ages." I'd like to get that content on the AAR website soon. My Photoshop skills are limited, so I'm unable to create the photo-with-background images that we're using on our For the Ages webpage.

[For the Ages from AAR Magazine.pdf](https://github.com/aarome/aarome/files/4793331/For.the.Ages.from.AAR.Magazine.pdf)

**Comment by jasloe** [comment]
After staring at a template file for 30 minutes, I realized I was looking in the wrong place for the caption variable. Turned it on but need to tweak the spacing. 

Looking at page types 082118, I see images inset in page sections but not slideshows. Is there another example somewhere? Just trying to suss out all of the use cases.

Send me the photos for the F/W 2019 feature and I'll photoshop.

**Comment by cchristopherhowardd** [comment]
I'm looking at the PDF that Open made for "For the Ages."

[ad72_fortheages_webpagelayout_061120mm_withnotes.pdf](https://github.com/aarome/aarome/files/4794618/ad72_fortheages_webpagelayout_061120mm_withnotes.pdf)

The second "For the Ages" page is something we can do after the website is launched.

**Comment by cchristopherhowardd** [comment]
Two requests:

1. Can you break the introductory text like it appears in Open's design?

<img width="939" alt="Screen Shot 2020-06-18 at 9 08 36 AM" src="https://user-images.githubusercontent.com/38765846/85023941-5bd78e80-b143-11ea-926f-2922340e1ee7.png">

2. Can you move the page to staging?

**Comment by cchristopherhowardd** [comment]
I noticed today that formatting for "For the Ages" got a little tipsy, took a wrong turn down an alley, and got roughed up by some kids looking for trouble. I unpublished the page and await your return from vacation.

<img width="631" alt="Screen Shot 2020-08-05 at 4 09 00 PM" src="https://user-images.githubusercontent.com/38765846/89459033-09275580-d736-11ea-9598-418ffa6534e8.png">

**Comment by cchristopherhowardd** [comment]
Can you take a look at the For the Ages page this week? I imagine that AAR will soon be sending an email blast about this page. Once the page is fixed, I will probably begin creating another For the Ages page, using content from the fall/winter 2019 magazine.

**Comment by cchristopherhowardd** [comment]
Might you be able to revisit this page soon? The decision was made recently to do a spring 2021 magazine, to be printed in May/June. Another decision was to take a couple of feature articles from the magazine and do a "web presentation" of them, which means doing something like "For the Ages." That means I will need to have https://www.aarome.org/news/features/ages ready as an example of what these web presentations might look like.

Monday is a holiday for the Academy.

**Comment by jasloe** [comment]
Shoot, I thought I pushed that to production a while ago. I guess I didn't! I'll have it up for you by Tuesday.

**Comment by jasloe** [comment]
Pushed to production.
