### ISSUE TITLE
User account migration

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#32]
List of current and active users on aarome.org. Retain all of them? 

[aarome-users.xlsx](https://github.com/aarome/aarome/files/2202439/aarome-users.xlsx)

**Comment by cchristopherhowardd** [comment]
Retain just the current and active users. All those other folks--goodbye!

**Comment by jasloe** [comment]
Ok! I'll make your account the "owner" of those pages.

**Comment by jasloe** [comment]
Done. Including this table for reference here as some of the migrations are dependent on user ids.

<pre>
0		NULL	0
1	kPUQcGDNC2HZFT42kQjQWk9H	jason@minorscience.com	1
3	staging	j@minorscience.com	1
8	a.coulson	a.coulson@aarome.org	1
9	a.olweiler	a.olweiler@aarome.org	1
10	archives	archives@aarome.org	1
11	c.puglisi	c.puglisi@aarome.org	1
12	g.battaglia	g.battaglia@aarome.org	1
13	l.ciuffa.ext	l.ciuffa.ext@aarome.org	1
14	m.mcclary	m.mcclary@aarome.org	1
17	s.hierl	s.hierl@aarome.org	1
18	k.iara	k.iara@aarome.org	1
19	c.howard	c.howard@aarome.org	1
</pre>
