### ISSUE TITLE
Overlapping boxes for PDF downloads on Library page

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#324]
At the bottom of https://www.aarome.org/research/library/about, the boxes for PDF downloads are overlapping. 

<img width="1440" alt="Screen Shot 2020-07-27 at 9 53 49 AM" src="https://user-images.githubusercontent.com/38765846/88551463-e3d96f80-cff0-11ea-8e98-2d604e2405a6.png">

**Comment by cchristopherhowardd** [comment]
I've found another example of this overlapping at https://www.aarome.org/research/resources/tutorials.

**Comment by cchristopherhowardd** [comment]
As a side note, there isn't an issue with overlapping in the Programs section. One example of a beautifully functioning stack of PDF downloads is https://www.aarome.org/apply/academic-programs/2019-classical-summer-school.

**Comment by jasloe** [comment]
Applied hotfixes. The Packard Humanities link title is very long, so maybe consider shortening that.

**Comment by jasloe** [comment]
@cchristopherhowardd ––

is: https://www.aarome.org/it/ricerca/biblioteca/sulla-collezione

the correct translation for: https://www.aarome.org/research/library/about

?

**Comment by cchristopherhowardd** [comment]
Yes, those are the English and Italian language versions of the same page content.

**Comment by cchristopherhowardd** [comment]
More overlapping boxes at https://www.aarome.org/research/archaeology/affiliated-projects

There's a spacing issue with the box at https://www.aarome.org/research/archaeology/archaeological-archive. It's probably unrelated to the larger issue but needs a quick fix!

**Comment by cchristopherhowardd** [comment]
I shortened a few long titles, but not enough to satisfying my iPhone. Here is a screenshot of the Research Tutorials page.

![IMG_7907](https://user-images.githubusercontent.com/38765846/88687793-afd07e00-d0c6-11ea-91e3-27a6bb3a7774.PNG)

**Comment by jasloe** [comment]
I'm sure there's some obscure CSS property that will handle that. I'll have to dig into it.

**Comment by cchristopherhowardd** [comment]
Reupping this request:

More overlapping boxes at https://www.aarome.org/research/archaeology/affiliated-projects and https://www.aarome.org/research/institutional-archive

There are spacing issues with boxes at https://www.aarome.org/research/archaeology/archaeological-archive and https://www.aarome.org/research/institutional-archive. It's probably unrelated to the larger issue but needs a quick fix! The issue is white space above and/or below the box itself.

**Comment by cchristopherhowardd** [comment]
I just uploaded a Friends of the Library Brochure to https://www.aarome.org/support/join-renew and got this:

<img width="1355" alt="Friends of the Library Brochure" src="https://user-images.githubusercontent.com/38765846/99823577-909ca700-2b22-11eb-96b1-1f91665ddf3c.png">

**Comment by jasloe** [comment]
Links and files take different file sheets. There's no way to predict which order they'll appear in so we'll need to figure out another system.

**Comment by cchristopherhowardd** [comment]
In my experience, links appear above files.

**Comment by jasloe** [comment]
Sure, but it's not terribly resilient in any case. I'm going to dumb down the templating to that links and files use the same template.

**Comment by cchristopherhowardd** [comment]
Another example of the curious overlapping boxes at https://www.aarome.org/support/join-renew and https://www.aarome.org/it/sostegno/iscriviti-e-rinnova. 

I uploaded new PDFs for the Current Members for both the page sections "Friends of the AAR" and "Friends of the Library" (deleting the older PDFS and adding the new ones). The boxes for "Friends of the AAR" render like they should, but the boxes for "Friends of the Library" overlap.

<img width="1357" alt="Screen Shot 2020-12-04 at 3 44 08 PM" src="https://user-images.githubusercontent.com/38765846/101215338-ad20ff00-364b-11eb-99f4-c7129c883c6a.png">

<img width="1334" alt="Screen Shot 2020-12-04 at 3 43 56 PM" src="https://user-images.githubusercontent.com/38765846/101215368-b8742a80-364b-11eb-84d6-9e5507ce205a.png">

**Comment by jasloe** [comment]
Yes, that's getting a refactor from scratch. Do you want this moved up higher in the priority queue?

**Comment by cchristopherhowardd** [comment]
Move up.

**Comment by jasloe** [comment]
Ok, got this more or less resolved. Didn't take long. Will push this up first thing Monday.

**Comment by jasloe** [comment]
Layout demo on local server. Will add typography and hover states on Monday.

<img width="629" alt="Screen Shot 2020-12-04 at 5 57 43 PM" src="https://user-images.githubusercontent.com/1063667/101223595-6090f000-365a-11eb-855a-2c7315e595c4.png">

**Comment by jasloe** [comment]
Pushed. Please test and close.

**Comment by jasloe** [comment]
Can this be closed?

**Comment by jasloe** [comment]
Reopening for a minute to fix border on "Apply" button for home page. Got too aggressive with refactoring overlapping buttons on library/support pages!
