### ISSUE TITLE
URL changes

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#326]
In this issue I'll begin to compile a list or URL changes for various sections of the site. Once a URL has been updated, we can ~~strike through~~ the text.

https://www.aarome.org/research/library/collection-policy --> https://www.aarome.org/research/library/collection-development

https://www.aarome.org/it/ricerca/biblioteca/nuove-acquisizioni --> https://www.aarome.org/it/ricerca/biblioteca/sviluppo-della-collezione

**Comment by jasloe** [comment]
I've granted permission to your role to make these changes.

- Edit desired node
- Customize url alias at right
- Save node
- Edit desired translated node
- Customize url alias as above
- Save node

Please confirm that works for you.

**Comment by cchristopherhowardd** [comment]
It works. Closing issue.
