### ISSUE TITLE
Library resource repairs

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#327]
The list of Electronic Journals needs formatting: https://www.aarome.org/research/resources/electronic-journals

The list of Research Databases has disappeared: https://www.aarome.org/research/resources/research-databases

The list of Libraries & Institutions is gone: https://www.aarome.org/research/resources/libraries-institutions

The list of Useful Links is gone: https://www.aarome.org/research/resources/useful-links

**Comment by jasloe** [comment]
Pushed fix. Not sure what happened there. 

For some reason, the select list at libraries & inst. isn't receiving styling. Leaving this open until that's resolved.

**Comment by cchristopherhowardd** [comment]
Fantastic.

**Comment by cchristopherhowardd** [comment]
This request, previously on the back burner but needing attention now, may fall under a separate issue (that I can't find this morning), but it could be categorized here. 

The drop-down menu for three library resource pages--[Electronic Journals](https://www.aarome.org/research/resources/electronic-journals), [Research Databases & Digital Collections](https://www.aarome.org/research/resources/research-databases), and [Libraries & Institutions](https://www.aarome.org/research/resources/libraries-institutions)--need to be alphabetized. 

<img width="1153" alt="Electronic Journals" src="https://user-images.githubusercontent.com/38765846/110487040-30bf1180-80bb-11eb-8a99-389be3c7e44e.png">

<img width="1195" alt="Research Databases" src="https://user-images.githubusercontent.com/38765846/110487051-33ba0200-80bb-11eb-93fc-2e7b80a4c80c.png">

<img width="1153" alt="Libraries Institutions" src="https://user-images.githubusercontent.com/38765846/110487067-374d8900-80bb-11eb-8247-676ec3b596c1.png">

**Comment by cchristopherhowardd** [comment]
The Italian pages are also out of alphabetical order, in mirrored form. In other words, the Italian translations appear in the same order as the out-of-order English terms. If we need to prioritize one right away because the problem is complicated (as I recall it being many months ago), then the English terms take priority. 

<img width="1115" alt="Riviste Elettroniche" src="https://user-images.githubusercontent.com/38765846/110488063-26e9de00-80bc-11eb-8be2-ef9b0204c951.png">

<img width="1223" alt="Banche dati collezioni digitali" src="https://user-images.githubusercontent.com/38765846/110488082-2b15fb80-80bc-11eb-9733-f3c32ce03763.png">

<img width="1086" alt="Biblioteche   Istituzioni" src="https://user-images.githubusercontent.com/38765846/110488094-2ea98280-80bc-11eb-9d46-0a7e4df3b6bf.png">

**Comment by cchristopherhowardd** [comment]
A related issue is this: a new taxonomy category for Library Resources is Art Museums & Galleries ( https://www.aarome.org/taxonomy/term/1064 ). Kristine Iara in Rome created a handful for the [Research Databases & Digital Collections](https://www.aarome.org/research/resources/research-databases) page, and they're appearing on the page at the very bottom, but the category Art Museums & Galleries is not appearing in the drop-down menu.

**Comment by cchristopherhowardd** [comment]
Related to the related issue above: a newishly created Resource Subject category for the [Libraries & Institutions](https://www.aarome.org/research/resources/libraries-institutions) is American Studies ( https://www.aarome.org/taxonomy/term/1050 ). Like the category Art Museums & Galleries above, the content appears at the bottom of the page and the category is missing from the drop-down menu.

**Comment by jasloe** [comment]
Taking a look now.

**Comment by jasloe** [comment]
@cchristopherhowardd –– note the following. Tested locally. Will apply to production after 6 pm in case I need to roll back.

- [] Alphabetize select lists in both English and Italian. A patch is ready for this. Update ```better_exposed_filters``` and ```selective_better_exposed_filters``` as follows:

```
composer require 'drupal/better_exposed_filters:4.x-dev@dev' --no-update
composer update drupal/better_exposed_filters

composer require 'drupal/selective_better_exposed_filters:^2.0@beta' --no-update
composer update drupal/selective_better_exposed_filters

drush cr
drush updatedb
```

- [] Add new term to select list.

**Comment by cchristopherhowardd** [comment]
Great, thanks! I look forward to seeing the reconfigured drop-down menus!

**Comment by jasloe** [comment]
Ok rolled to production. There was a dependency snafu that was a little vexing. Hoping that there aren't any negative side-effects. I tested fairly extensively though I didn't tinker with the editorial workflows (creating, editing, deleting content). If you encounter any errors, let me know. 

Also, looks like "Art & Museums" needs a translation.

**Comment by cchristopherhowardd** [comment]
Musei & gallerie d’arte

**Comment by jasloe** [comment]
I accidentally blew away the translation for "All subjects". Do you recall it?

**Comment by cchristopherhowardd** [comment]
Never fear! A screenshot a few responses above tells me it's Qualsiasi.

**Comment by jasloe** [comment]
Ok, all set. Please test and close. 

Reminder about the untranslated terms in the sidebar. From #350:

```
> If there are untranslated nodes in the view (and, hence, no reference to the Italian language vocabulary term), the query results default to English because it only has a reference to the English-language term. Not much can be done about this as Drupal's 'fallback to whatever primary language' is pretty deeply baked in.
```

In other words, all of the library resources nodes need to be translated (or at least step through the /node/*/translations [add]) in order for the sidebar term to appear in the correct language. 

Going forward, it would be good to step through the translation forms when creating a node, even if there's no specific Italian translation available. (The content would appear in English at /it.)

**Comment by cchristopherhowardd** [comment]
I understand the situation about creating English and Italian nodes for a single resource so that the sidebar (drop-down menu) functions properly on both language-sites. The entirety of the library resources are in English, though. I may have a conversation about the issue with Kristine Iara soon, to gauge how important it is for the library to have a fully functioning Italian side.
