### ISSUE TITLE
News Feature bylines and publication dates

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#328]
Can you reinstate the byline and publication dates on News Feature pages? Most articles do not have an author, but some do and their names should be on the page. Publication dates are needed for all pages.

**Comment by jasloe** [comment]
Where should both appear?

**Comment by cchristopherhowardd** [comment]
In earlier versions of the staging site, the byline and date appeared after the headline and before the photo/slideshow.

**Comment by cchristopherhowardd** [comment]
Can you prioritize this issue this week?

**Comment by jasloe** [comment]
Uncommented template references and applied stylesheet. 

https://www.aarome.org/news/features/keys-castle-interview-tomaso-de-luca

Please test & close.

**Comment by cchristopherhowardd** [comment]
Can the phrase "Texts by" be "Text by"? I think the plural came about because that's what was needed for the For the Ages page ( https://www.aarome.org/news/features/ages ).

Nearly all other regular articles with a byline are by a single author (e.g., Claudia Trezza in https://www.aarome.org/news/features/art-video-live-performance-converge-rome).

**Comment by cchristopherhowardd** [comment]
Actually, can the phrase be "Written by" and "Scritto da" for the Italian pages?

**Comment by jasloe** [comment]
Fixed.
