### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#330]
When might we expect to see the search function on the site? A few staff members noticed that we don't have one.

**Comment by jasloe** [comment]
Before Thursday.

**Comment by cchristopherhowardd** [comment]
Still experiencing problems?

**Comment by cchristopherhowardd** [comment]
Will we see a functioning search function on the new site soon?

**Comment by cchristopherhowardd** [comment]
Might you be able to work on the search function this week?

**Comment by jasloe** [comment]
Was planning to get back to that this week, yes.

**Comment by jasloe** [comment]
Solarium 6.x is an explicit requirement for November release Search API 4.x. Uninstall search_api and search_api_solr and remove from composer.json, then add both modules back in via composer.

**Comment by jasloe** [comment]
More update notes. 

Running ```drush updatedb``` is a requirement, else: 

```
 [warning] Schema information for module search_api was missing from the database. You should manually review the module updates and your database to check if any updates have been skipped up to, and including, search_api_update_8106().
```

**Comment by jasloe** [comment]
Solr core lives at: http://solr-633.hostedapachesolr.com:80/solr/#/LGSgPwi5C9_tika_aarome_org

**Comment by jasloe** [comment]
@cchristopherhowardd –– Based on our current arrangement of content, we can index and present search results that click straight through to their respective URLs for the following:

-- Basic pages
-- Events
-- News features
-- People

Resources and Publications can certainly be indexed through search results aren't so useful, simply because we don't have discreet pages for each resource or publication, only lists of nodes. I think that's probably fine for Publications. Would be nice if Resources were searchable and have some ideas about how to slightly rearrange resources lists to efficiently accomplish that.

**Comment by cchristopherhowardd** [comment]
Thanks for the note. I'll read it more closely tomorrow and offer some thoughts and suggestions.

**Comment by jasloe** [comment]
Remove cruft.

```
drush pm-uninstall ds chosen chosen_library workflow workbench auth0 nodeaccess fast_404 views_url_alias_node views_url_path_arguments
```

Remove search_api_solr and dependencies and update to 4.x release (and Solarium >5.x as described above.)

**Comment by jasloe** [comment]
At the moment, the search index contains keyword data for the following: 

- Basic page page sections
- Content type
- Event description
- Event series
- Event type
- News feature page sections
- Node titles (basic page, events, news features) 

Notes:
- Event dates and date ranges are a work-in-progress.
- Body text is excerpted. The keyword will appear highlighted in the excerpted text.
- Selecting the title will take user to the node. 
- Event series and types appear below excerpted text, i.e. Tours, Book presentation, etc.
- If the keyword search returns an event node, a second filter will appear containing Event series and Event type vocabularies. This is proposed functionality and is optional. We could do the same for the People content type (i.e. filters for fellows, residents, etc.).
- There's a second implementation for research/library resources that I'll push this evening.

**Comment by jasloe** [comment]
Pulled some of this to rewrite the filters. Will have project back online in a bit.

**Comment by cchristopherhowardd** [comment]
I like this idea for Events and People.

> If the keyword search returns an event node, a second filter will appear containing Event series and Event type vocabularies. This is proposed functionality and is optional. We could do the same for the People content type (i.e. filters for fellows, residents, etc.).

A question about searching English and Italian pages: will searches coming from /it/ include only results from Italian-language pages? Most News Features and Events are published in English only, so it would be nice if someone on the /it/ site would receive /it/ pages if there is a translation, and EN pages when there isn't. Conversely, a person doing a search on the EN site should default to EN pages. Does that make sense?

**Comment by cchristopherhowardd** [comment]
I'd like to have Publications appear in search results. People might have to scroll to find the particular book they're looking for, but that's OK for now based on how publications are currently divided into sections. I'm fine with individual Resources not being searchable, because they're all browseable on their respective sections (Electronic Journals, Digital Collections, etc.). I would imagine that someone would search "International Journal of Nautical Archaeology" on Google and not the AAR website. But if someone were to type in "International Journal of Nautical Archaeology" or any other journal that is published at https://www.aarome.org/research/resources/electronic-journals, for instance, why wouldn't that URL appear in the search results? Is it just incredibly messy to present this information on the search results page?

> Resources and Publications can certainly be indexed through search results aren't so useful, simply because we don't have discreet pages for each resource or publication, only lists of nodes. I think that's probably fine for Publications. Would be nice if Resources were searchable and have some ideas about how to slightly rearrange resources lists to efficiently accomplish that.

**Comment by jasloe** [comment]
Untranslated content falls back to English.

> A question about searching English and Italian pages: will searches coming from /it/ include only results from Italian-language pages? Most News Features and Events are published in English only, so it would be nice if someone on the /it/ site would receive /it/ pages if there is a translation, and EN pages when there isn't. Conversely, a person doing a search on the EN site should default to EN pages. Does that make sense?

**Comment by cchristopherhowardd** [comment]
Can we make sure that these content types are included in search results?

Programs
Society of Fellows

> @cchristopherhowardd –– Based on our current arrangement of content, we can index and present search results that click straight through to their respective URLs for the following:
> 
>     Basic pages
>     Events
>     News features
>     People
>

**Comment by cchristopherhowardd** [comment]
> Untranslated content falls back to English.
> 
> > A question about searching English and Italian pages: will searches coming from /it/ include only results from Italian-language pages? Most News Features and Events are published in English only, so it would be nice if someone on the /it/ site would receive /it/ pages if there is a translation, and EN pages when there isn't. Conversely, a person doing a search on the EN site should default to EN pages. Does that make sense?

So, to confirm, someone conducting a search on the /it/ site will see /it/ pages first, even when searching a person's name? If I'm on the /it/ site and search "Dillon Gisch" I'll see https://www.aarome.org/it/comunita/victorini-del-rome-prize/dillon-gisch instead of https://www.aarome.org/people/rome-prize-fellows/dillon-gisch? 

This would be the preferred way of doing things, no?

**Comment by jasloe** [comment]
There happens to be an Italian version of that page, so, yes, in this case the /it edition would appear if searching from /it/cerca/.

If there isn't an Italian version of Dillon Gisch, it'd fall back to /people/rome-prize-fellows/dillon-gisch.

> > Untranslated content falls back to English.
> > > A question about searching English and Italian pages: will searches coming from /it/ include only results from Italian-language pages? Most News Features and Events are published in English only, so it would be nice if someone on the /it/ site would receive /it/ pages if there is a translation, and EN pages when there isn't. Conversely, a person doing a search on the EN site should default to EN pages. Does that make sense?
> 
> So, to confirm, someone conducting a search on the /it/ site will see /it/ pages first, even when searching a person's name? If I'm on the /it/ site and search "Dillon Gisch" I'll see https://www.aarome.org/it/comunita/victorini-del-rome-prize/dillon-gisch instead of https://www.aarome.org?
> 
> This would be the preferred way of doing things, no?

**Comment by jasloe** [comment]
Yes, to both.

> Can we make sure that these content types are included in search results?
> 
> Programs
> Society of Fellows
>

**Comment by jasloe** [comment]
The publications pages are built with grouped views of nodes, not the nodes themselves. Search can only index nodes and can only return links to individual nodes. We'd need a node page of each publication for the user to land on from search results. 

There may be a way to hardcode the various parent publication URLs, e.g. publications/magazine, and simply return the user to that though I'm not sure how/if that would work. 

> I'd like to have Publications appear in search results. People might have to scroll to find the particular book they're looking 
for, but that's OK for now based on how publications are currently divided into sections.

**Comment by jasloe** [comment]
Ok, I have this working for all of the aforementioned content types and their respective filters, excluding Publications which I'd like to table for now (until I can figure out a way to achieve the desired functionality!) Will work on getting this posted to staging now.

Ergo:

**Events**
available filters: series, types; let's start with a simple date filter (by year) and go from there; include location? e.g. Rome, New York

**Society of Fellows**
available filters: obituary, news, events

**Programs**
no filters atm; should we include a date filter? (by year)

**Basic pages**
no filters

**News features**
no filters; include date filter? (by year) 

**People**
available filters: discipline and affiliation type; by year filter?

**Comment by cchristopherhowardd** [comment]
I don't understand how filters work (or what they looks like) in search results. I typically do keyword searches and assume that most folks will do the same. Please pardon my ignorance.

**Comment by jasloe** [comment]
Go to Amazon.com and search for camera. Filters appear on left-hand side.

**Comment by jasloe** [comment]
Here's a working demonstration of search with a few filters. I didn't go too deeply into setting this up since there are a lot of variables. Graphic design for this could get a little complicated so I've done only the basics.

Enter a common term such as "Academy" or a personal name such as "Dillon". Search will return results containing–from top to bottom–the content type, title of the node, an excerpt of the textual content with the keyword in bold and gray (though this highlighting should be something more readable), and additional metadata (e.g. Information Session, year of news feature, etc.). Almost anything that appears in a node can be added to these results.

Filters at left will show *only* content from selected term. Selecting the events filters will spawn additional filters (type, series, year); news features will spawn year. That's as far as I took though obviously this can be taken a lot further. 

I'm not convinced that filters would be so helpful for casual site users though I think it might be very useful to staff (e.g. [show me all exhibitions that occurred at Cinque Mostre in the years 2014 and 2017](https://staging.aarome.org/search?keys=Academy&f%5B0%5D=content_type%3Aevents&f%5B1%5D=event_dates%3A2014&f%5B2%5D=event_dates%3A2017&f%5B3%5D=event_series%3ACinque%20Mostre&f%5B4%5D=event_type%3AExhibition). I dunno, just speculatin'.

Another note: "Basic page" is displayed as a content type which is confusing to almost anyone. Search for "Deadline" and you'll get a few. I can remove "Basic page" from the search results column but we'll need something for the filter. I have no ideas on this point.

**Comment by cchristopherhowardd** [comment]
Wow, this looks really good.

Yeah, nobody who doesn't know Drupal will know what a Basic Page is. I'll have to think of a better term.

**Comment by cchristopherhowardd** [comment]
I'll start adding a few minor suggestions first. Could there be a _little_ more space (a couple of characters or extra pixels or whatever) between things like Event Type and Event?

<img width="965" alt="Screen Shot 2021-01-08 at 1 42 46 PM" src="https://user-images.githubusercontent.com/38765846/104052541-dfc49700-51b7-11eb-8596-2ce30be99472.png">

**Comment by cchristopherhowardd** [comment]
You probably know that the numbers should spread horizontally, not vertically.

<img width="1056" alt="Screen Shot 2021-01-08 at 1 35 56 PM" src="https://user-images.githubusercontent.com/38765846/104052717-1ac6ca80-51b8-11eb-93c8-a92dd94e323f.png">

**Comment by cchristopherhowardd** [comment]
I did a search for Mark Robbins here. I suggest that we place the year of the event in the line of gray text that identifies the event type and event series.

<img width="962" alt="Screen Shot 2021-01-08 at 1 49 02 PM" src="https://user-images.githubusercontent.com/38765846/104052955-7a24da80-51b8-11eb-949e-57d3ddbad636.png">

**Comment by cchristopherhowardd** [comment]
Does the search draw from names of photos, photo captions, and titles of PDFs?

**Comment by cchristopherhowardd** [comment]
Similarly, can the search draw from site taxonomy such as fellowship and residency names? I imagine that development would want to conduct searches by funder (Lester Little Resident, NEH Postdoctoral fellow, Arthur Ross Rome Prize, etc.).

**Comment by jasloe** [comment]
Replying in toto....

Adding media texts to search: I'm not sure! Will look into it. 

Fellowship and residency names, theoretically, yes.

Will clean up styling after I resolve above. Let me know if anything else comes to mind.

**Comment by jasloe** [comment]
Got tied up with #387 this afternoon but will get back to this on Monday.

**Comment by jasloe** [comment]
Added the following.

These terms will not have filters since the list is far too long to practically display without a more sophisticated UI than we can manage at the moment.
- Fellowship names
- Italian fellowship names
- Residency names

These terms will have filters.
- Affiliation types (fellows, residents, etc.)
- Disciplines

Dates are the next big hurdle but I have an idea how to tackle that.

**Comment by jasloe** [comment]
Added full text search for:

- Profession
- Project title
- Project description
- Biography (residents only)

**Comment by jasloe** [comment]
Resolved an issue where pagination was working correctly. Moving style sheets back on to staging tomorrow (Friday).

**Comment by jasloe** [comment]
@cchristopherhowardd –– This is pretty far long. 

Indexing, keyword excerpts, pagination, facets all work well. RP, IF, and residency names are now indexed. 

Need styling for event type and series in results, as well fellowship name and dates for people. Also need to replace guillemets in pager (seems like a weird choice, out of the box.) This is minor stuff. 

Known functional issues include hiding "refine results", need to rename 'Basic page' content type, ```<strong>``` tags in excerpted text not rendering properly. 

Lastly, and a potential blocker, is what to do with untranslated content. Will open another issue for discussion.

**Comment by cchristopherhowardd** [comment]
I don't see a search magnifying glass. Should I test the search function at https://staging.aarome.org/search?

**Comment by cchristopherhowardd** [comment]
Can you make it so that the search terms either appear in **bold** or don't have the < strong > tag in the search results?

<img width="1203" alt="Screen Shot 2021-02-19 at 2 20 57 PM" src="https://user-images.githubusercontent.com/38765846/108551380-e158a300-72bd-11eb-86c5-760333c90676.png">

**Comment by jasloe** [comment]
Those are known issues listed above. Let's make sure everything else (i.e. non-style sheet stuff) is working as desired. Let me know if there any changes/additions to what search is returning, fix or add those things, then do the styling last.

**Comment by cchristopherhowardd** [comment]
For any Event that appears in search results, I'd say it's unimportant for event type, event series, and location to appear in the search results. When an event spans two or more days, it looks kinda ugly to see the entire span of dates and times, like it does for "X Locus" and "Translating Poetry" in the example below.

<img width="1182" alt="Screen Shot 2021-02-19 at 2 27 11 PM" src="https://user-images.githubusercontent.com/38765846/108552090-d6524280-72be-11eb-9866-93773ad00e90.png">

**Comment by cchristopherhowardd** [comment]
I don't know if the above change and this one are style-sheet issues or non-style-sheet stuff. I don't think it's important to show a particular fellow's dates. It's nice to see their Rome Prize name, though.

<img width="901" alt="Screen Shot 2021-02-19 at 2 41 45 PM" src="https://user-images.githubusercontent.com/38765846/108553549-d81d0580-72c0-11eb-8610-1cd1d3e2e3fe.png">

**Comment by jasloe** [comment]
Ok, those are all structural changes. Will do.

We can "boost" the results so that titles are given higher relevancy before excerpted content. Right now, everything is flat, i.e. results are given equal weight.

**Comment by jasloe** [comment]
I should add that search results can also return images if there's interest. Pretty simple to implement. (Indexing image captions is possible, too, though that's a bit more involved....how would you represent the third slide caption in a node slideshow in search results?)

**Comment by cchristopherhowardd** [comment]
Do you mean an image that accompanies a search result from an individual webpage? Or an image that is a standalone search result? In other words, if I search for Ashley Fure, will it produce all pages that include a thumbail of the primary image from that page? Or will her People page be one result, and her portrait be another result?

<img width="1259" alt="Screen Shot 2021-02-19 at 3 12 38 PM" src="https://user-images.githubusercontent.com/38765846/108556548-2df3ac80-72c5-11eb-9c55-1f58e7fea2d2.png">

**Comment by jasloe** [comment]
Those are some sick sketches. 

The image would be taken from the node. in our example above, the first people result would display Fure's portrait, etc.

**Comment by cchristopherhowardd** [comment]
I'm stumped when it comes to a new name for Basic Page:

General Page
General AAR Page
Section Page

Is it possible to rename the page basic on what part of the website the page is in? For example, the [Staff](https://www.aarome.org/about/staff) page and [Tours](https://www.aarome.org/about/tours) page would be categorized as About. And [Access, Rules & Policies](https://www.aarome.org/research/library/access-rules-policies) and [Photographic Archive Index](https://www.aarome.org/research/photographic-archive/index) would be categorized as Research.

**Comment by jasloe** [comment]
Basic page, event, news, etc. are derived from the content type. If I understand you correctly, could have a tagging mechanism and go through and categorize *all* basic page nodes with the desired term (About, Research, etc.) then display that category in the result and a new facet.

**Comment by jasloe** [comment]
There are ~170 basic pages. A lot of the tagging could be done in bulk.

**Comment by cchristopherhowardd** [comment]
You seem to understand me correctly. Actually 170 pages aren't too many to tag individually, but it's probably faster to tag them in bulk and check the work.

**Comment by cchristopherhowardd** [comment]
A comment about displaying pictures from nodes in search results: many recent images have a 16 x 9 ratio, so the image box will have to take both wide "landscape" images into account alongside "portraits" from People and anywhere else we have a vertically oriented image.

You mentioned a while back that there was difficulty in adding Publications pages into the search. Can you describe again why it would be difficult to search for "Anamericana" and have the result be the [Exhibitions Catalogue](https://www.aarome.org/publications/exhibition-catalogues) page? A person who clicks the link and have to scroll down. I understand that the Exhibition Catalogues page is comprised of many nodes. Is it difficult or impossible to bypass search results for an [individual node](https://www.aarome.org/node/3968) and go straight to the Exh Cat page? Sorry to bring this up again.

**Comment by cchristopherhowardd** [comment]
The search is working decently--even well. I've found that searching for pairs of words such as "John Ochsendorf" and "James Ackerman" will turn up good matches in the first few results, but then devolve into a bunch of unrelated pages. Obvious John and James are super common name words, so it's not unexpected, but I have to wade through unrelated links for John to get to pages that mention Ochsendorf.

What are the criteria for weighing searches?

**Comment by jasloe** [comment]
> A comment about displaying pictures from nodes in search results: many recent images have a 16 x 9 ratio, so the image box will have to take both wide "landscape" images into account alongside "portraits" from People and anywhere else we have a vertically oriented image.

No problem. I'll work out some constraints that'll make it render nicely.

> You mentioned a while back that there was difficulty in adding Publications pages into the search. Can you describe again why it would be difficult to search for "Anamericana" and have the result be the [Exhibitions Catalogue](https://www.aarome.org/publications/exhibition-catalogues) page? A person who clicks the link and have to scroll down. I understand that the Exhibition Catalogues page is comprised of many nodes. Is it difficult or impossible to bypass search results for an [individual node](https://www.aarome.org/node/3968) and go straight to the Exh Cat page? Sorry to bring this up again.

Thought about this a little more: it seems like we should be able to add anchor links to each node in the collection of node views (i.e. /publications/exhibition-catalogues#academic-body) and pass that anchor link to the search result. This is just off the top of my head. Let me look at the search configuration a little more and get back to you. 

Just to be clear, we want to do:

- anchor tags in results
- add images to results 
- remove terms/tags as described at https://github.com/aarome/aarome/issues/330#issuecomment-782299716
- work out tagging and indexing for basic pages

**Comment by cchristopherhowardd** [comment]
Anchor tags in results for Publications search results sound good to me. The other stuff is good, too. Do you think it's possible to have the search go live this month, and we can fine-tune as we (and other people) us it?

**Comment by jasloe** [comment]
My preference is to finish #400,  https://github.com/aarome/aarome/issues/330#issuecomment-782299716, add images to search results, update to Drupal 9, and then roll search as-is. I view Publications search as a lower priority (simply because I’m not even sure what I’ve described will work). I’m working on getting our office network up at the moment but will be able to comment more completely on this tomorrow. Will (finally) roll #327 this evening!

**Comment by jasloe** [comment]
#327 committed to production.

**Comment by jasloe** [comment]
Just wanted to provide a quick update on this. There's one remaining issue with search. HTML tags that 'highlight' the excerpted keyword aren't rendering properly:

> Known functional issues include....`<strong>` tags in excerpted text not rendering properly.

Took a little while to track down this issue though I have a solution for this that I think will work pretty well. Should have that at least partially resolved and pushed to staging by tomorrow afternoon.

**Comment by jasloe** [comment]
The excerpted text issue is resolved. 

> Just wanted to provide a quick update on this. There's one remaining issue with search. HTML tags that 'highlight' the excerpted keyword aren't rendering properly:
> 
> > Known functional issues include....`<strong>` tags in excerpted text not rendering properly.
> 
> Took a little while to track down this issue though I have a solution for this that I think will work pretty well. Should have that at least partially resolved and pushed to staging by tomorrow afternoon.

**Comment by cchristopherhowardd** [comment]
Thanks! I'm looking forward to a working site search!

**Comment by jasloe** [comment]
Added code that prevents block from rendering when no facets are present.

**Comment by jasloe** [comment]
Can you confirm that you don't want to show fellow, resident, et al. dates? Only the prize name, e.g. Garden Club of America Rome Prize, Prince Charitable Trusts Rome Prize, etc.?

**Comment by jasloe** [comment]
Pushed a few changes including aforementioned prize information and images for Events and Page content types. Will add the others if you think image placement and formatting looks ok. 

Regarding organizing and naming 'basic page' results, I've added 'page type' tags to basic pages, incl. 'about', 'research', etc. 
Go to http://staging.aarome.org/admin/page-types to see work-in-progress of assigning page types (some of these will be deleted or changed).

Unfortunately, these facets can't be merged and alphabetized and they'll appear in two separate blocks. Go to /search and search for 'Robert'. The top block contains page types; the second block contains top-level facets for other content types. 

With that mind, I think this is confusing and it'd be better to simply add 'basic page' back to the top-level facets. Maybe call it 'page' instead of 'basic page'. Seems to work well enough for the [Walker](https://walkerart.org/?isSearch=true): go to the WAC site and search for Mission. You'll see 'page' as a type.

Thoughts?

**Comment by cchristopherhowardd** [comment]
The images seems a little big here. Can you shrink them? It seems like the textual information should be more prominent than photos.

I'll look at your other comments more closely before responding.

**Comment by cchristopherhowardd** [comment]
Is http://staging.aarome.org/admin/page-types still a working webpage?

**Comment by cchristopherhowardd** [comment]
```
Regarding organizing and naming 'basic page' results, I've added 'page type' tags to basic pages, incl. 'about', 'research', etc.
Go to http://staging.aarome.org/admin/page-types to see work-in-progress of assigning page types (some of these will be deleted or changed).

Unfortunately, these facets can't be merged and alphabetized and they'll appear in two separate blocks. Go to /search and search for 'Robert'. The top block contains page types; the second block contains top-level facets for other content types.

With that mind, I think this is confusing and it'd be better to simply add 'basic page' back to the top-level facets. Maybe call it 'page' instead of 'basic page'. Seems to work well enough for the Walker: go to the WAC site and search for Mission. You'll see 'page' as a type.
```
I'm fine with renaming Basic Page to Page.

Do you think we're reading to add the Search function to the live site this week?

**Comment by jasloe** [comment]
Is there any other feedback other than the image sizes and renaming basic page to page?

**Comment by cchristopherhowardd** [comment]
It does bother me a little that, when searching for people (Mark Robbins, Elizabeth Rodini, John Ochsendorf), I get pages for all the other Marks and Johns and Elizabeths on the second page of results. I don't know what a solution would be.

**Comment by cchristopherhowardd** [comment]
I found that doing Mark+Robbins yields better results, but the average website visitor wouldn't add the plus.

**Comment by jasloe** [comment]
A search for Mark Robbins yields all Mark Robbins related content on the first page. That seems correct to me. Other incidences of Mark appear on subsequent pages. As an end user, this seems desirable to me as I'm not looking for Mark Rabinowitz or Mark Strand. Am I missing something?

**Comment by cchristopherhowardd** [comment]
I guess the problem is that pages with only "Mark" on them come ahead of pages that have both "Mark" and "Robbins." This is the case on the second, third, fourth pages of search results.

I'd like the search results to be more useful for words and people that may have numerous pages linked to them (Mark Robbins, Martin Brody, Peter Benson Miller).

Unrelatedly, a search for Corey Brennan on the staging site yields no results, which is very odd!

**Comment by cchristopherhowardd** [comment]
`Unrelatedly, a search for Corey Brennan on the staging site yields no results, which is very odd!`

I don't get results for either Corey or Brennan, using one word as a search term. And I get results for Peter Miller but not for Peter Benson Miller.

**Comment by cchristopherhowardd** [comment]
`A search for Mark Robbins yields all Mark Robbins related content on the first page. That seems correct to me. Other incidences of Mark appear on subsequent pages. As an end user, this seems desirable to me as I'm not looking for Mark Rabinowitz or Mark Strand. Am I missing something?`

I guess what I'm asking for is to "upvote" search results that have both or all search terms on a page.

**Comment by cchristopherhowardd** [comment]
"Nobody likes a stale Triscuit"
--Christopher Howard, 2021

**Comment by jasloe** [comment]
We can tighten things up search criteria by changing the operand from or to and, i.e.

only show results containing Mark (and) Robbins

instead of 

only show results containing Mark (or) Robbins

Just posted that to staging. Let me know what you think.

> I guess the problem is that pages with only "Mark" on them come ahead of pages that have both "Mark" and "Robbins." This is the case on the second, third, fourth pages of search results.
> 
> I'd like the search results to be more useful for words and people that may have numerous pages linked to them (Mark Robbins, Martin Brody, Peter Benson Miller).
> 
> Unrelatedly, a search for Corey Brennan on the staging site yields no results, which is very odd!

**Comment by jasloe** [comment]
The staging site has fallen quite a few commits behind production. Working on getting that up to date. I'm also working on staging a few additional fields including images for news features, sof, people. Worked out renaming ```basic_page|pagina_base``` to ```page|pagina```, so that's good to go.

**Comment by jasloe** [comment]
Staging updated with latest build of search functionality.

**Comment by cchristopherhowardd** [comment]
I'll turn my attention to the search engine next week. Do you think we close to finishing it?

**Comment by jasloe** [comment]
I think most (all?) of the configuration was moved to production some time ago. I'd just need to turn on the menu item and search overlay to make it available/visible to end users. I'm out of the office through Wednesday but can pick this following my return. Meanwhile, let me know if there's any additional functionality you'd like to see.

**Comment by jasloe** [comment]
Back in the office just this morning. Working on wiring up the menu item and related functionality. Otherwise, good to go. We can add other features as desired, including but not limited to 'sort by' and 'autocomplete' functions. Will report back this afternoon.

**Comment by jasloe** [comment]
Pushed search updates including eyeglass to staging. The modal form Open provided long ago is pretty minimal, so let me know if you'd like to see something else.

**Comment by cchristopherhowardd** [comment]
Minimal is good. Can you push to production? I'd like to see the search on the live site very soon. Are there any outstanding issues?

**Comment by jasloe** [comment]
None that I am aware of. As long as you are ok with what's on staging, it's good to go. Can get started on migrating to production this afternoon.

**Comment by jasloe** [comment]
Pushed to production. Closing this monster issue. New bugs and feature requests can be reported in new tickets.
