### ISSUE TITLE
Society of Fellows index page

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#332]
The boxes on the Society of Fellows index page have shifted out of order: https://www.aarome.org/society-of-fellows. The first and last nodes are positioned correctly.

About (node 2349)
News & Events (node 3268)
History (node 2440)
Bylaws (node 2441)
All Fellows (node 3267)
Past Presidents (node 2442)

**Comment by jasloe** [comment]
Fixed.
