### ISSUE TITLE
Device/display notice

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#333]
After a person begins scrolling on any given AAR webpage, a notice related to device and display appears in the upper right corner in a yellow box. It appears in Chrome, Safari, and Firefox on my Apple laptop, as well as in Firefox on my iPhone 6.

<img width="1390" alt="mobile menu" src="https://user-images.githubusercontent.com/38765846/88839384-fa2a2b80-d1a8-11ea-8ca8-2d2eea9dfd99.png">

<img width="1094" alt="desktop" src="https://user-images.githubusercontent.com/38765846/88839389-fd251c00-d1a8-11ea-94b9-b4d2f9530697.png">

**Comment by cchristopherhowardd** [comment]
I should add that the yellow box notice appears in Firefox and Safari on my iPhone 6 **when turned sideways**.

**Comment by jasloe** [comment]
Fixed. Please test and close.
