### ISSUE TITLE
Events Calendar train wreck

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#335]
It looks like the Events Calendar page got hit by a train: https://www.aarome.org/events/calendar 

<img width="1386" alt="Screen Shot 2020-07-29 at 3 23 11 PM" src="https://user-images.githubusercontent.com/38765846/88843702-8c353280-d1af-11ea-808e-6c756cd17082.png">

**Comment by cchristopherhowardd** [comment]
Exhibition page, too: https://www.aarome.org/events/exhibitions

**Comment by jasloe** [comment]
Grid fixed. Fixing links now. 

Clearly something is wrong in the production pipeline.

**Comment by jasloe** [comment]
Fixed events/* grid view including grid view itself and links to inside page. Working on hover state for links now. 

Note that there is something not quite correct with the way this Twig template handles the canceled boolean variable. I've temporarily disabled the template output for that variable.

**Comment by jasloe** [comment]
Fixed breadcrumbs.

**Comment by jasloe** [comment]
Pushed fix for events hover state.

**Comment by cchristopherhowardd** [comment]
> Note that there is something not quite correct with the way this Twig template handles the canceled boolean variable. I've temporarily disabled the template output for that variable.

You're referring to the black box at upper right that says CANCELED in white letters, correct?

**Comment by jasloe** [comment]
That is correct. Working on getting that fixed now.

**Comment by jasloe** [comment]
"Canceled" label on events index front end is working. Working on cleaning up some content and the edit form now.

**Comment by jasloe** [comment]
And one hiccup with presenting the translated string "annullato" to the front end....

**Comment by cchristopherhowardd** [comment]
The English language CANCELED thingee looks great!

**Comment by jasloe** [comment]
Cool. Took some figuring. Will move logic to the inside event page as well.
