### ISSUE TITLE
Italian index page for Features

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#337]
The formatting for the publication date looks different on the Italian-language page. You can see the difference in the screenshots below. 

English page: 

<img width="1358" alt="Screen Shot 2020-08-05 at 3 58 50 PM" src="https://user-images.githubusercontent.com/38765846/89458402-fb250500-d734-11ea-809a-19801b6d614e.png">

Italian page: 

<img width="1360" alt="Screen Shot 2020-08-05 at 3 59 02 PM" src="https://user-images.githubusercontent.com/38765846/89458436-04ae6d00-d735-11ea-9a4d-5b78af03c0a1.png">

Also, the breadcrumb should be ARTICOLI on the Italian page instead of FEATURE.

**Comment by jasloe** [comment]
Fixed.
