### ISSUE TITLE
Small changes for Library section

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#338]
In the Library section of Research ( https://www.aarome.org/research/library ), Sebastian has requested that the box for "Access, Rules & Policies" be placed before "Request Forms & Services."

**Comment by cchristopherhowardd** [comment]
Why don't we switch "Notices" and "Library" while we're at it. The current order is a minor irritant to me. "Library" first, followed by "Notices," "Access, Rules & Policies," and "Request Forms & Services."

**Comment by cchristopherhowardd** [comment]
At https://www.aarome.org/research/photographic-archive, let's switch "About" and "Notices."

**Comment by cchristopherhowardd** [comment]
Parallel changes should be made to the Italian pages, natch.

**Comment by jasloe** [comment]
Fixed.
