### ISSUE TITLE
Drupal Access for Library Staff

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#339]
Sebastian and his staff have requested access to the new AAR website. We need to set up accounts for them, and I will have to monitor their content and provide guidance. I want to create a how-to manual for the site, and it seems like writing a quick one for AAR Library staff is needed right away. Can we have a conversation early next week about setting up accounts for Sebastian and Kristine?

Sebastian Hierl
s.hierl@aarome.org

Kristine Iara
k.iara@aarome.org

**Comment by cchristopherhowardd** [comment]
A related issue is the lack of an automatic password reset feature at https://aarome.org/user/login. There are only two active users right now--you and me--but if others gain access to the site, they will inevitably forget their passwords.

**Comment by cchristopherhowardd** [comment]
Two others:

Denise Gavio
denise.gavio@aarome.org

Lavinia Ciuffa
l.ciuffa.ext@aarome.org

**Comment by jasloe** [comment]
Ok. I have this sort of working. I need to fix two bugs then will push to staging for testing. 

As I see it, we'll need to constrain their access to a specific list of nodes, file uploading for those nodes, and the library resources content type (as well as all translation entities). Do you want to also give them access to media management so they can change images? 

Can you put together a list of node ids that they'll need editorial permissions for?

**Comment by jasloe** [comment]
> A related issue is the lack of an automatic password reset feature at https://aarome.org/user/login. There are only two active users right now--you and me--but if others gain access to the site, they will inevitably forget their passwords.

I'm working on a solution for signing in with Gmail which will obviate this requirement. Added benefit is that it's much, much more secure.

**Comment by jasloe** [comment]
Another question: do you want moderation for library-related nodes _and_ library resources? Seems like the latter would be onerous to manage as they sometimes add several dozen resources a month.

**Comment by cchristopherhowardd** [comment]
Good to know about the password reset functioning.

I don't understand the question regarding library-related nodes and library resources. I don't know what "latter" means when the "former" isn't defined....

**Comment by jasloe** [comment]
latter = library resources

**Comment by jasloe** [comment]
I guess I should confirm that the Academy is still using Gmail, yes?

**Comment by cchristopherhowardd** [comment]
Yes, email accounts for aarome.org are based on Gmail.

I don't foresee a problem with managing Library Resources, even if a dozen or two are added a month. In fact, it's likely that a  number of resources (e.g., electronic journal subscriptions) will be removed--or at least unpublished--because of library budget cuts. 

But I say this not quite understanding how the content moderation process would work. If someone adds, deletes, or unpublishes a resource, or updates a library-related node, will the action not be implemented on the live website until I approve it?

If so, the moderation process wouldn't take very long. An update made in Rome in the morning would be approved or sent back with a request for change on the same day (morning in New York). The only delay would be caused if I were taking a vacation or sick day or were otherwise unable to log in.

**Comment by jasloe** [comment]
Yeah, that's pretty much it. Still trying to figure out how to grant access to specific nodes. Generally, roles are assigned to a content type....but I think that's too coarse.

**Comment by jasloe** [comment]
#### Library role permission grants

**Nodes**
Library resources: Edit any content
Library resources: View any unpublished content
Translate Library resources content item

**Vocabularies**
Resource subjects: Edit terms
Resource types: Edit terms
Resource subjects: Delete terms
Resource types: Delete terms
Translate Resource subjects taxonomy term
Translate Resource types taxonomy term

**Administration**
Access the Content overview page
Access the taxonomy vocabulary overview page

**Comment by jasloe** [comment]
I've stripping the library resources content type down to the very basics. A few questions:

- Do we need to provide an Italian translation of field labels at /it/node/add/library_resources?
- The default help text under Link to Resource/URL could be confusing. Omit altogether?
- Remove the source edit options at Resource Description? Not sure what user(s) skill level is/are.
- Any other changes to field labels?
- I made title, type, and subject required. Ok?
- Changed resource type to radio button to make purpose of field more transparent. Ok?
- Changed form field for subject so that user can create subjects on the fly instead of bouncing back and forth between node edit and taxonomy edit pages. Foresee any issues with this?
- Disabled preview since it'll send user to the node view page for this content type (which is more or less unstyled, could be confusing).

**Comment by jasloe** [comment]
Also, let me know if you want to propose instructional text for any of these fields.

**Comment by jasloe** [comment]
Created new user accounts and assigned "library" role. 

l.ciuffa
d.gavio
s.hierl
k.iara

**Comment by cchristopherhowardd** [comment]
I'm writing a how-to document for updating Library Resources, using written instructions with screenshots, for the AAR Library staff.

**Comment by cchristopherhowardd** [comment]
Can I get a password for the s.hierl account? I'd like to take screenshots of the log-in and updating processes for the how-to document, using the actual screen library uses would see (instead of screenshots of what my c.howard account sees). I imagine that we're looking at slightly different back-end administrative pages and don't want to confuse readers of the how-to.

**Comment by cchristopherhowardd** [comment]
Do we need to provide an Italian translation of field labels at /it/node/add/library_resources?

The default help text under Link to Resource/URL could be confusing. Omit altogether?

Remove the source edit options at Resource Description? Not sure what user(s) skill level is/are.

Any other changes to field labels?

I made title, type, and subject required. Ok?

Changed resource type to radio button to make purpose of field more transparent. Ok?

Changed form field for subject so that user can create subjects on the fly instead of bouncing back and forth between node edit and taxonomy edit pages. Foresee any issues with this?

Disabled preview since it'll send user to the node view page for this content type (which is more or less unstyled, could be confusing).

**Comment by cchristopherhowardd** [comment]
**Do we need to provide an Italian translation of field labels at /it/node/add/library_resources?**

Yes. Is this something I can do? If not, I can provide the translations in a Word doc.

**The default help text under Link to Resource/URL could be confusing. Omit altogether?**

If you're referring to " Start typing the title of a piece of content to select it. You can also enter an internal path such as /node/add or an external URL such as http://example.com. Enter <front> to link to the front page. Enter <nolink> to display link text only" then yes, that text can be omitted.

**Remove the source edit options at Resource Description? Not sure what user(s) skill level is/are.**

Leave in. Sometimes descriptions have text in italics and bold, and sometimes there are additional links.

**Any other changes to field labels?**

Under Resource Type, you can omit Research Tutorials. I don't believe there are any Library Resources that are categories with this term. There is a webpage ( https://www.aarome.org/research/resources/tutorials ) that publishes this content, and it's pretty minimal and doesn't lend itself to the same kind of database organization.

Earlier this year the AAR Library created an "Online Resources for Photographic Collections" page on the old site: https://old.aarome.org/research/photo-archive/online-resources. The content appears here on the new site: https://www.aarome.org/research/photographic-archive/publications. Eventually we should convert the page's contents into a Library Resource-style page, but this work can be postponed for the time being.

**I made title, type, and subject required. Ok?**

Great.

**Changed resource type to radio button to make purpose of field more transparent. Ok?**

Very helpful--thanks!

**Changed form field for subject so that user can create subjects on the fly instead of bouncing back and forth between node edit and taxonomy edit pages. Foresee any issues with this?**

Not really. The library staff seems to stay in bounds regarding categories. A related issue is that sometimes a single resource can take two subjects. For example, the electronic journal _Analecta Romana Instituti Danici_ is categorized in Resource Subjects under both Classics and Postclassical Art & Architecture. In the past, library staff created two separate Library Resource entries (nodes 714 and 715 for _Analecta Romana Instituti Danici_; nodes 723 an 724 for _Ancient World Online_). It would be helpful, going forward, if library staff could create one entry per resource and select multiple subjects.

**Disabled preview since it'll send user to the node view page for this content type (which is more or less unstyled, could be confusing).**

Sure.

**Comment by jasloe** [comment]
You can drop the translations in a new issue. The interface for managing backend translations is buried under several layers of cruft.

Regarding editor tools, meant only the source code edit function, not bold, italic, etc.

Will omit link help text. 

Going to postpone applying multiple subjects per resource for the moment. Want to wrap up basic functionality and deploy to library users first. 

Working on wrapping up moderation workflow now.

**Comment by jasloe** [comment]
> Can I get a password for the s.hierl account? I'd like to take screenshots of the log-in and updating processes for the how-to document, using the actual screen library uses would see (instead of screenshots of what my c.howard account sees). I imagine that we're looking at slightly different back-end administrative pages and don't want to confuse readers of the how-to.

Right. Good idea. Sent you an email with credentials for testing. This user belongs to the same permissions group as the four library users.

**Comment by jasloe** [comment]
The library resources workflow is ready for testing. My development notes are here: https://github.com/aarome/aarome/wiki/Content-moderation-states-and-workflow

Here's some real content to use to test. Refer to documentation for description of states and workflow.

Resource title:The Comparative Archaeology Database
Resource type: Research Databases & Digital Collections
Resource subject: Archaeology & Classical Art
Link: http://www.cadb.pitt.edu/
Link text: leave empty

Here's a quick-and-dirty script to test. The idea here is to test a likely real world use case, e.g. library user creates draft; site editor reviews and publishes; site editor later changes published node to an unpublished or draft state for editorial reasons; library user makes revision; site editor "republishes" revised node. 

- As ```test-library-role``` (credentials provided in email), create and save ```Draft``` Library resource node with content listed above
- As ```c.howard```, save ```Draft``` resource to ```Published``` state
- As ```c.howard```, move ```Published``` resource to ```Unpublished``` state
- As ```c.howard```, move ```Unpublished``` resource to ```Draft``` state
- As ```test-library-role```, make change to node such as adding a resource description and save
- As ```c.howard```, save ```Draft``` resource to ```Published``` state once more

**Comment by cchristopherhowardd** [comment]
Thanks. I'll review this today and tomorrow.

**Comment by jasloe** [comment]
Update admin_toolbar to version 2.3.

**Comment by cchristopherhowardd** [comment]
In my role as test-library-role, I do not have the ability to edit Library Resources. I expect to see an Edit button on the far right side of the screen, under the Actions column, but nothing appears in that column.

<img width="1346" alt="Screen Shot 2020-08-13 at 2 03 35 PM" src="https://user-images.githubusercontent.com/38765846/90170381-f9c78e00-dd6d-11ea-9a39-1840f411792d.png">

**Comment by cchristopherhowardd** [comment]
I'm rethinking the tenability of the draft/moderation process for library staff. If Kristine Iara cannot edit existing Library Resources, but can only create new ones, then it doesn't make practicable sense to control access. Library staff will have little control of their content. I may just have to police their additions and updates silently.

**Comment by jasloe** [comment]
If you want the library role to edit existing content _and_ reintroduce content back into the moderation workflow (that is, give you the final say whether an edited node can be republished), we'd have to develop an additional set of workflows.

Sounds like you want the library user to be able to move from Published to Draft (which will unpublish the node), make edits, then you would Publish (or republish) the node. Is that right?

**Comment by jasloe** [comment]
Note that the library role has access to Basic Page, too. We can lock down access to a specific set of node ids when you're ready.

**Comment by cchristopherhowardd** [comment]
> If you want the library role to edit existing content _and_ reintroduce content back into the moderation workflow (that is, give you the final say whether an edited node can be republished), we'd have to develop an additional set of workflows.

Is this complicated?

> Sounds like you want the library user to be able to move from Published to Draft (which will unpublish the node), make edits, then you would Publish (or republish) the node. Is that right?

That's right. Is this complicated? I'm starting to feel frustrated, like we're pouring too much effort into moderation. It might be easier for me to give library staff access to the Drupal back-end, give them instructions for updating Library Resources, and deal with the fallout. Which means I'll always be sweeping up after them. It also means hoping they won't go poking around the rest of the website. The main content page ( https://www.aarome.org/admin/content ) defaults to showing the most recently updated pages, so I'll know what pages have been worked on.

One source of hope is that Sebastian or whoever gets a look at the back-end and sees that it's very different from the admin pages of the old website, throws up their hands, and gives me content to update for them.

**Comment by jasloe** [comment]
It's pretty much done. Just need a little more testing.

**Comment by cchristopherhowardd** [comment]
Testing today.

I see now that Test Library User has access to create, edit, and delete (??) Basic Pages and Library Resources--the two page types that all Research section pages fall into. I don't think we need to lock down specific nodes yet. I hope that library staff won't go wilding on the new site.

**Comment by cchristopherhowardd** [comment]
As Test Library User, I can edit an existing Library Resource and then save it, waiting for the content moderator (me) to approve the new resource. But as Test Library User, I cannot make any further edits to that Library Resource. 

Say I realize that I copied and pasted the wrong URL for a single resource. I don't have any way to fix the mistake until the content moderator approves. Is it possible for library users to continue making edits to a single resource they've already saved?

**Comment by cchristopherhowardd** [comment]
It looks like Library Test User can access a page that was just changed but not approved by content moderator via https://www.aarome.org/admin/workbench/content/all and https://www.aarome.org/admin/workbench. On the latter page, I can access recently edited pages NOT via "Your most recent edits" but below that section, in "Recent content." This is a little confusing. The two places where I'd expect to make additional changes I can't.

It's not possible to access those pages again from https://www.aarome.org/admin/workbench/content/edited.

**Comment by cchristopherhowardd** [comment]
What is the difference between draft and unpublished?

<img width="283" alt="Screen Shot 2020-09-02 at 3 50 47 PM" src="https://user-images.githubusercontent.com/38765846/92029902-3d416680-ed34-11ea-9d7e-09021eddfab3.png">

**Comment by cchristopherhowardd** [comment]
Can you create log-in credentials for Catherine Heitz using archives@aarome.org as the email? I am doing a training session for library staff via Google Meet. I'll be sharing my screen but it may be helpful if people follow by logging in.

**Comment by cchristopherhowardd** [comment]
Is it possible to give the five library users regular access to the back end of the website? I'm not sure it's going to be possible, politically speaking, to restrict access via moderated content. Should we have a call on Monday to discuss?

**Comment by jasloe** [comment]
Decoupling content moderation now, then adding users. Will roll up login page theming (#318) until we get Auth0/Gmail sign-in implemented (#362).

**Comment by jasloe** [comment]
Content moderation removed.

**Comment by cchristopherhowardd** [comment]
How can the new users receive their initial passwords? Is there an automatic process or do I notify them individually with their log-in credentials?

l.ciuffa
d.gavio
s.hierl
k.iara
archives

**Comment by jasloe** [comment]
These accounts are set up. I usually send a one-time login to each user. The user can input a new password after following the link. 

We were going to use Google Authentication in order to simplify login, password reset, etc. See #https://github.com/aarome/aarome/issues/362#issuecomment-705205911: would need to set up a few things on the Academy's G Suite account. In the meantime, I'm turning the 'forgot password' processor on.

Apart from library resources and basic page nodes, what other content types does the library role need access to?

**Comment by jasloe** [comment]
@cchristopherhowardd –– I figured out a way to allow library users to edit only a specific set of nodes. Previously, I had to grant permissions to ALL basic page nodes...which could have been a disaster in the making. I'll configure this on staging for testing purposes but it seems to work pretty well.

**Comment by jasloe** [comment]
Ok, this is working pretty well on staging. I'm comfortable moving this to production whenever you're ready. Let me know if you want to test and I'll send you a one-time login.

Users with the library staff role can:

- create, read, update, delete ANY library resource node
- create, read, update basic page nodes that they are authorized to edit (I tracked down all of the library-specific nodes and administered the required grant.)
- create, read, update, delete ANY resource subject
- translate all of the above
- manage media (file attachments, images) where needed

A few other notes:

- Following login, users are sent to /admin/content.
- The most useful links are under "shortcuts" in the admin toolbar (have to figure out how to show shortcuts by default, #366).
- Users can have an Italian or English user interface by default, whichever you think is appropriate.
- There's a 'persistent' login tab at /user/*/edit which is confusing. I'll remove it.

**Comment by cchristopherhowardd** [comment]
Send the test log in.

**Comment by cchristopherhowardd** [comment]
I am able to create, revise, and publish/unpublish library resources, which is good. 

I am not able to change, for example, the Notices page (https://staging.aarome.org/admin/content?title=notices&type=All&status=All&langcode=All), which lists the library hours. In the Operations column at far right, I don't see the Edit/Translate/Delete button.

The same goes for a normal library page such as Institutional Archive ( https://staging.aarome.org/admin/content?title=institutional+archive&type=All&status=All&langcode=All ). I can't edit, translate, or delete the page.

**Comment by jasloe** [comment]
I haven't added those node ids to the grants (it's a tedious process). They'll be added on production.

**Comment by cchristopherhowardd** [comment]
I created a new basic page but am unable to translate it. The button to edit/translate at https://staging.aarome.org/node/5494/translations is missing.

<img width="1338" alt="Screen Shot 2020-10-14 at 4 18 44 PM" src="https://user-images.githubusercontent.com/38765846/96045049-6bd85400-0e3f-11eb-8bff-b2b3ee9b2b7b.png">

**Comment by jasloe** [comment]
Oy, that's a tough one. Looks like you can translate already existing nodes, but not new ones. Will have to track that one down.

**Comment by cchristopherhowardd** [comment]
When you move library access to production (today?), can the system automatically send the log-in email to library staff? Or should we do this manually (i.e., an email from me to them)?

**Comment by jasloe** [comment]
Yeah, probably excepting the bug described above, I hope to finish that up today. I need to bust the server cache to complete the configuration and will do that after hours. 

The email should come from the content management system, since it auto-generates the one-time login when the account is activated. I can give you the administrator credentials (which you should have anyone) so that you can activate the accounts whenever you like.

**Comment by jasloe** [comment]
Patching [hide_revision_field](https://www.drupal.org/files/issues/2020-07-28/call_to_a_member_function_getcomponent%28%29_on_null_in_hide_revision_field_form_user_form_alter-3018160-031.patch) module.

**Comment by jasloe** [comment]
Missed a checkbox in the permissions matrix. This is fixed on production.

> I created a new basic page but am unable to translate it. The button to edit/translate in the Operations column at https://staging.aarome.org/node/5494/translations is missing.
> 
> <img alt="Screen Shot 2020-10-14 at 5 04 36 PM" width="1344" src="https://user-images.githubusercontent.com/38765846/96045108-84486e80-0e3f-11eb-87e9-b203445b7d8b.png">
