### ISSUE TITLE
Translations for event types

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#34]
Looks like we're missing translations for event types. For the sake of thoroughness, these would be good to have. 

<pre>
AIA Lecture
Benefit
Book Presentation
Ceremony
Colloquium
Concert
Conference
Conversation
Conversations That Matter
Conversations/Conversazioni
Exhibition
Fellow Shoptalks
Film Screening and Conversation
Home from Rome
Keynote
Lecture
Multimedia Conversation
Ongoing
Open Studios
Panel Discussion
Patricia H. Labalme Friends of the Library Lecture
Performance
Presentation
Reading
Reading and Musical Performance
Reunion
Seminar
Symposium
Talk
Thomas Spencer Jerome Lecture Series
Tour
Workshop
</pre>

**Comment by cchristopherhowardd** [comment]
I'll get on it.

**Comment by cchristopherhowardd** [comment]
Some of these may change, but for now let's go with these terms.
[Event Types.docx](https://github.com/aarome/aarome/files/2233256/Event.Types.docx)

**Comment by jasloe** [comment]
AIA Lecture | Conferenza d'AIA
Benefit | Raccolta di Fondi
Book Presentation | Presentazione del Libro
Ceremony | Ceremonia
Colloquium | Colloquio
Concert | Concerto
Conference | Convegno
Conversation | Conversazione
Conversations That Matter | Conversazioni che Contano
Conversations/Conversazioni | Conversations/Conversazioni
Exhibition | Mostra
Fellow Shoptalks | Shoptalks da/di Fellows
Film Screening and Conversation | Proiezione di Film e Conversazione
Home from Rome | Home from Rome
Keynote | Nota Fundamentale
Lecture | Conferenza
Multimedia Conversation | Conversazione Multimedia
Ongoing | In Corso
Open Studios | Studi Aperti
Panel Discussion | Discussione
Patricia H. Labalme Friends of the Library Lecture | Conferenza da/di Patricia H. Labalme Friends of the Library
Performance | Prestazione
Presentation | Presentazione
Reading | Lettura
Reading and Musical Performance | Lettura e Performance Musicale
Reunion | Riunione
Seminar | Seminario
Symposium | Symposium
Talk | Discorso
Thomas Spencer Jerome Lecture Series | Serie di Conferenze da/di Thomas Spencer Jerome
Tour | Tournée
Workshop | Laboratorio
