### ISSUE TITLE
Photographic Archive trouble

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#342]
I ran into trouble today when changing the photo for a Photographic Archive page.

I replaced the photo at https://www.aarome.org/research/photographic-archive/about but the new picture isn't appearing on the page or on the Photographic Archive index page: https://www.aarome.org/research/photographic-archive. 

The new picture is, however, appearing on the Italian version of the page at https://www.aarome.org/it/ricerca/archivio-fotografico/sulla-collezione and on the index page: https://www.aarome.org/it/ricerca/archivio-fotografico

Relatedly, I successfully changed the picture for Photographic Archive on the Research index page at https://www.aarome.org/research but the link goes to https://www.aarome.org/node/1805 instead of https://www.aarome.org/research/photographic-archive.

And strangely enough, the old photo remains on the Italian version of the Research index page at https://www.aarome.org/it/ricerca, and the link goes to https://www.aarome.org/it/node/1805 instead of https://www.aarome.org/index.php/it/ricerca/archivio-fotografico.

**Comment by jasloe** [comment]
Checking it out.

**Comment by jasloe** [comment]
Second issue first: there's a box at the bottom of node/*/edit titled "Internal link". For nodes on index pages that link to other index pages, you'll need to hardcode the destination link in this form field. (No need to do so on the translation; the routing system will automatically negotiate the translation path.) This was a last minute-ish change to the way index pages are structured and apologies for not communicating this. 

<img width="771" alt="Screen Shot 2020-08-10 at 3 39 04 PM" src="https://user-images.githubusercontent.com/1063667/89823730-fdfe6c00-db1f-11ea-8204-e9a281a3eab4.png">

**Comment by jasloe** [comment]
Regarding the first issue, I emptied the site cache and the correct image resolves.

In the process of doing so, I noticed that the internal caching (the thing that makes the site faster) is unacceptably large: 2.7 GB! Which partially explains why the server keeps running out of disk space. The site should periodically remove stale cache files after 24 hours but isn't. Looking into this now.
