### ISSUE TITLE
Cleanup "empty page" artifacts

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#343]
@cchristopherhowardd –– Noticing something odd while testing moderation. The footer menu disappears for logged in users. Works fine for admin (me) and anonymous but not users with the 'site editor' (you) or 'library' roles. Not sure what's going on or when this started. I rolled back to a database snapshot from early July and it seems to be broken there, too.

**Comment by cchristopherhowardd** [comment]
The header menu disappears, too. It's been that way for months, even going into 2019. I don't recall the footer menu was missing, but definitely noticed the header but didn't mention it as an issue.

**Comment by jasloe** [comment]
Header menu is "behind" the admin menu which is a major design flaw in Drupal administration. There's a fix for that forthcoming. 

The footer issue, however, is not so easily explained. The template is only rendering the opening and closing tags and none of the actual content. If I strip away the custom theming down to the barebones, it's still missing, which suggests some business logic issue or possibly a permissions issue? Very bizarre. Will ponder as I wrap up the library administration issue.

**Comment by jasloe** [comment]
@cchristopherhowardd –– working on debugging this. You may see an access denied page on index pages while logged in for the next 20-30 minutes.

**Comment by jasloe** [comment]
Ok, this is fixed. Renaming issue and leaving open to address a few clean up tasks.

**Comment by jasloe** [comment]
Prior to install the "empty page" module, I used a custom content type to provide the content region for index pages. This content and supporting content type can be deleted.

**Comment by jasloe** [comment]
Pushed.
