### ISSUE TITLE
Homepage slideshow with space on both sides

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#344]
Open commented that photos on the homepage slideshow should have space on the right and left side that displays the edges of images preceding and succeeding the present image. Is it possible to implement this? If so, how would the left and right arrows look?

![Homepage Slideshow with space on left and right](https://user-images.githubusercontent.com/38765846/89908689-2b98f300-dbbc-11ea-958d-bf5d3136e25d.png)

**Comment by jasloe** [comment]
Can do. Changed this to a bug. Intend to fix arrows, too. Will try to get to that before I leave the office for the week on Thursday, pending acceptance of library admin.

**Comment by cchristopherhowardd** [comment]
We should pick this back up in early January, when we start posting winter and spring events.

**Comment by jasloe** [comment]
Closed in favor of #380
