### ISSUE TITLE
Breadcrumb issue on News & Events pages in Society of Fellows section

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#345]
In the breadcrumb for the News & Events index page in the Society of Fellows section (see https://www.aarome.org/society-of-fellows/news-events/salone and https://www.aarome.org/society-of-fellows/news-events/sof-gatherings-present-tuesday-talks as examples), the ampersand (&) is rendering as the HTML code for ampersand (&amp;). Can you make the & an & again?

**Comment by cchristopherhowardd** [comment]
Forgot to include a screenshot.

<img width="1006" alt="Screen Shot 2020-08-12 at 4 59 37 PM" src="https://user-images.githubusercontent.com/38765846/90069173-ecec6100-dcbf-11ea-8723-71d2e13ee72e.png">

**Comment by jasloe** [comment]
Yeah, that was a bug from quite some time ago but resurfaced in the latest module release. Working on tracking down the bug.

**Comment by jasloe** [comment]
To wit: https://www.drupal.org/files/issues/2020-06-08/double_escaped_titles-2979389-34.patch

**Comment by jasloe** [comment]
Patch applied. Please test &amp; close.

**Comment by cchristopherhowardd** [comment]
Tested and closing.
