### ISSUE TITLE
Long URLs for Elsewhere (formerly Quick News) on the homepage.

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#347]
I noticed this month that lengthy URLs for items in the Elsewhere section (formerly Quick News) at https://www.aarome.org/news/elsewhere that appear on the homepage don't work. As a temporary fix I replaced the long link with a shortened Bitly URL that I use for Twitter and Facebook, which works. 

As an example, try out the Holland Cotter link currently on the homepage. It's using the full URL to the _New York Time_s.

<img width="500" alt="Screen Shot 2020-08-24 at 1 51 14 PM" src="https://user-images.githubusercontent.com/38765846/91078796-23f03a00-e611-11ea-8df4-eba0fb2b3453.png">

This is what happens when you click the link. Notice how the URL trails off in the toolbar. Is there a built-i  character limit somewhere?

<img width="500" alt="Screen Shot 2020-08-24 at 1 50 01 PM" src="https://user-images.githubusercontent.com/38765846/91078853-3e2a1800-e611-11ea-84cd-3285e1ef4cfe.png">

**Comment by jasloe** [comment]
Link length in the view is set to 80 characters by default. Changed limit to unlimited though be advised the node itself is capped at 512 characters. (For context, the NYT article link contains 101 characters.)

**Comment by cchristopherhowardd** [comment]
So the answer is to use Bitly URLs for links with a lot of characters in them?

**Comment by jasloe** [comment]
No, the upper limit is 512 characters. Anything longer than that will need to be shortened though I doubt you will ever encounter a URL that long.
