### ISSUE TITLE
Support pages - More Ways to Give

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#348]
I've connected the six webpages in the Support section ( https://www.aarome.org/support ) in a novel way. Toward the bottom of each page, I created a final Page Section that consists solely of link boxes directing people to the other five pages. The development crew asked for something like this, and I like this solution. 

<img width="1282" alt="McKim Medal Gala links" src="https://user-images.githubusercontent.com/38765846/91198714-ec45c880-e6ca-11ea-93c1-62f5981d37ee.png">

Since the website launch, I've noticed an inconsistencies. On two pages, the first link box appears **above** the headline to the left, horizontally speaking. See https://www.aarome.org/support/annual-fund and https://www.aarome.org/support/virtual-benefit (Annual Fund seen below):

<img width="1368" alt="Annual Fund links" src="https://user-images.githubusercontent.com/38765846/91194353-10eb7180-e6c6-11ea-861a-9c7d476c9280.png">

A few variables: the horizontal alignment looks fine on pages in which the preceding Page Section has similar links (https://www.aarome.org/support/corporate and https://www.aarome.org/support/join-renew). The alignment looks fine at https://www.aarome.org/support/planned-giving as well, though it seems like the amount of spacing between Page Sections here is shorter than for most other pages.

**Comment by cchristopherhowardd** [comment]
I should note that spacing issues on Italian pages mirror the English pages--what's described above applies to the IT pages as well.

Perhaps a related issue is spacing between the body text and the link box on the McKim Medal Gala page: https://www.aarome.org/support/mckim-medal-gala. There should be a little more spacing between the last paragraph in the page section for 2020 Gala and the link box that reads "I wish to make a contribution!"

**Comment by jasloe** [comment]
I fixed the egregious, very noticeable errors on annual fund and virtual benefit pages. 

Part of the problem with this cluster of fields is the variable use cases: sometimes with preceding content, sometimes not and in different combinations of file download buttons and external link buttons.  

Leaving this open until I have time to do a thorough refactor. Until then, I'm simply writing one-off style sheet declarations and calling it a day. Let me know if anything jumps out at you in the meantime.

**Comment by cchristopherhowardd** [comment]
Thanks, Jason.
