### ISSUE TITLE
Library Notices

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#349]
Sebastian has suggested putting the Library Notices page ( https://www.aarome.org/research/library/notices ) as the first item in the Research index page ( https://www.aarome.org/research ). That means removing the block from https://www.aarome.org/research/library, too. I'm OK with all this. I imagine the URL of the new page would be https://www.aarome.org/research/notices.

I have asked Sebastian if we should merge the Photographic Archive Notice page with the new Library Notices page and am awaiting his reply.

Relatedly, I'd like to propose an edit to the footer for Research section:

<img width="1325" alt="Research Footer" src="https://user-images.githubusercontent.com/38765846/91205367-6da15900-e6d3-11ea-95f5-4e990ec81634.png">

For each of the four columns, I'd like a line space between "Closed until further notice" and "Regular hours:"

Thanks!

**Comment by jasloe** [comment]
Moved notices block to requested page. Will add spacing as part of other theming activity (i.e. Virtual Benefit fixes).

**Comment by cchristopherhowardd** [comment]
Thanks. Can you add the green block with opening hours to https://www.aarome.org/research/notices? I'd like Sebastian to see the page with it there and ask if he wants it there or not.

**Comment by jasloe** [comment]
Added spacing; added block to /research/notices and /it equivalent. Test, close.

**Comment by jasloe** [comment]
N.B. The callout block takes some CSS that adds spacing to the first line of the content. When the library is ready to resume regular hours, let me know so that I can remove that declaration.

**Comment by cchristopherhowardd** [comment]
Can you make one small edit before I close the issue? The edit is changing "Photo Archive" to "Photographic Archive."

Is it possible to add hyperlinks to the four headers in this block?

**Comment by jasloe** [comment]
Sure. Where do you want links?

**Comment by cchristopherhowardd** [comment]
LIBRARY
https://www.aarome.org/research/library

PHOTOGRAPHIC ARCHIVE
https://www.aarome.org/research/photographic-archive

ARCHAEOLOGICAL STUDY COLLECTION
https://www.aarome.org/research/archaeology

BARBARA GOLDSMITH RARE BOOK ROOM
https://www.aarome.org/research/special-collections/

Let's try these. I'm having second thoughts about this move, but let's add the links and test them.

**Comment by jasloe** [comment]
Do you want the link to print like that? Or make the header the link? Problem with first is that the length of link will exceed available width; problem with second is how do ppl know the header is a link?

**Comment by jasloe** [comment]
Ancillary issue: #357

**Comment by cchristopherhowardd** [comment]
Oh, no. I want the header be the link, not for the link to appear under the header. Regarding the problem with the second is that people won't know the header is a link until they hover over the letters with their cursors, and the arrow turns into the gloved Mickey Mouse hand. For people on a mobile device or tablet, they won't know. Maybe the idea for links here is without good reason?

**Comment by cchristopherhowardd** [comment]
I have updates for the green box in the Research section, first in English and then Italian.

**LIBRARY**

Opening on November 2

Regular hours:
Monday–Wednesday
9:00–13:00 & 14:00–18:00

**PHOTOGRAPHIC ARCHIVE**

Opening on November 2

Regular hours:
Tuesday & Thursday
10:00–13:00 & 13:30–17:00
By appointment only

**BIBLIOTECA**

Apertura il 2 novembre

Orari regolari:
Lunedì–mercoledì
9:00–13:00 & 14:00–18:00

**ARCHIVIO FOTOGRAFICO**

Apertura il 2 novembre

Orari regolari:
Martedì & giovedì
10:00–13:00 & 13:30–17:00
Solo su appuntamento

On the Italian green box, please change ARCHAEOLOGICAL STUDY COLLECTION to COLLEZIONE DI STUDI ARCHEOLOGICI. If we need to translate Barbara Goldsmith Rare Book Room, I'll let you know soon.

**Comment by jasloe** [comment]
Did we ever resolve whether leading days of week should be capitalized? My (cursory) research resulted with no definitive conclusion.

**Comment by cchristopherhowardd** [comment]
Days of the week are capitalized in English, lowercase in Italian. Both languages capitalize the first word of a sentence (or in this case, a phrase).

**Comment by cchristopherhowardd** [comment]
Can you prioritize the update to the library hours? Or give me access to this module so that I can change the language?

**Comment by jasloe** [comment]
This is done. Leaving open for including links and translating block titles. Which'll require a template override.

**Comment by cchristopherhowardd** [comment]
Sebastian needs updates to library hours for the Research section. Can you make these changes to text in the green box?

**English**

LIBRARY
Opening on November 2
Regular hours:
Monday–Wednesday
9:00–13:00 & 14:00–18:00
By appointment only

PHOTOGRAPHIC ARCHIVE
Opening on November 2
Regular hours:
By appointment only

ARCHAEOLOGICAL STUDY COLLECTION
Opening on November 2 
Regular hours:
By appointment only

BARBARA GOLDSMITH RARE BOOK ROOM
Opening on November 2
Regular hours:
Monday–Wednesday
14:30–16:30
By appointment only  

Italian

LIBRARY
Apertura il 2 novembre
Orari regolari:
Lunedì–mercoledì
9:00–13:00 & 14:00–18:00
Solo su appuntamento

PHOTOGRAPHIC ARCHIVE
Apertura il 2 novembre
Orari regolari:
Solo su appuntamento

ARCHAEOLOGICAL STUDY COLLECTION
Apertura il 2 novembre
Orari regolari:
Solo su appuntamento

BARBARA GOLDSMITH RARE BOOK ROOM
Apertura il 2 novembre
Orari regolari:
Lunedì–mercoledì
14:30–16:30
Solo su appuntamento

**Comment by jasloe** [comment]
Posted.

**Comment by cchristopherhowardd** [comment]
Thanks so much.
