### ISSUE TITLE
Microsite for 2020 Virtual Gala

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#351]
There is talk in the AAR development department about the creation of a microsite for the 2020 Virtual Gala. Visualization will come from Open. Among the content for this site, which would probably consist of five to ten webpages, are:

1. Basic information about the event (time, day, format, honorees)
2. Details on the program
3. Information about the artists confirmed for the auction (to be run by Artsy)
4. The names of the Host Committee members
5. Levels of support as described on a PDF currently being circulated

The microsite will probably link to the Virtual Benefit page on the current site ( https://www.aarome.org/index.php/support/virtual-benefit ), but it seems like the idea for the microsite is to supersede this page. In other words, the AAR webpage serves to send people to the microsite.

I imagine that development will expect a ticket page on the microsite to supplant the NetCommunity ticket page ( https://support.aarome.org/2020-virtual-benefit ), but I don't know if this is possible.

I don't know if the microsite will require a subdomain (e.g., benefit.aarome.org) or if development envisions a unique URL (e.g., aarvirtualbenefit.org). Are there advantages for choosing one over the other?

I have a call with Marques and development at 1:00 PM today, after which I may know more about the project.

**Comment by cchristopherhowardd** [comment]
Here is the PDF about giving levels that is being circulated and is probably intended to be integrated into the microsite.

[2020-host-committee-benefits.pdf](https://github.com/aarome/aarome/files/5136696/2020-host-committee-benefits.pdf)

**Comment by cchristopherhowardd** [comment]
Part of today's call will be about budget issues. I may ask you to submit a separate invoice for development-related projects, which includes the gala/benefit emails. This invoice would be in addition to your monthly work with the main Academy website, not part of it. I could parse a single invoice and charge things to different internal accounts, but it might be easier for my colleagues to understand a bill that includes only their expenses.

Just a head's up.

**Comment by cchristopherhowardd** [comment]
I'm going to close this issue. It turns out that development has rejected the microsite idea, and I propose replicating it in the form of a handful of pages that circle around https://www.aarome.org/support/virtual-benefit. That page will be a homepage from which four or five related pages will be linked.

**Comment by jasloe** [comment]
Sounded like a great idea to me. That's too bad.

**Comment by cchristopherhowardd** [comment]
It's not a bad idea, but for various reasons it's not meant to be.
