### ISSUE TITLE
Updates to footer menu

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#352]
In Support, please change "New York Gala" to "2020 Virtual Benefit" and add a new URL: https://www.aarome.org/support/virtual-benefit ; in Italian, use the phrase "Beneficio Virtuale 2020"

In Publications, move "Affiliated Books" to after "Papers & Monographs" and before "Cookbooks"; make same movement on Italian footer

In Research, please remove the s in https in the URL for "Digital Humanities Center" (http://dhc.aarome.org/) for both the English and Italian footers.

In Events, change "Full Calendar" to "Calendar"; in Italian, change "Calendario Completo" to "Calendario"

**Comment by jasloe** [comment]
Fixed. Please test and close.

**Comment by cchristopherhowardd** [comment]
Tested and closed.
