### ISSUE TITLE
Canceled rectangle in Events

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#353]
I created a new event in the Events section and did **not** select the "Canceled" box on the edit node page, right under the Event Title field. When I published the page, a black box with the word OFF in white letters appeared in the upper right corner on the Event Calendar page: https://www.aarome.org/events/calendar

<img width="1288" alt="Screen Shot 2020-09-08 at 10 16 03 AM" src="https://user-images.githubusercontent.com/38765846/92488641-d2bd7a00-f1bc-11ea-8e8e-7bdabb2d023a.png">

**Comment by jasloe** [comment]
I can't recall whether I handled that with a style template or database logic. WIll check it out and report back.

**Comment by jasloe** [comment]
Looks like the template is only pulling the field contents: 

```
	<div class="card-image-wrapper">
		{{ content.field_events_image }}
		{{ content.field_events_canceled }}
	</div>
```

...which suggests a configuration error. I thought that this was pretty well tested prior to launch and looking through my notes to figure out if something else needed to happen to the new node to render the correct state.

**Comment by jasloe** [comment]
Template now looks like this:

```
		{% if node.field_events_canceled.0.value %}
			{{ content.field_events_canceled }}
		{% endif %}
```

In other words, if the field has a value (i.e. "Canceled"), publish the field. This is a quirk with how booleans work in general and not specific to Drupal or Twig.

Tested as follows:

- create new node
- select 'canceled'
- publish/save

and

- select and deselect 'canceled' on existing node
- publish/save

**Comment by jasloe** [comment]
Please test and close.

**Comment by jasloe** [comment]
Working on applying logic to events/calendar/some-event, as well.

**Comment by jasloe** [comment]
Pushed

**Comment by jasloe** [comment]
Pushed fix for events/calendar/some-event.
