### ISSUE TITLE
Library Resources sans hyperlinks

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#354]
As we know, a number of Library Resources that don't have URLs in the "Link to Resource" receive different typographic treatment.

<img width="862" alt="Screen Shot 2020-09-09 at 12 27 43 PM" src="https://user-images.githubusercontent.com/38765846/92629844-e809d580-f29c-11ea-9181-54d10e0dfd0b.png">

We've known about this issue for a while, and I'm bringing it back up in order to provide Sebastian with an explanation and possible next steps. One of those next steps might be asking him to reconsider how these resources are described and published, but that would mean there isn't a technical solution.

**Comment by jasloe** [comment]
Easy fix. Will knock out today. 

The bracketed ellipses is intentional, yes?

**Comment by cchristopherhowardd** [comment]
Yeah, brackets are intentional (though I don't quite know why library staff uses them like this).

**Comment by jasloe** [comment]
Fixed and pushed to production. Please t&c.
