### ISSUE TITLE
Fall events on homepage

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#355]
This week I added a handful of fall 2020 events to the Calendar: https://www.aarome.org/events/calendar. When you return at the end of the month, we should look at reverting to the original homepage design, which puts Events in the slideshow instead of News Features.

**Comment by jasloe** [comment]
Do you want to to do this now? Or wait? It's a pretty simple change.

**Comment by cchristopherhowardd** [comment]
Sure, if it's easy to do. It would be nice to have Monday's Zoom lecture on the homepage.

**Comment by jasloe** [comment]
Ack, I misspoke. The front page slider was built around a single content type, either news or events but not both. Do we have enough events atm to put them back in the slider? Should we bounce NF back down to the Elsewhere block?

**Comment by cchristopherhowardd** [comment]
We have enough events through the end of November. Right now there are five new events, though one is taking place today so that makes it four after today. I have three forthcoming events (two Conversations and one Italian Fellow lecture) that are unpublished because I'm awaiting more information.

Yes, we'll bounce News Features back to the Elsewhere block.

**Comment by cchristopherhowardd** [comment]
As the homepage goes back to its original form, with Events taking the slideshow, I'd like to replace the photograph for the Rome Prize competition block.

<img width="1413" alt="Screen Shot 2020-09-23 at 10 21 41 AM" src="https://user-images.githubusercontent.com/38765846/94025679-c58cb780-fd86-11ea-910f-03e458546350.png">

Please replace the photo of Raymond Carson with this new photo, which is part of Open's light branding of the RP competition. You can see a similar branded image at https://www.aarome.org/index.php/apply/rome-prize.

![2021-rome-prize-competiton-1](https://user-images.githubusercontent.com/38765846/94025837-f40a9280-fd86-11ea-9408-e6c264b7c945.jpg)

**Comment by jasloe** [comment]
Ok. Will have to take care of this when back in NYC.

**Comment by cchristopherhowardd** [comment]
It can wait until then, of course.

**Comment by cchristopherhowardd** [comment]
Any chance we could squeeze in the Features to Events homepage change this week? I'd like to get Mark Robbins's October 5 event on the homepage for a few days. 

I also feel anxious about posting the announcement of the new Classical Summer School director by the end of the week and having Sanjaya Thakur's portrait appear on the homepage. Not that he's not an unattractive fellow, it's just boom--there's his face super huge on the screen!

**Comment by jasloe** [comment]
Yeah I can switch gears and take care of that. Any feedback on the mailing?

**Comment by cchristopherhowardd** [comment]
Surprisingly no feedback, though I don’t expect a lot of changes. I forwarded a draft a little before 7 last night.

Chris
-------
Christopher Howard
Communications Manager

**Comment by jasloe** [comment]
When you get a minute can you promote all of the event nodes you'd like to display in the home page slideshow?

Right now, the Virtual Benefit and Encounters II are promoted.

I just issued the "promote" option to Events for your role.

**Comment by cchristopherhowardd** [comment]
Four events are now promoted.

**Comment by jasloe** [comment]
Trying to untangle my local development environment in my home office ate up a bunch of unbillable time this afternoon. Ok if we shoot to get this posted tomorrow?

**Comment by cchristopherhowardd** [comment]
Tomorrow is fine.

**Comment by jasloe** [comment]
Is this the correct date format for events?

Monday, November 9, 2020–6:00 PM
lunedì, novembre 9, 2020 18:00

I feel like we had something else at some point....a little confused.

**Comment by cchristopherhowardd** [comment]
Monday, November 9, 2020–6:00 PM
Lunedì, 9 novembre 2020–18:00

**Comment by cchristopherhowardd** [comment]
I see the styles at https://www.aarome.org/it/eventi/calendario and https://www.aarome.org/events/calendar match what you suggested. I'd say add the en dash for the Italian phrase. I don't know what the implications are for capitalizing the day of the week, which is lowercase in Italian (just like names of months) but in the case where that word leads off a phrase or sentence, then the word should be capitalized?

**Comment by jasloe** [comment]
I can push the home page event slider and news features blocks in the next 30 minutes if you have time to review between 5:30 and 6.

**Comment by cchristopherhowardd** [comment]
I'll come back at 5:30.

**Comment by jasloe** [comment]
Pushed. 

(You stop for the day at 5 or 6?)

**Comment by cchristopherhowardd** [comment]
I clock out at 5.

**Comment by cchristopherhowardd** [comment]
Looks good and links function properly. Can you reverse the order of events, so that the October 5 event is first, followed by October 19, October 27, and November 30? Right now the event farthest into the future appears when a visitor first reaches the homepage.

**Comment by jasloe** [comment]
Changed to ascending dates.

Added media query so news features stack on narrow devices.

**Comment by cchristopherhowardd** [comment]
Great. Until tomorrow!
