### ISSUE TITLE
Request Forms in News section

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#356]
There are two blocks in the News section ( https://www.aarome.org/news ) that are supposed to go to web forms: "Submit Your News" and "Film and Photography Request Form." AAR web forms aren't working, and that's OK for now. I rerouted the AAR Library request forms to the existing Google forms. These two pages will need some attention.

First, can we unpublish "Submit Your News"? This box doesn't need to appear on the News index page, and we can deal with it later.

Second, can the link for "Film and Photography Request Form" go to the Google form that was being used on the old site? You can see it embedded here: https://old.aarome.org/content/filmingphotography-permission-request-form.

I bring this up in part because there's going to be two shoots at the Rome campus this fall. One is for a perfume commercial (Gucci or some other luxury Italian brand). Another is for an Amazon Prime TV series, _Tom Clancy's Jack Ryan_. AAR is going to be the American Embassy. What fun!

**Comment by jasloe** [comment]
Sure, I just need the full URL for the film request Google form.

Unpublished submit your news.

The form business logic is pretty much ready to go. I detached the form stylesheets at some point. I'll try to get them re-attached to the master branch.

**Comment by cchristopherhowardd** [comment]
The form is at https://docs.google.com/forms/d/e/1FAIpQLScoKpph8Gx_Czj-NWKeYd9uTWG5qUShkkfdlRXqvywRd7fmyg/viewform
