### ISSUE TITLE
Delete Library Resource type

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#358]
Can you delete the radio-button option for Research Tutorials in the Library Resources section? I'm pretty sure that no Research Tutorials exist, as the information that appears on https://www.aarome.org/research/resources/tutorials is body text in a page section.

<img width="1204" alt="Screen Shot 2020-09-28 at 12 17 09 PM" src="https://user-images.githubusercontent.com/38765846/94459974-0ff6a580-0186-11eb-8ef1-804b3f14928f.png">

When I go over updating and creating Library Resources with library staff tomorrow, this bit of information is superfluous and may actually get in the way ("what's that for?").

**Comment by jasloe** [comment]
There's one node carrying that term:

https://aarome.org/node/1373/edit

I'm not even sure where this lives or whether it's an artifact of the old site. Pretty sure both the term (and node, for that matter) can be deleted, unless it's somehow deemed essential.

**Comment by cchristopherhowardd** [comment]
If the node isn't for https://www.aarome.org/research/resources/tutorials it can be deleted.

**Comment by jasloe** [comment]
Deleted.
