### ISSUE TITLE
load testing /benefit

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#361]
Opening this as a separate issue so we don't muddy the waters on design matters.

About how many visitors are we expecting to the Virtual Benefit? I'm running load tests and setting up caching and it would be good to have a high estimate of potential concurrent visitors in mind.

**Comment by jasloe** [comment]
Information provided at #359.

**Comment by cchristopherhowardd** [comment]
Wendy says that we expect between 500 and 1,000 viewers.
