### ISSUE TITLE
Virtual Benefit link redirect

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#363]
The URL for https://www.aarome.org/benefit should redirect to https://www.aarome.org/support/virtual-benefit

**Comment by cchristopherhowardd** [comment]
Can this be done ASAP? It's the last thing that needs to be done before the gala invite email is to be sent.

**Comment by jasloe** [comment]
Yeah I'm working on it now.

**Comment by jasloe** [comment]
Redirects working now. I put this configuration into the database (instead of at the level of the web server). Seems a little bit easier to manage that way.

/benefit => /support/virtual-benefit
/beneficio => /sostegno/beneficio-virtuale

Please test and close.
