### ISSUE TITLE
New photo for Rome Prize on homepage

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#371]
As the homepage goes back to its original form, with Events taking the slideshow, I'd like to replace the photograph for the Rome Prize competition block.

<img width="1413" alt="Screen Shot 2020-09-23 at 10 21 41 AM" src="https://user-images.githubusercontent.com/38765846/94025679-c58cb780-fd86-11ea-910f-03e458546350.png">

Please replace the photo of Raymond Carson with this new photo, which is part of Open's light branding of the RP competition. You can see a similar branded image at https://www.aarome.org/index.php/apply/rome-prize.

![2021-rome-prize-competiton-1](https://user-images.githubusercontent.com/38765846/94025837-f40a9280-fd86-11ea-9408-e6c264b7c945.jpg)

_Originally posted by @cchristopherhowardd in https://github.com/aarome/aarome/issue_comments/697440505_

**Comment by jasloe** [comment]
Replaced.

This node can be reached at: https://www.aarome.org/node/5152/edit

**Comment by cchristopherhowardd** [comment]
Can you quickly replace the image that says "Apply by Nov. 15" with the previous image, without the deadline?

https://user-images.githubusercontent.com/38765846/97891586-f6082f80-1cfc-11eb-8e67-9f36c8100fa3.jpg

**Comment by jasloe** [comment]
Replaced. 

Pretty sure you have access to this node at https://www.aarome.org/node/5152/edit if you need to change it again.
