### ISSUE TITLE
Add 2021 program to Academic Programs

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#373]
I just created a new Program page for the 2021 Classical Summer School: https://www.aarome.org/apply/academic-programs/2021-classical-summer-school

Can you add it to the index page for Apply --> Academic Programs at https://www.aarome.org/apply/academic-programs?

The image is a placeholder as I search for a better photo. But it may stay if I don't find anything better.

**Comment by cchristopherhowardd** [comment]
Shawn asked if the "Apply Now" link on the 2021 Classical Summer School page can open in a new tab/window. He writes: "For some reason, when using Firefox, once it's clicked and the user is taken to the SlideRoom page, the back button does not take the user back to our website. The back button works in Chrome, but not Firefox for some reason."

I've found that Safari works the same way that Firefox does. Shawn's concern brings up something that I've wanted to ask for a while: can we make it so that a link entered in the Links field on this and other pages automatically opens in a new tab/window using the coding target="_blank"? I've found that almost all of these links go to non-AAR websites.

<img width="935" alt="Screen Shot 2020-10-16 at 4 57 23 PM" src="https://user-images.githubusercontent.com/38765846/96308322-29df1780-0fd1-11eb-932f-5c22eddb87ba.png">

**Comment by cchristopherhowardd** [comment]
Can I interrupt your work on the Virtual Benefit page to implement this task?

**Comment by jasloe** [comment]
Oops....did that last week and forgot to push it to production.

**Comment by jasloe** [comment]
Will do here in a minute.

**Comment by jasloe** [comment]
Regarding opening links in new window, I came across this thread: https://www.drupal.org/project/drupal/issues/2946155

Comment #9 is pretty strident and, well, pretty wrong-headed. 

Fortunately, there's a sane workaround which I'll test now on staging and report back.

**Comment by jasloe** [comment]
@cchristopherhowardd –– can you check the following link and let me know if it's doing what you want it to do?

https://staging.aarome.org/apply/academic-programs/2020-classical-summer-school

**Comment by cchristopherhowardd** [comment]
It works.

**Comment by jasloe** [comment]
Pushed to aarome.org and applied to https://www.aarome.org/apply/academic-programs/2021-classical-summer-school.

Default behavior is to target attribute. Simply select "Select a target: New window (_blank)" to set attribute and spawn link in new browser window.
