### ISSUE TITLE
Rewrite library hours custom blocks

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#375]
In light of recent COVID-19 restrictions, it's important to allow staff access to edit the custom library hours blocks. Drupal core does not provide granular control of custom blocks. Two modules provide this functionality: 

https://www.drupal.org/project/block_permissions
https://www.drupal.org/project/block_content_permissions

Implementing these modules requires a minor reworking of custom blocks, including replacing current library hours blocks. This site will be put into maintenance mode this evening after 10 pm in order to push these changes.

**Comment by cchristopherhowardd** [comment]
In the meantime, can you replace "Opening on November 2" with "Closed until further notice" on the English pages and "Chiuso fino a nuovo avviso" on the Italian pages?

The information under Regular Hours/Orari regolari can remain.

**Comment by jasloe** [comment]
Took about 90 minutes but managed to cobble together a decent solution. I reckon the situation there is going to be very fluid and they'll need to change these blocks fairly often. So instead of all of the hoop jumping, library users can simply hover the desired library hour block. A pencil icon will appear in the upper right hand corner and the block. Selecting the pencil will take the user to the edit page. Make changes and save. That's it. 

This should be working for your role as well. Let me know what you think.

There are one or two tiny theming issues I need to fix but putting that aside for now as it's getting late!

**Comment by cchristopherhowardd** [comment]
The pencil icon doesn't allow me to change the text in the blocks. When I click the icon, I get a translation option only.

<img width="483" alt="Screen Shot 2020-12-04 at 12 09 32 PM" src="https://user-images.githubusercontent.com/38765846/101192874-b8633300-3629-11eb-8039-a793caa94fde.png">

<img width="1128" alt="Screen Shot 2020-12-04 at 12 09 41 PM" src="https://user-images.githubusercontent.com/38765846/101192882-bb5e2380-3629-11eb-925b-1180a02ca7ee.png">

**Comment by cchristopherhowardd** [comment]
I updated the Italian library box (see https://www.aarome.org/it/ricerca/avviso for example). It looks like there's an automatic line space baked in, between the first line and the following lines. There shouldn't be a line space between "Orari regolari:" and the lines underneath them.

<img width="1303" alt="Screen Shot 2020-12-04 at 12 21 16 PM" src="https://user-images.githubusercontent.com/38765846/101193941-4b509d00-362b-11eb-97ed-bc2517698c33.png">

Compare to the English language box:

<img width="1291" alt="Screen Shot 2020-12-04 at 12 26 20 PM" src="https://user-images.githubusercontent.com/38765846/101194393-f2353900-362b-11eb-8435-e0470991b97d.png">

**Comment by jasloe** [comment]
Only library users had rights to edit. I've added your role to the rights' matrix. Tested here. Let me know if working for you.

**Comment by jasloe** [comment]
So, no "closed until further notice" on the Italian side?

**Comment by cchristopherhowardd** [comment]
I deleted the Italian translation of "closed until further notice" already. I was able to do that.

**Comment by cchristopherhowardd** [comment]
Do you see what I mean with the spacing? I deleted "Closed until further notice" under the Library header and it moved up "Regular hours:" to take its place.

<img width="651" alt="Screen Shot 2020-12-04 at 2 31 19 PM" src="https://user-images.githubusercontent.com/38765846/101206675-7348fc00-363d-11eb-8482-8e246170c817.png">

**Comment by jasloe** [comment]
Yep. So you want the text in one block with no spacing on the first line?

**Comment by cchristopherhowardd** [comment]
Sure. And if I need spacing I'll add a br tag. 

I do like the space between the line "Closed until further notice" and the rest, but I can add that with the br tag or a hard return.

**Comment by jasloe** [comment]
There was a reason I hard coded the spacing in and I can't remember why. It'll come back to me. I have to fix one other thing with those blocks and will get to it in about 20 minutes.

**Comment by cchristopherhowardd** [comment]
Another minor thing. When seen in a narrow viewport, the last line of a block and the header of the next run into each other. This could be solved with a soft return after the final line of block text or another way?

<img width="500" alt="Screen Shot 2020-12-04 at 3 25 53 PM" src="https://user-images.githubusercontent.com/38765846/101211384-1cdfbb80-3645-11eb-8f73-2367b7a1b3c0.png">

**Comment by jasloe** [comment]
Yep, that was the one other thing!

**Comment by jasloe** [comment]
Pushed. 

https://aarome.org/research/library/about

Ok to close?

**Comment by cchristopherhowardd** [comment]
Did the ability for me to update the library green blocks survive the migration from Drupal 8 to 9? I'm logged in to the site, but don't see the edit icon when I'm in the green block.

<img width="1360" alt="Screen Shot 2021-04-01 at 9 56 15 AM" src="https://user-images.githubusercontent.com/38765846/113305388-fa973b00-92d0-11eb-81cd-7784855f035e.png">

**Comment by jasloe** [comment]
Looks like there's a hornet's nest of permission issues with the front end quick edit function. I've moved block editing permissions to the custom block library page at: http://staging.aarome.org/admin/structure/block/block-content

You can also access this page via the 'shortcuts' in the admin menu bar. I'm in the process of expanding site editor permissions so that you can edit/manage modals, COVID notices, etc. Library users will only be able to edit/manage library blocks.

This actually may be a better way to edit/update this content as you don't need to jump in and out of the front end and admin pages. 

Please test on staging and I'll move to production.

**Comment by cchristopherhowardd** [comment]
Test completed on staging. It works for me.

I've gotten used to not having front-end quick editing, and am OK with it. Other users may not feel the same, though.

**Comment by jasloe** [comment]
Great, will post with #404.

**Comment by cchristopherhowardd** [comment]
Will the URL for changing the blocks be this?

https://www.aarome.org/admin/structure/block/block-content ?

**Comment by jasloe** [comment]
Correct. Site editor and library roles have a shortcut in the admin menu.
________________________________

**Comment by cchristopherhowardd** [comment]
I don't have access yet!

<img width="775" alt="Screen Shot 2021-04-02 at 3 07 22 PM" src="https://user-images.githubusercontent.com/38765846/113446144-36abc800-93c5-11eb-8d50-72e6d4cc758f.png">

**Comment by jasloe** [comment]
It's not in production quite yet.

**Comment by jasloe** [comment]
Just pushed a slew of front and back end changes to production. Try it now.

**Comment by cchristopherhowardd** [comment]
It works, thanks!
