### ISSUE TITLE
Trouble in Elsewhere

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#376]
Last week I discovered that links on the Elsewhere page ( https://www.aarome.org/news/elsewhere ) stop working for all items below the "More Elsewhere" link. After I click that link and more items appear, none of them have hyperlinks. Try it yourself. 

<img width="1040" alt="Screen Shot 2020-11-06 at 10 46 49 AM" src="https://user-images.githubusercontent.com/38765846/98386032-b784b480-201d-11eb-948d-d5ca3a04eb0e.png">

<img width="987" alt="Screen Shot 2020-11-06 at 10 47 06 AM" src="https://user-images.githubusercontent.com/38765846/98386046-ba7fa500-201d-11eb-9ed1-892c704fe76c.png">

**Comment by jasloe** [comment]
Very odd. I'll check it out.

**Comment by jasloe** [comment]
It looks like the template for nodes on the other side of the "more" button aren't loading completely. I'm going to try the dev release of the module that manages infinite scrolling and apply a few patches.

**Comment by cchristopherhowardd** [comment]
Perhaps this request deserves an Issue of its own, but I'm having trouble getting AAR staff to recognize that the Elsewhere section ( https://www.aarome.org/news/elsewhere ) is an expanded version of the Far Afield section of the magazine. (It's also what we did on the homepage of the old site, called Quick News, but nobody seems to remember that, either.) 

So, can Elsewhere be renamed Far Afield, with a URL of https://www.aarome.org/news/far-afield? The Italian title can be simply Notizie Recenti until I can get an approximate translation for the English phrase.

**Comment by jasloe** [comment]
You bet. Will get going on this after I push a search demo here in a minute. See #330 for more.

**Comment by jasloe** [comment]
Moved issue to #385.

**Comment by jasloe** [comment]
@cchristopherhowardd –– Pushed stylesheet change to production at /events/watch and /news-features/far-afield. To test, scroll to bottom, load more items, then click card to spawn link in new window.

> Last week I discovered that links on the Elsewhere page ( https://www.aarome.org/news/elsewhere ) stop working for all items below the "More Elsewhere" link. After I click that link and more items appear, none of them have hyperlinks. Try it yourself.
