### ISSUE TITLE
December homepage

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#378]
The final fall 2020 event ended less than two hours ago, and the next event doesn't take place until January 26, 2021. That means we will need a placeholder image for the AAR homepage for the rest of this month. I've started to review the possibilities and will list a few soon. Watch this space!

**Comment by cchristopherhowardd** [comment]
**December 1–6**
Apply for an Italian Fellowship
https://www.aarome.org/apply/italian-fellowships 
https://www.aarome.org/it/partecipazione/borse-di-studio-italiani

**December 7–15**
2021 Classical Summer School
https://www.aarome.org/apply/academic-programs/2021-classical-summer-school 
https://www.aarome.org/it/partecipazione/programmi-accademici/2021-classical-summer-school 

**December 16–20**
Apply for an Italian Fellowship
Same links as above

**December 21–January 1**
Annual appeal (need 16 x 9 image)
https://support.aarome.org/

**January 2–??**
Apply for an Italian Fellowship
Same links as above

**Comment by jasloe** [comment]
The home page can take news or event content types and isn't currently configured to support basic pages. I'll look at the configuration and see what can be done to support basic pages.

**Comment by cchristopherhowardd** [comment]
I'm not so much interested in having an automatic, possibly complicated process by which this section of the homepage draws from Basic Pages (like it does for News and Events). What interests me is having one block for content (image and headline with links) at the top of the page that is interchangeable (i.e., no slideshow).

**Comment by jasloe** [comment]
I figured out something that's pretty straightforward. This needs a few minor style tweaks: https://staging.aarome.org/

I added the "promote to front page" boolean and a "teaser" to the Basic Page content type. (In this case, the teaser field contains the "Apply for an Italian Fellowship".) 

Let me know if that works for you and I'll make the style sheet changes and move this to production.

**Comment by cchristopherhowardd** [comment]
That looks good and functions well. I suggest that the teaser text be stylized with the larger serif font, as seen on the current homepage. Can I write separate teaser texts in both English and Italian?

<img width="1157" alt="Screen Shot 2020-12-01 at 11 56 56 AM" src="https://user-images.githubusercontent.com/38765846/100771460-738e9080-33cc-11eb-8a21-ac1a00c26771.png">

**Comment by jasloe** [comment]
Sounds good. I just added the Italian translation configuration: http://staging.aarome.org/it

Will work on style sheet now. Should be able to get this wrapped up today.

**Comment by jasloe** [comment]
Applied style sheet to staging: https://staging.aarome.org/

Let me know if ok.

**Comment by cchristopherhowardd** [comment]
Looks great. Move to production, please!

**Comment by cchristopherhowardd** [comment]
I just noticed that the links for the three news items on the homepage open in a new tab/window. This is vestige from when we had the Elsewhere section on the homepage, in late summer/early fall. Those links went to external, non-AAR sites. Can you make these links open in the same window?

<img width="1370" alt="Screen Shot 2020-12-04 at 5 15 52 PM" src="https://user-images.githubusercontent.com/38765846/101220917-97640780-3654-11eb-9e81-131d109ee42f.png">

**Comment by jasloe** [comment]
Pinned this issue to fix the news bug.

Also, should we try to bang out this annual appeal this afternoon?

December 21–January 1
Annual appeal (need 16 x 9 image)
https://support.aarome.org/

January 2–??
Apply for an Italian Fellowship
Same links as above

**Comment by cchristopherhowardd** [comment]
I never pursued a 16 x 9 image for the annual appeal. I'm OK with leaving the Italian Fellowship notice there, or we could revert to the News Feature slideshow at the top with three Elsewhere (formerly Quick News) items underneath it, if that's easy to implement.
