### ISSUE TITLE
Short clips from Virtual Benefit for Support section

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#379]
Development has produced four one-minute videos from 2020 Virtual Benefit footage that they would like posted to the AAR website. The videos are currently hosted on Point Studio's Vimeo account, which you can view at:

Video #1: https://vimeo.com/481767034
Video #2: https://vimeo.com/481832561
Video #3: https://vimeo.com/481777988
Video #4: https://vimeo.com/486138915

The password is: AAR. The videos will soon be uploaded onto an AAR account (either Vimeo or YouTube).

The videos relate to AAR's year-end appeal. The next two emails, scheduled for December 21 and 31, will link to the videos on the AAR website (somewhere like https://www.aarome.org/support/whatever-the-title-is). I imagine that each video will live on its own page and have its own URL.

We have a precedent page at https://www.aarome.org/benefit/ of course. The new pages could be a stripped down version of this, minus all the Virtual Benefit language, information, and colors. In other words, the page ought to have a video embed like the VB page but otherwise look more like the regular AAR site. Something of a cross between VB and https://www.aarome.org/support/annual-fund for instance, with the header menu, some room for page sections, and the footer.

Does this make sense?

**Comment by cchristopherhowardd** [comment]
Any thoughts on this? I'd like to present a couple of practical ideas to development this week.

**Comment by cchristopherhowardd** [comment]
I'm working to get the videos uploaded to AAR's YouTube, trying to connect the person with access to the video files and the person who can do the upload.

**Comment by jasloe** [comment]
Will there be a text or any other page elements that live on each page?

**Comment by cchristopherhowardd** [comment]
I imagine there will be a short headline and an area for two or three sentences of text. Right now the temporary headlines for each video are: AAR Support Video #1, AAR Support Video #2, and so on. 

There will also be a link box that takes people to https://support.aarome.org/ so they can donate. That link box is built into the Drupal site, like on this page. 

<img width="1045" alt="Screen Shot 2020-12-07 at 4 43 32 PM" src="https://user-images.githubusercontent.com/38765846/101409104-65001780-38ab-11eb-91a1-d4e83da89565.png">

**Comment by jasloe** [comment]
Based on what you've described at the top of thread, it seems like the sane route is to simply embed the video in the space where the main image usually lives and include the two-column layout below that. 

If this works for you, it's easy to add a field to support remote videos and tweak the styling accordingly. Let me know what you think.

**Comment by cchristopherhowardd** [comment]
That sounds fine. Something simple and manageable is good.

**Comment by jasloe** [comment]
I created four placeholder nodes, one for each video. They are currently unpublished. I'll pull these down to local dev and work on the styling this afternoon.

https://www.aarome.org/node/5523/edit
https://www.aarome.org/node/5524/edit
https://www.aarome.org/node/5525/edit
https://www.aarome.org/node/5526/edit

Have the videos been published to YouTube?

**Comment by cchristopherhowardd** [comment]
Videos posted to YouTube this morning: https://www.youtube.com/channel/UCZqVVswAO_EfDiNKyOd12Mg/videos

**Comment by jasloe** [comment]
Styled: https://staging.aarome.org/support/video-1

The video can autoplay or not.

**Comment by cchristopherhowardd** [comment]
Headlines for the videos on YouTube are as follows. They're kinda long, so I don't know how they'll look on the draft pages.

Video #1
Why Support the American Academy in Rome – An Immense Opportunity

Video #2
Why Support the American Academy in Rome – Because Art Matters

Video #3
Why Support the American Academy in Rome – The Collaborative Spirit

Video #4
Why Support the American Academy in Rome – Community

**Comment by jasloe** [comment]
Should also give some thought to what the URLs should be, I suppose.

https://staging.aarome.org/support/an-immense-opportunity

**Comment by cchristopherhowardd** [comment]
Revised headlines:

Video 1
Support the AAR: Opportunity

Video 2
Support the AAR: Because Art Matters

Video 3
Support the AAR: The Collaborative Spirit

Video 4
Support the AAR: Community

Still no descriptions. In the meantime, we should include a link to the donation page. So, the description for each video can be the same sentence:

Make a donation to the American Academy in Rome at https://support.aarome.org.

**Comment by cchristopherhowardd** [comment]
Your URL suggestion make sense. I suppose "The Collaborative Spirit" becomes "collaborative-spirit"

**Comment by jasloe** [comment]
Will move this to production this afternoon, though will remain unpublished. You'll be able to make content edits there. Will let you know when this is ready.

**Comment by jasloe** [comment]
These are custom URLs and can be anything you want.

> Your URL suggestion make sense. I suppose "The Collaborative Spirit" becomes "collaborative-spirit"

**Comment by jasloe** [comment]
Moved template to production. You have rights to edit the relevant nodes:

https://www.aarome.org/node/5523/edit
https://www.aarome.org/node/5524/edit
https://www.aarome.org/node/5525/edit
https://www.aarome.org/node/5526/edit

To change the URL alias, deselect the checkbox in the right-hand pane, complete the "URL alias" field, and save node.
