### ISSUE TITLE
Grant custom block permissions for "notice" block type to "site editor" role

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#383]
Can we change the black bar at the top of every page to the following phrase through December 23?

English site: While AAR is currently closed due to COVID-19, the Library and Archives are open on a limited basis.
Italian site: Sebbene l’AAR sia attualmente chiusa a causa di COVID-19, la Biblioteca e gli Archivi sono aperti su base limitata.

From December 24 to January 10, it can read:

English site: AAR is closed for the holidays. The Library and Archives will reopen on January 11.
Italian site: L’AAR è chiusa per ferie. La Biblioteca e gli Archivi riapriranno l’11 gennaio.

<img width="490" alt="Screen Shot 2020-12-15 at 9 59 55 AM" src="https://user-images.githubusercontent.com/38765846/102232503-34c50400-3ebd-11eb-95da-8d8154fd5b02.png">

**Comment by cchristopherhowardd** [comment]
Sebastian had a couple of changes. Here are the sentences in full.

Through December 23:

English site: While AAR is currently closed due to COVID-19, the Library and Archives are open by appointment.
Italian site: Sebbene l’AAR sia attualmente chiusa a causa di COVID-19, la biblioteca e gli archivi sono aperti su prenotazione.

From December 24 to January 10:

English site: AAR is closed for the holidays. The Library and Archives will reopen on January 11.
Italian site: L’AAR è chiusa per ferie. La biblioteca e gli archivi riapriranno l’11 gennaio.

**Comment by cchristopherhowardd** [comment]
Can I prioritize this issue for today? If there's a way I can change the text myself, I'm happy to do the work!

**Comment by jasloe** [comment]
Sorry, losing track of everything amidst the flurry of mailings! I'll post today. Will need a style sheet change or two accommodate the line break that will occur due to the length of the text.

**Comment by jasloe** [comment]
Ok, added a couple of styles to make this work. Have to rewire the block to give you easy access to this block (like the library hour blocks). Changed title of issue and will get it to it before the 24th.
