### ISSUE TITLE
Links to press release PDFs

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#384]
We've lost formatting for the English and Italian links on the Press Releases page: https://www.aarome.org/news/press-releases

The links used to look like this: https://web.archive.org/web/20200726061540/https://www.aarome.org/news/press-releases

**Comment by jasloe** [comment]
Fixed. Please test and close.

**Comment by jasloe** [comment]
Reopened to address links at /publications/*.

**Comment by jasloe** [comment]
Pushed with #386. Please test and close.
