### ISSUE TITLE
GDPR/cookie notice

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#386]
Can you change the text of the box from "Dismiss" to "OK"? I had a request to make the notice friendlier.

Also, can you add more space between the sentences and the box? In Chrome, the box is often right next to the text, as you can see below. In Safari, the distance looks fine except at certain screen sizes.

<img width="1357" alt="Screen Shot 2021-01-07 at 12 34 28 PM" src="https://user-images.githubusercontent.com/38765846/103925208-2ac1aa00-50e5-11eb-8a05-5879566e0d59.png">

<img width="1071" alt="Screen Shot 2021-01-07 at 12 37 02 PM" src="https://user-images.githubusercontent.com/38765846/103925213-2dbc9a80-50e5-11eb-97f7-5d933629081f.png">

**Comment by jasloe** [comment]
Change to 'Ok'. Will fix styling and push with #384.

**Comment by jasloe** [comment]
Pushed with #384. Please test and close.
