### ISSUE TITLE
Notice at the top of the page

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#388]
We need to change the notice at the top of the page today to: The Library and Archives have reopened.

<img width="672" alt="Screen Shot 2021-01-11 at 9 47 56 AM" src="https://user-images.githubusercontent.com/38765846/104196965-6ebcf380-53f2-11eb-89e2-65ffc411d4c6.png">

This notice is going to change again this week, with something that goes "The Academy is pleased to reopen for 2021 and to welcome the new Fellows to the campus..." but this sentence hasn't been finalized. I haven't seen the draft yet but it's guaranteed to be grandiose and flowery with many unnecessary words.

**Comment by jasloe** [comment]
> guaranteed to be grandiose and flowery with many unnecessary words.

Ha.

Is there a translation for "The Library and Archives have reopened"?

**Comment by cchristopherhowardd** [comment]
Let's use: La Biblioteca e gli Archivi sono stati riaperti.

The sentences AAR IS CLOSED FOR THE HOLIDAYS and L’AAR È CHIUSA PER FERIE can be deleted entirely. I'm sorry for not being more specific about the replacement text.

**Comment by jasloe** [comment]
No problem. Made the change. Keep me posted if a COVID-closing is on the horizon.

**Comment by cchristopherhowardd** [comment]
Can you please change the notice to:

The Academy has reopened.

**Comment by cchristopherhowardd** [comment]
Italian site: 

L’Accademia ha riaperto.

**Comment by jasloe** [comment]
Posted.
