### ISSUE TITLE
Zoom video page in Event section

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#389]
I've been told to create a new index page in the Events section (https://www.aarome.org/events) for the Zoom videos. It should be placed second on the section page, with the title Zoom Videos (i.e., https://www.aarome.org/zoom-videos), placed between Calendar and Exhibitions.

Clicking the box would lead website visitors to a page not dissimilar to https://www.aarome.org/events/calendar and https://www.aarome.org/events/exhibitions. The attached PDF contains notes about placement of images and text.

[Index page for video.pdf](https://github.com/aarome/aarome/files/5797323/Index.page.for.video.pdf)

In order to have the Zoom Videos page not look identical to the Calendar or Exhibition pages, I will substitute the stills from the YouTube page for the image on the Calendar and Exhibition pages, or find another way to generate an image. 

The "template" for the Zoom Videos page would be duplicated and used in the Society of Fellows section ( https://www.aarome.org/society-of-fellows ), because SOF has been doing their own Zoom talks since February and they want their work represented on the AAR website. (It should be noted that SOF has not yet created a YouTube page and thus has not uploaded any video content.)

It should also be noted that I've been embedding video for fall 2020 Zoom talks on each individual event page (e.g.,  https://www.aarome.org/events/calendar/giovanna-silva-narratives-relazioni), but the C suite wants these videos to be easier to find, hence the special new section.

**Comment by cchristopherhowardd** [comment]
Prioritization is roughly "end of the month."

**Comment by jasloe** [comment]
We'll need a vocabulary term to organize this content. What shall we call it? E.g.:

Video
Video talk
Zoom
Zoom video

**Comment by cchristopherhowardd** [comment]
Zoom video.

**Comment by jasloe** [comment]
Added the term to the ```event type``` vocabulary. 

The term will show up on the event index and detail page. Do we want that or no? 

https://www.aarome.org/events/calendar
https://www.aarome.org/events/calendar/lynne-lancaster-rome-urbs-pensilis-hanging-city-its-hanging-gardens

**Comment by cchristopherhowardd** [comment]
I'm not sure I understand the question. 

There won't be detail pages for the individual items at https://www.aarome.org/events/zoom-video. The box for Lynne Lancaster, for example, would open in a new window/tab at https://www.youtube.com/watch?v=425-kUXaMTc. The link goes directly to YouTube.

**Comment by jasloe** [comment]
I assumed it would be the usual event layout with links to the inside detail page. Sounds like it's more like the Far Afield ux. 

In that case, we still need to use the ```event type``` tag to collect the content in a view (though it won't appear in the view). Do you still want to display "Lecture", "Shoptalks", etc.? 

Seems like a redundancy to have two views of the same content, one at ```/events/calendar``` and another at ```/zoom-videos```.  

I'd instead recommend embedding and playing (and replaying) the video in the existing event node. That way 1) keeps viewers on the site and 2) gives them access to the event description which very often contains useful information. 

But I understand this may be a short order cook situation. In which case, we'll just do what's being requested.

**Comment by jasloe** [comment]
Pretty important that I come up with a solution to #376. Prioritizing that first, then this.

**Comment by cchristopherhowardd** [comment]
> I assumed it would be the usual event layout with links to the inside detail page. Sounds like it's more like the Far Afield ux.

Yes. And the photos for each "event" are going to be different images, not those used in the regular event detail page. Like these, for example.

![silva-talk](https://user-images.githubusercontent.com/38765846/104347806-06900f80-54cf-11eb-8a32-505f6be68c5b.jpg)

![pergamon](https://user-images.githubusercontent.com/38765846/104347814-08f26980-54cf-11eb-87a6-d24cc0530cae.jpg)

**Comment by cchristopherhowardd** [comment]
Images for the eight Zoom talks are in the attached zipped file.

[Zoom Event Images.zip](https://github.com/aarome/aarome/files/5851327/Zoom.Event.Images.zip)

**Comment by cchristopherhowardd** [comment]
Links for each of the seven Zoom talks and the Virtual Benefit videos are:

zoom-lancaster
https://www.youtube.com/watch?v=425-kUXaMTc

zoom-scott-bradley
https://www.youtube.com/watch?v=Ebc-BShqwOI

zoom-silva
https://www.youtube.com/watch?v=7TpKJEwfRdY

zoom-pergamon
https://www.youtube.com/watch?v=eB0ItTs2tDY

zoom-virtual-benefit
https://www.aarome.org/benefit/

zoom-istanbul
https://www.youtube.com/watch?v=Q1lxK9gHvZ4

zoom-opie
https://www.youtube.com/watch?v=IYsyFWwvrdM

zoom-shalem
https://www.youtube.com/watch?v=sh7YcaaxLV0

**Comment by jasloe** [comment]
You'll be able to build those out using the existing ```Events``` nodes. There will be a stanza at the bottom with Zoom-related fields. I'll starting posting this configuration change to production in the next hour. 

https://staging.aarome.org/node/5521/edit?destination=/admin/content

**Comment by cchristopherhowardd** [comment]
Oh, great. I understand now. Let me know when I can start.

**Comment by jasloe** [comment]
You can make edits to Event nodes now.

Just pushed:

Zoom content admin configuration
Removed ```target="_blank" from news features on home page
#330 (in progress)
#376 (in progress)

Let me know if anything breaks or causes grief.

**Comment by jasloe** [comment]
Note applying a quick hotfix for a styling issue on /it pages now, as well.

**Comment by cchristopherhowardd** [comment]
I have added links and uploaded images to the eight event nodes intended for the new Zoom talks section.

The news features on the homepage open in the same window--no breaks, no griefs.

**Comment by jasloe** [comment]
Cool. I'll push up the style sheet shortly. Any objection to the page living at /events/zoom-videos? Without /events, we don't pick up breadcrumb or url translation. We can redirect /zoom-videos to /events/zoom-videos if folks are attached to the shorter url.

**Comment by jasloe** [comment]
This is ready for review/comment. 

https://www.aarome.org/events/zoom-videos

Tags for Zoom events may need to be tweaked. 

I suppose we should omit Zoom videos from /events/calendar?

Note #376 still needs to be resolved which will impact this page and the Far Afield page. Working on a solution for that.

**Comment by cchristopherhowardd** [comment]
The page looks great, and the links to the videos all function well. The tag for Zoom videos (i.e., the event type) works well in gathering the right nodes. I'll need to remember to not select "Zoom video" as event type for an upcoming event until the live event has taken place and the video is uploaded to YouTube. Otherwise a future-dated event appears on the Zoom Video page, like it does here:

![Uploading Screen Shot 2021-01-22 at 9.31.48 AM.png…]()

**Comment by cchristopherhowardd** [comment]
One oddity that we've created is that the event type for Zoom videos does not appear on event nodes that have an event series. For example, we've set it up so that if an event node has Conversations/Conversazioni as the event series, it supersedes anything chosen for event type. We did this on purpose, so that we don't have dozens of events that are listed as, to give two examples:

Conversations/Conversazioni
Conversation

Patricia H. Labalme Friends of the Library Lecture
Lecture

This would seem odd to people browsing the Events section. But now, would like a node to be presented as like the following, so that the event type Zoom Talk is published but event type Conversation is not:

Conversations/Conversazioni
Zoom Talk

Is there a solution?

<img width="961" alt="Screen Shot 2021-01-22 at 9 39 34 AM" src="https://user-images.githubusercontent.com/38765846/105505684-40170680-5c97-11eb-9afa-3921afc8ca0f.png">

**Comment by cchristopherhowardd** [comment]
Perhaps a solution is to **not** use Zoom video as an event type and to tag the node in another ways, so that it shows up on /events/zoom-video.

**Comment by cchristopherhowardd** [comment]
New question: is it possible to list **only** the date and **not** the start time of an event? In other words, and using the screenshot two comments above this one, can the Scott-Bradley just have "Monday, November 23, 2020" without the "–6:00 PM"?

**Comment by jasloe** [comment]
Yes, for sure. 

Regarding tags, I was just making it up as I went along! Let me rework the logic a little bit.

**Comment by jasloe** [comment]
Thinking this through: seems like the simplest solution is to move the ```Zoom Video``` tag from and corresponding logic from ```event_type``` to ```event_series```?

> Perhaps a solution is to **not** use Zoom video as an event type and to tag the node in another ways, so that it shows up on /events/zoom-video.

**Comment by cchristopherhowardd** [comment]
That seems fine to me, but I wonder how that would affect how . In the example below, if Lynne Lancaster's lecture was tagged as ```Zoom Video``` as ```event_series``` instead of ```event_type```, then the output on the page would read only as ```Zoom Video``` and leave ```Lecture``` off the page. That's how it works for the Nirenberg/Shalem conversation, which has a ```Conversations/Conversazioni``` as the ```event_series``` which means that the ```event_type``` for ```Conversation``` is left off the page. Does that make sense?

<img width="1363" alt="Screen Shot 2021-01-25 at 4 02 18 PM" src="https://user-images.githubusercontent.com/38765846/105766102-520ed880-5f27-11eb-8314-35f42bc63506.png">


Is a better solution creating a feature similar to ```promote to homepage``` where all you do is check a box for ```promote to Zoom Video page``` and it's done?

**Comment by jasloe** [comment]
I see what you mean. 

> Is a better solution creating a feature similar to `promote to homepage` where all you do is check a box for `promote to Zoom Video page` and it's done?

Yes, that was my next thought!

**Comment by cchristopherhowardd** [comment]
Marques wants to change the name of the section from Zoom Videos to Watch, which is fine by me. That would mean the section's URL goes from aarome.org/events/zoom-videos to aarome.org/events/watch. We can still use Zoom Video as a categorical term to route information to the page, as we discussed yesterday.

**Comment by jasloe** [comment]
Sounds good. Trying to wrap this up this afternoon. Our office internet connection just came back so post to production may be after 6 pm.

**Comment by jasloe** [comment]
Do you still want to display "Zoom Talk"? 

> But now, would like a node to be presented as like the following, so that the event type Zoom Talk is published but event type Conversation is not:
> 
> Conversations/Conversazioni
> Zoom Talk

**Comment by cchristopherhowardd** [comment]
No, it's no longer important to display it.

**Comment by jasloe** [comment]
I'm going to output all event series and event types for the time being and push that to staging for discussion.

**Comment by jasloe** [comment]
Seems like a good time to revisit this in toto. 

Looking at staging.aarome.org, this is the current template logic for event/* indices and nodes.

```
		{% if content.field_events_event_series|render is not empty %}
			{{ content.field_events_event_series }}
		{% else %}
			{{ content.field_events_event_type }}
		{% endif %}
```

In English, print series if series exist; if series is empty, print type. 

So it seems like we need to just move Zoom video to event series and that's that. (We also need to remove Lecture from event series as it already exists in event type.)

Reminder that event type exists as a backstop if there's no event series. It also (and importantly) supports search filtering.

**Comment by cchristopherhowardd** [comment]
> (We also need to remove Lecture from event series as it already exists in event type.)

You caught me cheating. Well, I was experimenting by adding Lecture, Exhibition, and Conference as event_series. I wasn't happy with the template logic. For instance in this event, the event_series THE CITY overrode the event_type LECTURE, and I want both to appear.

<img width="499" alt="Screen Shot 2021-01-27 at 5 33 35 PM" src="https://user-images.githubusercontent.com/38765846/106063328-00508480-60c6-11eb-84d8-ec3d5f667688.png">

**Comment by jasloe** [comment]
I'd like to work on fleshing this out a little bit if you're interested. Printing "The City" or "Encounters" doesn't really convey any information. How about printing "Part of the {{ content.field_events_event_series }} lecture series" or "Part of the {{ content.field_events_event_series }} conference"? Would consolidate the event series and lecture in a single statement and clear up ambiguity. The event series tag could also send the user to a dedicated page for the event series page with a brief series précis and the corresponding list of events.

**Comment by jasloe** [comment]
Meantime, cloned https://staging.aarome.org/events/watch config and posted to https://staging.aarome.org/society-of-fellows/watch.

Let me know if you have a translation for "watch" and whether any final changes to */watch indices.

**Comment by jasloe** [comment]
Posted to production. 

/events/watch 
/society-of-fellows/watch

Pending #376 and content and vocabulary wrangling, this is ready for production. A fix for #376 is in the works.

**Comment by cchristopherhowardd** [comment]
Thanks. I'll review these early next week. I'm neck deep in a couple of other projects today....

**Comment by jasloe** [comment]
No rush. There's a lot of configuration and stylesheet changes afoot and I
didn't want production to trail behind too much.

**Comment by cchristopherhowardd** [comment]
> So it seems like we need to just move Zoom video to event series and that's that.

I deleted Zoom Video as an event_type and added it as an event_series. The Watch page ( https://www.aarome.org/events/watch ) is now blank, of course.

I don't feel this is a good solution. Didn't we agree last week that it would be best if nodes could be added to the Watch page if some kind of selection was made [e.g., a check box] instead of having the event_type or event_series be Zoom Video?

**Comment by cchristopherhowardd** [comment]
> Let me know if you have a translation for "watch" and whether any final changes to */watch indices.

Use /guardare

**Comment by jasloe** [comment]
I alluded to this above but to clarify, the checkbox approach won't work with search. Since we're settled on using the ```event_series``` term, we're all set. The view and node template needs a revision to support ```event_series``` instead of ```event_type```. I'll get started on that this afternoon.

**Comment by jasloe** [comment]
https://www.aarome.org/events/watch now shows all events tagged with Zoom Video. 
https://www.aarome.org/events/calendar does not show Zoom Videos. It can if needed but maybe seems noisy to me?

If ok, will also post to SOF view.

**Comment by jasloe** [comment]
Note: production stylesheets are trailing staging by a few commits, so you'll see the wrong arrow type at /events/watch until I get them merged.

**Comment by cchristopherhowardd** [comment]
> https://www.aarome.org/events/calendar does not show Zoom Videos. It can if needed but maybe seems noisy to me?

The Calendar page, as the master list of all AAR events, should still display all of these events, with the Main Image (as opposed to the Zoom Image).

I'm not sure what you mean by noise. Are you referring to ZOOM VIDEO as event_series?

**Comment by jasloe** [comment]
Ok, main calendar shall **all** events, including Zoom videos with main image instead of Zoom image. Will merge stylesheet shortly and /guardare translation shortly.

**Comment by cchristopherhowardd** [comment]
Is the Watch/Guardare section ready for integration into the Events section?

The discussion over events_series and events_type and how that information renders on pages can take place in another issue. 

The Society of Fellows video page (https://www.aarome.org/society-of-fellows/watch) is still in progress, mainly because we don't have an example ready for testing. I see that I can add Zoom images and links to SOF pages ( https://www.aarome.org/node/add/society_of_fellows ), but there aren't fields for dates, event_location, and stuff. I'll create an SOF Zoom - New York event location in a few minutes.

**Comment by cchristopherhowardd** [comment]
For the Events section page, I envisioned the Watch block to appear after Calendar and before Exhibitions. The photo can be the screenshot of A. O. Scott and Garrett Bradley. 

![zoom-scott-bradley](https://user-images.githubusercontent.com/38765846/106797916-3e502a00-662b-11eb-9040-85c2fca68dba.jpg)

**Comment by jasloe** [comment]
Pushed to production. 

https://www.aarome.org/events/watch
https://www.aarome.org/it/eventi/guardare

You can edit the "Watch" node at https://www.aarome.org/node/5616/edit.

When that's done, I'll change permissions so anonymous visitors can see the new views.

**Comment by jasloe** [comment]
> Use /guardare

"Watch" and "Guardare" already appear in footer menu which sends user to Livestream. Change that to "Livestream Archive"?

**Comment by cchristopherhowardd** [comment]
I added English and Italian summaries to Watch and Guardare, so the section can be debuted. I'll probably edit them very soon, but what's there is good for now.

Yes, the old "Watch" becomes "Livestream Archive." The new order is:

Calendar
Watch
Exhibitions
Livestream Archive

Calendario
Guardare
Mostra
Archivio Livestream

**Comment by jasloe** [comment]
Published. 

One other note: the Zoom Events at /events/calendar should have the upward pointing error. I have some code that fixes that in the hopper.

**Comment by jasloe** [comment]
Realize that the upward pointing arrow doesn't make sense here since the event card points to an event description, not an external URL. Closing.

> Published.
> 
> One other note: the Zoom Events at /events/calendar should have the upward pointing arrow. I have some code that fixes that in the hopper.
