### ISSUE TITLE
New development page in the Support section 

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#392]
Development wants to split the Membership page ( https://www.aarome.org/support/join-renew ) into two pages, which I think is a good idea. This requires changing the name of Memberships to Individuals while also changing the end of the URL to /individuals. The Italian page will be /individui.

It also means adding a new box to https://www.aarome.org/support that is called Institutions. I've already created the Institutions page at https://www.aarome.org/support/institutions. The node ID is 5582 ( https://www.aarome.org/node/5582/ ). The Italian page is https://www.aarome.org/it/sostegno/istituzioni.

The box item for Institutions can be placed after Individuals (formerly Memberships) and before McKim Medal Gala.

<img width="1322" alt="Screen Shot 2021-01-19 at 11 56 14 AM" src="https://user-images.githubusercontent.com/38765846/105067395-a3adf380-5a4d-11eb-907e-4075d4cdd273.png">

**Comment by cchristopherhowardd** [comment]
I've already changed the name of the Memberships page to Individuals and Individui and updated the URLs.

**Comment by cchristopherhowardd** [comment]
I've also created and moved content to the new pages https://www.aarome.org/support/institutions and https://www.aarome.org/it/sostegno/istituzioni.

**Comment by jasloe** [comment]
Applied directly changes to production for expediency. Let me know if ok and close.

**Comment by jasloe** [comment]
Fixed footer menu.

/support/join-renew will automatically redirect to /support/individuals. Would you prefer the old URL redirect to /support instead?

**Comment by cchristopherhowardd** [comment]
Looks fine. The names of the pages may change (such as Individuals --> Individual Giving), but I don't expect that to change the underlying structures. I'd like to see Individuals and Institutions in the number 3 and 4 spots on the section page, and McKim Gala and Virtual Benefit/NY Gala as 5 and 6, but there's no front runner for the number 2 spot.

**Comment by cchristopherhowardd** [comment]
The footer--yes, and thank you. If necessary, support/join-renew can redirect to /support/individuals, but I don't know where that would happen. In other words, I don't know if any place on the AAR site links to support/join-renew.

**Comment by jasloe** [comment]
Footer is fixed. 

Re: direct, It's more about links in the wild that connect to the old path. Made change to redirect to /support. 

Anything else?

**Comment by cchristopherhowardd** [comment]
The Institutions box disappeared from https://www.aarome.org/support. Can you put it back?

**Comment by cchristopherhowardd** [comment]
I'm reopening this because there are changes to the Support section of the footer, due to the renaming of a few pages.

Individuals --> Memberships
Individui --> Membri

Institutions --> Member Institutions
Istituzioni --> Istituzioni Membri

2020 Virtual Benefit --> New York Gala/Virtual Benefit
Beneficio Virtuale 2020 --> New York Gala/Beneficio Virtuale

**Comment by jasloe** [comment]
Posted.
