### ISSUE TITLE
Donation features

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#395]
AAR's development team is keen on making it easier for people to donate through our website. They want to know how feasible it is to create something (a box, a form, a pop-up, etc.) that might appear on most or all AAR webpages. The question is open ended regarding what this would look like, where it would appear, how it would function, and so on.

We used Donorbox for the Virtual Benefit last year, which worked well. People were making donations well after the event--I think one gift was made in early January 2021. Another possibility is something called DAF Direct ( dafdirect.org ), which appears to be a widget ( dafdirect.org/about-daf-direct/index.html ) that can be tacked onto a website.

I think what might make development happy is a creatively designed box or button that could be inserted in a visible location. When a website visitor clicks on the box or button, the donation form appears. Compatibility with phones, tablets, and laptops/desktops is desirable, of course.

This project is near term--not immediate but not six or eight months from now. A slow, considered approach seems to be in order. Development is aware that we'll concurrently use the present donation system, hosted by NetCommunity and Raiser's Edge (e.g., pages like support.aarome.org and support.aarome.org/McKimMedalGala ) until that platform can be rebuilt, which is another project on its own. In other words, this would be a special project with a budget line separate from the main AAR website and related tasks. Development is aware that a redesign includes not only the webpages but also the accompanying acknowledgment emails--all of which function the way they should but look out of date.

The short-term goal, I think, is to create a way in which people can easily donate to AAR with just their name, email, and credit card information (or via PayPal or whatever), instead of using the long forms like that at support.aarome.org.

**Comment by jasloe** [comment]
In terms of dropping a third-party form into a node template, any of these integration points are pretty straightforward, as long as we use which third-party's transaction processor widget. You mentioned PayPal and DonorBox and both provide capable widgets with a handful of cosmetic customization options. As such, this is something that I could do under general monthly maintenance. If it turns out there's an unusual volume of volleys on page placement and styling or some other requirement either of us aren't aware of, I can convert it to a separate line-item project.

Regarding RE, are you disbanding RE altogether?

**Comment by cchristopherhowardd** [comment]
As far as I know, we're not disbanding Raiser's Edge. I'll have to ask development for more information. A new vice president for development started last October, and it seems like she's reviewing current procedures and seeking improvements.

**Comment by jasloe** [comment]
Ok. The current RE/NC implementation is an artifact of a time (>10 years ago) when transactions couldn't be easily (or safely) handled with third-party processors. My unsolicited advice is to move the donation forms into Donorbox or PayPal or something else and embed their form into a node page. That would obviate the need to roll out a new series of NC pages. If using Donorbox, [looks like you can readily export user data from DB into RE](https://donorbox.zendesk.com/hc/en-us/articles/360032811032-How-to-Export-Donorbox-Data-into-Raiser-s-Edge). Only other thing left would be newsletter sign-ups and there a lot of relatively frictionless ways to handle that.

None of this is particularly "technical"...more of an operations/process issue. Happy to discuss further as needed.

**Comment by cchristopherhowardd** [comment]
This issue is paused. Development isn't currently pursuing a widget for Donorbox ,PayPal, or Direct DAF for the Support section. I've noted your recommendations and will certainly keep them in mind. I would much rather see that implemented than roll out new NetCommunity pages.
