### ISSUE TITLE
Tune up image padding for images embedded in page sections

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#396]
I'm working on a webpage for the Patrons group (in the Support section of the website) and noticed that hyperlinks in the bullet points don't have an underline. Is there something in the code that prevents hyperlinks in < ul > and < il > from having underlining?

The page is https://www.aarome.org/support/patrons and the node is 5613.

In particular is the section Patron Events, where I link to People pages throughout. On the page you can see various links in the running text, but nothing for bullet lists. I tested the theory by creating hyperlinks in the Tiers section of the page, and sure enough, no underline.

**Comment by jasloe** [comment]
Pushed fixed to prod. Also, I added the bulleted list widget to the editor (which will save you the trouble of hand coding the elements). Changing this ticket name as I think the inline image padding could use a tune up.

**Comment by jasloe** [comment]
Closed in favor of #397.
