### ISSUE TITLE
New blocks for Support section

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#397]
I have a new webpage for the Support section, called [Ways to Give](https://www.aarome.org/support/ways-to-give). A block for this page needs to be created on the [Support index page](https://www.aarome.org/support), to be placed at the very top, before Annual Fund.

**Comment by cchristopherhowardd** [comment]
I am working on another page, [Patrons](https://www.aarome.org/support/patrons), but am not sure where it will be placed. It's possible that a secondary index page in the Support section will be requested, to gather Patrons, Friends of the Academy, and Friends of the Library.

Related to Ways to Give above, a line and link should be added to the site footer. Ways to Give in English, Modi per dare in Italian.

**Comment by jasloe** [comment]
Pushed to production.

**Comment by cchristopherhowardd** [comment]
Development would like to see the new index page for Memberships, a secondary index page that lives within [Support](https://www.aarome.org/support). This new index page would take the URL https://www.aarome.org/support/memberships. which is already an existing page. The idea is that the Memberships box on the main Support page would link to the secondary index page containing these three items:

Patrons: https://www.aarome.org/support/patrons
Friends of the Academy: https://www.aarome.org/support/friends-academy (placeholder page that I created today).
Friends of the Library: https://www.aarome.org/research/library/friends (which is already a part of the sub-index page for the [Library](https://www.aarome.org/research/library), there at the very bottom)

I recognize that URLs for the three above pages may change (e.g., Patrons might end up as https://www.aarome.org/support/memberships/patrons), but for right now, these are the three pages that form the Memberships index page. Development needs to flesh out the Friends of the Library page and decide what to do with the Friends of the Library page.

**Comment by jasloe** [comment]
Sure, I'll park the work-in-progress at /support/memberships-new. Have that for you this afternoon.

**Comment by jasloe** [comment]
Here's the basics: https://www.aarome.org/support/memberships-new

Let me know when the rest of the content is ready and/or if there are any changes.

We can make url aliases for each of these nodes in the node configuration when ready for production.

**Comment by cchristopherhowardd** [comment]
This may be a separate issue, but I'm winging it with inline photos on the [Patrons](https://www.aarome.org/support/patrons) page, as Development has requested. As you can see here, these GIFs are hosted offsite (on AAR's [Amazon AWS site](https://s3-eu-west-1.amazonaws.com/cdn.aarome.org/html-emails/images/patrons-events.gif) where the email blasts live). 

The captions are jerryrigged, too, using an < h4 > and < br / > tags. There ought to be a little less space between the bottom of the photo and the caption.

Few AAR webpages have these inline images. Apart from the For the Ages page, I can think of this unused page for [Support Opportunities](https://www.aarome.org/support/support-opportunities). On the Patrons page, the inline images appear at the top of the Page Section. On Support Opportunities, they're placed within the running text. Images on neither page are web responsive, meaning they don't collapse fully on the narrowest view ports.

**Comment by cchristopherhowardd** [comment]
Is the link to the [new Memberships index page](https://www.aarome.org/support/memberships-new) visible to someone not logged into AAR Drupal? I'd like to share the link with mu colleague Ilana.

**Comment by jasloe** [comment]
Changed permissions. Try it now.

https://www.aarome.org/support/memberships-new

**Comment by jasloe** [comment]
Yeah, there's an open ticket for this at #396. I don't think I can get to this today. Unless it's super important, I can triage this tomorrow.

> This may be a separate issue, but I'm winging it with inline photos on the [Patrons](https://www.aarome.org/support/patrons) page, as Development has requested. As you can see here, these GIFs are hosted offsite (on AAR's [Amazon AWS site](https://s3-eu-west-1.amazonaws.com/cdn.aarome.org/html-emails/images/patrons-events.gif) where the email blasts live).
> 
> The captions are jerryrigged, too, using an < h4 > and < br / > tags. There ought to be a little less space between the bottom of the photo and the caption.
> 
> Few AAR webpages have these inline images. Apart from the For the Ages page, I can think of this unused page for [Support Opportunities](https://www.aarome.org/support/support-opportunities). On the Patrons page, the inline images appear at the top of the Page Section. On Support Opportunities, they're placed within the running text. Images on neither page are web responsive, meaning they don't collapse fully on the narrowest view ports.

**Comment by cchristopherhowardd** [comment]
The images/caption issue isn't urgent for today.

**Comment by jasloe** [comment]
I just pushed a config change to the text editor. You'll see an image icon in the toolbar. You can use that to upload and embed images in running copy. Click the image icon to insert an image. Select the caption checkbox and, following save, you'll see a "enter caption here" prompt below the image. The image and caption will be wrapped in appropriate tags, ```figure``` and ```figcaption```, respectively. Let me know if that works for you.

**Comment by cchristopherhowardd** [comment]
I was able to upload two GIFs and their captions to the [Patrons page](https://www.aarome.org/support/memberships/patrons) with great success. The photos look big to me on a 15 inch laptop, but they look better when the screen size is reduced. I wonder if the images would scale better if they fell a few pixels short of the full width of the column for body text.

**Comment by jasloe** [comment]
Pushed fix for inline images. Width at 80% for full screen; 100% at lower screen ratio. 

Let me know when ok to make /support/memberships-new public.

> I was able to upload two GIFs and their captions to the [Patrons page](https://www.aarome.org/support/memberships/patrons) with great success. The photos look big to me on a 15 inch laptop, but they look better when the screen size is reduced. I wonder if the images would scale better if they fell a few pixels short of the full width of the column for body text.

**Comment by cchristopherhowardd** [comment]
Can you add just a little more padding (space) between the inline photo caption and the start of the running text. I feel like there's good spacing at the top of the photo, but the bottom is a little cramped!

<img width="889" alt="Screen Shot 2021-03-04 at 2 56 20 PM" src="https://user-images.githubusercontent.com/38765846/110022896-7e71fd80-7cfa-11eb-878a-3f2ed11bf7f4.png">

**Comment by cchristopherhowardd** [comment]
New request for the [Support index page](https://www.aarome.org/support): swap the boxes for Ways to Give and Corporate. The change should also be made in the website's footer.

**Comment by jasloe** [comment]
All set.

**Comment by jasloe** [comment]
Ok, all set. Please test and close.

**Comment by jasloe** [comment]
Oops one second. Forgot something.

**Comment by jasloe** [comment]
Ok all set.
