### ISSUE TITLE
Updating aarome.org to Drupal 9, updating PHP to 7.4

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#399]
@cchristopherhowardd –– Drupal 9 came out in June of last year and is well into [dot releases](https://www.drupal.org/project/drupal/releases/9.1.4). There are no major data type, API, or dependency changes but several improvements to the update paths. Drupal 9 has a few additional server requirements and will necessitate a new server build. We'll need a content freeze for about four hours so that we don't miss any content in the migration to the new server.

I am at the tail end of updating a half-dozen other client projects and will work the Academy's site into the schedule next week (or whenever is convenient for you).

**Comment by cchristopherhowardd** [comment]
OK. Let me know when you'd like to do the content freeze, and I'll send the website to Texas.

**Comment by jasloe** [comment]
Finally (post-office move) getting back to this. A survey of modules and patches shows that there are ~25 projects that need update, apart from Drupal core itself. None of these updates appear particularly onerous and I'll set to work on this on Friday.

**Comment by jasloe** [comment]
@cchristopherhowardd –– Spent some time getting everything in order for the update to version 9. Only one (minor?) red flag: there's a module that controls per-user access to specific nodes. This functional requirement is driven by the library. They need to be able to edit some ```basic_pages``` and not have site wide editorial permission to *all* ```basic_pages```. 

I'm pretty sure [this](https://www.drupal.org/project/permissions_by_term) will work though it will require tagging library content. Not a major undertaking. The module has ~4,700 sites reporting use, so it seems to have fairly high adoption.

**Comment by jasloe** [comment]
As described [here](https://www.drupal.org/project/drupal/issues/3153455), content translations use a deprecated method and causes a fatal error. Dumped the configuration, manually updated the method in each *yml file, and reimported the configuration. 

```
core.base_field_override.media.basic_pages.uid.yml
core.base_field_override.media.file.uid.yml
core.base_field_override.media.image.uid.yml
core.base_field_override.media.people.uid.yml
core.base_field_override.media.publications.uid.yml
core.base_field_override.media.quick_news.uid.yml
core.base_field_override.media.video.uid.yml
core.base_field_override.node.page.uid.yml
core.base_field_override.node.quick_news.uid.yml
core.base_field_override.node.webform.uid.yml
```

```
default_value_callback: 'Drupal\node\Entity\Node:getCurrentUserId' changed to
default_value_callback: 'Drupal\node\Entity\Node::getDefaultEntityOwner'

default_value_callback: 'Drupal\media\Entity\Media::getCurrentUserId' changed to
default_value_callback: 'Drupal\media\Entity\Media::getDefaultEntityOwner'
```

**Comment by jasloe** [comment]
Post install clean up including resizing disk space and removing MariaDB binary logs.
