### ISSUE TITLE
Build 'events' data model.

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#4]

**Comment by jasloe** [comment]
In progress. @cchristopherhowardd, the Events content type is pretty well fleshed out here:

https://dev.aarome.org/node/add/events

From the top of the form: 

A language drop-down (default English, we may not even this since most [all?] content is created in English first, then translated)

Event title
Event type
Related places
Related people
Date and time
Documents (for uploading PDFs, etc.)
Links (for Livestream or other points of interest)

Up next, adding an image handler and a two-way relationship between events, people, and places. See #29.

**Comment by cchristopherhowardd** [comment]
After clicking the link, my browser tells me my access is denied. I am not authorized to view this page?

Chris
-------
Christopher Howard
Communications Manager

**Comment by jasloe** [comment]
Oh, right. Sorry. Need to set permissions for the "editor" role. Let me get back to you on that later this afternoon.

**Comment by jasloe** [comment]
@cchristopherhowardd, sorry (again) but did you login first?

**Comment by jasloe** [comment]
Oh shoot. Well, I'm away from the office most of the day and don't have my server keys handy. We'll pick it up tomorrow.

**Comment by jasloe** [comment]
Hi @cchristopherhowardd:

Here's a quick-and-dirty csv that shows the candidate migration content for the Events data type. 

Kind of mindnumbing to look at but you might want to briefly review it and call out any possible issues. 

Fields migrated include: 

Nid (node id, i.e. unique data identifier
Content Type
Title
Event Type
Event Date
Event Location
Name
Event Series
Body
Body (translated) 

Holding off on migrating images until we have art from Open. 

https://docs.google.com/spreadsheets/d/1cbsryPRr2EXPXHayplfPjSPeqmuzTLa1sDRBqSiRvJ4/edit?usp=sharing

**Comment by jasloe** [comment]
@cchristopherhowardd Migration for events is complete, excepting images as described above. 

Checklist of migration scripts here: https://github.com/aarome/aarome/wiki/Migration-pattern-for-public-site-records

Moving the images issue over to #38 and closing this issue.
