### ISSUE TITLE
2021 Residents

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#401]
Can you make the default view of the [Residents](https://www.aarome.org/people/residents) page be [2021](https://www.aarome.org/people/residents?field_affil_discipline_target_id=All&field_affil_year_target_id=1037) instead of 2020?

Relatedly, can you have the homepage slideshow for Invited Residents draw from 2020 and 2021? Right now it shows 2019 and 2020.

**Comment by jasloe** [comment]
Both done.

**Comment by cchristopherhowardd** [comment]
Thanks!
