### ISSUE TITLE
Society of Fellows News in Publications

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#402]
I'd like to add a _Society of Fellows News_ page to the [Publications](https://www.aarome.org/publications) section. The page would operate like other Publications pages but would most resemble the _[AAR Magazine](https://www.aarome.org/publications/magazine)_ page. A couple of months ago Sebastian mentioned that he used to refer people to these publications, so it's important to add them back to the AAR website. ([Here is where they lived](https://old.aarome.org/people/alumni/sof/archive) on the old AAR website.)

There are thirteen issues of _Society of Fellows News_, published between 2001 and 2009, that I've created English and Italian pages for. The main node is [68](https://www.aarome.org/node/68/edit?destination=/admin/content). For the taxonomy, the [publication type](https://www.aarome.org/admin/structure/taxonomy/manage/publication_types/overview) is Society of Fellows News.

**Comment by cchristopherhowardd** [comment]
On the [Publications](https://www.aarome.org/publications) section page, we can place Society of Fellows News last, after Cookbooks.

**Comment by jasloe** [comment]
Something like this? 

https://www.aarome.org/publications/society-of-fellows-news

**Comment by cchristopherhowardd** [comment]
Exactly like that!

**Comment by cchristopherhowardd** [comment]
I noticed that, when creating the pages for each issue, names that have hyperlinks (to a person's People page) don't get the underlined treatment. Can you style the pages so that hyperlinks are underlined?

**Comment by jasloe** [comment]
Pushed anchor link fix. 

What is the translation for */society-of-fellows-news and "Society of Fellows News"?

**Comment by cchristopherhowardd** [comment]
A URL with /pubblicazioni/notizie-society-fellows is fine, taking out the prepositions.

The footer in Italian can be: Notizie della Society of Fellows

**Comment by jasloe** [comment]
Updated menu items. Please test and close.
