### ISSUE TITLE
Reorder blocks on Support page

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#403]
Development has a new preferred order of blocks on the [Support index page](https://www.aarome.org/support).

Annual Fund
Memberships 
Corporate
Planned Giving
McKim Medal Gala
New York Gala/Virtual Benefit
Ways to Give
Member Institutions 

Changes would apply in the footer, too.

**Comment by jasloe** [comment]
All set. Please test and close.

**Comment by cchristopherhowardd** [comment]
Looks good, thanks. I appreciate getting this done today--I know you're busy with the other project.

**Comment by jasloe** [comment]
No problem!
