### ISSUE TITLE
Annual Fund Pop-up

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#404]
Development is interested in a pop-up for the Annual Fund. By pop-up I mean a notice that appears onscreen when someone is visiting aarome.org. We already have the GDPR notice when visitors first come to the site. Is it possible to add another one?

We can't do away with the GDPR notice, so could an Annual Fund pop-up appear when someone visits a third or fourth page at aarome.org? Can it appear on some pages/sections and not others?

**Comment by jasloe** [comment]
Pop-up can stack above cookie notice. Or as a separate pop-up on any page. Yes, can be restricted to a subset of pages.

**Comment by cchristopherhowardd** [comment]
Is it possible to set the Annual Fund pop-up to appear on, like, the third or fourth page a person visits? Or pops up after 60 or 90 seconds of being on the site? I don't think the appeal and the cookie notice should appear at the same time.

**Comment by cchristopherhowardd** [comment]
Development is inquiring about this again. Do you know if the possibilities I ask about above are possible?

**Comment by jasloe** [comment]
Huh, thought I replied to this one. Yes, everything is possible!

**Comment by cchristopherhowardd** [comment]
I have a little more information about this. Development prefers a small box in the lower left or right corner to pop-up after 60 to 90 seconds on the site. The text in the box should read "Support the Academy today" and it should link to https://support.aarome.org/. The text will most surely change as the draft pop-up is reviewed. An X-to-close button should be part of the functionality.

The pop-up would appear in these sections:

/about
/people
/news
/events
/publications
/support

And not these:

/apply
/research
/society-of-fellows

Does Google Analytics track how many times a visitor clicks the X-to-close? Does it count how many click the link to the Annual Fund page? AAR's NetCommunity platform doesn't 

I did some reading about pop-ups and interstitials and learned that they're actually highly effective even though people hate them. I learned that Google tends to diminish a website that uses pop-ups, too, so it seems they should be used sparingly.

Developers tend to turn off pop-ups for mobile platforms. Is this possible for aarome.org?

As far as the design, I don't have clear direction from development. Using house fonts and general website style makes sense, but what that looks like graphically I can't say. I'll browse the internet today and tomorrow and try to find something that we could emulate. If you have any ideas, I'd appreciate hearing them.

**Comment by jasloe** [comment]
Quick note to distinguish between modal windows and pop-ups. A modal window appears in the context of the parent HTML document; a pop-up appears in a separate frame and as a separate HTML document. I'm assuming you want a modal window, functionally similar to the current cookie notice. 

Google does discourage pop-ups for a number of reasons though they do not penalize sites that use modals. A modal on a mobile site is perfectly acceptable.

Yes, GA can easily track user actions including button clicks. 

According to GA, the average time on the site over the last year is 1'05". So I think you'd want the modal to appear in the first 15-30 seconds. 

Any thoughts on #395? This would be a good time to revisit the issue.

**Comment by jasloe** [comment]
> Let's go with a modal window, which **is** the donation feature in #395, for all screens. Should we combined #395 and #404?

#395 tracks discussion for a payment processor form integration, which is now tabled. So let's leave that open and separate for now even though it's indefinitely postponed.

I can start with the functional work probably tomorrow and the design implementation can follow whenever.

**Comment by jasloe** [comment]
@cchristopherhowardd –– When the modal appears it registers a cookie in the visitor's browser. The cookie can expire when the user closes their browser. The modal will appear again the next time they visit the site. Alternately, the cookie can expire after a period of time, say, 3 days. During that period the modal won't appear. Any thoughts?

**Comment by cchristopherhowardd** [comment]
A three-day waiting period sounds good. I wouldn't want to annoy certain regular users of the website (e.g., staff members).

**Comment by jasloe** [comment]
I can definitely turn it off for logged in users. And possibly by IP address? Not sure about that.

**Comment by jasloe** [comment]
There's also a way to do something like this:

Show popup on users each visit
Show popup on users first and second visit
Show popup on users first, forth and seventh visit

And so on. 

We could even do a Fibonacci series.

**Comment by cchristopherhowardd** [comment]
I wasn't thinking about logged-in users, but rather staff members who go on the website to look up things. Development folks, people in Rome. 

I think the every three days is a good solution.

**Comment by jasloe** [comment]
If the visitor enters the site through /about/mission or /people/rome-prize-fellows does the modal appear? Or only on the following index pages?

/about
/people
/news
/events
/publications
/support

**Comment by jasloe** [comment]
The functional part of this is done. Working on Google tagging now. Is there copy and a design available?

**Comment by cchristopherhowardd** [comment]
The copy is: Support the Academy today
The link is: https://support.aarome.org/

There is no design other than the words themselves. I imagine that we can use one or both of the AAR website fonts at a larger size.

**Comment by cchristopherhowardd** [comment]
> If the visitor enters the site through /about/mission or /people/rome-prize-fellows does the modal appear? Or only on the following index pages?
> 
> /about
> /people
> /news
> /events
> /publications
> /support

The modal would appear on both the index pages and any page within those sections. So yes, being on /about or /about/mission or /about/staff would all trigger the modal.

**Comment by cchristopherhowardd** [comment]
We need a translation for the /it pages. 

Let's go with: Sostieni l’Accademia oggi

**Comment by jasloe** [comment]
staging.aarome.org
staging.aarome.org/it

Working on replacing the close ('x') button. 

The link spawns a new window at the moment. This can be disabled, of course.

**Comment by jasloe** [comment]
Also note that for testing purposes, the modal will appear every time a visitor enters the site. I'll reconfigure with the desired frequency on production.

**Comment by jasloe** [comment]
Just noticed a bug on /admin pages. The modal briefly flashes and prevents logged-in user from scrolling. Will investigage.

**Comment by jasloe** [comment]
Looks like I'm going to have to write a small custom library to support event tracking. Won't take long; it's just two handlers, one each for the close button and support link. While I'm in there, do you to track any other links for development? Thinking of the buttons here: https://www.aarome.org/support/ways-to-give. Would be a good way to begin measuring their effectiveness.

**Comment by jasloe** [comment]
I went ahead and configured GA to capture all internal links as well as outbound links to support.aarome.org/*. I wanted to learn the new Google Tag Manager and this was a good opportunity. Still trying to figure out how to track the 'x' (close) button but should have something working soon.

**Comment by jasloe** [comment]
Popup will be temporarily unavailable while I merge this feature with work on #330.

**Comment by cchristopherhowardd** [comment]
OK. In the meantime, is there something I can show the development folks? A screen shot or partially functioning modal on the staging site?

**Comment by jasloe** [comment]
It's there now.

**Comment by jasloe** [comment]
Just noticed the modal doesn't close after the link is clicked. Will roll a patch in the morning. 

Given the prominence of the modal, it seems like a contribution from Open is in order. I have my own ideas but would rather defer to the house shop.

**Comment by cchristopherhowardd** [comment]
The modal closes for me, so it looks like the patch worked!

I had thought about having Open make a contribution but decided against it. 

For the current modal, can you add a sentence under the existing phrase, but in a smaller (or different) font? The sentence is: Make a donation to the Annual Fund

The word "donation" should be a hyperlink using an underline, so that people know it's a link.

**Comment by jasloe** [comment]
Ok, will post changes along with #375.

A couple of other minor quibbles. Putting the modal in the main content region interferes with the main content style sheet. Note the collapsed space between the bottom two tiles: http://staging.aarome.org/events Have a fix for this that'll go up tomorrow by mid-day. 

> The modal closes for me, so it looks like the patch worked!

The x does close the modal but when the outgoing link to the support site is clicked, the modal should close. Ditto post tomorrow.

**Comment by jasloe** [comment]
> For the current modal, can you add a sentence under the existing phrase, but in a smaller (or different) font? The sentence is: Make a donation to the Annual Fund
> 
> The word "donation" should be a hyperlink using an underline, so that people know it's a link.

Updated text and link on staging.

**Comment by cchristopherhowardd** [comment]
Looks good. 

Was there a problem with having SUPPORT THE ACADEMY TODAY be a link? I liked how it was in the previous version, with the letters changing to gray when hovering the cursor over them.

**Comment by jasloe** [comment]
No problem. Thought the "donation" text superseded it.

**Comment by jasloe** [comment]
> Was there a problem with having SUPPORT THE ACADEMY TODAY be a link? I liked how it was in the previous version, with the letters changing to gray when hovering the cursor over them.

Fixed on staging. 

Forgot to mention that I put some extra time into this so that, in the future, modals are easy to spin-up and get into production.

**Comment by cchristopherhowardd** [comment]
Thanks. Should I expect an invoice from you soon?

**Comment by cchristopherhowardd** [comment]
Can you please change the primary phrase from "Support the Academy today" to "Support the AAR today" and also make "AAR" a different color? It seems like #f26641 would be a good choice.

**Comment by jasloe** [comment]
Pushed to staging.

> Can you please change the primary phrase from "Support the Academy today" to "Support the AAR today" and also make "AAR" a different color? It seems like #f26641 would be a good choice.

**Comment by cchristopherhowardd** [comment]
Looks good. One thing that I noticed on staging is that if I close the modal and navigate to another AAR webpage, the modal appears again. This happens every time I go to a new page.

**Comment by cchristopherhowardd** [comment]
Here is the view of the modal on an iPhone 8 on Safari. In the vertical view, the X to close starts to go off screen. Can padding (or whatever) be added to bring in the X?

![iPhone 8 Safari Vertical](https://user-images.githubusercontent.com/38765846/113629005-c060cd00-9633-11eb-861a-03d86cc0fca8.PNG)

![iPhone 8 Safari Horizontal](https://user-images.githubusercontent.com/38765846/113629038-ceaee900-9633-11eb-80e5-e716a094a145.PNG)

**Comment by cchristopherhowardd** [comment]
I get the same view using Firefox on an iPhone 8. (My wife has the same phone, so I can't test the view on a different phone.)

![iPhone 8 Firefox Vertical](https://user-images.githubusercontent.com/38765846/113629246-26e5eb00-9634-11eb-8e43-54b7c546663f.PNG)

**Comment by jasloe** [comment]
> Looks good. One thing that I noticed on staging is that if I close the modal and navigate to another AAR webpage, the modal appears again. This happens every time I go to a new page.

> Also note that for testing purposes, the modal will appear every time a visitor enters the site. I'll reconfigure with the desired frequency on production.

**Comment by jasloe** [comment]
Hm...took a minute to figure out what was going on there but think I fixed it. The style sheet now sets the width to 90% of the browser width on smaller viewports. Let me know if that works for you.  

> I get the same view using Firefox on an iPhone 8. (My wife has the same phone, so I can't test the view on a different phone.)
> 
> ![iPhone 8 Firefox Vertical](https://user-images.githubusercontent.com/38765846/113629246-26e5eb00-9634-11eb-8e43-54b7c546663f.PNG)

**Comment by jasloe** [comment]
Modal now closes after user clicks either link to support.aarome.org.

**Comment by cchristopherhowardd** [comment]
The modal looks better on mobile now, thanks!

**Comment by cchristopherhowardd** [comment]
The Italian translation for "Make a donation to the Annual Fund" on http://staging.aarome.org/it is:

Fai una donazione al Fondo annuale.

That's with a sentence-ending period. Can you add a sentence-ending period to the English text, so that it's:

Make a donation to the Annual Fund.

**Comment by cchristopherhowardd** [comment]
Desired frequency after a person closes the x of the model: three days. So if I come to the site today (Thursday) and close it, the next time I'll see the modal is 72 hours later.

Is this done by IP address?

**Comment by jasloe** [comment]
Fixed. Note that custom blocks can be self-administered at http://staging.aarome.org/admin/structure/block/block-content. (Also note, I'm working on getting the sitewide notice that appears at the top of the page into the new regime.)

> The Italian translation for "Make a donation to the Annual Fund" on http://staging.aarome.org/it is:
> 
> Fai una donazione al Fondo annuale.
> 
> That's with a sentence-ending period. Can you add a sentence-ending period to the English text, so that it's:
> 
> Make a donation to the Annual Fund.

**Comment by jasloe** [comment]
That is correct. The cookie can be deleted after an arbitrary number of days. That can be combined with an optional visit count parameter, such as every first, second, and twentieth visit, i.e. the modal displays the first, second, and twentieth visit over the three day cookie session period. The cookie resets after three days and the routine starts over again. I don't know enough about marketing to know what's effective and what's not.

Also, we discussed a delay. Based on bounce rates and time per page, I recommend displaying the modal after just a few seconds. 

At the moment, the modal appears on every visit and appears after 3 seconds.

> Desired frequency after a person closes the x of the model: three days. So if I come to the site today (Thursday) and close it, the next time I'll see the modal is 72 hours later.
> 
> Is this done by IP address?

**Comment by jasloe** [comment]
This configuration is handled by cookie policies. IP address does not figure into the process (though it can, if needed: e.g. never show the appeal based on a user's IP address).

> Is this done by IP address?

**Comment by cchristopherhowardd** [comment]
The Italian translation of "Make a donation to the Annual Fund" is now:

Per contribuire al Fondo annuale con una donazione.

**Comment by jasloe** [comment]
Oops. Missed these! Sorry for the delay. 

Made change to text. Yes, to the frequency. I tested locally and it is working fine. Since there may be further content changes, it will appear on every visit (with a five second delay). I'll make the change to every first visit (with a three day cookie expiration) when we move to production.

**Comment by jasloe** [comment]
I'm going to go ahead and move this to production and disable the pop-up. Just FYI.

**Comment by cchristopherhowardd** [comment]
OK. I'm looking forward to seeing how it works on the live site!

**Comment by jasloe** [comment]
Should I release this? Or will there be more feedback from staff?

**Comment by cchristopherhowardd** [comment]
Why don't we wait until at least Monday of next week. I don't usually monitor aarome.org over the weekend.

**Comment by jasloe** [comment]
Ok, this is now installed and disabled on the live site. Let me know when you’re ready.

**Comment by cchristopherhowardd** [comment]
Sure, let's try it out.

**Comment by jasloe** [comment]
Sounds good. I’m a little tied up right now but will enable it this afternoon.

**Comment by jasloe** [comment]
I think this is working. This is what the cookie manifest looks like after nine visits (as indicated by '9' in the value column and spb_block-appeal row). This cookie expires in 3 days. The third row contains the GTag information for registering clicks and so on.

I also noticed that the EU cookie notice appeared in every user session. Meaning that the user visited the site, dismissed the notice, closed the browser then return to the site later....only to be greeted by the notice again. *Highly* annoying. Anyway, fixed that. Now the cookie is stored for 100 days.

**Comment by jasloe** [comment]
<img width="1489" alt="Screen Shot 2021-04-13 at 5 33 52 PM" src="https://user-images.githubusercontent.com/1063667/114627796-da2d9000-9c83-11eb-89b6-45f2b4e54361.png">

**Comment by cchristopherhowardd** [comment]
I thought the EU cookie notice was supposed to work that way.

**Comment by jasloe** [comment]
Visitors do not have to consent every time. Just once is enough.

> I thought the EU cookie notice was supposed to work that way.

**Comment by cchristopherhowardd** [comment]
Ilana from Development loves the modal. Shawn from Programs does not. That's because (1) he loathes pop-ups and (2) he is experiencing an aggressive modal. 

He is on a PC desktop in the office and writes that "currently the modal appears every time I visit the site AND every time I click on a new page during a session. So, for example, if I land on aarome.org and then visit four other pages, the modal pops up five times in just that one session. It's a very aggressive modal!!"

I don't have a PC to reproduce this experience. For me, the modal closes and doesn't reappear on Mac laptop using Firefox, Safari, and Chrome.

**Comment by cchristopherhowardd** [comment]
Relatedly, is it possible to close the modal by hitting the ESC key?

**Comment by jasloe** [comment]
I'll check it out. Yes, to the ESC key.

**Comment by jasloe** [comment]
Can you find out which browser Shawn is using? And, this is a long shot, is there any chance he is browsing in incognito/private mode?

**Comment by cchristopherhowardd** [comment]
He said he was experiencing the issue in both Chrome and Firefox. I just asked him about incognito/private.

**Comment by jasloe** [comment]
I'm able to replicate the issue on a virtual machine. Investigating.
