### ISSUE TITLE
Rome Prize ceremony mini-project

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#406]
A ticket to collect information on the RP ceremony, scheduled for 4/23 at 12 noon. Current plan is to replicate last year's benefit with new style direction provided by Open and text and assets provided by Academy staff.

Note that I have two other major projects hitting the street around the same time as well as travel that weekend, so it'd be good to get things rolling as soon as humanly possible.

**Comment by cchristopherhowardd** [comment]
It looks like the plan is to hold the Rome Prize Ceremony on Zoom ( https://us02web.zoom.us/webinar/register/WN_sctd-eDQThOoWmSq4WfmIA ), which would obviate the need to have a dedicated page. I imagine that the PRC video would be archived on YouTube. I should know more after an all-staff meeting later this morning, when Marques and Wendy present their update on the subject.

**Comment by jasloe** [comment]
Sounds good. Keep me posted.

**Comment by cchristopherhowardd** [comment]
One thing that I know we need for certain is the Rome Prize winners email announcement. [This is what we did](https://s3-eu-west-1.amazonaws.com/cdn.aarome.org/html-emails/html/072320-rome-prize-winners-italian-fellows.html) last year and Open will likely design something similar.

**Comment by jasloe** [comment]
Closing. Will pick up discussion on mailing in the mjml repo.
