### ISSUE TITLE
Website banner update

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#407]
The Library and Archives are reopening to the public next week. Can you change the text of the black banner at the top of the page to these?

The Library and Archives will reopen on April 14.

and

La Biblioteca e gli Archivi riapriranno il 14 aprile.

On April 14 we'll change them again. Exact wording to follow.

<img width="843" alt="Screen Shot 2021-04-06 at 10 17 50 AM" src="https://user-images.githubusercontent.com/38765846/113725634-80e0c200-96c1-11eb-8703-e4d685a04779.png">

**Comment by cchristopherhowardd** [comment]
New sentences and translations to be posted now:

The Library and Archives will reopen on April 14.
La biblioteca e gli archivi riapriranno il 14 aprile.

And to be posted next week:

The Library and Archives are open.
La biblioteca e gli archivi sono aperti.

**Comment by jasloe** [comment]
Posted.

**Comment by jasloe** [comment]
@cchristopherhowardd –– Still reopening tomorrow?

**Comment by cchristopherhowardd** [comment]
Yes.
