### ISSUE TITLE
Test cookie persistence on Windows/Chrome/FF

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#409]

**Comment by jasloe** [comment]
@cchristopherhowardd –– I am tested this on FF and Chrome on the latest Windows release. The cookie value is incrementing with each visit, as designed. 

There are two possibilities: 1) the user is browser in incognito mode or 2) the user's bandwidth is extremely constricted and the cookie doesn't load before navigating to the next page.

I'll wait for confirmation on the first prospect before proceeding with the second.

**Comment by jasloe** [comment]
![Screen Shot 2021-04-15 at 15 39 33](https://user-images.githubusercontent.com/1063667/114930171-b17fd480-9e02-11eb-9b23-e8153e9af29d.png)

**Comment by jasloe** [comment]
```spb_block_appeal``` shows a value of 4 after 4 page visits.

**Comment by cchristopherhowardd** [comment]
Shawn wrote "I'm not aware that I'm browsing incognito or in private mode. (I didn't even know that was an option.) Anyhow, my Chrome browser definitely knows who I am."

I'm not in the office to confirm myself that he's not incognito or private, but he would surely encounter similar problems on many other websites, no? He hasn't complained of that.

**Comment by jasloe** [comment]
I'm throttling the network down to 3G speeds (have hard time imagining users on anything slower) and unable to replicate. 

Next step is to ask Shawn to visit a few pages and inspect cookies for the domain.

Right click anywhere in the browser window + Inspect Element + Storage tab + Cookies (left hand column) + https://www.aarome.org (see screenshot above)

Ask him to take a screenshot of what is displayed.

The modal uses pretty generic javascript to execute cookie storage but it's possible he's on a deprecated browser that doesn't support some of its functions. Would be good to get his exact browser version and Windows edition, just to rule that out. That being said, he'd have innumerable problems with the site (and many other sites) if that were the case!

**Comment by jasloe** [comment]
Instructions above are for FF, by the way.

**Comment by jasloe** [comment]
Ok, I figured it out. If visitors don't consent to cookie storage, the appeal cookie won't get stored. I'll need a couple of hours to think about how to remedy that.

**Comment by jasloe** [comment]
This is all set now. To test, simply dismiss the appeal modal and visit another page.

**Comment by cchristopherhowardd** [comment]
Shawn writes "Yes, it seems to be fixed. Yay!!!"
