### ISSUE TITLE
Arbitrary absence of YouTube embed

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#411]
I have had no problem embedding YouTube videos to Event webpages, except on two occasions. 

The embed is absent from this page posted today: https://www.aarome.org/events/calendar/christy-q-schirmer-paulette-marie-singley

The only other time this has happened was here: https://www.aarome.org/events/calendar/mary-t-boatwright-mia-fuller-colonial-cities-imperial-citizens

All other Event pages accept the YouTube coding. See for example:

https://www.aarome.org/events/calendar/2021-arthur-janet-c-ross-rome-prize-ceremony
https://www.aarome.org/events/calendar/rebecca-levitan-katy-barkan
https://www.aarome.org/events/calendar/a-o-scott-garrett-bradley

**Comment by cchristopherhowardd** [comment]
I posted another YouTube embed just now, and it works normally: https://www.aarome.org/events/calendar/corinna-gosmaro

**Comment by jasloe** [comment]
I took a quick look at the backend and the theme templates and didn't see anything obvious. I tried replicating on staging with no luck. Only thing I can think of is a screwy permissions issue on the production server. Reluctant to tinker with that while I'm away from the office. Ok to wait on this until I return?

**Comment by cchristopherhowardd** [comment]
OK to wait.

**Comment by jasloe** [comment]
Took some time to track down the exact issue. It looks like both of these embed URLs begin with a dash i.e.:

https://www.youtube.com/embed/-xrVtGMGqyA
https://www.youtube.com/embed/-a3pUYRuKBg

I wasn't able to find a similar issue in Drupal but Wordpress users are reporting a [similar problem](https://wordpress.org/support/topic/youtube-embed-problem-when-the-video-url-has-a-dash-character/).

The upshot is that the sanitization routines that occur when embedding content in text fields are too aggressive. Finding and overriding that function is going to take some time. A simple workaround is adding another link field to support the YouTube content.

**Comment by jasloe** [comment]
- [ ] Create new media type that supports remote video
- [ ] Add media field to page, event content types
- [ ] Migrate ```video_embed_field``` content in 5523, 5524, 5525, 5526 to core media field 
- [ ] Theme field output

**Comment by jasloe** [comment]
Added field that supports remote video to Events and Page content types. This field currently supports Youtube and Vimeo services. Youtube embed codes that begin with a dash render properly. Migrated Events and Page content from the old ```video_embed_field``` to the new field. [Page videos appear in the marquee region](http://aarome.dvm/the-collaborative-spirit) and [Events videos appear below the body copy](https://www.aarome.org/events/calendar/christy-q-schirmer-paulette-marie-singley).

**Comment by jasloe** [comment]
Livestream support can be added pending resolution of #413.

**Comment by jasloe** [comment]
Let me know if this can be closed. Livestream support is tracked at #413.

**Comment by cchristopherhowardd** [comment]
Can the /it/ pages have the phrase "Guarda il video" for the video embed? Two events this month have Italian translations. See https://www.aarome.org/it/eventi/calendario/la-citta-tracce-di-memoria-urbana for example?

**Comment by cchristopherhowardd** [comment]
Scratch that request. The vast majority of /it/ event pages with video are nearly completely in English. It would look more like an error to have 30 mostly English-language pages with "Guarda il video" than to have 3 Italian-language pages with "Watch the Video."

**Comment by jasloe** [comment]
Gotcha. I noticed that, too, and turned the label translation off. There's a per-node translation hook that can be wired up but I think that might be more bother than it's worth.
