### ISSUE TITLE
Alphabetical lists of events

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#414]
The list of Event Types isn't completely alphabetized at https://www.aarome.org/events/calendar and attempts to correct this in Taxonomy ("reset to alphabetical") aren't taking.

<img width="1000" alt="Screen Shot 2021-05-24 at 11 13 11 AM" src="https://user-images.githubusercontent.com/38765846/119368819-797d7400-bc81-11eb-9a72-87176622298b.png">

<img width="403" alt="Screen Shot 2021-05-24 at 11 15 48 AM" src="https://user-images.githubusercontent.com/38765846/119368852-84d09f80-bc81-11eb-84e7-c5f1fd540021.png">

**Comment by cchristopherhowardd** [comment]
The same thing is happening to the Italian page ( [](https://www.aarome.org/it/eventi/calendario) ), too.

![Uploading Screen Shot 2021-05-24 at 11.18.59 AM.png…]()

**Comment by jasloe** [comment]
Errrr...I thought I fixed that some time ago? I guess not! Checking it out now. Should be a quick fix.

**Comment by jasloe** [comment]
[This note](https://github.com/aarome/aarome/issues/327#issuecomment-794338451) documents an identical issue with library resource lists. Going through ```selective_better_exposed_filters``` module to see what broke, though it's still working on the library resource list pages.

**Comment by cchristopherhowardd** [comment]
I didn't think to check the library resources.

**Comment by jasloe** [comment]
I’ll need to compare the configuration of the two filters and modify the event type filter to bring it inline. I’ll take a look at this this evening and report back.
________________________________
