### ISSUE TITLE
Search form translations

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#416]
Need a handful of translations for search form elements. We're not using all of these but would be good to have on hand if we decide we need more interface tools.

Search|Cerca
Reset|
Refine results|
Sort by|
Asc| [abbreviation for ascending)
Desc| (ditto descending)
Previous|
Next|
First|
Last|
Items per page|
All results|
View more results|

**Comment by cchristopherhowardd** [comment]
This is what I came up with. I asked Lexi in Rome if she could make sure these are the right words, but I likely won't hear back until tomorrow morning.

Search | Cerca
Reset | Ripristina
Refine results | Perfeziona i risultati
Sort by | Ordina per
Asc | Asc (for Ascendente)
Desc | Disc (for Discendente)
Previous | Precedente (for Risultato precedente)
Next | Successivo (for Risultato successivo) - should this be Prossimo instead?
First | Primo (for Primo risultato)
Last | Ultimo (for Ultimo risultato)
Items per page | Oggetti per pagina
All results | Tutti i risultati
View more results | Visualizza più risultati

**Comment by jasloe** [comment]
Ok, let's see what Lexi comes back with. No rush.

**Comment by jasloe** [comment]
Great, I'll set them up. Thanks!
