### ISSUE TITLE
Exclude nodes from search indexing

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#417]
We need to exclude some nodes from the indexer. The cards on most index pages are nodes and we don't want to return these in search results as they do not have full page display modes. Their ids are:

```
1
2
4
10
15
19
25
26
32
35
41
44
45
50
52
54
55
56
57
57
58
59
61
64
66
68
70
1805
1809
1810
1814
1815
1827
2418
2421
2422
2423
2424
2430
2431
2431
2433
2434
2435
2444
2445
2446
2447
2448
2449
2450
2992
3262
3266
3271
3273
3275
3276
3277
3278
3279
3280
3283
3284
3285
3286
3298
3921
3922
3923
3925
3926
3927
3962
3963
3964
3965
3966
3967
3977
4000
4001
4002
4003
4559
5222
5498
5582
5616
5622
```

**Comment by cchristopherhowardd** [comment]
I think I noticed that earlier but didn't act on it. Good catch!

**Comment by jasloe** [comment]
This is done. If you need self-service for excluding nodes in the future, let me know and I'll open up the permissions for the site editor role.
