### ISSUE TITLE
Change of URL for PDF

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#418]
Can you create URL forwarder that sends people who click on

https://www.aarome.org/sites/default/files/filefield_paths/streetscapes.pdf

to this URL?

https://www.aarome.org/sites/default/files/filefield_paths/streetscapes_1.pdf

**Comment by cchristopherhowardd** [comment]
Even though I just deleted the file for https://www.aarome.org/sites/default/files/filefield_paths/streetscapes.pdf it seems like people can still download it. That's fine. It's just weird that I deleted it via Drupal and it's still available. For right now, that's good. I sent an email blast with that link, so I actually want it to be available for now.

<img width="1271" alt="Screen Shot 2021-05-31 at 12 32 27 PM" src="https://user-images.githubusercontent.com/38765846/120221564-a2b37c80-c20c-11eb-9983-a3b224af1372.png">

**Comment by cchristopherhowardd** [comment]
If you can't reroute the URL because it ends with .pdf, then as long as https://www.aarome.org/sites/default/files/filefield_paths/streetscapes.pdf works, we'll be OK. I thought I had deleted it permanently.

**Comment by cchristopherhowardd** [comment]
Hold this request. I've received an even more final PDF to post. I may just post the PDF to the Amazon CDN account, where email blast HTML and images are stored.

**Comment by cchristopherhowardd** [comment]
If it's possible, please route internet traffic from https://www.aarome.org/sites/default/files/filefield_paths/streetscapes.pdf to https://s3-eu-west-1.amazonaws.com/cdn.aarome.org/html-emails/pdf/streetscapes.pdf

**Comment by jasloe** [comment]
I manually replaced the file on the server, swapping out the file at filefield_paths with the file at S3.

**Comment by jasloe** [comment]
I've been using [this module](https://www.drupal.org/project/unmanaged_files) for a new project. Seems like we have ample use cases for deploying it to production.

**Comment by cchristopherhowardd** [comment]
The new module seems like a good idea. Rome sends me a new PDF for Friends of the Academy and Friends of the Library members every few weeks. See https://www.aarome.org/admin/content/files?filename=friends&filemime=&status=All&sort_by=fid&sort_order=DESC 

I upload the file four times for each update, for the English and Italian pages of nodes 2424 and 5634.

**Comment by jasloe** [comment]
A better way to do this is picking the file from an existing library of files. You'd upload the file once, then pick it from a list on the other three nodes. That'd obviate the need to upload it four separate times. (You'll encounter a namespace collision in any filesystem if you upload a file n+1 times.)
