### ISSUE TITLE
Homepage hiccup: repeating slides for two events

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#419]
There's a hiccup on the homepage--literally. The slides for two events, "Soldiers for Rome" and "Streetscapes," are repeating in the slideshow at the top of the page. A third event between those two, "Timing 40 Shots," has a single slide and functions normally.

**Comment by jasloe** [comment]
Will check it out.

**Comment by jasloe** [comment]
I think I know what's going on here but have to test on staging. Will report back in a bit.

**Comment by jasloe** [comment]
That took a minute to untangle! I have to run one more test but I think this is good to go. Also added logic for the event date override which I noticed was missing from the view output. 

There's a replacement slideshow and image handler in the works at #380 and #381 though probably best to roll this out mid-summer when the Academy is more or less quiet.
