### ISSUE TITLE
Contact info for News Feature pages

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#420]
Can you replace Marques's information in the green footer with my own?

Christopher Howard
Communications Manager
212-751-7200, ext. 340
c.howard@aarome.org

This is for the green block on News Feature pages like https://www.aarome.org/news/features/marla-stone-be-aar-s-next-andrew-w-mellon-humanities-professor

<img width="790" alt="Screen Shot 2021-06-08 at 4 01 25 PM" src="https://user-images.githubusercontent.com/38765846/121249735-e93f5180-c872-11eb-8cf5-3c63512aad98.png">

**Comment by jasloe** [comment]
Fixed. 

When is Marques' last day?
