### ISSUE TITLE
Homepage switch from Events to News Features

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#421]
On Friday, we will need to make the summer switch from the Events module on the homepage to the News Features. In that secondary slot on the homepage (currently occupied by News Features), we will need to change it to Far Afield (formerly Quick News).

Since we only publish in the News Feature section every month or so, would it be possible to leave News Features where it currently is and place Far Afield in the primary slider? I update [that section](https://www.aarome.org/news/far-afield) a lot more frequently than News Features. The problem is, links in Far Afield go offsite (to other websites). Do you think it makes sense to promote the five most recent items and link to https://www.aarome.org/news/far-afield, where a person can then click on the news item he/she wants to read, and maybe scroll a little to find it if it's not the top two items? This kind of functionality seems awkward, but it produces fresher content for the homepage. Although I do expect to publish something new in News Features soon (a collaboration between AAR and NYPL), it's going to be a stale summer. 

What do you think?

**Comment by jasloe** [comment]
This was kind of in the back of my mind and I already started decommissioning the events marquee. I can rework the news features slider to support Far Afield content. I think jumping through an additional page to get to the desired content is indeed awkward. Let me think about how to include some kind of way finding or tooltip or something to cue the user that they're leaving the site.

**Comment by cchristopherhowardd** [comment]
I wonder if it makes sense to highlight a single News Feature article at a time, so that the slideshow becomes static.

**Comment by cchristopherhowardd** [comment]
Let's just switch to the News Features for the main slider, with Far Afield (Quick News) underneath for now.

**Comment by jasloe** [comment]
Ok, sounds good. I'm out of the office today and can make progress on this tomorrow.

**Comment by jasloe** [comment]
Are we showing only one (i.e. the most recent) news feature or all news features that have been promoted?

**Comment by cchristopherhowardd** [comment]
I believe that I had checked the "promote on home page" box for the three most recent News Features published (Margaret Laird, 2021-22 fellows, Tomaso De Luca), which is fine for now.

That said, I may later check the box only for 2021-22 fellows and toggle among the three photos on that page when selecting the primary image.

**Comment by jasloe** [comment]
Pushed changes to staging.aarome.org. A few cosmetic things to clean up but otherwise ready to roll.

Need translation for "more" at "More Far Afield".

**Comment by cchristopherhowardd** [comment]
The translation for Far Afield on the /it/ site is Notizie Recenti, which just means Recent News. Translating "More Recent News" isn't easy to do, because it's an awkward, ambiguous phrase that's supposed to mean "Additional news that is recent" but also comes across as "Here is news that is even more recent than the news you just read." All this to say, the Italian phase on the /it/ homepage should just be "Leggi Altre Notizie" (Read More News).

**Comment by cchristopherhowardd** [comment]
I see that the Italian page has Altrove as the main header. This should be Notizie Recenti. Altrove means "somewhere else," which was a poor translation of Elsewhere, the former name of this section.

**Comment by cchristopherhowardd** [comment]
Here is the screenshot:

<img width="808" alt="Screen Shot 2021-06-23 at 3 48 06 PM" src="https://user-images.githubusercontent.com/38765846/123160135-cfd60200-d43b-11eb-92e3-7a4578c00aef.png">

**Comment by jasloe** [comment]
Fixed translation. Forget to mention that (perhaps obviously) the content on staging is a few weeks out of date.

**Comment by cchristopherhowardd** [comment]
I noticed the content was out of date, but also saw that a News Feature from December 2020 was promoted to homepage. I unchecked the box.

**Comment by jasloe** [comment]
Content and code/configuration are independent of one another. In other words, consider content on production status quo.

**Comment by cchristopherhowardd** [comment]
Well, yes. But it turned out the node promoted to homepage on staging was also promoted to homepage on production. I unchecked the box for the node on production.

**Comment by cchristopherhowardd** [comment]
Is Altrove going to turn into Notizie Recenti?

**Comment by jasloe** [comment]
Just getting to this. Fixed. If all ok, can push to production tomorrow.

**Comment by cchristopherhowardd** [comment]
Looks good to me. Push push push!

**Comment by jasloe** [comment]
Ok, likely won't get to this until after hours but definitely this evening.

**Comment by cchristopherhowardd** [comment]
Can you flip the switch today?

**Comment by jasloe** [comment]
I pushed everything on Friday. But noticed yesterday that something is wrong with front end caching. (I picked the wrong time to mess with [Varnish](https://varnish-cache.org/). Going to decouple that failed experiment here in a minute. Will let you know when that's done.
