### ISSUE TITLE
Italian Fellows

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#422]
I have added the [five new Italian Fellows](https://www.aarome.org/people/italian-fellows?field_affil_discipline_target_id=All&field_affil_year_target_id=1072) to the People section. Two of them are listed under the category Modern Italian Studies. While this has been a Rome Prize category for many years, it is new for Italian Fellows. (Previously, Italian Fellows would have been listed under Modern Studies).

Can you add the discipline Modern Italian Studies to the drop-down menu in the [Italian Fellows section](https://www.aarome.org/people/italian-fellows)? 

<img width="493" alt="Screen Shot 2021-07-16 at 11 20 35 AM" src="https://user-images.githubusercontent.com/38765846/125971074-0a337e08-33aa-42c6-ba1b-8eeef7fa2dc2.png">

**Comment by cchristopherhowardd** [comment]
If possible, it would be nice to have the translations for the disciplines on the Italian version of the [Italian Fellows](https://www.aarome.org/it/comunita/borse-di-studio-per-italiani) page (as well as Italian pages for the Rome Prize Fellows page and Residents page. Also, it would be nice to have Italian dates for /it/ pages for Fellows, Italian Fellows, and Residents.

For this screenshot, the date ought to be: 11 gennaio-30 aprile 2021

<img width="1186" alt="Screen Shot 2021-07-16 at 1 43 59 PM" src="https://user-images.githubusercontent.com/38765846/125988238-3c21b476-2c11-44f4-a7b2-ce45f4c10674.png">

**Comment by jasloe** [comment]
Fixed "Modern Italian Studies".

Easy enough to add translations to labels. Just need translations for Profession, Project title, Project description. Will work on translating discipline labels for grid view, as well.

**Comment by cchristopherhowardd** [comment]
I should have pointed out that Modern Italian Studies does not replace Modern Studies. We should have both.

**Comment by cchristopherhowardd** [comment]
Profession --> Professione
Project title --> Titolo del progetto
Project description --> Descrizione del progetto

**Comment by jasloe** [comment]
Added Modern Studies to filter. Added translations. Field labels are cached so I'll have to flush that before translations will appear. Leaving open until I can do that after business hours.

**Comment by jasloe** [comment]
I was able to locate the individual cache records and manually delete them. 

Translate field labels here:

https://aarome.org/it/comunita/residenti-invitati/anuradha-mathur-dilip-da-cunha

and here:

https://aarome.org/it/comunita/victorini-del-rome-prize/maggie-l-popkin

if ok, please close.

Date issues discussed here #400.
