### ISSUE TITLE
Defaults for Rome Prize and Italian Fellows pages

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#423]
As mentioned in issue #422, I have added the 2022 Italian Fellows to the website. I have also published all of the [2022 Rome Prize Fellows](https://www.aarome.org/people/rome-prize-fellows?field_affil_discipline_target_id=All&field_affil_year_target_id=1072) to the People section. 

However, I don't want to have 2022 be the default date for either the [Rome Prize Fellows](https://www.aarome.org/people/rome-prize-fellows) page or the [Italian Fellows](https://www.aarome.org/people/italian-fellows) page until August 9. (The 2021 fellows go home on August 6.)

**Comment by cchristopherhowardd** [comment]
Relatedly is the homepage slideshows for fellows. The change would not happen until August 9. Both Rome Prize Fellows and Italian Fellows should be represented on the slider.

<img width="1265" alt="Screen Shot 2021-07-16 at 11 31 59 AM" src="https://user-images.githubusercontent.com/38765846/125972410-b0f8f0a7-c953-45d1-9455-b0dc0e2e91c3.png">

People pages for 2022 Residents are behind RPFs and IFs. I expect to begin publishing them in August. In the meantime, Invited Residents on the homepage should draw from 2020 and 2021. I believe that a few 2019 Residents are appearing on the page (Paolo Gioli, Mary Margaret Jones). They can be removed.

**Comment by cchristopherhowardd** [comment]
I am wrong about Mary Margaret Jones--she is a 2020 Resident. Paolo Gioli is 2019.

**Comment by jasloe** [comment]
> As mentioned in issue #422, I have added the 2022 Italian Fellows to the website. I have also published all of the [2022 Rome Prize Fellows](https://www.aarome.org/people/rome-prize-fellows?field_affil_discipline_target_id=All&field_affil_year_target_id=1072) to the People section.
> 
> However, I don't want to have 2022 be the default date for either the [Rome Prize Fellows](https://www.aarome.org/people/rome-prize-fellows) page or the [Italian Fellows](https://www.aarome.org/people/italian-fellows) page until August 9. (The 2021 fellows go home on August 6.)

Is there a downside to simply unpublishing the nodes?

**Comment by jasloe** [comment]
> Relatedly is the homepage slideshows for fellows. The change would not happen until August 9. Both Rome Prize Fellows and Italian Fellows should be represented on the slider.
> 
> <img alt="Screen Shot 2021-07-16 at 11 31 59 AM" width="1265" src="https://user-images.githubusercontent.com/38765846/125972410-b0f8f0a7-c953-45d1-9455-b0dc0e2e91c3.png">
> 
> People pages for 2022 Residents are behind RPFs and IFs. I expect to begin publishing them in August. In the meantime, Invited Residents on the homepage should draw from 2020 and 2021. I believe that a few 2019 Residents are appearing on the page (Paolo Gioli, Mary Margaret Jones). They can be removed.

The Meet the Fellows slider shows Italian Fellows now. The logic for this slider contains a "promote to home page" filter. You'd need to promote this year's fellows then demote this year's fellows. I whipped up a little form to make that less clicky. 

https://aarome.org/admin/manage-promotions

**Comment by jasloe** [comment]
I think I may have misread the original issue. 2021 is currently the default date for fellows and residents pages. On August 9, I'd simply add '2022' to the filter for these pages. Make sense?

**Comment by jasloe** [comment]
Demoted Paolo Gioli.

**Comment by cchristopherhowardd** [comment]
That makes sense. I want to keep the 2021 Fellows on the homepage, because they're still in Rome!

**Comment by jasloe** [comment]
Ok, cool. So, can this be closed?

**Comment by cchristopherhowardd** [comment]
I'm reopening this issue quickly to ask that 2022 be the default date for both the [Rome Prize Fellows page](https://www.aarome.org/people/rome-prize-fellows) and the [Italian Fellows page](https://www.aarome.org/people/italian-fellows).

Residents can remain 2021, as I don't have People pages for them yet.

**Comment by cchristopherhowardd** [comment]
In a related note, we're getting repeats of Residents again on the homepage.

<img width="1273" alt="Screen Shot 2021-08-09 at 2 39 41 PM" src="https://user-images.githubusercontent.com/38765846/128757105-5fd0131b-75a8-4adf-92e9-a1c521060b17.png">

**Comment by jasloe** [comment]
Fixed. 

> I'm reopening this issue quickly to ask that 2022 be the default date for both the [Rome Prize Fellows page](https://www.aarome.org/people/rome-prize-fellows) and the [Italian Fellows page](https://www.aarome.org/people/italian-fellows).
> 
> Residents can remain 2021, as I don't have People pages for them yet.

**Comment by jasloe** [comment]
Opened new issue for carousel.
