### ISSUE TITLE
Captions in Support section

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#425]
I noticed that captions aren't appearing for pages in the /support/ section. Some pages don't have captions, but others (such as [New York Gala](https://www.aarome.org/support/new-york-gala) and [Corporate](https://www.aarome.org/support/corporate), do have them and they're not rendering on the page.

**Comment by jasloe** [comment]
Whoops. It appears there was a configuration mismatch for ```image``` media. (Which would explain why *all* images on the ```page``` content type lacked captions.) Captions now restored.

**Comment by cchristopherhowardd** [comment]
Some pages still have missing captions. Here are a few:

https://www.aarome.org/apply/visiting-artists-scholars
https://www.aarome.org/apply/italian-fellowships
https://www.aarome.org/about/mission
https://www.aarome.org/about/history/academy

**Comment by jasloe** [comment]
I see captions on all of those pages.

**Comment by cchristopherhowardd** [comment]
I cleared my cache and can see the captions now.

**Comment by jasloe** [comment]
I was unable to replicate but I manually removed those pages from the cache table, just to be safe. Should be ok for all users regardless of local browser conditions.
