### ISSUE TITLE
New domain for student project

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#428]
An undergraduate student at John Cabot University had a semester abroad in Rome. As part of her studies, she created a website that documents the portraits in the Academy Bar: https://sites.google.com/morningside.edu/portraitstester

AAR leadership in Rome would like to continue the project, or keep it alive, or something. One idea was to give the site its own URL, instead of having a Google Site URL. Is it within your scope to purchase, set up, and host new domains? My idea is to use academybarportraits.org, which is available, but I'll have to check with my colleagues. You can pass along the bill to us, of course.

I can't speak about the longevity of the project, or who will be managing it, but it's something that Rome wants now, so I'm making the request.

**Comment by cchristopherhowardd** [comment]
One additional note that I forgot to include above: Rome wants to place an iPad in the Academy Bar that people can pick up and navigate to this Google site, to identify the names of people in the portraits. Here are three views of the Academy Bar:

![_GB11700](https://user-images.githubusercontent.com/38765846/127896568-3a9d3bbe-d627-4a16-a605-ec28f8027b11.jpg)
![_GB11711](https://user-images.githubusercontent.com/38765846/127896575-652c2f06-0476-4a2b-bd41-0f1a21716c13.jpg)
![_GB11710](https://user-images.githubusercontent.com/38765846/127896583-61c0cee6-3179-4653-88c4-b7532ac974ed.jpg)

**Comment by jasloe** [comment]
Sure, no problem. Just let me know the details when you have them.

**Comment by jasloe** [comment]
Could also just create a subdomain, i.e. barportraits.aarome.org.

**Comment by cchristopherhowardd** [comment]
Naw, I think the unique domain is better.

**Comment by jasloe** [comment]
I get a 404 for: https://sites.google.com/morningside.edu/portraitstester

**Comment by jasloe** [comment]
Domain registration can be made through Amazon Web Services. No need to use an outside service. It's $15 annually.

**Comment by cchristopherhowardd** [comment]
The site is live for me.

<img width="1397" alt="Screen Shot 2021-08-03 at 4 50 26 PM" src="https://user-images.githubusercontent.com/38765846/128084394-5cacc528-c7af-4eaa-be07-0a8471c70172.png">

**Comment by jasloe** [comment]
Sign out of Google and try it.

**Comment by cchristopherhowardd** [comment]
The domain to use is: academybarportraits.org.

U: aarbarportraits@gmail.com
P: Americanacademy2021 (nb: if this doesn't work, let me know and I will reset the password)

**Comment by jasloe** [comment]
I'm asked for a recovery email address.

![Screen Shot 2021-08-05 at 13 59 11](https://user-images.githubusercontent.com/1063667/128398645-a8ae2528-2889-42c1-95d7-7d4e22a9e504.png)

**Comment by cchristopherhowardd** [comment]
mnp002@morningside.edu

**Comment by jasloe** [comment]
Ok, I've registered academybarportraits.org. It takes a little time to process. You should get an email confirmation from AWS. Go ahead and click the link to verify your email address.

**Comment by jasloe** [comment]
https://www.academybarportaits.org is live.
