### ISSUE TITLE
Calendar for programs and application deadlines

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#43]
Just a quick idea here I'd like to suggest: a single page that shows all of the programs with their application deadlines. Sort of a "master calendar" for applicants. This information is currently spread across several pages and not always easy to find.

**Comment by cchristopherhowardd** [comment]
Not a bad idea. I'll think of how best to implement it. I'm inclined to produce a chronological list of deadlines instead of a calendar-looking thing, with seven-day weeks.

**Comment by cchristopherhowardd** [comment]
But having a calendar-looking calendar, as we do now, is fine with me.

**Comment by cchristopherhowardd** [comment]
We should still create a webpage that lists upcoming deadlines for various fellowships and programs, but this can wait until after launch. A pair of ideas involve the homepage.

1. We can change this homepage section periodically to reflect the most important impending application deadline:

<img width="1370" alt="Screen Shot 2019-05-06 at 10 20 12 AM" src="https://user-images.githubusercontent.com/38765846/57231600-cc2b5b00-6fe8-11e9-8005-7a04b87e2e17.png">

2. We can update this homepage section periodically with a few upcoming programs and their deadlines.

<img width="1376" alt="Screen Shot 2019-05-06 at 10 20 20 AM" src="https://user-images.githubusercontent.com/38765846/57231721-17456e00-6fe9-11e9-9468-237dcd049729.png">

One of the > lines here (such as "> Explore Other Fellowships") could read "> See Upcoming Deadlines."

I do not envision these two sections remaining static over time. But like I just said, these changes will be part of regular site maintenance, not something to do before launch.
