### ISSUE TITLE
Affiliation handles

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#44]
Picking up the correspondence here....

Something like this?

<pre>
FAAR | Fellow
RAAR | Resident
VAAR | Visiting Artist or Visiting Scholar
AFAAR | Affiliated Fellow
</pre>

**Comment by cchristopherhowardd** [comment]
Yeah.

**Comment by jasloe** [comment]
Also, do you want to go back through and change any mention of FAAR, RAAR, etc. in news features and events. The news features corpus alone has 485 instances of FAAR and 183 instances of RAAR. Can be done easily with command line functions. 

Altering the dates will be trickier but definitely doable. Slightly out of scope but could handle it as a separate mini-project under remaining maintenance term. 

<pre>
<p>After the Rome Prize winners’ names were announced, the audience enjoyed a program entitled ""Poetry, Visual Art and Place,"" presented by the Academy’s Andrew Heiskell Arts Director Karl Kirchwey, FAAR’95, Trustee Mark Strand, RAAR’83, and Rosanna Warren, RAAR’01.</p>
</pre>

to: 

<pre>
<p>After the Rome Prize winners’ names were announced, the audience enjoyed a program entitled ""Poetry, Visual Art and Place,"" presented by the Academy’s Andrew Heiskell Arts Director Karl Kirchwey, 1995 Fellow, Trustee Mark Strand, 1983 Resident, and Rosanna Warren, 2001 Resident.</p>
</pre>

I think it's worth doing.

**Comment by jasloe** [comment]
Or...?

by the Academy’s Andrew Heiskell Arts Director Karl Kirchwey (1995 Fellow), Trustee Mark Strand (1983 Resident), and Rosanna Warre (2001 Resident).

**Comment by cchristopherhowardd** [comment]
Let's skip this correction. The decision to abandon FAAR and RAAR is for future writing, not for past usage. Editorial review of previously published material would involve much more than this switch of terms.
