### ISSUE TITLE
Translation for affiliation types

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#45]
Sorry if I missed this. Do we have translations for the following handles?

Fellow | Fellows
Resident | Residents
Affiliated Fellow | Affiliated Fellows
Italian Fellow | Italian Fellows
Visiting Artist | Visiting Artists
Visiting Scholar | Visiting Scholars
Visiting Artists and Scholars
Jury Member | Juries (including by discipline, i.e. Ancient Studies Jury Member | Ancient Studies Jury)
Advisor | Advisors (including by discipline, i.e. Ancient Studies Advisor | Ancient Studies Advisors)
Trustees | Trustees
Trustee Emeritus | Trustee Emerti

Not super urgent.

**Comment by jasloe** [comment]
Ditto RP Fellowship disciplines.

**Comment by jasloe** [comment]
And if that wasn't fun enough....there's a very noisy list of current and legacy Staff position handles.

AAR Librarian
AAR Professor
AAR Publications, Assistant to the Director
AAR Summer School
Acting Director
Acting Professor-in-Charge
Administrative Assistant
Advisory Council
Advisory Council Member
Andrew W. Mellon Professor-in-Charge
Architecture Committee Juror
ASCSR
Assistant Director
Assistant Director for Operations
Assistant Director for Properties
Assistant Professor
Associate Director of Development
Associate Librarian
Board Liaison, Public Information Officer
Board of Trustees
Bookeeper
Cashier
Chair
Chair Emeritus
Charter Member
Classical Society
Classical Studies Jury
Classical Summer School
Co-Director
Composition
Design Arts
Development Assistant
Director
Director of Administration
Director of Finance & Administration
Director of Programs
Ex Officio
Executive Committee
Executive Secretary
Executive Secretary and Chief Administrator
Executive Vice-President
Finance Assistant
Fototeca Unione Director
Gate Reception
Grounds Staff
History of Art Jury
Housekeeping Staff
Italian Committee
Jerome Lecturer
Juror
Jury Member
Librarian-in-Residence
Library Assistant
Maintenance Staff
Maintenance Superintendent
Member
NEH Summer Seminar
NEH Summer Seminar for College Teachers
Newsletter Editor
President
Professor
Professor-in-Charge
Program Associate
Receptionist, Administrative Assistant
School of Classical Studies
Secretary
Secretary and Chair
Secretary, Treasurer
Secretary-Treasurer
SoF Council
Superintendent of Grounds
Treasurer
Vice Chair Special Projects
Vice-president
Visual Arts Liaison

**Comment by cchristopherhowardd** [comment]
Regarding staff positions, the current website doesn't give Italian-language job titles, so I'm not inclined to introduce them now. I'll review and clean up the current titles and post them here.

**Comment by cchristopherhowardd** [comment]
I don't want to change much to the Job Titles here.
[Job Titles.docx](https://github.com/aarome/aarome/files/2283591/Job.Titles.docx)
