### ISSUE TITLE
Untranslated content

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#61]
A running list of untranslated headings and body copy.

### Research
Library Guides and Histories

**Comment by cchristopherhowardd** [comment]
In other words, some aarome.org/it/ pages have Italian on them like they're supposed to ( https://www.aarome.org/it/biblioteca ), while others default to what's on the English pages ( https://www.aarome.org/it/ricerca/risorse/la-collezionie-archeologica ). Is this what you mean?

A second problem, unrelated to design, is that English pages get updated but Italian pages are left behind.

**Comment by jasloe** [comment]
Add that to the list of issues. 

Specifically regarding URLs, we have:

https://www.aarome.org/research/archaeology-projects
https://www.aarome.org/it/research/archaeology-projects

Neither the URL nor the title (for starters) are translated. 

And, yes, Italian pages very, very often get abandoned.

**Comment by cchristopherhowardd** [comment]
I've completed preliminary translations for Italian-language URLs in the spreadsheet and passed them along to Rome, for verification.
