### ISSUE TITLE
Blocks on about front page

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#62]
@cchristopherhowardd – 

Open's design pattern features 6-up blocks on section front pages, e.g. /about, /apply, etc. 

Which content blocks should appear on /about. So far I have:

mission
place
gardens
villa-aurelia
rsfp

Any others?

**Comment by cchristopherhowardd** [comment]
Looking at http://dev.aarome.org/about, the blocks should be: Mission, Place, Board, Staff, Jobs & Internships, and RSFP.  

Under Place should be The Gardens, The Villa Aurelia, and The Library.

I will need to consult the sitemap to make sure.

**Comment by jasloe** [comment]
Ok. Place is a discrete page at the moment, as described in the site map. 
```
https://aarome.org/about/place
- https://aarome.org/about/villa-aurelia
- https://aarome.org/about/gardens
- https://aarome.org/about/directions
```
Do you want to remove this content:

dev.aarome.org/about/place

 and replace it with a block layout?

**Comment by cchristopherhowardd** [comment]
Yes. Should the URLs be changed to this?

/about/place/villa-aurelia
/about/place/gardens
/about/place/directions

The new sitemap called for eliminating this page ( https://www.aarome.org/about/place/library ), but I'd like to keep it now. /about/place can have four blocks. 

I feel ambivalent about web visitors going through too many pages with blocks. It seems like we should aim to not have more than two clicks on block/index pages in the same section. Going from /about/ to /about/place is OK but no more.

**Comment by cchristopherhowardd** [comment]
[Current AAR Sitemap.docx](https://github.com/aarome/aarome/files/2563305/Current.AAR.Sitemap.docx)
[Four Ups Six Ups Eight Ups.pdf](https://github.com/aarome/aarome/files/2563306/Four.Ups.Six.Ups.Eight.Ups.pdf)

**Comment by cchristopherhowardd** [comment]
I have noticed that the font size gets smaller after I edit the block text. See http://dev.aarome.org/people for an example. The text in the top two I edited and posted in the Summary. The two below were not touched. Perhaps something in the CSS makes Summary text smaller than Body text.

**Comment by cchristopherhowardd** [comment]
[Remaining Four Ups Six Ups.pdf](https://github.com/aarome/aarome/files/2573343/Remaining.Four.Ups.Six.Ups.pdf)
