### ISSUE TITLE
Behavior of people carousel on home page

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#63]
Regarding the people carousel, under **Meet the Fellows**, are these texts ```Rome Prize Fellows / Affiliated Fellows / Italian Fellows``` intended to function as links to inside pages, i.e. people/rome-prize-fellows, etc.? Or will they filter carousel items?

**Comment by cchristopherhowardd** [comment]
Are you referring to this page: http://dev.aarome.org/people? There isn't a carousel there, so I don't understand what a link or filter would do.

**Comment by jasloe** [comment]
On the home page. 
![home-page-fellows](https://user-images.githubusercontent.com/1063667/47582166-a2022d80-d921-11e8-8e89-9e19eb6b6605.jpeg)

**Comment by cchristopherhowardd** [comment]
OK I see. Let's make those links to:

/people/rome-prize-fellows
/people/affiliated-fellows
/people/italian-fellows

**Comment by jasloe** [comment]
Done.
