### ISSUE TITLE
Detail page for People?

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#65]
Last month we discussed developing a template for People. I've attached a screenshot of from the legacy "Directory" project. 

I can pull together a quick skeleton of the available People fields on the new site. There are a **lot** of fields!

![carter](https://user-images.githubusercontent.com/1063667/46228232-662e7500-c32f-11e8-9661-4a9a43c3156e.jpeg)

**Comment by cchristopherhowardd** [comment]
I'm OK with some pages for individuals being long and having lots of information. Can a design be created that accommodates these folks, as well as the people who might not have much information to display?

**Comment by jasloe** [comment]
In progress. Awaiting design spec from Open.
