### ISSUE TITLE
Breadcrumb development

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#66]
Do sections at the third level need submenus (or some way to get back to where they came from besides the browser back button)?

For example, ```/research/resources``` will resolve to a templated page with 7-up content blocks. Each block links to a detail page for the last item in the url below, i.e. online-catalogs, electronic-journals, etc?

```
http://dev.aarome.org/research/resources/online-catalogs
http://dev.aarome.org/research/resources/electronic-journals
http://dev.aarome.org/research/resources/periodical-indexes
http://dev.aarome.org/research/resources/libraries
http://dev.aarome.org/research/resources/maps-gis
http://dev.aarome.org/research/resources/research-tutorials
http://dev.aarome.org/research/resources/links
```

In other words, how do users get back to the 7-up page without scrolling to the bottom of the page and selecting links there?

**Comment by cchristopherhowardd** [comment]
Good question. I'll take a look at the above pages, and the AAR website as a whole, for potential solutions.

**Comment by cchristopherhowardd** [comment]
Would a graphic button at the bottom of the page (and before the footer) that says, or indicates otherwise to, "Return to Resources" or "Return to Research"

**Comment by jasloe** [comment]
I think we might want to explore some kind of breadcrumb pattern. The navigation system as designed is very shallow and it's easy to get lost.

**Comment by cchristopherhowardd** [comment]
I understood "breadcrumb" in a general sense and just realized it's a specific UX feature. Yes, this would help with the submenus levels. Placing it at upper right, under the main navigation items (About, Apply, etc.) makes sense and doesn't seem to be obtrusive to the overall page designs.

**Comment by jasloe** [comment]
I think that's the right way to do it. Open may have another idea or rationale for the original design. 

Regardless, we'll need design input and a change order.

**Comment by cchristopherhowardd** [comment]
So, is this something that Open will or won’t need to design?

**Comment by jasloe** [comment]
Yes, Martha agreed to propose at a few possibilities.

**Comment by jasloe** [comment]
Observing that we likely don't need bcs on section front pages, e.g. /about, /people, /events, etc.
