### ISSUE TITLE
Design specifies portrait format; unclear about support for varying formats

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#76]

**Comment by jasloe** [comment]
@cchristopherhowardd: In desktop view, how do you want to handle layouts with varying aspect ratios, i.e. landscape v. portrait? Leave it as-is? Or source portrait only images? Add the dreaded "gray box"?

http://dev.aarome.org/people/rome-prize-fellows

**Comment by cchristopherhowardd** [comment]
Leave as is. Portraits can be landscape, portraits, or squares.

NO GRAY BOXES!

Chris
-------
Christopher Howard
Communications Manager
