### ISSUE TITLE
Need placeholder image for people

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#77]
Per @cchristopherhowardd, very often we don't have an appropriate image for a fellow, resident, et al.

**Comment by cchristopherhowardd** [comment]
I'll look for some kind of generic image. It doesn't make sense to use a photo of the buildings in Rome or even a colored box with the word "Fellow" in it.

**Comment by cchristopherhowardd** [comment]
Is it possible for me to select, say, six photos from the AAR Photo Archive that depict a work of ancient sculpture, and program the website to randomly choose one of the six for the placeholder profile?
