### ISSUE TITLE
News features need trimming/summary

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#78]

**Comment by jasloe** [comment]
Refer to the following. 

In this case, the body copy begins with unusual formatting.
http://dev.aarome.org/node/1802/edit

In this case, the a tag is sanitized.
http://dev.aarome.org/node/1800/edit

**Comment by cchristopherhowardd** [comment]
I'm not sure what the concern is here, between the two examples (/1802/ and /1800/) above. The latter begins with a normal paragraph and the former doesn't.

**Comment by jasloe** [comment]
Done. Sanitization tasks remain at #79.
