### ISSUE TITLE
Sanitize body and summary fields

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#79]
In these cases, there is extraneous or improperly formatted markup.

http://dev.aarome.org/node/1793/edit

```
<p>On 2–3 February, the&nbsp;renowned&nbsp;<a href="http://www.scharounensemble.de/en">Scharoun Ensemble</a>&nbsp;of the&nbsp;Berlin Philharmonic Orchestra&nbsp;performed two concerts at the American Academy in&nbsp;Rome as the culminating events of a week-long residency. This is the tenth year of the group’s annual visit and concert series for the AAR community and the city of Rome.</p>
```

**Comment by cchristopherhowardd** [comment]
Oh lord, the &nbsp; is found everywhere, not just in the News section. Since January I've been deleting these whenever I encounter them. They show up even when creating new pages, copying and pasting text from Word. The nonbreaking space code is like a rat or cockroach on the AAR website.

**Comment by cchristopherhowardd** [comment]
Oh lord the <nonbreakingspacecode> is found everywhere.

**Comment by cchristopherhowardd** [comment]
Github is messing with me. I can't write non breaking space without it disappearing from the sentence.

**Comment by jasloe** [comment]
Renamed issue. Likely all body and summary fields will need sanitization at some point. Post-launch task, I guess.

**Comment by jasloe** [comment]
Doing this in a limited way. Refer to #133.
