### ISSUE TITLE
Produce sitemap and story book for review.

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#8]

**Comment by cchristopherhowardd** [comment]
Though the sitemap is not complete, I am uploading two Word documents that describe my work so far. One file presents the existing sitemap with annotations. The other file presents a proposed sitemap. A few things are color coded. Please let me know if this information makes sense, or if I can present it in a more legible form. We may wish to set up an in-person meeting soon for a discussion. It might be easier to review sections of the website together and look at my piles of printed webpages.
[New AAR Sitemap.docx](https://github.com/aarome/aarome/files/2134502/New.AAR.Sitemap.docx)
[Old AAR Sitemap.docx](https://github.com/aarome/aarome/files/2134503/Old.AAR.Sitemap.docx)

**Comment by jasloe** [comment]
This is pretty straightforward. I can use this to build and populate the basic pages, about/*, apply/*, research/*, rsfp/*, support/*. Of course, the page layout is incumbent on what Open produces. As such, I'll hold off on migrating images and building slideshows until we have a clearer sense of their proposal. 

Take a look at #12 when you have a chance and follow up with any comments or questions there. That issue regards translation paths for URLs.

**Comment by cchristopherhowardd** [comment]
I've revised the sitemaps from last month and will upload it here. The New Sitemap is (obviously) what I'd like the URLs to be. The Current Sitemap contains annotations for where pages are to be moved in the New Sitemap. Let me know if anything isn't clear!
[New AAR Sitemap.docx](https://github.com/aarome/aarome/files/2220000/New.AAR.Sitemap.docx)
[Current AAR Sitemap.docx](https://github.com/aarome/aarome/files/2220001/Current.AAR.Sitemap.docx)

**Comment by jasloe** [comment]
No problem. I put the docs over here so we can continue to edit if needed: 
https://drive.google.com/drive/folders/1PtMZVAUQYryu6HwUP1dE21nCHs7PlgtZ?usp=sharing

I'm ready to run most of the migrations this week and will tick them off on this page: https://github.com/aarome/aarome/wiki/Site-map

**Comment by jasloe** [comment]
@cchristopherhowardd: Quick question. 

The Apply section and subsections are specified as follows:

| /apply/rome-prize
|- /apply/rome-prize/application
|- /apply/rome-prize/faq

Do you want /apply/rome-prize to contain the General Infomation, Eligibility, Deadlines and Fees, Selection Process, Project Funding, and Return of Materials subsections to appear there? 

Or instead broken out, into discrete pages like so:

| /apply/rome-prize
|- /apply/rome-prize/general-information
|- /apply/rome-prize/eligibilty
|- /apply/rome-prize/deadlines-fees
|- /apply/rome-prize/selection-process
|- /apply/rome-prize/project-funding
|- /apply/rome-prize/return-of-materials

**Comment by cchristopherhowardd** [comment]
Don't break out. The page for /apply/rome-prize will be a long but important one.

**Comment by jasloe** [comment]
Got it. Closing.
