### ISSUE TITLE
Select image assets for all inside front pages

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#80]
http://dev.aarome.org/news/

**Comment by cchristopherhowardd** [comment]
Update for About --> Place. This should be a five-up now: Academy, Villa Aurelia, Gardens, **Library**, Directions. The link for Library should go to aarome.org/research.

**Comment by cchristopherhowardd** [comment]
There is some kind of bug related to the inside front pages. On Monday I added a clip-art image to the Services page at http://dev.aarome.org/research/library. Now that same image appears on inside front pages for other sections. On the aforementioned link, the clip-art copier is placed in Request Forms and Friends of the Library. The image is found on other pages--such as http://dev.aarome.org/publications and http://dev.aarome.org/research/archaeology--that don't yet have a selected image.

**Comment by jasloe** [comment]
I’ll take a look.

________________________________

**Comment by jasloe** [comment]
I flushed the file & media associations from those nodes and removed the clip art from the file system. Then I attached a gray square to the Services node and a few others to see if I could replicate. No luck. I made a db snapshot and tagged it. If the issue occurs again, I'll have a data point to refer to.
